### ISSUE TITLE
Shortened Buffer Names

### ISSUE THREAD

**Issue by vito-c** [Shougo/unite.vim#1000]
For system information, vim version and vimrc see [info](https://github.com/Shougo/unite.vim/issues/998)

When buffer names are shortened due to long paths and a small window the file name is being replaced with s..file.txt instead of the pathoshorten() function being used.
![issue](https://monosnap.com/file/OjmMO2eIVoZHsPKGkaQunGuAMJcVyf.png)

Actual:
/code/rewards/models/src/main/scala/c..teModels.scala
Expected:
/c/r/m/s/m/s/c/r/r/m/ActivityTemplateModels.scala

**Comment by Shougo** [comment]
Well, I think you should use "converter_file_directory" feature.

```vim
  call unite#custom#source(
        \ 'buffer', 'converters',
        \ ['converter_file_directory'])
```

**Comment by vito-c** [comment]
Bonus would be to drop the time and filetype info before shortening the path

**Comment by Shougo** [comment]
@vito-c If you want to drop time info, you should change `g:unite_source_buffer_time_format` variable.

**Comment by Shougo** [comment]
Closing.  You can change the output format.

**Comment by vito-c** [comment]
@Shougo ok thanks I'll check those two features out

**Comment by vito-c** [comment]
>Well, I think you should use "converter_file_directory" feature.
>```
>  call unite#custom#source(
>        \ 'buffer', 'converters',
>        \ ['converter_file_directory'])
>```

When I use that option I lose the timestamp. I believe I could create my own custom converter and call it via the source command outlined above though correct? :)

**Comment by Shougo** [comment]
> When I use that option I lose the timestamp. I believe I could create my own custom converter and call it via the source command outlined above though correct? :)

If you need the timestamp, you should create own converter.
