### ISSUE TITLE
Make opening newly created files optional

### ISSUE THREAD

**Issue by kba** [Shougo/unite.vim#1005]
When executing the `vimfiler_new_file` action in Shougo/vimfiler.vim, it calls the `newfile` action in `autoload/unite/kinds/file_vimfiler_base.vim`.

That action creates new files for a list of file names. In https://github.com/Shougo/unite.vim/blob/master/autoload/unite/kinds/file_vimfiler_base.vim#L320, it also open the file.

Can the opening of the new file be made optional? Sometimes, I just want to lay out the structure of a directory tree, create files, move/rename them and *then* start working on the files.

**Comment by Shougo** [comment]
Implemented.

**Comment by kba** [comment]
Awesome, thank you!
