### ISSUE TITLE
jumping forward/back with <c-i>/<c-o>

### ISSUE THREAD

**Issue by vito-c** [Shougo/unite.vim#1006]
After I open a file with unite and then press `<c-o>` to jump back to the previous file it is instead taking me the previous unite buffer.

Steps:
 1. Open a group of files with vim (files a.vim, b.vim, c.vim)
 2. You are in file a.vim
 2. Use unite to list your buffers and select a different file from the current one. (b.vim)
 3. press `<c-o>`

Actual:
You are taken to the unite buffer that was listing the files
 
Expected:
You should jump back to a.vim

**Comment by Shougo** [comment]
It is feature.

https://github.com/Shougo/unite.vim/issues/929

And the patch is available in vim_dev.
You can vote it.

https://groups.google.com/forum/#!searchin/vim_dev/lock/vim_dev/IOrR9_ZF6Jo/nYgEbZBR5mUJ
