### ISSUE TITLE
Browse yank history from specific register?

### ISSUE THREAD

**Issue by for-coursera** [Shougo/unite.vim#1007]
I know it's possible to browse *all* yank history from *all* registers with `:Unite register history/yank`. But is there any way to browse yank history from a specific register (let it be register `z`) only?

**Comment by Shougo** [comment]
Why this feature is needed?  
Please describe it.

**Comment by for-coursera** [comment]
Oh, what would be of limited demand, I think :). But let that be just an example: on deleting certain unsaved buffers I yank them automatically to a certain register (which depends on a filetype) just in case I still may need 'em in the future. Thus, browsing those all together lately makes it kinda mess... :)

**Comment by Shougo** [comment]
OK.  I implemented the feature.
