### ISSUE TITLE
`grep` source: Multiple files/directories

### ISSUE THREAD

**Issue by rafi** [Shougo/unite.vim#1008]
How can one use the `grep` source to search multiple files and/or directories? Help says:
```markdown
	Source arguments:
	1. the target directories splitted by newlines.
	2. "grep" options.
	3. the narrowing pattern
```

How can I feed source with items split by newlines?

My use-case is mapping `gr` in VimFiler differently:
- If no marked files, grep in cursor's current directory
- Otherwise, grep in marked files/directories
```viml
nnoremap <silent><buffer> gr  :<C-u>Unite grep:<C-R>=<SID>selected()<CR><CR>

function! s:selected()
	let marked_files = vimfiler#get_marked_files()
	if empty(marked_files)
		let file_dir = vimfiler#get_file_directory()
		if empty(file_dir)
			return '.'
		endif
		call add(marked_files, { 'action__path': file_dir })
	endif

	return join(map(marked_files, 'v:val.action__path'), ':')
endfunction
```

**Comment by Shougo** [comment]
> My use-case is mapping gr in VimFiler differently:

This feature is already supported in vimfiler.

**Comment by Shougo** [comment]
> How can I feed source with items split by newlines?

https://github.com/Shougo/unite.vim/issues/864
