### ISSUE TITLE
problem with project root

### ISSUE THREAD

**Issue by 7belrhalmia** [Shougo/unite.vim#1009]
@Shougo  unite don't consider my root project

my Workspace is : ~/Go

myproject is in : ~/Go/src/main/

unite tkae src as the root but the main is the root

also when i change current working directory to main it's dosen't work

**Comment by ujihisa** [comment]
Your description is unclear. What exactly you did? `:UniteWithProjectDir`?

**Comment by Shougo** [comment]
Yes, it is unclear.  But it seems feature.
unite.vim searches progject root, but it is not found.  So, unite.vim uses "src" directory as root.
You should put "Makefile" or ".git" or other project marker files in the directory.

Closing.
