### ISSUE TITLE
can not ag search for unicode

### ISSUE THREAD

**Issue by jjwt** [Shougo/unite.vim#1011]
to reproduce the problem, i do 

1. my vimrc is
    ```
      if executable('ag')
        let g:unite_source_grep_command = 'ag'
        let g:unite_source_grep_default_opts =
              \ '-i --vimgrep --hidden '
              \ . '--ignore ".hg" '
              \ . '--ignore ".svn" '
              \ . '--ignore ".git" '
              \ . '--ignore ".bzr" '
              \ . '--ignore "__pycache__" '
              \ . '--ignore "_build" '
        let g:unite_source_grep_recursive_opt = ''
      endif
      nnoremap <silent> <leader>fg :<C-u>Unite -vertical grep:. -buffer-name=search-buffer<CR>

    ```
1. press these command to create sample:

    ```
    cd ~/temp
    mkdir temp
    cd temp
    echo "hello=你好" > 1.txt
    echo "hello=你好" >> 1.txt
    ```
1. then i try:

    1. press `\fg` and input hello, find the two lines
    1. press `\fg` and input 你好, find nothing
    1. comment lines except the last line in my vimrc, then press `\fg` and input hello, find the two lines
    1. comment lines except the last line in my vimrc, then press `\fg` and input 你好, find the two lines
    1. i input command in the shell:

        ```
        ➜  temp  ag hello ./*
        1:hello 你好
        2:hello 你好
        ➜  temp  ag 你好 ./* 
        1:hello 你好
        2:hello 你好
        ```

as a result, only the second does not make sense.

Though i use chinese, i think it may be for unicode. 
why?

**Comment by Shougo** [comment]
Reproduced.  But it is not unite.vim' bug.
You should report the problem in ag repository.
I have reproduced it in latest ag command....

You can reproduce it by following command.
```
$ ag -i 你好 ./*
```

Oh, "ag -i" is broken in multibyte pattern.

**Comment by jjwt** [comment]
thank you very much!
