### ISSUE TITLE
Taking too long to load

### ISSUE THREAD

**Issue by vito-c** [Shougo/unite.vim#1013]
I am using neovim: 
`Unite -start-insert -toggle -no-split file_rec/git`
I am seeing delays on projects of all sizes. It is taking around 25 seconds to run this command. 
```
time git ls-files --cached --others --exclude-standard | wc -l
    4860

real	0m0.044s
user	0m0.020s
sys	0m0.027s
```
Although my ctrl-p is not using the same command it is returning around 3800 files and only takes a 2~3 seconds.

**Comment by vito-c** [comment]
I believe I'm also seeing files that are git ignored when in unite but not when running on the cli

**Comment by vito-c** [comment]
> I believe I'm seeing files that are git ignored when in unite but not when running on the cli

ok this happened because I was running `file_rec/neovim` and `file_rec/git` w/o clearing my cache.. maybe there is some relation going on here with the cache not getting cleared. There are probably two is issues here. The command taking too long, and that when you run a different file_rec command the caches should auto clear.

**Comment by Shougo** [comment]
@vito-c 

> ok this happened because I was running file_rec/neovim and file_rec/git w/o clearing my cache.. maybe there is some relation going on here with the cache not getting cleared. There are probably two is issues here. The command taking too long, and that when you run a different file_rec command the caches should auto clear.

I will fix the problem.

But please upload your unite.vim configuration.
Please read the issue template.

https://github.com/Shougo/unite.vim/issues/584

**Comment by vito-c** [comment]
See this issue for my version: https://github.com/Shougo/unite.vim/issues/998

This issue is two fold:
  1. file_rec/git is taking too long
  2. cache should be cleared when you run file_rec/neovim, file_rec/async, file_rec/git

**Comment by vito-c** [comment]
I'm running latest version of unite.

**Comment by Shougo** [comment]
@vito-c Please upload your minimal .vimrc to reproduce it.
Because, in #998 you don't load vimproc.
So, you have to upload the correct .vimrc configuration.

**Comment by Shougo** [comment]
> cache should be cleared when you run file_rec/neovim, file_rec/async, file_rec/git 

Fixed the problem.

> file_rec/git is taking too long

I think it is your configuration problem.
So, please upload your unite configuration.

**Comment by vito-c** [comment]
I will pull with your latest changes and test. I think file_rec/git was appearing to be slow because it was using the cache from file_rec/neovim

**Comment by vito-c** [comment]
how can I clear the cache before I run the command?

**Comment by vito-c** [comment]
`execute "normal \<Plug>(unite_redraw)"`

**Comment by Shougo** [comment]
`<Plug>(unite_redraw)` or use `-redraw` argument.

**Comment by vito-c** [comment]
`:Unite -start-insert -toggle -no-split -redraw file_rec/git` is giving me: 
```
[unite.vim] Invalid option "-redraw" is detected.
[unite.vim] unite.vim: Invalid option
Press ENTER or type command to continue
```

**Comment by Shougo** [comment]
Oh, sorry.  `-force-redraw` is correct.

**Comment by vito-c** [comment]
Ok I can confirm the two issues were related. So what I think was happening was:
1. run file_rec/neovim
2. Since there are a lot of files it would take awhile.
3. Close Unite buffer
4. run file_rec/git 
5. it would take awhile for all of the files to load because it was loading from cache first

Thanks @Shougo!

**Comment by Shougo** [comment]
OK
