### ISSUE TITLE
Negative conditions broken

### ISSUE THREAD

**Issue by wilywampa** [Shougo/unite.vim#1014]
Negative conditions don't work anymore after 81801960ed1f461dcc6f5fb814b78e17b2a31322.

For example, write in a buffer:

```
abc
abcdef
abc123
```

Then do `:Unite line` and enter `abc !def`. `!def` is ignored and all three lines show up as candidates (only lines 1 and 3 should remain).

**Comment by Shougo** [comment]
Fixed.
