### ISSUE TITLE
Couple Issues

### ISSUE THREAD

**Issue by vito-c** [Shougo/unite.vim#1015]
When using `-immediately` switching is working correctly but after the switch the syntax is no longer set correctly on the file. The other issue with `-immediately` is that the new buffer is left in insert mode. I tried to fix this since I don't think many people will use fast buffer switching but couldn't get it to work :(

My unite configs: https://github.com/vito-c/pirate-vim/blob/master/rc/plugins/unite.vim

I was also playing around with https://github.com/mattn/unite-gist and fixing some things. I was wondering  if you could give me some pointers on how to make the syntax coloring better. The output looks like this:
```
<SHA>   <File Name>               <Description>
```
Example:
````
9861534 multiline                      multiline string in viml
7727679 gistfile1.txt                  Getting this compile error
6845013 gistfile1.cs
5596907 gistfile1.txt                  --enable--clientserver??
5513753 gistfile1.txt                  tail that unity log
5513522 gistfile1.txt                  function to grep for non unicode characters like those evil dashes
```

**Comment by Shougo** [comment]
> I was also playing around with https://github.com/mattn/unite-gist and fixing some things. I was wondering if you could give me some pointers on how to make the syntax coloring better. The output looks like this:

You can use `on_syntax()` hook.
But to use vim-gista is better.

https://github.com/lambdalisue/vim-gista

**Comment by Shougo** [comment]
> When using -immediately switching is working correctly but after the switch the syntax is no longer set correctly on the file. The other issue with -immediately is that the new buffer is left in insert mode. I tried to fix this since I don't think many people will use fast buffer switching but couldn't get it to work :(

Please read the issue template!

https://github.com/Shougo/unite.vim/issues/584

I don't understand/test your issues.

**Comment by vito-c** [comment]
### Problems summary
When using the following: `Unite -immediately -start-insert -toggle -no-split buffer:-`
The syntax on the highlighting on the buffer you are switching to is disabled. `set syntax?` returns `syntax=` You are also left in insert mode after switching.

* Expected

* Environment Information
 * OS: OS X Yosemite 10.10.4
 * Vim version: Neovim `01a0d4b`

* Minimal vimrc less than 50 lines
https://github.com/vito-c/pirate-vim/blob/master/vimrc-minimal

* Reproducable ways from Vim starting
 0. startup nvim.
 1. nvim ./autoload/unite/*.vim
 2. `:Unite -immediately -start-insert -toggle -no-split buffer:-`
 3. type action.vim

**Comment by Shougo** [comment]
Reproduced.  But I cannot fix the problem...
I will remove immediately feature when narrowing.

**Comment by Shougo** [comment]
Pull request is wellcome if you can fix it.

**Comment by vito-c** [comment]
Thanks. I will take a look when I have time.

**Comment by Shougo** [comment]
I have fixed 1st problem "no filetype".
But I cannot fix 2nd problem "insert mode".
It seems Vim's bug.  But I don't know why...
"stopinsert" command is just ignored.

**Comment by vito-c** [comment]
This commit? https://github.com/Shougo/unite.vim/commit/cb58517abbc427d79c4f85a220af01f9635c3149  I don't see the call to `stopinsert`

**Comment by Shougo** [comment]
@vito-c I added stopinsert, but it don't work.  So I have removed it.
You can add stopinsert in it manually.

**Comment by vito-c** [comment]
This has to do with the updatetime... when you do this
```
    set updatetime=0
    stopinsert
```
it works as expected.  I was going to try and store off the updatetime set it to 0 and then restore it but then noticed in handlers.vim you have some functions that might be able to do this
```
unite#handlers#_save_updatetime()
unite#handlers#_on_insert_leave()
```

i will look more tomorrow

**Comment by Shougo** [comment]
@vito-c Thanks.  I fixed .  It s updatetime work around though.

**Comment by vito-c** [comment]
After opening an issue on vim and neovim I experimented a little more. When I run nvim/vim -u NONE then `:execute 'normal! iputting text here'|stopinsert` I would expect `stopinsert` to be delayed but that was not the case it worked as expected. So I am trying to create a simple test case to show how it's failing. Any thoughts?

**Comment by Shougo** [comment]
Yes.  I think you should create test case.
But it is not easy.  Unite.vim is complex plugin.

**Comment by vito-c** [comment]
Is there a way I can figure out what autocommand that is actually calling the function: `function! unite#view#_redraw(is_force, winnr, is_gather_all) "{{{` in `autoload/unite/view.vim`

I think it has to do with the stopinsert being on an autocommand.

**Comment by vito-c** [comment]
One thing I noticed is that if you do `au CursorHoldi * stopinsert` `au CursorHold * stopinsert` and then `i` `<c-o>` stopinsert will not fire! I was trying to write a `:execute "normal iabc\<c-o>"` to see if I could force myself into (insert) mode but was unable
