### ISSUE TITLE
Unite.vim file_rec/async not working with ag

### ISSUE THREAD

**Issue by markwu** [Shougo/unite.vim#1017]
## Problems summary

Unite.vim file_rec/async not working with ag.

##  Expected

It should works without problems.

## Environment Information
 * OS: OSX 10.10.5
 * Vim version: Vim 7.4.769
 * ag version: 0.31.0

## Here comes the minimal vimrc

```
set nocompatible
filetype off

let test = 'neocomplete'

set rtp+=~/.vim/bundle/neobundle.vim/

call neobundle#begin(expand('~/.vim/bundle/'))

NeoBundleFetch 'Shougo/neobundle.vim'
NeoBundle 'Shougo/vimproc.vim', {
    \ 'build' : {
    \     'windows' : 'make -f make_mingw32.mak',
    \     'cygwin' : 'make -f make_cygwin.mak',
    \     'mac' : 'make -f make_mac.mak',
    \     'unix' : 'make -f make_unix.mak',
    \    },
    \ }

NeoBundle 'Shougo/unite.vim'

call neobundle#end()

filetype plugin indent on

NeoBundleCheck


"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" unite.vim
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

let g:unite_source_history_yank_enable = 1
let g:unite_source_rec_max_cache_files = 0
let g:unite_prompt = '» '

call unite#filters#matcher_default#use(['matcher_fuzzy'])
call unite#filters#sorter_default#use(['sorter_rank'])
call unite#custom#profile('default', 'context', {
    \   'start_insert' : 1
    \ })
call unite#custom#source('line',
    \ 'matchers', 'matcher_fuzzy')

let g:unite_source_rec_async_command = ['ag', '--follow', '--nocolor', '--nogroup', '--hidden', '-g', '']

function! <SID>UniteSetup()
    nmap <buffer> Q <plug>(unite_exit)
    nmap <buffer> <Esc> <plug>(unite_exit)
    imap <buffer> <Esc> <plug>(unite_exit)
endfunction
autocmd FileType unite call <SID>UniteSetup()

nmap <space> [unite]
nnoremap [unite] <nop>

nnoremap <silent> [unite]f :<C-U>Unite -auto-resize -toggle -buffer-name=files file_rec/async<CR>
nnoremap <silent> [unite]b :<C-U>Unite -auto-resize -buffer-name=buffers buffer<CR>
nnoremap <silent> [unite]q :<C-U>Unite -quick-match -buffer-name=buffers buffer<CR>

```

## Reproducable ways from Vim starting

 1. clear unite.vim cache first
 2. start vim
 3. hit `<space>f`
 4. you will get nothing.

**Comment by Shougo** [comment]
I cannot reproduce the problem.
I think your unite.vim or vimproc is too old.
Please update both plugins.

**Comment by markwu** [comment]
I already use the most updated plugins, that's the problem. :(

**Comment by zekzekus** [comment]
i hit the same problem with silver searcher (ag) 0.31.0. then switched back to 0.30 and problem vanished

**Comment by dlanileonardo** [comment]
I have the same problem.

**Comment by dkotvan** [comment]
I think it's something related to commit "1803299 Fix #1013 rec source cache problem"
, I reseted my plugin to commit 385a52a and it started to work again.

**Comment by Shougo** [comment]
OK.  I have reproduced.  It seems ag ver.0.31's bug.

> I think it's something related to commit "1803299 Fix #1013 rec source cache problem", I reseted my plugin to commit 385a52a and it started to work again.

It is not cache problem.

**Comment by Shougo** [comment]
Fixed.
Ag after 0.31 requires pty like "ack" or "pt".
It seems bad design.

**Comment by markwu** [comment]
Shougo, thanks! I confirmed it fixed in this commit under my environment.
