### ISSUE TITLE
grep result is not complete

### ISSUE THREAD

**Issue by xr081221097** [Shougo/unite.vim#1018]
Hi, Shougo, 
First, I' very appreciate for your unite!
but I am very sorry for disturbing you to consult this maybe simple question.
I use ag as grep action command for search a word in some files.
Some configurations are listed below:
if executable('ag')
 let g:unite_source_grep_command = 'ag'
 let g:unite_source_grep_default_opts =
    \  '-i --line-numbers --nocolor --nogroup --hidden --ignore ' .
    \  '''.hg'' --ignore ''.svn'' --ignore ''.git'' --ignore ''.bzr'''
  let g:unite_source_grep_recursive_opt = ''
  let g:unite_source_rec_async_command =
    \ ['ag', '--follow', '--nocolor','--nogroup','--hidden','-g','']
  endif
When i grep a word, such as "cancel", I execute command Unite -auto-preview grep:. 
Then search "cancel".
The result display that 
Unite > default > grep:.(100/188) | Pattern: CANCEL
So, does the result means that there are 188 candidates all, but only 100 are showed?
Also, I add:
let g:unite_source_rec_max_cache_files = 0
call unite#custom#source('file_rec,file_rec/async',
       \ 'max_candidates', 0)
The files it lists are file_rec/async:!(4289/4312).
How can I get all results? Should I configure some accelerator keys or other parameters in .vimrc?
Thank you very much!

**Comment by xr081221097** [comment]
Great I found the answer! <Plug>(unite_disable_max_candidates), it maybe results in machine becoming slow!

**Comment by Shougo** [comment]
> So, does the result means that there are 188 candidates all, but only 100 are showed?

Yes, it sets "max_candidates" attribute to 100 by default.
