### ISSUE TITLE
Quit unite buffer after selecting candidate

### ISSUE THREAD

**Issue by petobens** [Shougo/unite.vim#1019]
Consider the following minimal vimrc:

```vim
set nocompatible

let $ONEDRIVE_HOME = expand('C:/OD/Users/Pedro')
let $DOTVIM = expand('$ONEDRIVE_HOME/vimfiles')

set runtimepath+=$DOTVIM/bundle/unite
set runtimepath+=$DOTVIM/bundle/neomru

filetype plugin indent on
```

Now open Gvim and edit two files, for example `vimrc` and `vimrc_min`. Then run `:Unite neomru/file` and select one of the candidates. Once the file opens delete the buffer with `:bd`. You will see that the nite buffer appears once again.
Once I select a candidate I expect the unite buffer to quit completely. 

![gif](https://cloud.githubusercontent.com/assets/2583971/9853078/44d20ef2-5ad8-11e5-8391-80fbd493cf15.gif)

**Comment by petobens** [comment]
I think the problem can be perceived in a bettery if add:

```vim
set runtimepath+=$DOTVIM/bundle/airline/
let g:airline#extensions#tabline#enabled = 1
```
to the minimal vimrc above. You can see that once  I select a candidate the Unite buffer remains open rather than quitting:

![blahh](https://cloud.githubusercontent.com/assets/2583971/9853337/76ce8a06-5ad9-11e5-8ba4-ab42ad6e11c9.gif)

**Comment by joshgummersall** [comment]
I was seeing this problem as well. I ran `git bisect` and narrowed it down to this commit:

https://github.com/Shougo/unite.vim/commit/8a8fafa4d955953d40bd6e74cd50fb9b7c15fc75

A revert of that commit fixes the issue for me. Hope that's somewhat helpful.

**Comment by petobens** [comment]
Thanks @joshgummersall . That commit seems to be the source of the problem. Let's hope @Shougo fixes it.

**Comment by joshgummersall** [comment]
@petobens feel free to use https://github.com/joshgummersall/unite.vim for the time being.

**Comment by petobens** [comment]
@joshgummersall  will do. Thanks once again.

**Comment by Shougo** [comment]
Fixed.

**Comment by joshgummersall** [comment]
Thanks!

**Comment by petobens** [comment]
Thank you!

**Comment by zekzekus** [comment]
the commit ff4b233645fcbec0b3140160e10c8d541de93955 again caused this problem. fyi.

**Comment by petobens** [comment]
@zekzekus I'm using the latest version and, at least for me, the problem seems fixed.

**Comment by petobens** [comment]
@zekzekus, my mistake. I was to reproduce with the following minimal vimrc:

```vim
set nocompatible

let $ONEDRIVE_HOME = expand('C:/OD/Users/Pedro')
let $DOTVIM = expand('$ONEDRIVE_HOME/vimfiles')

set runtimepath+=$DOTVIM/bundle/unite
set runtimepath+=$DOTVIM/bundle/airline/

filetype plugin indent on

let g:airline#extensions#tabline#enabled = 1
```

If I open Gvim, edit that minimal vimrc and run `:Unite file` two times then the second time the Unite buffer remains visible.

![blahh](https://cloud.githubusercontent.com/assets/2583971/9911969/4277a33e-5c7b-11e5-838a-75f2e9073ccc.gif)

**Comment by Shougo** [comment]
OK.  Fixed.

**Comment by petobens** [comment]
Thanks!

**Comment by petobens** [comment]
Sorry it doesn't seem fixed. I can still reproduce it using latest version and my last minimal vimrc.

**Comment by Shougo** [comment]
@petobens I don't want to use airline.
Please create reproduce ways without airline.
I think execute `:ls` is better way.

> If I open Gvim, edit the minimal vimrc and run :Unite file two times then the second time the Unite buffer remains visible.

The statement and the screenshot are hard to understand.
You should explain it more detailed.
 
Example:

* vim -u min_vimrc min_vimrc
* `:Unite file`
* press q key
* `:Unite file`
* press q key
* `:ls`

Unite buffer is not displayed in `:ls` result.
What is the problem?

**Comment by petobens** [comment]
I will try to reproduce it without using airline,

**Comment by petobens** [comment]
Closing since it seems to be an airline issue (see [here](https://github.com/bling/vim-airline/issues/855)).

**Comment by Shougo** [comment]
OK.
