### ISSUE TITLE
nnoremap <C-p> :Unite file_rec/async<cr> does not do anything?

### ISSUE THREAD

**Issue by gerroon** [Shougo/unite.vim#1021]
Hi

I am trying to adjust to Unite. Now when I type :Unite file, I get nice file list. When I try the command above, all I get is a separate buffer with nothing, I type i for instert no listing is done, I try tab nothing is going on.

According to this page it should work like charm
https://bling.github.io/blog/2013/06/02/unite-dot-vim-the-plugin-you-didnt-know-you-need/

**Comment by ujihisa** [comment]
Which Vim are you using, and how exactly is your vimrc file specifying that key mapping?

**Comment by gerroon** [comment]
I just used the command in the title. I am using Linux  7.4 (2013 .

I think there is a glitch. I will investigate it further.

**Comment by Shougo** [comment]
@gerroon Please read the issue template.

https://github.com/Shougo/unite.vim/issues/584

I think your configuration is wrong.  But I don't have ESP skills.

**Comment by Shougo** [comment]
No response.
