### ISSUE TITLE
-start-insert is broken

### ISSUE THREAD

**Issue by mrbiggfoot** [Shougo/unite.vim#1022]
```
Unite -start-insert file_list:<list>
```

It opens the Unite window and enters insert mode. However when I start typing, it shows the error: "E21: Cannot make changes, 'modifiable' is off". It works when I remove "-start-insert" and enter insert mode manually.

**Comment by Shougo** [comment]
Sorry, fixed.

**Comment by mrbiggfoot** [comment]
Thank you sir!
