### ISSUE TITLE
Toggle loop behaviour

### ISSUE THREAD

**Issue by dkiyatkin** [Shougo/unite.vim#1023]
How to prevent jump to first line in unite preview, when cursor is in last position and key down (J) is pressed and otherwise jump from first line to last line, when key up (K) is pressed?

**Comment by mrbiggfoot** [comment]
```
autocmd FileType unite call s:unite_settings()
function! s:unite_settings()
	" Disable cursor looping
	silent! nunmap <buffer> <Up>
	silent! nunmap <buffer> <Down>
endfunction
```

You will probably have to add iunmap as well.
