### ISSUE TITLE
-update-time doesn't change default value of updatetime

### ISSUE THREAD

**Issue by askobara** [Shougo/unite.vim#1025]
Hello!

When I try to invoke Unite buffer with option `-update-time` it still uses a default value.
I expected that this option will change the `updatetime` value according buffer's settings.

Tested in vim and neovim.

Here vimrc:
```viml
" vim: ft=vim
if has('vim_starting')
  if &compatible
    set nocompatible               " Be iMproved
  endif

  set runtimepath+=~/.vim/bundle/neobundle.vim/
endif

call neobundle#begin(expand('~/.vim/bundle/'))

NeoBundleFetch 'Shougo/neobundle.vim'

  NeoBundle 'Shougo/unite.vim' "{{{
    let g:unite_data_directory='$HOME/.vim/.cache/unite/'
    let g:unite_enable_start_insert=1
    let g:unite_source_history_yank_enable=1
    let g:unite_source_rec_max_cache_files=0

    nnoremap <silent> <leader>f :<C-u>Unite -auto-resize -toggle -update-time=400 -input= -buffer-name=files file_rec/async:!<CR>

  "}}}

  NeoBundle 'Shougo/vimproc.vim', {'build': {'unix': 'make -f make_unix.mak'}}
call neobundle#end()

filetype plugin indent on
NeoBundleCheck
syntax on
```

**Comment by Shougo** [comment]
I cannot reproduce the problem.
I think your reproduce ways are wrong.
Please upload the reproduce ways.  I will check it.

**Comment by askobara** [comment]
Oh, yeah, I'm forgot about reproducing way, sorry

1. `vim -u test.vimrc`
2. `:echo &ut` # you get 4000
3. `:Unite -update-time=400 file_rec/async:!`
4. Unite buffer is opened. Trying to type what we want to find in folder. Only after a pause of 4sec filelist is updated. To make sure execute `:echo &ut` and see 4000.

As I understand from docs a value of `ut` should be changed to 400 after opening buffer.

**Comment by Shougo** [comment]
No.  It is feature.
The updatetime is changed if needed.
If the filelist is updated, the updatetime will be restored.
