### ISSUE TITLE
Feature request (?): open files in a new tab

### ISSUE THREAD

**Issue by ag4ve** [Shougo/unite.vim#1026]
I see that new files open in a split or current buffer but I normally use tabs. While adding tabnew to the call is the obvious short term solution, there's an empty buffer if I bail out and seems kludgy.

**Comment by ujihisa** [comment]
`<C-t>` does it. `:h unite-action-openable`

**Comment by Shougo** [comment]
This feature is already implemented.
In normal mode, you can use `t` key.
In insert mode, you can use `<C-t>` key.  Closing.
