### ISSUE TITLE
First run Unite get the error message!

### ISSUE THREAD

**Issue by wsdjeg** [Shougo/unite.vim#1028]
1. Problems summary
    First run Unite get the error message
2. Expected
    do not show me the message
3. Environment Information
        OS:ubuntu
        Vim version:7.4.712
        Enabled lua interface?: (It is important!),i install the vim by apt-get install ,so i think it do not support lua

    Minimal vimrc less than 50 lines
     https://github.com/wsdjeg/DotFiles/blob/master/vimrc

    " Your vimrc
   
    set nocompatible

    set runtimepath+=~/path/to/unite.vim/

    Reproducable ways from Vim starting

    0.startup vim.
    1.:Unite
    2.show me the message
![2015-09-26 22-09-28](https://cloud.githubusercontent.com/assets/13142418/10117924/49aa9166-649b-11e5-9bd2-8d6703cbacaa.png)

    3.

    Screen shot (if possible)

**Comment by Shougo** [comment]
It is unite-launch feature.
You must define `g:unite_launch_apps` in your .vimrc.
You should read unite-launch documentation.

**Comment by wsdjeg** [comment]
thank you for your reply,i will read it at once

**Comment by wsdjeg** [comment]
i have add this to my vimrc ,and the issue is gone,thank you!
