### ISSUE TITLE
During search, whitespaces are not converted to folders /

### ISSUE THREAD

**Issue by p3rsist** [Shougo/unite.vim#1029]
This is my config:
call unite#filters#matcher_default#use(['matcher_fuzzy'])
call unite#filters#sorter_default#use(['sorter_rank'])
call unite#custom_source(
            \ 'buffer,file,file_mru,file/new,file_rec,line,file_rec/async', 'matchers', 'matcher_fuzzy')
call unite#custom_source(
            \ 'buffer,file,file_mru,file/new,file_rec,line,file_rec/async', 'converters', 'converter_file_directory')

Whitespaces are working and I'm pretty sure they used to work. Something not okey with my config?

I'm using Vim 7.4-488 with Lua support.

**Comment by Shougo** [comment]
I cannot understand your problem.
I have not ESP skills.
Please read the issue template.
https://github.com/Shougo/unite.vim/issues/584

**Comment by Shougo** [comment]
No response.
