### ISSUE TITLE
Uniteで立ち上げ、削除したbufferが`:bn`コマンドで再度立ち上がってしまう。

### ISSUE THREAD

**Issue by kagerouttepaso** [Shougo/unite.vim#1030]
下記のコマンドで立ち上げたUnite bufferに対し、下記のいずれの方法を使って削除した場合でも、必ず`:bn`コマンドを使ってバッファ移動した際に削除したバッファが蘇ってしまいます。
`:bn`コマンドを使ってもバッファが蘇らないようにする設定などはありますでしょうか?

**立ち上げのコマンド**
1. `:Unite file`
1. `:Unite buffer`

**削除のコマンド**
1. `<Plug>(unite_all_exit)`
1. `:Unite buffer`で選択したUnite bufferに対し、Actionのdeleteを実行。
1. 何らかのActionを実行しUnite bufferが非表示になる。

現象が再現するときのvimrcを添付します。

``` vim
if isdirectory($HOME."/.vim")
  let $DOTVIM_DIR = $HOME."/.vim"
elseif isdirectory($HOME."/vimfiles")
  let $DOTVIM_DIR = $HOME."/vimfiles"
elseif isdirectory($HOME."/dotfiles/_vim")
  let $DOTVIM_DIR = $HOME."/dotfiles/_vim"
endif
set encoding=utf-8

if has('vim_starting')
  set nocompatible
  set runtimepath+=$DOTVIM_DIR/bundle/neobundle.vim/
  set maxfuncdepth=190
endif
call neobundle#begin(expand($DOTVIM_DIR.'/bundle'))

NeoBundle 'Shougo/unite.vim'

call neobundle#end()

```

**Comment by kagerouttepaso** [comment]
また、この現象ですが、自分の環境では、香り屋板GVim 7.4.884 (2015/09/26版)では発現し、cygwin版vim 7.4.838-1では発現しません。
ご参考まで

**Comment by Shougo** [comment]
Fixed.

**Comment by kagerouttepaso** [comment]
動作が改善されていること確認しました。
対応ありがとうございます。
