### ISSUE TITLE
Narrowing not working with fuzzy matcher

### ISSUE THREAD

**Issue by bartlibert** [Shougo/unite.vim#1032]
* Problems summary
When fuzzy matching is enabled, narrowing using space or pipe does not work anymore. It used to work before, but it went wrong with a newer version of unite. 

When typing a first word, I get the results, but if I type a space or "|" after that, no results are shown anymore. When I disable fuzzy matching, it works again.

I confirmed the issue when using both file_rec/async, file and neomru/file.
I tried some "git bisect", but I had to skip some revisions due to other problems, so the result is maybe not as helpful:

There are only 'skip'ped commits left to test.
The first bad commit could be any of:
3b54e4c658c04f733d8da34bd335a8107e000f0b
73b51f35767baba5e7850dce7dbcbc08923863ba
75108159d68d5440f9b455ad9e0b85d9d01b63a2
81801960ed1f461dcc6f5fb814b78e17b2a31322

* Expected
By typing " " or "|" after a first keyword, I should be able to narrow the result list.

* Environment Information
 * OS: reproduced both on Debian stretch/sid and CentOs 6
 * Vim version: 7.4 (patches 1-826) and 7.4 (patches 1-591)

* Minimal vimrc less than 50 lines

```
" Change find arguments
let g:unite_source_rec_find_args = ['-path', '*/.git/*', '-prune', '-o', '-path', '*/.hg/*', '-prune', '-o', '-type', 'l', '-print']

" Use fuzy matching by default
call unite#filters#matcher_default#use(['matcher_fuzzy'])

```

* Reproducable ways from Vim starting

 0. startup vim.
 1. start ':Unite file_rec/async"
 2. type a (part of a) filename
 3. type a space
 4. All results are gone, no narrowing possible

* Screen shot (if possible)

Correct case:
![ok](https://cloud.githubusercontent.com/assets/948770/10282935/a025b3fc-6b7d-11e5-8b25-a5116742003d.gif)

Error case:
![nok](https://cloud.githubusercontent.com/assets/948770/10282947/ab8c60ec-6b7d-11e5-8670-bf232efd2ef6.gif)

**Comment by Shougo** [comment]
Fixed.

**Comment by bartlibert** [comment]
Thank you!
