### ISSUE TITLE
Unexpected E706: Variable type mismatch for: g:unite_source_rec_async_command

### ISSUE THREAD

**Issue by carlesandres** [Shougo/unite.vim#1034]
After updating unite.vim today, the following line in my `.vimrc` is now causing an error:

    let g:unite_source_rec_async_command= 'ag --follow --skip-vcs-ignores --nocolor --nogroup --ignore ".hg" --ignore ".svn" --ignore ".git" --ignore ".bzr" -g ""'

The error is:

    E706: Variable type mismatch for: g:unite_source_rec_async_command

Moreover, `file_rec/async` doesn't ignore my  `.agignore` files anymore.

To be honest, I'm not even sure `ag` is being used by `unite` for `file_rec/async`.

**Comment by carlesandres** [comment]
I didn't notice the accepted type for that option had changed. I've fixed it by changing it to:

let g:unite_source_rec_async_command = ['ag', '--follow', '--skip-vcs-ignores', '--nocolor', '--nogroup', '-g', '']

@Shougo is there a way to be keep track of these breaking changes?

I'll close the issue as it is not such.

**Comment by Shougo** [comment]
#961 

> @Shougo is there a way to be keep track of these breaking changes?

No.  But I added the warning message.

**Comment by carlesandres** [comment]
Thanks! Much appreciated.
