### ISSUE TITLE
2回目のインサートモード開始後、入力がプロンプト行でなく現在候補行にされてしまう

### ISSUE THREAD

**Issue by LeafCage** [Shougo/unite.vim#1037]
再現条件
バージョン7.3.417以下
Win7 64bit gvim (32bitでも発生)
luaなし
発生は[このコミット](https://github.com/Shougo/unite.vim/commit/ee8ba7689b77e7dfc5778c8b64f1f445d2b964ed)から

推定原因（おおまか）
`autocmd InsertCharPre` が定義されないため
実際  InsertCharPre をコメントアウトすると 7.4.843 でも発生する。

スクリーンショットを載せようとしましたが適当なアップローダーが分かりませんでした。

入力例
```
:Unite buffer<CR>
i      #インサートモードを開始する。プロンプト行が現れカーソルがプロンプト行に移動する。
drop     # "drop" で絞り込み
<Esc>     #インサートモードを抜ける
i      #再びインサートモードに入る。プロンプト行は表示されず、現在行先頭でインサートモードになる。
box    # 絞り込み文字列に "box" を追記しようとするが、実際には現在行の候補が先頭に box と入力されて修正される。
```

**Comment by Shougo** [comment]
バッファが modifiable なので行の修正はできないはずです。
ちょっとその状況は再現できていないんですが、以前の挙動のほうがよい人がいるのは確かなので
prompt_focus オプションを追加しました。これを使ってください。

**Comment by Shougo** [comment]
今回の issue には minimal な .vimrc が提示されていません。
それが私の環境で問題を再現できない原因でしょう。

https://github.com/Shougo/unite.vim/issues/584

今度からは issue template を参照してから報告してください。

**Comment by LeafCage** [comment]
vimrcを切り詰めて最小のものを提示しようとしたのですが、どこまで切りつめても問題が発生するので、vimrcに関係なく発生すると判断しました。
プロンプト行を変更するときに、一時的に modifiable に変更されますから、バッファが修正されるのは不思議ではないと思います。カーソルがプロンプト行に移動しないために起きている不具合と思われます。

**Comment by Shougo** [comment]
どこまで切りつめても問題が発生するのなら、最小限の unite 設定を作ってください。

>プロンプト行を変更するときに、一時的に modifiable に変更されますから、バッファが修正されるのは不思議ではないと思います。カーソルがプロンプト行に移動しないために起きている不具合と思われます。

いや、modifiable にされるのはプロンプトに移動したときです。
InsertCharPre イベントが起こらない場合、入力してもプロンプトにそもそも移動しないので modifiable になりません。
だからこの問題が起こるのが不思議なわけです。

**Comment by Shougo** [comment]
unite だけの最小 .vimrc で再現しました。この問題は別に原因を調べます。

>vimrcを切り詰めて最小のものを提示しようとしたのですが、どこまで切りつめても問題が発生するので、vimrcに関係なく発生すると判断しました。

これは issue の最初に書いてください。
最小構成で再現するのなら、こちらでも試せるので。
最初の issue の書きかたでは分かりません。

**Comment by Shougo** [comment]
原因が分かったので修正しました。

**Comment by LeafCage** [comment]
薄々 Shougo さんの設定に問題があるのではと思っていましたが、
さすがにここまではっきり再現しないと名言されたからには最低構成で試されているに違いないと考え、疑念を否定しておりました。

**Comment by Shougo** [comment]
なるほど。双方とも説明不足だったわけですね。
「相手は分かっているだろう」と変に空気を読んでしまうと、このようにすれ違ってしまいます。
だからこそ定型のテンプレートが重要だったりするのですが……。
互いに気をつけましょう。
