### ISSUE TITLE
file_rec/neovim windows support

### ISSUE THREAD

**Issue by prabirshrestha** [Shougo/unite.vim#1038]
This is the only unite config I have set for neovim in windows with `set shellslash` option enabled.

```viml
let g:unite_source_rec_async_command=expand('$ProgramFiles/Git/usr/bin/find.exe')
```

But using `:Unite file_rec/neovim` I still get the following error. Is this not supported on windows?

![image](https://cloud.githubusercontent.com/assets/287744/10419318/c16c9b52-7028-11e5-96b5-5975137c4569.png)

**Comment by Shougo** [comment]
I don't know neovim works in Windows...

But you have the wrong config.

```
					*g:unite_source_rec_async_command*
g:unite_source_rec_async_command
		Specify the filelist command and arguments in file_rec/async
		source.  It is arguments List.
>
		" Using ack-grep as recursive command.
		let g:unite_source_rec_async_command =
		\ ['ack', '-f', '--nofilter']

		" Using ag as recursive command.
		let g:unite_source_rec_async_command =
                \ ['ag', '--follow', '--nocolor', '--nogroup',
		\  '--hidden', '-g', '']
<
		The default value is ["find", "-L"] which follows symbolic
		links to have the same behaviour as file_rec, and the
		args(|g:unite_source_rec_find_args|).
		Because, "find" command is fastest.
		Note: In windows environment, you must install file list
		command and specify the variable.
```

`g:unite_source_rec_async_command` is List.

```
let g:unite_source_rec_async_command= [expand('$ProgramFiles/Git/usr/bin/find.exe'), '-L']
```

**Comment by prabirshrestha** [comment]
Changing to array didn't work.

I'm using neovim-qt binaries from Appveyor. https://github.com/equalsraf/neovim-qt/wiki/Binaries

**Comment by Shougo** [comment]
Hm....  But I cannot support it.
I will add support if neovim Windows version is officially available.

**Comment by Shougo** [comment]
@prabirshrestha 
Please check your command is executable.

`:echo executable(expand('$ProgramFiles/Git/usr/bin/find.exe'))`
