### ISSUE TITLE
Preview highlights non-preview buffers.

### ISSUE THREAD

**Issue by jordwalke** [Shougo/unite.vim#1041]
<img width="1012" alt="unite" src="https://cloud.githubusercontent.com/assets/977348/10563220/5c326a98-7535-11e5-8efb-8c6252b53d94.png">

In this screenshot, you can see how the unite preview highlighting highlights buffers that are not the preview window. In this case, I just happen to have the same file open in a vertical split. Another problem is that when closing Unite, the vertical split remains highlighted (incorrectly). When Unite closes, it should probably clear any preview highlighting it has done, and also only highlight in the preview window (if possible).

**Comment by Shougo** [comment]
> In this screenshot, you can see how the unite preview highlighting highlights buffers that are not the preview window. In this case, I just happen to have the same file open in a vertical split.

It is (Vim's) feature.   The words are highlighted in the search buffers.
So I cannot change it.

>  Another problem is that when closing Unite, the vertical split remains highlighted (incorrectly). 

I think it is fixed.

Important:  Please read the issue template.   I cannot reproduce your problem.
