### ISSUE TITLE
The fix for issue #1040 broke source-specific actions

### ISSUE THREAD

**Issue by wilywampa** [Shougo/unite.vim#1043]
This commit https://github.com/Shougo/unite.vim/commit/8d665589af3d0c8a9e6e463ece9d31bee91265cd which fixed `_choose_action` errors (https://github.com/Shougo/unite.vim/issues/1040) seems to have broken actions defined by a source. For example, run `:Unite process` and `sigkill`, `sigterm`, `sigint` are missing.

**Comment by Shougo** [comment]
Fixed.
