### ISSUE TITLE
Share history across vim instances

### ISSUE THREAD

**Issue by faceleg** [Shougo/unite.vim#1046]
Is this possible using unite/history?

I've set:

```VIMRC
let g:unite_source_history_yank_enable = 1
let g:unite_source_history_yank_file = $HOME . '/.vim/yankring.txt'
```

But `yy` in one vim does not result in an entry appearing in the unite/history list for another vim instance.

**Comment by Shougo** [comment]
Fixed.

**Comment by faceleg** [comment]
WTF Shougo you are a jedi.

**Comment by Shougo** [comment]
I have split the feature to https://github.com/Shougo/neoyank.vim.
Please use it.
