### ISSUE TITLE
Restore cursor position after Unite -no-split

### ISSUE THREAD

**Issue by WscriChy** [Shougo/unite.vim#1049]
I call `:Unite -no-split file` and every time after I quit unit it puts cursor at the first column.

Is it possible to restore cursor after quitting unite.

**Comment by Shougo** [comment]
I cannot reproduce the problem.

https://github.com/Shougo/unite.vim/issues/584

**Comment by WscriChy** [comment]
I fixed it with this changes

    Subject: [PATCH] Fix previous view after Unite with '-no-split' option quits

    ---
     autoload/unite/init.vim | 1 +
     autoload/unite/util.vim | 1 +
     2 files changed, 2 insertions(+)

    diff --git a/autoload/unite/init.vim b/autoload/unite/init.vim
    index 7aa016f..e3d544e 100644
    --- a/autoload/unite/init.vim
    +++ b/autoload/unite/init.vim
    @@ -295,6 +295,7 @@ function! unite#init#_current_unite(sources, context) "{{{
       let unite.prev_bufnr =
             \ (exists('b:unite') && !context.split) ?
             \ b:unite.prev_bufnr : bufnr('%')
    +  let unite.prev_win_saved_view = winsaveview()
       let unite.prev_winnr = winnr()
       let unite.prev_line = 0
       let unite.update_time_save = &updatetime
    diff --git a/autoload/unite/util.vim b/autoload/unite/util.vim
    index 041e469..8261c1a 100644
    --- a/autoload/unite/util.vim
    +++ b/autoload/unite/util.vim
    @@ -249,6 +249,7 @@ function! unite#util#alternate_buffer() "{{{
       if s:buflisted(unite.prev_bufnr)
             \ && getbufvar(unite.prev_bufnr, '&filetype') !=# "unite"
         execute 'buffer' unite.prev_bufnr
    +    keepjumps call winrestview(unite.prev_win_saved_view)
         return
       endif
     
    -- 
    2.1.1

**Comment by Shougo** [comment]
OK.

**Comment by WscriChy** [comment]
I am sorry that was not fully correct I forgot one important line, see the new here

    Subject: [PATCH] Fix previous view after Unite with '-no-split' option quits

    ---
     autoload/unite/init.vim  | 1 +
     autoload/unite/start.vim | 2 ++
     autoload/unite/util.vim  | 1 +
     3 files changed, 4 insertions(+)

    diff --git a/autoload/unite/init.vim b/autoload/unite/init.vim
    index 7aa016f..e3d544e 100644
    --- a/autoload/unite/init.vim
    +++ b/autoload/unite/init.vim
    @@ -295,6 +295,7 @@ function! unite#init#_current_unite(sources, context) "{{{
       let unite.prev_bufnr =
             \ (exists('b:unite') && !context.split) ?
             \ b:unite.prev_bufnr : bufnr('%')
    +  let unite.prev_win_saved_view = winsaveview()
       let unite.prev_winnr = winnr()
       let unite.prev_line = 0
       let unite.update_time_save = &updatetime
    diff --git a/autoload/unite/start.vim b/autoload/unite/start.vim
    index 4677d49..e9a9cd7 100644
    --- a/autoload/unite/start.vim
    +++ b/autoload/unite/start.vim
    @@ -329,6 +329,7 @@ function! unite#start#resume(buffer_name, ...) "{{{
     
       let prev_bufnr = bufnr('%')
       let winnr = winnr()
    +  let prev_win_saved_view = winsaveview()
       let win_rest_cmd = context.unite__direct_switch ||
             \ unite#helper#get_unite_winnr(context.buffer_name) > 0 ?
             \ '' : winrestcmd()
    @@ -347,6 +348,7 @@ function! unite#start#resume(buffer_name, ...) "{{{
       let unite = b:unite
       let unite.winnr = winnr
       let unite.prev_bufnr = prev_bufnr
    +  let unite.prev_win_saved_view = prev_win_saved_view
       let unite.prev_winnr = winnr
       if !context.unite__direct_switch
         let unite.win_rest_cmd = win_rest_cmd
    diff --git a/autoload/unite/util.vim b/autoload/unite/util.vim
    index 041e469..8261c1a 100644
    --- a/autoload/unite/util.vim
    +++ b/autoload/unite/util.vim
    @@ -249,6 +249,7 @@ function! unite#util#alternate_buffer() "{{{
       if s:buflisted(unite.prev_bufnr)
             \ && getbufvar(unite.prev_bufnr, '&filetype') !=# "unite"
         execute 'buffer' unite.prev_bufnr
    +    keepjumps call winrestview(unite.prev_win_saved_view)
         return
       endif
     
    -- 
    2.1.1

**Comment by Shougo** [comment]
@WscriChy 
Please don't send the patch.
Please create Pull request.
I don't want to merge it by hand.

**Comment by Shougo** [comment]
I have added your change.
