### ISSUE TITLE
i am startting to write a plugin for android adb logcat ,how to make unite catch the result of adb log cat

### ISSUE THREAD

**Issue by wsdjeg** [Shougo/unite.vim#1057]
https://github.com/wsdjeg/unite-logcat

**Comment by Shougo** [comment]
You can use `:Unite -log output/shellcmd:adb:logcat` for it.

**Comment by wsdjeg** [comment]
but how can i use this ,i want the output log to be colored
https://github.com/wsdjeg/logcat-color

**Comment by wsdjeg** [comment]
also this coloered logcat is very good
https://github.com/rubzo/coloredlogcat

**Comment by Shougo** [comment]
> but how can i use this ,i want the output log to be colored

You can add the ANSI color support for it.
Pull request is well come.

**Comment by wsdjeg** [comment]
thank you very much
if i want to use ag ,what is the command!
such as adb logcat | ag D/MyActivity

**Comment by wsdjeg** [comment]
when i use the cammand you give me ,the vim show me `Invalid source name "output/shellcmd" is detected.`

**Comment by Shougo** [comment]
> when i use the cammand you give me ,the vim show me Invalid source name "output/shellcmd" is detected.

Please update unite.vim to latest version.

> thank you very much
> if i want to use ag ,what is the command!
> such as adb logcat | ag D/MyActivity

`:Unite -log -wrap output/shellcmd:adb\ logcat|ag\ D/MyActivity`

> but how can i use this ,i want the output log to be colored
> https://github.com/wsdjeg/logcat-color

> also this coloered logcat is very good
> https://github.com/rubzo/coloredlogcat

I have tested both.
coloredlogcat doe not be colored.
logcat-color works.

**Comment by wsdjeg** [comment]
thank you for doing so much
in cammand line ,when start adb logcat it will not stop by itself,i need to type <c-c>
in the Unite ,if i close the Unite Buffer ,will the adb stop ?

**Comment by Shougo** [comment]
> in the Unite ,if i close the Unite Buffer ,will the adb stop ?

Yes.

**Comment by wsdjeg** [comment]
hi i find the coloredlogcat  works but has no color
let me show you the pic
`:Unite -log -wrap output/shellcmd:adb\ logcat\ -s\ MyActivity:d|~/test/coloredlogcat.py`

![2015-11-04 22-34-21](https://cloud.githubusercontent.com/assets/13142418/10940988/60d08fc2-8344-11e5-9dfb-899f1475aced.png)
`:Unite -log -wrap output/shellcmd:adb\ logcat\ -s\ MyActivity:d`
![2015-11-04 22-34-35](https://cloud.githubusercontent.com/assets/13142418/10941038/9b0c7584-8344-11e5-9e6e-d74546dd46d7.png)

**Comment by wsdjeg** [comment]
here is the pic for ag, colored the keywords
![2015-11-04 22-40-20](https://cloud.githubusercontent.com/assets/13142418/10941161/1e88569e-8345-11e5-92b1-a7f42870316e.png)

**Comment by Shougo** [comment]
> hi i find the coloredlogcat works but has no color

Why don't you read my previous comment?

> I have tested both.
> coloredlogcat doe not be colored.
> logcat-color works.

coloredlogcat has no color.
Because, it uses output/shellcmd not supported(complex) ESC codes.
It is feature.

**Comment by wsdjeg** [comment]
sorry it's my fault,thank you for adding the chellcmd source

**Comment by wsdjeg** [comment]
will the output log date update,when i close the android activiy and reopen it,i find i need to close Unite and reopen it to update the output

**Comment by Shougo** [comment]
@wsdjeg You can use `<Plug>(unite_redraw)` for it.

**Comment by wsdjeg** [comment]
how to begin with nomal mode

**Comment by Shougo** [comment]
Please read the unite documentation.
I'm not your helper.

**Comment by wsdjeg** [comment]
sorry,i should not ask so simple question,i will read the doc

**Comment by wsdjeg** [comment]
hi @Shougo 
alfter `:Unite -log output/shellcmd:` the space and ':'  in cmd should be change to '\ 'and '\:'
i think this should be add to plugin's doc

**Comment by Shougo** [comment]
This is unite command line feature.

Already documented.

```
	Note: In the evaluation, The special characters(spaces,  "\" and ":")
	are escaped automatically.
>
        :Unite -buffer-name=search%`bufnr('%')` line:forward:wrap<CR>
<
```

**Comment by wsdjeg** [comment]
but after :Unite -log output/shellcmd: these three characters will not be escaped automatically,we need too add \,for example
if i want to show the result of java -cp .:bin com.wsdjeg.test
i need to use

:Unite -log output/shellcmd:java\ -cp\ .\:bin com.wsdjeg.test

**Comment by Shougo** [comment]
You can use eval feature.

```vim
:Unite -log output/shellcmd:`"java -cp . bin com.wsdjeg.test"
```

**Comment by wsdjeg** [comment]
yes i have understand,thank you,and  all the cmd command should be the input of out/shellcmd,so it should not contains space and so on,it must be a continuously string
