### ISSUE TITLE
Start Unite in normal mode with -start-insert when resuming

### ISSUE THREAD

**Issue by nilsboy** [Shougo/unite.vim#1058]
When I run
:Unite -resume -start-insert file<cr>
It starts in insert mode.
When I run it again I would like it start in normal mode so I can start navigating directly without having to hit <esc> first.
Is that already possible or would this be a new feature?
If its a new feature mabe it could look something like this:
:Unite -resume -resume-in-normal-mode -start-insert file<cr>

Thank you.

**Comment by Shougo** [comment]
No.  I don't want to add the feature.
