### ISSUE TITLE
Using output/shellcmd to run tests

### ISSUE THREAD

**Issue by tbastos** [Shougo/unite.vim#1060]
I guess `output/shellcmd` could be used to run tests asynchronously and display the results in Vim with ANSI colors? That's something I've been missing in Vim for a while!

I'm using [vim-test](https://github.com/janko-m/vim-test) to run tests via [vim-dispatch](https://github.com/tpope/vim-dispatch), now I think I'll write a Unite integration for vim-test.

So, I tried using the following and it _almost_ worked:
`Unite -log -no-start-insert output/shellcmd:busted`

Output in Unite: 
<img width="485" alt="test-unite" src="https://cloud.githubusercontent.com/assets/150480/10926879/62d535e2-829b-11e5-9eae-0761c2819a0d.png">

Output in iTerm:
<img width="495" alt="test-iterm" src="https://cloud.githubusercontent.com/assets/150480/10926887/714a12b4-829b-11e5-9261-0944376e2c0f.png">

It's eating some characters there. Any idea of what might be wrong?

BTW it would be nice if Unite had a command like `:UniteShellCmd` to replace `:Dispatch` from [vim-dispatch](https://github.com/tpope/vim-dispatch), but with colors. 

Thanks :smiley:

**Comment by Shougo** [comment]
> It's eating some characters there. Any idea of what might be wrong?

`Unite -log -wrap -no-start-insert output/shellcmd:busted`

> BTW it would be nice if Unite had a command like :UniteShellCmd to replace :Dispatch from vim-dispatch, but with colors. 

You can create the command for it.

**Comment by tbastos** [comment]
Tested with the latest update, `-wrap` and `setlocal nowrap`, but there are still problems

Output:
<img width="692" alt="unite" src="https://cloud.githubusercontent.com/assets/150480/10948612/bcfeaf9c-832e-11e5-9e0f-f090603e8c8a.png">

The verbatim hex dump of busted's output: https://gist.github.com/tbastos/46d6994b21e47de2ede5

Could it be some internal Vim limitation? Max number of conceals per line? This would be unfortunate...

**Comment by Shougo** [comment]
@tbastos It may be Vim's problem.
But I must test it.  Please read the issue template.
