### ISSUE TITLE
How to use ignore_globs for grep

### ISSUE THREAD

**Issue by jithin1987** [Shougo/unite.vim#1061]
I have this set in my `.vimrc` file
 ```
call unite#custom#source('grep', 'ignore_globs', ['./public/*'])
nnoremap <leader>/ :Unite grep:`projectroot#guess()`<cr>

``` 
I expected `Unite` to ignore any files under `./public`. But that is not the case. Am I using this incorrectly ?

**Comment by jithin1987** [comment]
Got it working by removing `./` from ignore pattern. Since I have set `projectroot#guess()` as beginning directory for `Unite grep:` shouldn't `'./public/*'` worked as an ignore pattern ?

**Comment by ujihisa** [comment]
Good!

By the way where `projectroot#guess()` you got from?

**Comment by jithin1987** [comment]
Its from dbakker/vim-projectroot

**Comment by Shougo** [comment]
@jithin1987 "./" is current directory.  But `projectroot#guess()` is not change the current directory.
It is feature.
