### ISSUE TITLE
Invalid source name "history/yank" is detected

### ISSUE THREAD

**Issue by wsdjeg** [Shougo/unite.vim#1062]
why i can not use this source `history/yank`?
here is my setting
`let g:unite_source_history_yank_enable=1`
`nnoremap <leader>f :<C-u>Unite -no-split -buffer-name=files -start-insert file<cr>`
when i type `\f`
the vim show me `Invalid source name "history/yank" is detected`

**Comment by Shougo** [comment]
It is split.
And you don't have to set `g:unite_source_history_yank_enable`.
Please install https://github.com/Shougo/neoyank.vim.

**Comment by wikimatze** [comment]
Had the same errors, thanks for mentioning that is now an extra repository.
