### ISSUE TITLE
Delete left behind Unite buffers?

### ISSUE THREAD

**Issue by Murlocks** [Shougo/unite.vim#1063]
On some unite actions a new unite buffer is created (narrowing on cdable kind), and even though I am using (unite_all_exit) there are unite buffers that are left behind.

minimal vimrc:
```
set nocompatible
set runtimepath+=~/.vim/bundle/unite.vim/

function! s:unite_my_settings() " {{{

  nmap <buffer> q          <Plug>(unite_all_exit)
  nmap <buffer> <ESC>      <Plug>(unite_all_exit)
  nmap <buffer> <c-c>      <Plug>(unite_all_exit)

endfunction " }}}

autocmd FileType unite call s:unite_my_settings()
```
Steps to reproduce:
1. narrow on directory (CR) and pop back out (C-h) multiple times, creating multiple unite buffers.
2. In normal mode press q
3. ```:ls``` shows left behind Unite buffers

Is there any way to delete all Unite buffers on exiting Unite?

**Comment by Shougo** [comment]
`:Unite -auto-quit`

You cannot use resume feature though.

**Comment by Murlocks** [comment]
I tried out using the ```-auto-quit``` option but the steps above still leave behind a lot of "default" unite buffers. Any other ideas? Thanks.

**Comment by Shougo** [comment]
Sorry, `:Unite -wipe` is correct option.
