### ISSUE TITLE
`g:unite_source_rec_async_command` setting is not repsected

### ISSUE THREAD

**Issue by aandrieiev** [Shougo/unite.vim#1066]
* Summary:
Setting `g:unite_source_rec_async_command` to a custom search command makes no difference to search output. The list of candidates returned looks the same as with the default `find` and contains the same number of candidates (in my case, 1220) as before the change

* Expected:
Setting it to a custom command changes the output. For example it has to return exactly the same number of files as running the custom command from command line, e.g. `$ ag --follow --nogroup --nocolor --hidden -g "" | wc -l => 1241`

* Environment Information:
 * OS: OS X 10.11; Ubuntu 14.04
 * Vim version: 7.4.903; 7.4.52; 

* Minimal vimrc less than 50 lines:

```
set nocompatible
set rtp+=~/.vim/bundle/neobundle.vim
call neobundle#begin(expand('~/.vim/bundle/'))

NeoBundle 'Shougo/unite.vim'

NeoBundle 'Shougo/vimproc.vim', {
      \ 'build' : {
      \     'mac' : 'make',
      \     'linux' : 'make'
      \    },
      \ }

call neobundle#end()
filetype plugin indent on
NeoBundleCheck

let g:unite_source_rec_neovim_command =
    \ ['ag', '--follow', '--nogroup', '--nocolor', '--hidden', '-g', '']

let mapleader="\<Space>"
nnoremap <leader>f :<C-u>Unite -start-insert file_rec/async<CR>
```

* How to reproduce:

 0. Start Vim 
 1. Press space+f 
 2. See the candidate list and their overall number

* Screen shot:
![Screenshot](http://imgur.com/GQg0hT8.png)

* Extra notes:
The number of files is used as an example to demonstrate the issue. In bigger projects ack/ag/pt are the only means to easily respect .gitignore in order to keep the number of candidates sane. But since it's currently impossible to use them, default `find` returns literally everything which leads to significant delays.

**Comment by Shougo** [comment]
`g:unite_source_rec_async_command` is correct variable name.

```vim
let g:unite_source_rec_async_command =
    \ ['ag', '--follow', '--nogroup', '--nocolor', '--hidden', '-g', '']
```

**Comment by aandrieiev** [comment]
I am sorry, looks like an artifact left after my experiments with `file_rec/neovim` source. Nevertheless, using the correct variable name doesn't change anything. The number of files returned is still 1220, while `ag` returns 1241: 

```
set rtp+=~/.vim/bundle/neobundle.vim
call neobundle#begin(expand('~/.vim/bundle/'))

NeoBundle 'Shougo/unite.vim'

NeoBundle 'Shougo/vimproc.vim', {
      \ 'build' : {
      \     'mac' : 'make',
      \     'linux' : 'make'
      \    },
      \ }

call     neobundle#end()
filetype plugin indent on
NeoBundleCheck

let g:unite_source_rec_async_command =
    \ ['ag', '--follow', '--nogroup', '--nocolor', '--hidden', '-g', '']

let mapleader="\<Space>"
noremap <leader>f :<C-u>Unite -start-insert file_rec/async:!<CR>
```

**Comment by Shougo** [comment]
I think the result is cached.
Please clear the cache.

**Comment by alexbooker** [comment]
I had the same problem. Clearing the cache (`rm -rf ~/.cache/unite/file_rec`) worked for me :smile:

**Comment by lithp** [comment]
I appear to be having the same problem, after changing `g:unite_source_rec_async_command` to `false` and emptying the cache I still saw all the files I was previously, as if nothing had changed.
