### ISSUE TITLE
VCS management plugins

### ISSUE THREAD

**Issue by JCavallo** [Shougo/unite.vim#1067]
Hi,

I made a unite plugin to manage mercurial : 
https://github.com/JCavallo/vim-hg-unite

I am starting to use git rather than mercurial, and wondered if anyone knew of an existing plugin that interacts well with unite that manages git. I looked in the unite plugins wiki page, but my japanese is a little rusty :D

If nothing exists yet, I will probably create a vcs-unite plugin which will handle both git and mercurial soon :)

**Comment by Shougo** [comment]
I know the git source for unite.

https://github.com/kmnk/vim-unite-giti

**Comment by JCavallo** [comment]
Thank you very much, that's exactly what I was looking for.
