### ISSUE TITLE
Ignore vim doc files in neomru source

### ISSUE THREAD

**Issue by petobens** [Shougo/unite.vim#1070]
I want to ignore the vim doc files in neomru. The following used to work:

```vim
    call unite#custom#source('file_mru',
                \ 'ignore_pattern', join(['\.git\/', 'tmp\/', 'doc\/'], '\|')
                \ )
```

However now if for instance I run `:h :file` then in the neomru buffer I see 
```
    C:/prog-tools/Vim/vim74/doc/editing.txt
```

So my question is: how can I ignore vim help files in neomru?

**Comment by Shougo** [comment]
Hm...
Vim help file should be ignored by default.
I want to reproduce the behaviour.

Please read the issue template.

**Comment by petobens** [comment]
Consider the following minimal vimrc:

```vim
set nocompatible

let $ONEDRIVE_HOME = expand('C:/OD/OneDrive/Users/Pedro')
let $DOTVIM = expand('$ONEDRIVE_HOME/vimfiles')

set runtimepath+=$DOTVIM/bundle/unite
set runtimepath+=$DOTVIM/bundle/neomru/
filetype plugin indent on

call unite#custom#source('file_mru',
            \ 'ignore_pattern', join(['\.git\/', 'tmp\/', 'doc\/'], '\|')
            \ )
```

Now, as in the GIF, do the following:

i) Open Gvim and run `:Unite neomru/file`: you will see that there are no candidates
ii) Run `:h :file` and once the help buffer opens close it
iii) Run `:Unite neomru/file`: the `editing.txt` file is shown as a candidate but I expect help files not to be shown as candidates

![blahh](https://cloud.githubusercontent.com/assets/2583971/11324156/789a6ab6-9108-11e5-92bf-f5fcf428d74d.gif)

**Comment by Shougo** [comment]
Reproduced.  It is neomru's problem.
Please update neomru.

**Comment by petobens** [comment]
Thank you.
