### ISSUE TITLE
file_rec/neovim adds trailing characters to file names and paths

### ISSUE THREAD

**Issue by mhartington** [Shougo/unite.vim#1077]
Using the latest neovim, neobundle, and unite, if you run `Unite file_rec/neovim`, the files paths and file names gets appended with some extra characters

<img width="893" alt="screen shot 2015-11-29 at 11 49 53 am" src="https://cloud.githubusercontent.com/assets/2835826/11458533/ed41db92-968f-11e5-9d4f-c4fe2075edd7.png">
<img width="1166" alt="screen shot 2015-11-29 at 11 54 25 am" src="https://cloud.githubusercontent.com/assets/2835826/11458538/f6ee5030-968f-11e5-904f-e0f37902f885.png">

Minimal config, 

Include neobundle and unite
Use this unite search config

```
  let g:unite_data_directory='~/.nvim/.cache/unite'
  let g:unite_enable_start_insert=1
  let g:unite_source_history_yank_enable=1
  let g:unite_prompt='>> '
  let g:unite_split_rule = 'botright'
  let g:unite_source_rec_async_command =['ag', '--follow', '--nocolor', '--nogroup','--hidden', '-g', '', '--ignore', '.git', '--ignore', '*.png', '--ignore', 'lib']
  nnoremap <silent> <c-p> :Unite -auto-resize file_rec/neovim<CR>
```

Maybe something to do with using ag for the search?

**Comment by Shougo** [comment]
Reproduced.  I will fix it later.

**Comment by Shougo** [comment]
Fixed.
