### ISSUE TITLE
Grep/Neovim source

### ISSUE THREAD

**Issue by martin-svk** [Shougo/unite.vim#1078]
Hi, I am using Neovim and I just switched from `file_rec/async!` to `file_rec/neovim` source to be able to remove `vimproc` dependency. But then I noticed the `grep` source need `vimproc` as well.

Is there a possibility that similarly a `grep/neovim` source will be implemented? Thanks.

**Comment by Shougo** [comment]
No.  Because, I will create the rewrite of unite.vim plugin for neovim.
Yes, "grep/neovim" can remove the vimproc dependency.
But it is not faster.  No means for me.

**Comment by martin-svk** [comment]
Thanks for answer. I am looking forward to the neovim rewrite then. Any time-frame?

**Comment by Shougo** [comment]
It is in 2016.
