### ISSUE TITLE
`:Unite -start-insert file_rec/neovim` starts with 0 results instead of listing all files in current directory

### ISSUE THREAD

**Issue by vinsonchuong** [Shougo/unite.vim#1079]
## Problem Summary
In Neovim 0.1.0, running `:Unite file_rec/neovim` lists the files in the current directory as expected. However, when adding the `-start-insert` option (e.g. `:Unite -start-insert file_rec/neovim`), an empty buffer is shown instead. Files are populated after typing a character though.

## Expected
Even when using the `-start-insert` option, a list of files are shown without having to enter any search query.

## Environment Information
 * OS: Arch Linux
 * Vim version: Neovim 0.1.0

## Minimal init.vim
```
set runtimepath+=~/path/to/unite.vim/
```

## Steps to Reproduce
1. `mkdir directory`
1. `cd directory`
1. `touch file1 file2`
1. Run `nvim -u minimal_init.vim -c ':Unite -start-insert file_rec/neovim'` and compare with running `nvim -u minimal_init.vim -c ':Unite file_rec/neovim'`

**Comment by Shougo** [comment]
Reproduced.  It is neovim bug.
"CursorHoldI" autocmd is not triggered.

https://github.com/neovim/neovim/issues/3757

**Comment by wsdjeg** [comment]
thanks for the links

**Comment by wsdjeg** [comment]
marked,just encounter this issue,just want to open an issue,but it is here now.

**Comment by alexanderjeurissen** [comment]
I'm currently using the latest version of Unite on neovim 0.1.3 and `file_rec/neovim` works just fine, can you try updating to the latest version of neovim to see if this fixes your problems ?

**Comment by wsdjeg** [comment]
@alexanderjeurissen are you sure? I test it in the latest version unite and neovim ,still return 0.until I switch to normal mode,the result will be shown.

**Comment by gbcreation** [comment]
@wsdjeg I have the same result as you.

**Comment by alexanderjeurissen** [comment]
Hmm that is weird I use the following keybinds:

```vimscript
    nmap <leader>f [unite]
    nmap [unite] <nop>

    nnoremap <silent> [unite]m  :<C-u>Unite
          \ -start-insert -no-split file_rec/neovim:! buffer file_mru<CR>
```
and the list gets populated without me having to switch modes. Sure there is a small delay in large repositories but that is unavoidable with the current unite implementation.

my neovim version:
![screen shot 2016-04-25 at 15 44 35](https://cloud.githubusercontent.com/assets/1220084/14785779/b08adc80-0afc-11e6-9867-c3b53b2979d0.png)

**Comment by gbcreation** [comment]
@alexanderjeurissen You are using several Unite sources in your mapping. I think you get only the candidates of `buffer` and `file_mru` in the list. Can you test this command and tell if the list gets populated: `:Unite -start-insert file_rec/neovim` ?

**Comment by alexanderjeurissen** [comment]
@gbcreation In addition to testing my own config where I use multiple sources, I also tried a minimal neovim config using only the `file_rec/neovim` source and I can't reproduce your issue.

In other words: `:Unite -start-insert file_rec/neovim` does work on all of my machines (all of which run osx)

**Comment by alexanderjeurissen** [comment]
I just tried a minimal init.vim with only a `set runtimepath` to a unite.vim folder and can reproduce this error. So something in my configuration make unite work as expected. Not sure what..

**Comment by alexanderjeurissen** [comment]
Ok so I think somehow using the minimal init.vim unite gets stuck in async in some cases. The screenshot below shows the issue where the list doesn't get populated. In this directory I can reproduce the error every time.. however in other git repositories I can't.

<img width="1042" alt="screen shot 2016-04-26 at 01 48 18" src="https://cloud.githubusercontent.com/assets/1220084/14802463/3d060a50-0b51-11e6-9bc4-0ddc92c87e41.png">

**Comment by Shougo** [comment]
I have fixed.

**Comment by Shougo** [comment]
Oh, neovim timers feature does not work in insert mode with neovim job feature.

**Comment by wsdjeg** [comment]
@Shougo why I can not reproduce this issue, `:Unite -start-insert file_rec/neovim` show me 
![2016-05-28-09 23 36](https://cloud.githubusercontent.com/assets/13142418/15624270/08a6e2e2-24b6-11e6-9ecc-7b63c8b6fc05.png)

**Comment by Shougo** [comment]
@wsdjeg I think the files are already cached.
Please clear the cache.

**Comment by wsdjeg** [comment]
@Shougo thanks, I got it, `ctrl + l` will clean up all the result. I need switch to normal modle, then the result will be shown.

**Comment by Shougo** [comment]
You should use denite.nvim instead.

https://github.com/Shougo/denite.nvim
