### ISSUE TITLE
Large output display in unite.vim?

### ISSUE THREAD

**Issue by phongvcao** [Shougo/unite.vim#1082]
I am currently using `unite.vim` to replace my quickfix window. I've noticed that with files that have more than 40 lines (which is the `g:unite_winheight` value in my `.vimrc`), `unite.vim` only displays 40 lines (my file has 400 lines total). When I press `G` in normal mode to go to the end of the file in unite window, it only goes to line 41. Is there anyway to load the whole file into `unite` window/buffer instead of just 40 lines?

**Comment by Shougo** [comment]
@phongvcao My ESP skill results:

You must set `g:unite_no_default_mappings` variable to 0.
Because, unite overwrites `G` mapping to display all candidates.
But you have disabled it.
Result:  You cannot see all candidates in unite buffer.
