### ISSUE TITLE
UniteDo

### ISSUE THREAD

**Issue by MaienM** [Shougo/unite.vim#1084]
Would it be possible to add a command that works like :argdo, but then for the current list of unite matches? Sort of like :UniteNext/:UnitePrev.

What I currently usually do is start at the last match, and record a macro with the command I want to execute and :UnitePrev in it, but that is somewhat error-prone and tedious.

**Comment by Shougo** [comment]
I don't want to add the feature.
You can add it.
It is not difficult feature.

**Comment by Shougo** [comment]
Dup of #812
