### ISSUE TITLE
Grep source inexplicable error messages

### ISSUE THREAD

**Issue by zoqaeski** [Shougo/unite.vim#1085]
I'd like to use `ag` as the grep program in the Unite grep source, but I keep getting the following error message:

    [unite.vim] [grep] Your grep configuration is wrong. Please check ":help unite-source-grep" example.

I've set the configuration so it is the same as in the help text, and yet nothing displays if I put `ag` ahead of `ack` or any other grep program I have installed. If I put `ack` first in the list, I still get the error message, but eventually vimproc starts returning results (sometimes). I'm running the latest versions of all plugins and programs, and the relevant `init.vim` section is as follows:

    NeoBundle 'Shougo/unite.vim'
    let bundle = neobundle#get('unite.vim')
    function! bundle.hooks.on_source(bundle)
      call unite#filters#matcher_default#use(['matcher_fuzzy'])
      call unite#filters#sorter_default#use(['sorter_rank'])
      call unite#custom#profile('files', 'context.smartcase', 1)
      call unite#custom#source('line,outline','matchers','matcher_fuzzy')
    endfunction
    
    if neobundle#tap('unite.vim')
      function! neobundle#hooks.on_source(bundle)
    
        let g:unite_data_directory='~/.config/nvim/.cache/unite'
        let g:unite_enable_start_insert=0
        let g:unite_source_history_yank_enable=1
        let g:unite_source_rec_max_cache_files=5000
        let g:unite_prompt='» '
    
        if executable('ack')
          let g:unite_source_grep_command='ack'
          let g:unite_source_grep_default_opts='--no-heading --no-color -C4'
          let g:unite_source_grep_recursive_opt=''
        elseif executable('ag')
          let g:unite_source_grep_command='ag'
          let g:unite_source_grep_default_opts=''
          let g:unite_source_grep_recursive_opt=''
        endif
    
        function! s:unite_settings()
          nmap <buffer> Q <plug>(unite_exit)
          nmap <buffer> <esc> <plug>(unite_exit)
          imap <silent><buffer><expr> <C-i> unite#do_action('split')
          imap <silent><buffer><expr> <C-v> unite#do_action('vsplit')
        endfunction
        autocmd FileType unite call s:unite_settings()
    
        nmap <space> [unite]
        nnoremap [unite] <nop>
    
        nnoremap <silent> [unite]/ :<C-u>Unite -buffer-name=search -no-quit grep:.<cr>
      endfunction
      call neobundle#untap()
    endif
    
OS: Arch Linux x86_64
Neovim version: 

    NVIM v0.1.1-15-g81960df (compiled Dec 12 2015 20:18:57)
    Commit: 81960df9f55a1d378185e381fd81c2f21b56e085
    Build type: Dev
    Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -Wconversion -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto
    
    Optional features included (+) or not (-): +acl   +iconv    +jemalloc
    For differences from Vim, see :help vim-differences
    
       system vimrc file: "$VIM/sysinit.vim"
         fall-back for $VIM: "/usr/share/nvim"

**Comment by Shougo** [comment]
@zoqaeski Your ag's configuration is wrong.
Example configuration for ag:

```
	  let g:unite_source_grep_command = 'ag'
	  let g:unite_source_grep_default_opts =
	  \ '-i --vimgrep --hidden --ignore ' .
	  \ '''.hg'' --ignore ''.svn'' --ignore ''.git'' --ignore ''.bzr'''
	  let g:unite_source_grep_recursive_opt = ''
```
