### ISSUE TITLE
Support file_rec/git for NeoVim

### ISSUE THREAD

**Issue by bicycle1885** [Shougo/unite.vim#1088]
Hi,

I've started to migrate to neovim from vim these days and almost all of your plugins work fine. But I couldn't find a way to activate the file_rec/git source in neovim. Is there any way to use file_ref/git without installing vimproc like old vim? If not, do you have a plan to support the functionality like file_rec/neovim?

---

I'm using OS X Yosemite (10.10.5) and NVIM 0.1.1 installed with homebrew.

```
$ nvim --version
NVIM 0.1.1 (compiled Dec 17 2015 11:34:21)
Build type: RelWithDebInfo
...
```

**Comment by Shougo** [comment]
@bicycle1885 I don't want to add new sources for neovim.
Because, it is infinite loop.

file_rec/git -> grep -> find -> .... and so on.

And unite.vim is slower in neovim.
I will create unite.vim for neovim.

**Comment by bicycle1885** [comment]
Fair enough.

> I will create unite.vim for neovim.

It sounds pretty awesome! I hope to see it in neovim.

**Comment by bicycle1885** [comment]
Ah, and thank you for your reply :smiley:
