### ISSUE TITLE
UniteNext skip item after using UnitePrevious loop back

### ISSUE THREAD

**Issue by chemzqm** [Shougo/unite.vim#1089]
* Problems summary

When I use Unite with `-no-quit` option, and iterater with `:UniteNext` and `:UnitePrevious`, the `:UniteNext` command would skip one candidate.

* Expected

`:UniteNext` should not skip valid candidate

* Environment Information
 * OS: mac osx
 * Vim version: 7.4 Included patches 1-922
* Enabled lua interface: yes

* Minimal vimrc less than 50 lines

```
set nocompatible
set runtimepath+=~/path/to/unite.vim/
```

* Reproducable ways from Vim starting

 0. mkdir a folder and create three files: `fileA`, `fileB`, `fileC`
 1. startup vim.
 2. use command `:Unite file_rec -no-quit`
 3. use `:UniteNext` navigate to `fileC` (or just select `fileC` by type `<cr>`)
 4. use `:UnitePrevious` twice navigate to `fileA`
 5. use `:UniteNext`, it would jump to `fileC` this time, which should be `fileB`

**Comment by Shougo** [comment]
Fixed.
