### ISSUE TITLE
Unite resume works only once

### ISSUE THREAD

**Issue by tex** [Shougo/unite.vim#1090]
" Disable vi-compatibility
set nocompatible

set runtimepath+=~/.vim/bundle/unite.vim
set runtimepath+=~/.vim/bundle/vimproc

====

:Unite file_rec
q
:Unite -buffer-name=resume resume
`<CR>`
q
:Unite -buffer-name=resume resume
`<CR>`

Expected: to see what I saw the first time: resumed file_rec buffer.
What I see: nothing from Unite, only the original user buffer.

EDITED: `<CR>` was eaten by this markdown...

**Comment by Shougo** [comment]
Unfortunately, I cannot reproduce the problem.
My tested .vimrc.

```vim
" Your vimrc
set nocompatible

set runtimepath+=~/work/unite.vim/

filetype plugin indent on

nnoremap <silent> <F1> :Unite file<CR>
nnoremap <silent> <F2> :Unite -buffer-name=resume resume<CR>
```

Reproduce ways:

* `<F1>`
* q
* `<F2>`
* q
* `<F2>`

Please test it.

**Comment by tex** [comment]
I see my problem even with your config.

Second <F2> shows Unite resume correcctly, it even lists the file buffer, but hitting <CR> on it returns me into original buffer, it does not resume file buffer.

VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Nov 30 2015 08:28:28)
Použité záplaty: 1-944
přeložil  Arch Linux
maximální verzewith GTK2 GUI. Vlastnosti zahrnuté (+) a nezahrnuté (-):
+acl             +farsi           +mouse_netterm   +syntax
+arabic          +file_in_path    +mouse_sgr       +tag_binary
+autocmd         +find_in_path    -mouse_sysmouse  +tag_old_static
+balloon_eval    +float           +mouse_urxvt     -tag_any_white
+browse          +folding         +mouse_xterm     -tcl
++builtin_terms  -footer          +multi_byte      +terminfo
+byte_offset     +fork()          +multi_lang      +termresponse
+cindent         +gettext         -mzscheme        +textobjects
+clientserver    -hangul_input    +netbeans_intg   +title
+clipboard       +iconv           +path_extra      +toolbar
+cmdline_compl   +insert_expand   +perl            +user_commands
+cmdline_hist    +jumplist        +persistent_undo +vertsplit
+cmdline_info    +keymap          +postscript      +virtualedit
+comments        +langmap         +printer         +visual
+conceal         +libcall         +profile         +visualextra
+cryptv          +linebreak       +python          +viminfo
+cscope          +lispindent      -python3         +vreplace
+cursorbind      +listcmds        +quickfix        +wildignore
+cursorshape     +localmap        +reltime         +wildmenu
+dialog_con_gui  +lua             +rightleft       +windows
+diff            +menu            +ruby            +writebackup
+digraphs        +mksession       +scrollbind      +X11
+dnd             +modify_fname    +signs           -xfontset
-ebcdic          +mouse           +smartindent     +xim
+emacs_tags      +mouseshape      -sniff           +xsmp_interact
+eval            +mouse_dec       +startuptime     +xterm_clipboard
+ex_extra        +mouse_gpm       +statusline      -xterm_save
+extra_search    -mouse_jsbterm   -sun_workshop    -xpm
   systémový vimrc soubor: "/etc/vimrc"
     uživatelský vimrc soubor: "$HOME/.vimrc"
 druhý uživatelský vimrc soubor: "~/.vim/vimrc"
      uživatelský exrc soubor: "$HOME/.exrc"
  systémový gvimrc soubor: "/etc/gvimrc"
    uživatelský gvimrc soubor: "$HOME/.gvimrc"
druhý uživatelský gvimrc soubor: "~/.vim/gvimrc"
    systémový soubor s menu: "$VIMRUNTIME/menu.vim"
  implicitní hodnota $VIM:"/usr/share/vim"
Překlad: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-2.0 -I/usr/lib/gtk-2.0/include -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/libdrm -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/pango-1.0 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -D_FORTIFY_SOURCE=2  -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linkuji: gcc   -L. -Wl,-O1,--sort-common,--as-needed,-z,relro -fstack-protector -rdynamic -Wl,-export-dynamic -Wl,-E -Wl,-rpath,/usr/lib/perl5/core_perl/CORE  -Wl,-O1,--sort-common,--as-needed,-z,relro -L/usr/local/lib -Wl,--as-needed -o vim   -lgtk-x11-2.0 -lgdk-x11-2.0 -lpangocairo-1.0 -latk-1.0 -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lpangoft2-1.0 -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lfontconfig -lfreetype -lSM -lICE -lXt -lX11 -lXdmcp -lSM -lICE  -lm -lncurses -lelf -lnsl   -lacl -lattr -lgpm -ldl  -L/usr/lib -llua -Wl,-E -Wl,-rpath,/usr/lib/perl5/core_perl/CORE -Wl,-O1,--sort-common,--as-needed,-z,relro -fstack-protector-strong -L/usr/local/lib  -L/usr/lib/perl5/core_perl/CORE -lperl -lpthread -lnsl -ldl -lm -lcrypt -lutil -lc -L/usr/lib/python2.7/config -lpython2.7 -lpthread -ldl -lutil -lm -Xlinker -export-dynamic   -lruby -lpthread -lgmp -ldl -lcrypt -lm  -L/usr/lib

**Comment by tex** [comment]
Each time Unite resume shows enter `<CR>` to actually resume the file buffer.

**Comment by Shougo** [comment]
OK.  Reproduced.

**Comment by Shougo** [comment]
Fixed.

**Comment by tex** [comment]
Thanks! Fixed.

Just one nitpick. Is it possible to remember input for each Unite buffer? What I see is that any input (filter) in file / grep buffer entered is cleared when resumed with Unite resume.

**Comment by Shougo** [comment]
Fixed.

**Comment by tex** [comment]
Thank you!
