### ISSUE TITLE
how to deal with `"` in output:shellcmd?

### ISSUE THREAD

**Issue by wsdjeg** [Shougo/unite.vim#1092]
i have to exec a cmd in unite ,it works well in linux,but in windows,has a lot of issues;
for example i will exec
`java -cp "c:\Program Files\test\" com.wsdjeg.Test`
the cmd contains a space and two `"`.

**Comment by Shougo** [comment]
You should use `:Unite output/shellcmd:java:-cp:'c:/Program\ Files/test/' com.wsdjeg.Test`.

**Comment by wsdjeg** [comment]
do you means we need change space to :,and change"to'

**Comment by Shougo** [comment]
> do you means we need change space to :,and change"to'

In unite, you must escape the spaces.
But you can separate them as `:`.

If you use `'`, you can use `"` in `'` blocks.

`:Unite output/shellcmd:java:-cp:'"c:/Program\ Files/test/"' com.wsdjeg.Test`

**Comment by wsdjeg** [comment]
ok thank ,got it
