### ISSUE TITLE
Question: Can I use :Unite neobundle/update -sync ?

### ISSUE THREAD

**Issue by toshi32tony3** [Shougo/unite.vim#1093]
* Problems summary
以下のコマンドを実行後、処理が進みません。-no-syncの場合は問題ないようです。
その後、C-cを押すとasyncに切り替わって（？）処理が行われました。
> :Unite neobundle/update -sync

* Environment Information
 * OS: Windows 7 64-bit
 * Vim version: GVim 7.4.884

* Minimal vimrc less than 50 lines

```VimL
set encoding=utf-8

filetype plugin indent off

if has('vim_starting')
  set runtimepath+=~/.vim/bundle/neobundle.vim/
endif

call neobundle#begin(expand('~/.vim/bundle'))

NeoBundle 'Shougo/unite.vim'

call neobundle#end()

filetype plugin indent on
```

* How to reproduce

 0. GVimを起動
 1. 以下のコマンドを実行後、処理が進まない（完了しない？）
 2. その後C-cを押すとasyncに切り替わって（？）処理が行われます

> :Unite neobundle/update -sync

* Screen shot  
:Unite neobundle/update -sync 実行直後～2分経過後  
![unite_neobundle_update_sync](https://cloud.githubusercontent.com/assets/1744990/12049900/dec3e7a4-af30-11e5-8abd-a8b1754e970b.png)
<C-c>押下直後、asyncで処理中  
![unite_neobundle_update_sync_c-c](https://cloud.githubusercontent.com/assets/1744990/12049872/7ae71c38-af30-11e5-9ab0-b7aef134ca4b.png)
<C-c>押下後、asyncで処理完了後  
![unite_neobundle_update_sync_c-c_completed](https://cloud.githubusercontent.com/assets/1744990/12049874/7f235a64-af30-11e5-83e6-50c2033e0fb1.png)
:message実行後  
![unite_neobundle_update_sync_c-c_completed_message](https://cloud.githubusercontent.com/assets/1744990/12049889/bf778c2a-af30-11e5-89ed-ae7b0e70506e.png)

**Comment by Shougo** [comment]
Fixed.
Please update neobundle.

**Comment by toshi32tony3** [comment]
修正されていることを確認しました。迅速な対応ありがとうございます！
