### ISSUE TITLE
-no-split option causes horizontal split window to change size.

### ISSUE THREAD

**Issue by gbiggs** [Shougo/unite.vim#1095]
* Summary

  Using the -no-split option should disable Unite's feature to change the window height.

  If I am operating in a horizontal split, and then open a Unite buffer with -no-split, the current window is resized to the default Unite window size (20 lines). When the Unite buffer closes, then it often restores the window to its previous height. But often it doesn't, and I'm left with my window sizes all messed up after Unite closes.

  Possibly part of #309 is related.

* Expected

  The Unite buffer uses the existing window at its existing height when the -no-split option is given.

* Environment
  * Ubuntu Linux 15.04
  * Vi IMproved 7.4 (2013 Aug 10, compiled Dec  9 2014 17:36:40)

* vimrc

  ```VimL
  set modeline
  set nocompatible
  set encoding=utf-8
  set nowrap
  set softtabstop=2
  set shiftwidth=2
  set tabstop=8
  set expandtab
  set laststatus=2
  set textwidth=79
  set showcmd
  set number
  set lazyredraw
  set hidden
  set list
  set listchars=tab:>-,trail:-,extends:#,nbsp:.
  set showmatch
  set hlsearch
  syntax on
  filetype on
  filetype plugin on
  filetype indent on
  set ignorecase
  set smartcase
  set incsearch
  set autowrite

  " Better file name matching
  set wildmenu
  set wildmode=list:longest

  " Prevent the quickfix list from being included in buffer cycling
  augroup qf
      autocmd!
      autocmd FileType qf set nobuflisted
  augroup END

  " Unite
  let g:unite_source_history_yank_enable = 1
  call unite#custom#source('buffer', 'matchers', ['matcher_fuzzy'])
  call unite#custom#source('file,file/new,file_rec', 'matchers', ['matcher_fuzzy', 'matcher_hide_hidden_files'])
  call unite#custom#source('file,file/new,file_rec', 'max_candidates', 0)
  call unite#custom#source('buffer,file,file/new,file_rec', 'sorters', 'sorter_selecta')
  nnoremap <leader>f  :<C-u>Unite -no-split -marked-icon='✓' -buffer-name=files file file/new directory/new<cr>
  call unite#custom_source('file_rec,file_rec/async,file_mru,file,buffer,grep',
    \ 'ignore_pattern', join(['\.git/'], '\|'))
  if executable('ag')
      " Use ag in Unite grep source
      let g:unite_source_grep_command = 'ag'
      "let g:unite_source_grep_default_opts = '-i --line-numbers --nocolor --nogroup --hidden'
      let g:unite_source_grep_default_opts = '-i --vimgrep --hidden --ignore ''.hg'' --ignore ''.svn'' --ignore ''.git'' --ignore ''.bzr'''
      let g:unite_source_grep_recursive_opt = ''
  endif
  ```

* How to reproduce

  0. Start gvim
  1. Open one file.
  2. Create a horizontal split with :sp
  3. While in the top window of the split, open a Unite buffer using "Unite -no-split -marked-icon='✓' -buffer-name=files file file/new directory/new"
  4. The Unite buffer uses the top window of the split, but resizes it to 20 lines (the default winheight), rather than using its existing height.
  5. Close the Unite buffer (e.g. by selecting and opening a file). The window remains at 20 lines in height, rather than returning to its previous height.

  The same effect can be observed on the bottom window of the split if that is where the Unite buffer is opened.

![output](https://cloud.githubusercontent.com/assets/163151/12137681/0ab62b64-b496-11e5-8a25-d0244a5279da.gif)

**Comment by Shougo** [comment]
Fixed.

**Comment by gbiggs** [comment]
Window size restoring is fixed (have tested). However, a more complete fix would be to not resize the window when using the -no-split option.

**Comment by Shougo** [comment]
OK
