### ISSUE TITLE
Please deprecate g:unite_source_grep_max_candidates

### ISSUE THREAD

**Issue by kghost** [Shougo/unite.vim#1096]
Reasons:

* g:unite_source_grep_max_candidates doesn't work well, I tried

> let g:unite_source_grep_max_candidates = 0

it doesn't work

* Document for source grep/git also refers it, but it doesn't work at all for grep/git

* there is a much better solution:

> :call unite#custom#source('grep/git', 'max_candidates', 0)
> :call unite#custom#source('grep', 'max_candidates', 0)

So please deprecate g:unite_source_grep_max_candidates and remove the option from help document. It is really misleading.

**Comment by Shougo** [comment]
Fixed.
