### ISSUE TITLE
Regression: evaluating with backticks does not work correctly anymore.

### ISSUE THREAD

**Issue by maikelmeyers** [Shougo/unite.vim#1098]
I don't know where this regression happened but the follwoing example command does not work anymore, but worked before:

``:Unite grep:`glob('/foo/*.c') . "\n" .glob('/bar/*.c')`:-i:baz``

This quits now with the error message: `Invalid source name "." is detected`

**Comment by maikelmeyers** [comment]
With git bisect I found out that 805c17798cfa06f67cb859a67a93831377e13330 introduced the regression.

**Comment by maikelmeyers** [comment]
The -bar option treats the double quote as a comment. One solution is:

``:Unite grep:`glob('/foo/*.c') . \"\n\" .glob('/bar/*.c')`:-i:baz``

It's not that nice but so what...

**Comment by Shougo** [comment]
It is too bad.
Fixed.
