### ISSUE TITLE
Typing in unite breaks the redo (dot) 

### ISSUE THREAD

**Issue by yannack** [Shougo/unite.vim#1100]
I understand why this happens, but would there be a way to avoid this? I do an operation on a buffer, use unite to change buffers. I type some characters to fuzzy match my buffer... And when I arrive in my new buffer, I type dot "." to redo the same action again... But it types the characters from the unite buffer, rather than what I was hoping for. This is quite logical, but probably never what I want to do. Would it be possible for unite not to overwrite the "dot"?

**Comment by Shougo** [comment]
Unfortunately, it cannot.

* The register "." cannot be accessed from Vim plugins.

* It is Vim's feature

* It can be fixed in neovim version of unite.vim(It is the full scratch plugin)
