### ISSUE TITLE
質問: unite#start_temporary() が予想通り動かない

### ISSUE THREAD

**Issue by lambdalisue** [Shougo/unite.vim#1102]
https://github.com/lambdalisue/vim-gista-unite/blob/master/autoload/unite/kinds/gista.vim#L24-L35 のように `unite#start_temporary()` を利用して特定の要素にて `commit` アクションを選んだ時に `gista/commit` が開くようにしたのですが、`commit` アクションを実行しても何も起きません……

すぐ下にある `narrow` アクションは動くので、使い方を間違えているとも思えないのですが、なぜ動かないのかわかりません。お時間のある時で構わないのでご教示頂けると助かります。

**Comment by Shougo** [comment]
unite.vim の source を見れば分かりますが、
unite#start_temporary() をその用途で使ってはいけません。
unite#start_script() を使うべきでしょう。そして、is_quit は 1 にすべき。
なぜなら、unite#start_temporary() は unite バッファで呼ばれるので on_init() の
起動タイミングが source の想定と異なるからです。
gista/commit が動作せずに gista/narrow が動作するのはそのせいかなと。

```vim

let s:cdable_action_file = {
      \ 'description' : 'open this directory by file source',
      \ 'is_start' : 1,
      \}

function! s:cdable_action_file.func(candidate)
  call unite#start_script([['file',
        \ unite#helper#get_candidate_directory(a:candidate)]])
endfunction

call unite#custom_action('cdable', 'file', s:cdable_action_file)
```

**Comment by lambdalisue** [comment]
ありがとうございます。ご指摘通り `unite#start_script()` を利用するようにしたところ想定通りの動作となりました！
