### ISSUE TITLE
Shell Source

### ISSUE THREAD

**Issue by pdoak** [Shougo/unite.vim#1103]
I am trying to use `ls -ltr` as the shell source so that the initial view of the directory is in modified date order. When I use `:Unite output/shellcmd:ls -ltr`, I get the following error message: `Invalid option "ltr" detected`

Is there a way to do this?

**Comment by Shougo** [comment]
You must escape the spaces.

`:Unite output/shellcmd:ls\ -ltr` is correct command line.

**Comment by pdoak** [comment]
Thank you. I tried putting the command in ' and " but didn't think to escape the space.
