### ISSUE TITLE
Using a function as source

### ISSUE THREAD

**Issue by pdoak** [Shougo/unite.vim#1105]
I am trying to use a vim function as a source but can't seem to get it working.

The function is GetAllSnippets() which is from [UltiSnips](https://github.com/SirVer/ultisnips). It returns a list of all available snippets in the current buffer. I have tried to invoke it with `:Unite function:GetAllSnippets` but it does not work. What is the proper method of using a vim function as a source.

Many thanks

**Comment by Shougo** [comment]
`:Unite output:echo\ join(GetAllSnippets(),"\\n")`

**Comment by pdoak** [comment]
Thank you. That works. 

Why do you need to join the return of the function as doesn't it return an array of arrays.

**Comment by Shougo** [comment]
I don't know the `GetAllSnippets()` spec.
If `GetAllSnippets()` returns string, you don't have to convert it.
