### ISSUE TITLE
Grep command ag doesn't respect .gitignore

### ISSUE THREAD

**Issue by meunierd** [Shougo/unite.vim#1106]
Using the default configuration from the docs:

```viml
let g:unite_source_grep_command = 'ag'
let g:unite_source_grep_default_opts =
  \ '-i --vimgrep --hidden --ignore ' .
  \ '''.hg'' --ignore ''.svn'' --ignore ''.git'' --ignore ''.bzr'''
let g:unite_source_grep_recursive_opt = ''
```

Using `:Unite grep` will always return results that should be filtered out by my `.gitignore` but if I use `ag` from the commandline, the `.gitignore` is respected and those results are filtered.

**Comment by Shougo** [comment]
If you want to ignore .gitignore candidates, you should remove `--hidden` argument from `g:unite_source_grep_default_opts`.

I recommend to use `file_rec/git` though.

**Comment by meunierd** [comment]
I'm sorry I think you misunderstand. I don't mean the .gitignore file
itself but the patterns inside it when using ag pattern search, not
file_rec. Ag supports this by default (to not search logs for example) but
it doesn't work with unite.

**Comment by Shougo** [comment]
> I'm sorry I think you misunderstand. I don't mean the .gitignore file itself but the patterns inside it when using ag pattern search, not file_rec. Ag supports this by default (to not search logs for example) but it doesn't work with unite.

To remove `--hidden` option does not work?

**Comment by chemzqm** [comment]
The `--hidden` option have no effect of whether respect .gitignore or not.
I've tried with those options, ag did respect .gitignore
@meunierd could probably added `-a` option somewhere.

**Comment by meunierd** [comment]
I can confirm removing --hidden makes no difference and that I am not using '-a', the only argument I'm using is `--vimgrep`

**Comment by meunierd** [comment]
I suspect the command isn't being run from the PWD, so it doesn't use the .gitignore file.

**Comment by Shougo** [comment]
@meunierd The command line is executed in Vim PWD.

**Comment by meunierd** [comment]
I've found the issue, it lies with certain patterns behaving strangely with `ag`.
