### ISSUE TITLE
Add maps of every mode into "mapping" source

### ISSUE THREAD

**Issue by TKNGUE** [Shougo/unite.vim#1108]
When I check my mappings, I use "Unite mappings" and then filter it with keys.
Of current version, unite show the only result of nmap.
It is inconvenient to find the mapping of other modes such like insert, visual or command.

Is there problem to fix this problem?
If no problem exist, I add all mapping result into mapping source.

**Comment by Shougo** [comment]
No.  Because, mapping source can execute it.
I think it is not useful to add other mode mappings.
If you want to view the mappings, you should use `:Unite output:imap` instead.
