### ISSUE TITLE
some issue with neovim.

### ISSUE THREAD

**Issue by wsdjeg** [Shougo/unite.vim#1111]
core neovim config with plugin unite
```vim
nnoremap <silent> <C-b> :<C-u>Unite -start-insert -buffer-name=buffer buffer<cr>
augroup Terminal
    au!
    au TermOpen * let g:last_terminal_job_id = b:terminal_job_id
    au WinEnter term://* startinsert
augroup END
if has('nvim')
    tnoremap <C-Right> <C-\><C-n><C-w><Right>
    tnoremap <C-Left>  <C-\><C-n><C-w><Left>
    tnoremap <C-Up>    <C-\><C-n><C-w><Up>
    tnoremap <C-Down>  <C-\><C-n><C-w><Down>
    tnoremap <esc>     <C-\><C-n>
endif
```

start neovim with nvim test.vim

1. exec command `:terminal` to open terminal
2. type `esc` switch to normal mode
3. type ctrl + b open buffer unite source
4. select the buffer test.vim,type Enter 
5. the test.vim will be open in current buffer,but the mode is insert not normal,I do not know why.

by the way,if I switch to normal mode in unite buffer beffer select test.vim,then the test.vim will be opened in normal mode

**Comment by Shougo** [comment]
It is your configuration issue.

```vim
 au WinEnter term://* startinsert
```

It breaks unite.vim behavior.  Closing.

**Comment by wsdjeg** [comment]
by the way,if I switch to normal mode in unite buffer beffer select test.vim,then the test.vim will be opened in normal mode

I think it maybe not issue with event Winenter

**Comment by Shougo** [comment]
Hm...
Fixed the behavior.

**Comment by wsdjeg** [comment]
wow how fast.thanks

**Comment by wsdjeg** [comment]
wow how fast.thanks
