### ISSUE TITLE
regular vim -- function keys in Unite's insert mode need to be remapped for xterm

### ISSUE THREAD

**Issue by davidosomething** [Shougo/unite.vim#1113]
Reproduce in gnome-terminal, terminator, or other VTE100 terminal (not newer vte!)
Not an issue with Neovim -- only in regular vim:

#### .vimrc -- with unite installed, map F key to close unite:

```vim
autocmd FileType unite nmap <buffer><special> <F1> <Plug>(unite_all_exit)
```

#### in vim:

```
:Unite -start-insert buffer
```

#### result:

Pressing `<F1>` should close Unite window. Instead it will insert xterm function key value instead (  `<Esc>OP` ) so you get a newline from `O` and then letter `P` in buffer.

**I think this fix should be included in Unite:**

```
  nmap <buffer><special> <Esc>OP    <F1>
```

I added to my vimrc here: https://github.com/davidosomething/dotfiles/blob/0230945bf96a31fbe6972e01a56fe232899e2982/vim/plugin/unite.vim#L147-L159

**Comment by Shougo** [comment]
It is Vim and terminal problem.  Not unite.vim problem.  Closing.

> I think this fix should be included in Unite:

No.  I don't want to add the dirty hack.

https://github.com/davidosomething/dotfiles/blob/0230945bf96a31fbe6972e01a56fe232899e2982/vim/plugin/unite.vim#L145

You should not map `<ESC>`.
It causes the problem.

**Comment by davidosomething** [comment]
doh! i forgot that map esc is bad,  thanks
