### ISSUE TITLE
line matcher for current @/ pattern

### ISSUE THREAD

**Issue by dsummersl** [Shougo/unite.vim#1115]
I've been using this to show the matches to my current search:

    noremap <Leader>/ :exec "Unite -input=". @/ ." -no-start-insert line -horizontal"<cr>

But I have a problem in that for searches like `\<word\>` that I often get from using the <kbd>*</kbd> commands, the `-input` options escapes out.

Is there a way to make a custom source to search with a regexp or change the behavior of -input?

Thanks!

**Comment by Shougo** [comment]
@dsumumersl You must escape the input.

`escape(@/, '\ ')` seems works.

**Comment by chemzqm** [comment]
Looks like `escape(@/, ' ')` just works, the line source has a check to recognize regex, if `\` is escaped, the check would failed.

**Comment by chemzqm** [comment]
There's a problem at https://github.com/Shougo/unite.vim/blob/master/autoload/unite/sources/line.vim#L208,  if `ignorecase` option if off, the word contains uppercase would be changed to lowercase, and  `=~` would not match word conains uppercase for you.

**Comment by Shougo** [comment]
Fixed.

**Comment by chemzqm** [comment]
@Shougo I would prefer using the original input to match the line, like

     line =~ a:context.source__input

So that the user could decide ignore case or not by `ignorecase` option.

@dsummersl if you just want `unite line` to show the word under cursor of current buffer, instead of using <kbd>*</kbd> to perform a search, you can use something like:

    nnoremap <leader>/ :exec 'Unite -input=\<'. expand('<cword>') .'\> -no-start-insert line'<cr>

Single quote is required to have literal `\` without escape.
To list word in all buffers, you can use `buffers` as argument:

    nnoremap <leader>/ :exec 'Unite -input=\<'. expand('<cword>') .'\> -no-start-insert line:buffers'<cr>

**Comment by Shougo** [comment]
> @Shougo I would prefer using the original input to match the line, like

It is already implemented by `matcher_regexp`.
The routine just simple filter to get better performance.

**Comment by dsummersl** [comment]
Hey all, thanks so much for the feedback. I use this for the search register - commonly <kbd>*</kbd> but also for searches in general so `@/` is really what I'm looking for.

This appears to work:

    noremap <Leader>/ :exec "Unite -input=". escape(@/,' ') ." -no-start-insert line -horizontal"<cr>

Thanks so much!
