### ISSUE TITLE
Unite -toggle breaks on second attempt

### ISSUE THREAD

**Issue by mrbiggfoot** [Shougo/unite.vim#1116]
Repro:

```
vim
:Unite file
:Unite -toggle
:UniteResume
:Unite -toggle
```
The latest toggle shows two "interactive" windows instead of closing the Unite window with file list. Expected to behave exactly as the first "Unite - toggle".

**Comment by Shougo** [comment]
Fixed.

**Comment by mrbiggfoot** [comment]
Thank you, sir! Your continued work on this excellent project is much appreciated.
