### ISSUE TITLE
Miss buffer position when exec Unite command in Unite buffer.

### ISSUE THREAD

**Issue by wsdjeg** [Shougo/unite.vim#1118]
if I use no-split option,by default,if I type `<esc>` in unite buffer will switch to normal mode,and then if I type `q` will close the unite buffer,and the cursor is at the position just same as before.
ok let me show you the maps and reproduce step:
**maps**
```vim
nnoremap <silent><leader>um  :<C-u>Unite -start-insert mapping<CR>
inoremap jk <esc>
```
**setps**
1. open a file with vim,the file is about 50 - more lines
2. move mursor to some line 
3. type `\um` open unite with insert mode
4. type into `\um`
5. type `<esc>` switch to normal mode
6. type `\um` again to open unite again
7. type `<esc>` to switch to normal modo ,and type `q` to close unite,then you will find the cursor is not at the same position as before.

**Comment by Shougo** [comment]
Please do it.

**Comment by wsdjeg** [comment]
I means open unite buffer twice,first time open unite ,and just change to normal mode,do not close it,and open unite again,I can show it with a video

**Comment by Shougo** [comment]
Please create minimal init.vim.

**Comment by wsdjeg** [comment]
here is my test mini vimrc
https://github.com/wsdjeg/DotFiles/blob/test_Unite/vimrc
**Reproduce ways**
1. nvim README.md
2. `50j` move to line50
3. `\um` open unite map source
4. `<esc>` change to normal model
5. `\um` open unite map source again
6. `<esc>q` change to normal mode,and close unite,then you will at line 1 instead if line 50

**Comment by Shougo** [comment]
OK.  I will try it later.

**Comment by wsdjeg** [comment]
Thanks a lot

**Comment by Shougo** [comment]
Fixed.
