### ISSUE TITLE
Unite buffer with quick match showing error

### ISSUE THREAD

**Issue by ranranking** [Shougo/unite.vim#1120]
I set this in my .vimrc:
    
    nnoremap <m-tab> :Unite -auto-resize -quick-match -here buffer<CR>

Every time I open it, it shows
![screen shot 2016-02-14 at 5 25 33 pm](https://cloud.githubusercontent.com/assets/7812475/13037551/ba9e568c-d340-11e5-8f46-08c9d5b94a31.png)

I have to hit esc, close it and open it again, then everything shows fine. 
![screen shot 2016-02-14 at 5 32 42 pm](https://cloud.githubusercontent.com/assets/7812475/13037564/ffe0c2f2-d340-11e5-8de6-064025eba039.png)

What's the problem?

**Comment by chemzqm** [comment]
Probably a problem with one of your other plugins, you can use a minimal vimrc configuration with only Unite related and try again.

**Comment by ranranking** [comment]
I set my .vimrc file like this:

    if has('vim_starting')
    if &compatible
      " Be iMproved
      set nocompatible
    endif
    set runtimepath+=~/.vim/bundle/neobundle.vim/
    endif

    call neobundle#begin(expand('~/.vim/bundle/'))
    let pluginsExist = 1

    NeoBundleFetch 'Shougo/neobundle.vim'
    NeoBundle 'Shougo/unite.vim'
  
    call neobundle#end()

    filetype plugin indent on
    let pluginsExist=1
    NeoBundleCheck

    if pluginsExist
       nnoremap <m-tab> :Unite -auto-resize -quick-match -sync -here buffer<CR>
    endif

The block still shows

<img width="140" alt="screen shot 2016-02-15 at 10 39 14 am" src="https://cloud.githubusercontent.com/assets/7812475/13056106/7146342e-d3d0-11e5-8b0a-6e2011e5627d.png">

**Comment by wsdjeg** [comment]
@ranranking why do you add `-quick-match `,this option you need type into a match number to open the file

**Comment by ranranking** [comment]
@wsdjeq Because I think this option is interesting, I don't have to move my cursor or type file name to switch buffer. I am not sure whether I can just type buffer number to switch, that way would be easier.

**Comment by wsdjeg** [comment]
I think it is just a `input()` func of viml,you need type into a number or type `<esc>` to cancle it,after that you can use `q` close Unite buffer

**Comment by ranranking** [comment]
Yes, when the block shows, I can anything that doesn't match the file to make it show correctly. But that way, I can not use quick match anymore. Or, I can close it and open it again, everything shows fine.

**Comment by wsdjeg** [comment]
1. I can confirm it is a bug,if I remove `-here`,the plugin show fine.
2. no matter which number I type into ,the plugin will show me `[unite.vim] canceled`,and do not move the cursor to the matched file,just move my cursor to the first line

**Comment by Shougo** [comment]
Fixed.

**Comment by wsdjeg** [comment]
thanks,it works well
