### ISSUE TITLE
Disable swapfile for unit buffers

### ISSUE THREAD

**Issue by zdm** [Shougo/unite.vim#1122]
# Problems summary
Swap files are useless for unite buffers and can be disabled. Also sometimes I am seeing some problems when swapfile is used. For example, when I try to open unite buffer I need to press additional <ENTER>.

## Environment Information
 * OS: windows, linux
 * Vim version: latest, x64

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
" Your minimal .vimrc
set runtimepath+=~/path/to/unite.nvim/
```

## The reproduce ways from Vim starting (Required!)

 1. foo
 2. bar
 3. baz

**Comment by Shougo** [comment]
`:setlocal noswapfile` is already set.
You should check your config.
