### ISSUE TITLE
Can not turn off auto-resizing for vertically split Unite windows.

### ISSUE THREAD

**Issue by wanderer2** [Shougo/unite.vim#1123]
# Problem Summary
When `-vertical` option is set, the Unite window has variable (not fixed) width even if `no-auto-resize` is set. One can easily see this by inspecting the output of the command `set winfixwidth?`.

## Expected Behavior
Just like horizontal Unite windows, vertical Unite windows should be of fixed size, if the user specifies so.

## Environment Information
 * OS: Mac OS X El Capitan
 * Vim version: 7.4.1301

## Example `.vimrc` Template

```vim
...
call unite#custom#profile('myprofile','context',
         \ { 'vertical' : 1,
         \   'winwidth' : 35,
         \   'no_auto_resize' : 1
         \ })
nnoremap <leader>b :Unite -profile-name=myprofile buffer<CR>
...
```

## How to Reproduce

1. Open a vertical Unite window; e.g. by pressing `<leader>b` if the above `.vimrc` is used.
2. Split your window vertically; e.g. by issuing the command `:vsp another_file.txt`.
3. See that the Unite window auto-resizes.

**Comment by wanderer2** [comment]
Actually, I just discovered that same behavior manifests for horizontal Unite windows too.

**Comment by wsdjeg** [comment]
-auto-resize
		Auto resize unite buffer height by candidates number.
		Default: no-auto-resize

						*unite-options-no-resize*
		-no-resize
		Do not resize the unite buffer after opening it.
		Default: resize

you shoud use
```vim
call unite#custom#profile('myprofile','context',
         \ { 'vertical' : 1,
         \   'winwidth' : 35,
         \   'no_resize' : 1
         \ })
nnoremap <leader>b :Unite -profile-name=myprofile buffer<CR>
```

**Comment by wsdjeg** [comment]
sorry ,my last comments is wrong

**Comment by Shougo** [comment]
@wanderer2 Your minimal .vimrc is incomplete.
Please see other issues in the repository.

**Comment by Shougo** [comment]
I get it.  Fixed.
