### ISSUE TITLE
Using relative paths in source-grep does not return all results

### ISSUE THREAD

**Issue by wanderer2** [Shougo/unite.vim#1124]
# Problems summary
While using `source-grep`, specifying relative paths (e.g. `.`) does not return all results. If absolute paths are used instead, the correct result set is shown. I believe this happens when there are hidden files/folders within the search tree. Also, when `.` is used as the target path, and there are hidden files/folders in the search tree, `source-grep` sometimes (i.e. *not* always) prints the following message: `Your grep configuration is wrong.`.

## Expected
It shouldn't matter whether relative paths or absolute paths are used, and hidden files/folders should not mess up `source-grep`.

## Environment Information
 * OS: Mac OS X El Capitan
 * Vim version: 7.4.1345

## Minimal `.vimrc` to Trigger
Just load `Unite`, no custom `.vimrc` settings required.

## How to Reproduce

 1. Have hidden files/folders in your directory structure.
 2. Use `source-grep`, with the target `.`, and search for a pattern that would invoke many (i.e. more than 1000) results.
 3. Compare the results with those found via the absolute path for `.`.

**Comment by Shougo** [comment]
> Have hidden files/folders in your directory structure.

@wanderer2 Please create examples like this.

https://github.com/Shougo/unite.vim/issues/904#issuecomment-99756871

**Comment by wanderer2** [comment]
Will try and post when can. BTW, the faulty behavior does not happen if `ag` is used instead of `grep`. My suspicion is that this happens because `ag` ignores hidden files by default, which does not trigger the bug.

**Comment by Shougo** [comment]
No response.
