### ISSUE TITLE
`append` does not append but insert at the very beginning

### ISSUE THREAD

**Issue by ujihisa** [Shougo/unite.vim#1127]
# Problems summary

unite-action `append` does not append at the cursor position but insert at the very first part of the buffer, no matter where you are.

According to `git bisect`,

> 687b1c02c3f81e1142f479f4899562b4b9a11186 is the first bad commit

## Expected

unite-action `append` appends at the cursor position.

## Environment Information
 * OS: Mac OSX
 * Vim version: 7.4-1202

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
if has('vim_starting')
  set nocompatible
  set runtimepath+=~/.vimbundles/neobundle.vim
endif

call neobundle#begin(expand('~/.vimbundles'))

let g:neobundle#enable_name_conversion = 1
NeoBundle 'Shougo/unite.vim'
call neobundle#end()
" call neobundle#local("~/.vimbundles", {})

filetype plugin indent on
```

## The reproduce ways from Vim starting (Required!)

 0. Open a buffer with text, and go somewhere besides 1st line (such as 58243th line)
 1. `:Unite buffer` (or anything that has values, such as `file`, `rec`, or `process`)
 2. `<Tab>` (or `<Plug>(unite_choose_action)`)
 3. Choose `append`
 4. Check where the text is appended

**Comment by ujihisa** [comment]
687b1c02c3f81e1142f479f4899562b4b9a11186 is the first bad commit

**Comment by Shougo** [comment]
Fixed.

**Comment by ujihisa** [comment]
Confirmed! Thx! 🙇
