### ISSUE TITLE
Window layout chaos after exiting temporary Unite

### ISSUE THREAD

**Issue by wilywampa** [Shougo/unite.vim#1129]
# Problems summary
This happens with `{'direction' : 'botright'}` since https://github.com/Shougo/unite.vim/issues/1095. After exiting a temporary Unite (e.g. `<Plug>(unite_narrowing_input_history)`), window layout gets badly messed up:

![unite_problem](https://cloud.githubusercontent.com/assets/4472522/13309177/a516923a-db37-11e5-8f88-42a666447101.gif)

## Expected
Temporary Unite should exit back to original Unite without changing window layout.

## Environment Information
 * OS: OS X 10.10.5
 * Vim version: 7.4.1328

## Provide a minimal .vimrc with less than 50 lines

```vim
set nocompatible hidden backspace=indent,eol,start
set history=5000 undofile undolevels=1000 undoreload=10000
set expandtab shiftwidth=2 softtabstop=2 tabstop=2

function! s:UniteMaps()
    nmap <buffer> <C-p> <Plug>(unite_narrowing_input_history)
    imap <buffer> <C-p> <Plug>(unite_narrowing_input_history)
endfunction

function! s:UniteSetup()
    call unite#custom#profile('default', 'context', {
        \ 'direction': 'botright', 
        \ 'prompt_direction': 'top',
        \ })
endfunction

autocmd FileType unite call s:UniteMaps()
autocmd VimEnter * call s:UniteSetup()

nnoremap <silent> <C-p> :<C-u>Unite -buffer-name=buffers buffer<CR>

silent! if plug#begin('$HOME/.vim_sandbox_plugged')
Plug 'Shougo/unite.vim'
Plug 'Shougo/vimproc.vim', {'do': 'make'.(has('win32unix') ? ' -f make_cygwin.mak' : '')}
call plug#end()
endif
```

## The reproduce ways from Vim starting

0. `call unite#custom#profile('default', 'context', {'direction': 'botright', 'prompt_direction': 'top'})`
1. Open `:Unite buffer`
2. Use `<Plug>(unite_narrowing_input_history)` map to open temporary Unite
3. Choose an input history or just close the temporary Unite

**Comment by Shougo** [comment]
Fixed.
