### ISSUE TITLE
Feature Request: source for :ilist

### ISSUE THREAD

**Issue by kballard** [Shougo/unite.vim#1132]
I use the `:isearch` command or the `[<C-i>` mapping fairly often to jump to the declaration of things. But in C++ programs often the first declaration is not the right one (e.g. because it's a forward-declaration of a class and I want the actual declaration). In those instances I can use `:ilist` or `[I` to find the real one, but then it's a PITA to actually jump to the relevant location. I'd really love to see a Unite source that wraps `:ilist` to let me jump to the location of each result.

**Comment by Shougo** [comment]
I don't want to add the source.
You can create it.

I think unite-tag is better.

**Comment by kballard** [comment]
unite-tag is nice, but it requires me to have an existing tags file. I like isearch because it lets me find definitions in projects where I haven't generated a tags file (or where the tags file would be so massive that I'd have to wait a while for unite-tag/include to be usable).

**Comment by wsdjeg** [comment]
if you want a source in to Unite core repo,make sure mose people use it,otherwise  it is better create an extra source plugin

**Comment by Shougo** [comment]
> unite-tag is nice, but it requires me to have an existing tags file. I like isearch because it lets me find definitions in projects where I haven't generated a tags file (or where the tags file would be so massive that I'd have to wait a while for unite-tag/include to be usable).

unite-tag/include auto generate project tag files.
You need to install neoinclude plugin though.

**Comment by kballard** [comment]
I hadn't seen that plugin before. I'll check it out. Thanks!
