### ISSUE TITLE
Unite output/shellcmd show strange chars.

### ISSUE THREAD

**Issue by wsdjeg** [Shougo/unite.vim#1134]
# Problems summary
I want to use unite show git log for different plugins,
here is my terminal pic,and my pwd is not dein.vim
![2016-03-01 20-48-24](https://cloud.githubusercontent.com/assets/13142418/13427439/f6c9a188-dfee-11e5-83c7-43927626aae1.png)
but in unite there is some strang chars
![2016-03-01 20-49-46](https://cloud.githubusercontent.com/assets/13142418/13427462/275edd68-dfef-11e5-8264-f51510c3ef58.png)

## Expected
I want it is same as terminal ,and it is a best way to see update info ,no need rewrite UI.

## Environment Information
 * OS:ubuntu
 * Vim version:neovim

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
" Your minimal .vimrc
set runtimepath+=~/path/to/unite.nvim/
```

## The reproduce ways from Vim starting (Required!)

 1. 
```vim
call unite#start([['output/shellcmd', 'git -C ~/.cache/vimfiles/repos/github.com/Shougo/dein.vim log -n 6 --oneline']], {'log': 1, 'wrap': 1})
```

**Comment by wsdjeg** [comment]
and even I use color=never
```
call unite#start([['output/shellcmd', 'git -C ~/.cache/vimfiles/repos/github.com/Shougo/dein.vim log -n 6 --color=never --oneline']])
```
![2016-03-01 20-55-12](https://cloud.githubusercontent.com/assets/13142418/13427587/01021170-dff0-11e5-825b-5c61185e6bf5.png)

**Comment by Shougo** [comment]
@wsdjeg I cannot reproduce your problem.
It is from your git configuration.
Please upload your git configuration.

**Comment by wsdjeg** [comment]
```
[user]
	name = wsdjeg
	email = wsdjeg@outlook.com
[push]
	default = simple
[merge]
	tool = vimdiff
[credential]
	helper = store
[diff]
	tool = nvim
[difftool]
	prompt = false
[color]
	ui = true
	branch = auto
	status = auto
[core]
	editor = nvim
	excludesfile = ~/.gitignore
[mergetool]
  prompt = true
[mergetool "vimdiff"]
  cmd = nvim -d $BASE $LOCAL $REMOTE $MERGED -c '$wincmd w' -c 'wincmd J'

```

**Comment by Shougo** [comment]
Fixed.

**Comment by wsdjeg** [comment]
greate,but still add some thing in the end
![2016-03-01 22-05-02](https://cloud.githubusercontent.com/assets/13142418/13429152/b826399a-dff9-11e5-8348-4b2a8fe12f28.png)

**Comment by chemzqm** [comment]
@wsdjeg I think you should make git not using any pager by command like `git --no-pager`.
I have a unite plugin to show my git log https://github.com/chemzqm/unite-git-log, you can take that for example.

**Comment by wsdjeg** [comment]
thanks

**Comment by wsdjeg** [comment]
@chemzqm `--no-paper` need which version of git,my git has no such args, my git version is 2.5

**Comment by wsdjeg** [comment]
works well for me.
![2016-03-02 20-25-38](https://cloud.githubusercontent.com/assets/13142418/13460353/fa80e8c4-e0b4-11e5-9428-a14b85313fb5.png)
