### ISSUE TITLE
How to create a cheatsheet source

### ISSUE THREAD

**Issue by jottr** [Shougo/unite.vim#1135]
# Problems summary

I map ~20 keys to unite commands, which gets hard to memorize. 

It would be nice to have a Unite source, that creates a cheatsheet of current unite key mappings. 
I.e. given the following mapping: 

```
nnoremap <silent>[unite]c   :<C-u>Unite -buffer-name=colorscheme -start-insert colorscheme<CR>
nnoremap <silent>[unite]e   :<C-u>Unite -buffer-name=quickfix location_list<CR>
```

It would be nice to have a Unite source, that lists all configured unite mappings and its `buffer-name`, i.e.:

```
[c] colorscheme
[e] quickfix
```
My question: How could I achieve such a thing?

**Comment by wsdjeg** [comment]
why do not use unite-mapping

**Comment by wsdjeg** [comment]
`:Unite mapping -input=unite`

**Comment by jottr** [comment]
Oh, that makes sense. Thx.

**Comment by jottr** [comment]
Actually, I find it quite unreadable:
<img width="801" alt="screen" src="https://cloud.githubusercontent.com/assets/2744198/13638507/7a3fcc48-e604-11e5-8ec0-66910b282301.png">

Is there some way to only display the mapping and buffer name to make it more readable?

**Comment by lambdalisue** [comment]
How about https://github.com/lambdalisue/unite-linephrase

**Comment by supermomonga** [comment]
Unite has the official source `menu` to create user-defined menu. It may helps you.

**Comment by Shougo** [comment]
Yes, it is not unite work.
