### ISSUE TITLE
Add file_rec/auto / pick best method

### ISSUE THREAD

**Issue by blueyed** [Shougo/unite.vim#1136]
I was still using `file_rec/async`, which is based on vimproc only in Neovim.

It would be nice to have a method to automatically delegate to the best method, e.g. `file_rec/neovim`.

I could imagine delegating `file_rec` and `file_rec/async` sources to the best method that's available, e.g. `file_rec/neovim`.

This might include moving the current `file_rec/async` to `file_rec/vimproc`, and `file_rec` to `file_rec/...`.

But there could be also just a new `file_rec/auto` wrapper instead / additionally.

**Comment by chemzqm** [comment]
IMO, you can just check `has(neovim)` and remap your trigger key to the unite command you want.

**Comment by Shougo** [comment]
I don't want to add the source.
Yes, you can create it.  Closing.
