### ISSUE TITLE
'Unite -start-insert' inserts on the last typed character instead of after it

### ISSUE THREAD

**Issue by HarmtH** [Shougo/unite.vim#1138]
# Problems summary
When going to a previous Unite buffer, the previous text reappears, but the cursor is on the last typed character.

## Expected
The cursor should be behind the last typed character.

I know it is normal in Vim to be on the last character instead of behind it, but in this case you usually want to change the text, so it would be nice to be behind the last typed character.

## Environment Information
 * OS: Ubuntu 15.10
 * Vim version:  NVIM v0.1.3-361-g5730ad9                                                       

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
" Your minimal .vimrc
set runtimepath+=~/path/to/unite.nvim/
```
No further configuration necessary to trigger the bug.

## The reproduce ways from Vim starting (Required!)

 1. :Unite -start-insert file
 2. Narrow to a directory by typing (part) of the directory name and enter
 3. Exit the newly created Unite buffer (default-1) by going to normal mode and pressing q
 4. We are back in the previous Unite buffer (default), in Insert-mode, and with the cursor on the last character instead of after it.

## Screen shot (if possible)
![bugunite](https://cloud.githubusercontent.com/assets/2418402/13900287/10c5a3a8-ee03-11e5-9e00-686db516f479.png)

**Comment by HarmtH** [comment]
Nevermind, I fixed it for myself by:

```
function! s:unite_my_settings()"{{{
    if unite#get_context().start_insert
        imap <expr> <buffer> <bs> !empty(unite#helper#get_input()) ? "<Plug>(unite_delete_backward_char)" : "<Plug>(unite_exit)<Right>"
    else 
        imap <expr> <buffer> <bs> !empty(unite#helper#get_input()) ? "<Plug>(unite_delete_backward_char)" : "<Plug>(unite_exit)"
    endif
endfunction"}}}
```
This also lets my go back to the previous buffer with backspace, instead of closing all Unite buffers.

**Comment by Shougo** [comment]
> We are back in the previous Unite buffer (default), in Insert-mode, and with the cursor on the last character instead of after it.

Please provide the command to reproduce it.

**Comment by Shougo** [comment]
Fixed.
