### ISSUE TITLE
Unite update my scroll setting

### ISSUE THREAD

**Issue by nobe4** [Shougo/unite.vim#1140]
# Problems summary

When I open a file from the `Unite file` or `Unite file_rec` view, my scroll change.

## Expected

My scroll setting shouldn't change. It get 

## Environment Information
 * OS: OSX 10.10.1
 * Vim version: MacVim 7.4

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
set nocompatible

call plug#begin('~/.vim/plugged')
Plug 'Shougo/unite.vim'
call plug#end()

set scroll=10
```

## The reproduce ways from Vim starting (Required!)

`vim -u vimrc`
`:set scroll?`
=> 10
`:Unite file` 
(or `file_rec`)
Select a file
`:set scroll?`
32 / 12 (depends on the opened file I think).

## Screen shot
[![asciicast](https://asciinema.org/a/5quk3vgaiaztl0a5iazwqtqq8.png)](https://asciinema.org/a/5quk3vgaiaztl0a5iazwqtqq8)

**Comment by Shougo** [comment]
It is the Vim feature.
Please read below.

```
						*'scroll'* *'scr'*
'scroll' 'scr'		number	(default: half the window height)
			local to window
	Number of lines to scroll with CTRL-U and CTRL-D commands.  Will be
	set to half the number of lines in the window when the window size
	changes.  If you give a count to the CTRL-U or CTRL-D command it will
	be used as the new value for 'scroll'.  Reset to half the window
	height with ":set scroll=0".   {Vi is a bit different: 'scroll' gives
	the number of screen lines instead of file lines, makes a difference
	when lines wrap}
```
