### ISSUE TITLE
Buffer source quick-match not working

### ISSUE THREAD

**Issue by petobens** [Shougo/unite.vim#1141]
Consider the following minimal vimrc:

```vim
set nocompatible

let $CLOUD_DIR = expand('$HOME/OneDrive/')
let $DOTVIM = expand('$CLOUD_DIR/vimfiles')

set runtimepath+=$DOTVIM/bundle/unite
filetype plugin indent on

call unite#custom#source('buffer', 'converters', 'converter_tail_abbr')
call unite#custom#source('buffer', 'sorters',
            \ ['converter_tail', 'sorter_word'])

nnoremap <silent> ,be :Unite -default-action=switch -quick-match
            \ buffer<CR>
```

Now (as in the GIF) open MacVim and do:
i) open two files (in my GIF, `init.lua` and `arararc.yaml`
ii) press `,be`
iii) once the Unite windows opens press `s` 
After the last step I expect to switch to `init.lua` file but I'm still on `arararc.yaml` file.

![mar 23 2016 19 47](https://cloud.githubusercontent.com/assets/2583971/14003296/320d210a-f130-11e5-83aa-1ba5e06099c6.gif)

**Comment by Shougo** [comment]
I will check it.

**Comment by Shougo** [comment]
Fixed.

**Comment by petobens** [comment]
Thank you.
