### ISSUE TITLE
outeput:echo:"foo":!  が最初の候補だと (unite_do_default_action) が効かない

### ISSUE THREAD

**Issue by anekos** [Shougo/unite.vim#1142]
# Problems summary
outeput:echo:"foo":!  が最初の候補だと (unite_do_default_action) が効かない
-select=0  と明示的に指定しても駄目でした。
-select=1 とすると、期待通りスキップされた上で候補が選択されます。

## Expected
ダミーの候補はスキップした最初の候補でアクションを実行してほしい

## Environment Information
 * OS: Arch Linux
 * Vim version: 7.4.1529

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
set cpoptions-=C
set runtimepath=~/.cache/dein/repos/github.com/Shougo/unite.vim
```

## The reproduce ways from Vim starting (Required!)

 1. :Unite output:echo:"foo":! file
 2. o

**Comment by Shougo** [comment]
I get it.  But it is hard to fix.
Won't fix.

**Comment by anekos** [comment]
Thanks
