### ISSUE TITLE
Weird interaction with long registers and -quick-match

### ISSUE THREAD

**Issue by rlpowell** [Shougo/unite.vim#1143]
# Problems summary

I have long registers that take up more than one line, but each line gets assigned a quick-match entry, and then those don't work (using them causes Unite to say "cancelled".

## Expected

All presented quick-match buttons should work.

## Environment Information
 * OS: Linux
 * Vim version:  VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Aug 20 2015 09:52:41)

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
call plug#begin('~/.vim/plugged')

Plug 'Shougo/unite.vim'
Plug 'Shougo/neomru.vim'

call plug#end()
```

## The reproduce ways from Vim starting (Required!)

1.  :Unite -quick-match register

## Screen shot (if possible)

https://www.dropbox.com/s/wsgzy7vaea781e1/Screenshot%202016-04-09%2000.50.23.png?dl=0

## Upload the log messages by `:redir` and `:message`

:message:

```
Messages maintainer: Bram Moolenaar <Bram@vim.org>
"~/scratch/OLD_rj_house_contacts.txt" 14L, 518C
[unite.vim] Canceled.
E475: Invalid argument:
Press ENTER or type command to continue
```

**Comment by rlpowell** [comment]
In the screenshot, hitting "q" would produce the error, for example (as would ; and t).

**Comment by rlpowell** [comment]
Note that "-wrap" fixes this problem, although I'd *much* rather that the problem was fixed by having each register clipped to exactly one line on screen (i.e. throw away any characters past the screen width).

**Comment by Shougo** [comment]
Fixed.

**Comment by rlpowell** [comment]
That was so quick!  Thank you so much!
