### ISSUE TITLE
Support for alternative git grep file/line delimiters

### ISSUE THREAD

**Issue by JohannesZiegenbalg** [Shougo/unite.vim#1144]
### Problem summary
Git grep uses different file/line delimiters based on the arguments that are used.
The following example is the output of a call to something like: `git grep -p -C1 'baz'`
The result looks like: 
```
src/FOO_bar.c=73=FOO_bar(void)
src/FOO_bar.c-74-{
src/FOO_bar.c:75:    baz();
src/FOO_bar.c-76-}
```

**Note:** The line with the match uses `:` as delimiter, the surrounding context `-` and the function context `=`.

 Unite shows only line 75 where the delimiter is a colon. Is it possible to show the other lines too?

**Comment by lambdalisue** [comment]
No. I wrote that code but I didn't consider about the surrounding context or function context.

**Comment by Shougo** [comment]
I don't want to add the feature.
