### ISSUE TITLE
tabswitch action not working?

### ISSUE THREAD

**Issue by rlpowell** [Shougo/unite.vim#1145]
# Problems summary

I expect that if I open an entirely new file with the tabswitch action, that it will get placed in its own tab.  Instead it replaces the current buffer in the current tab.  It may be that I'm misunderstanding what tabswitch is for.

The "switch to currently open tab if we already have that file open" bit works fine.

## Environment Information
 * OS:Linux ; Fedora 23
 * Vim version:

VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Aug 20 2015 09:52:41)
Included patches: 1-207, 209-801, 803-808, 810-827

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
call plug#begin('~/.vim/plugged')


Plug 'Shougo/unite.vim'
Plug 'Shougo/neomru.vim'
Plug 'Shougo/vimproc.vim'
Plug 'Shougo/neoyank.vim'

call plug#end()

let g:unite_source_rec_max_cache_files = 0
call unite#custom#source('file_rec,file_rec/async', 'max_candidates', 0)
nnoremap <Space>uf :Unite -wrap -no-split -start-insert -smartcase -default-action=tabswitch buffer file_mru<CR>
```

## The reproduce ways from Vim starting (Required!)

1.  Open vim on several files with -p
2.  Hit <Space>uf
3.  Select a file that is not amongst those currenly open
4.  See that you don't get a new tab

## Screen shot (if possible)

Would require a screencast rather than a screenshot; I can do that if you want.

**Comment by Shougo** [comment]
Fixed

**Comment by rlpowell** [comment]
Man, you are *fast*.  Thank you so much!
