### ISSUE TITLE
line:buffers doesn't all the buffers (feature request)

### ISSUE THREAD

**Issue by rlpowell** [Shougo/unite.vim#1146]
# Problems summary

line:buffers doesn't actually search all the buffers, only all the buffers users have actually interacted with.  Specifically: if you do "vim a b c d", line:buffers only searches "a".  This is totally expected from the way vim loads files, and if you do "vim -p a b c d", all files are loaded and line:buffers searches them all.

I'm fixing this in my vimrc with:

autocmd VimEnter * silent bufdo echo|buffer 1

but it would be kind of a cool feature if line:buffers checked all the buffers from the start.

## Environment Information
 * OS: Fedora 23
 * Vim version:  I can't imagine it matters, but 7.4

**Comment by Shougo** [comment]
Fixed
