### ISSUE TITLE
Fast exit from quick match?

### ISSUE THREAD

**Issue by rlpowell** [Shougo/unite.vim#1147]
# Problems summary

When I hit q in quick match mode, I end up in regular match mode; I have to hit q twice to exit Unite entirely.

## Expected

I would expect one q to work

## Environment Information
 * OS:  Fedora 23
 * Vim version:  Vim 7.4

## Provide a minimal .vimrc with less than 50 lines (Required!)

This happens with every :Unite -quick-match , even with nothing else in my vimrc (I tried).

**Comment by Shougo** [comment]
Please use `<ESC>`
