### ISSUE TITLE
'No such action do' when selection

### ISSUE THREAD

**Issue by m42e** [Shougo/unite.vim#1148]
# Problems summary
I cannot invoke specific actions after selecting a file. There will be an error message

## Expected
open file in vsplit

## Environment Information
 * OS: Ubuntu 14.04.1
 * Vim version:
```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Mar 18 2016 10:49:52)
Included patches: 1-1589
Compiled by vagrant@HAF-SWI
Huge version without GUI.  Features included (+) or not (-):
+acl             +farsi           +mouse_netterm   +tag_binary
+arabic          +file_in_path    +mouse_sgr       +tag_old_static
+autocmd         +find_in_path    -mouse_sysmouse  -tag_any_white
-balloon_eval    +float           +mouse_urxvt     -tcl
-browse          +folding         +mouse_xterm     +terminfo
++builtin_terms  -footer          +multi_byte      +termresponse
+byte_offset     +fork()          +multi_lang      +textobjects
+channel         +gettext         -mzscheme        +timers
+cindent         -hangul_input    +netbeans_intg   +title
-clientserver    +iconv           +packages        -toolbar
-clipboard       +insert_expand   +path_extra      +user_commands
+cmdline_compl   +job             -perl            +vertsplit
+cmdline_hist    +jumplist        +persistent_undo +virtualedit
+cmdline_info    +keymap          +postscript      +visual
+comments        +langmap         +printer         +visualextra
+conceal         +libcall         +profile         +viminfo
+cryptv          +linebreak       +python          +vreplace
+cscope          +lispindent      -python3         +wildignore
+cursorbind      +listcmds        +quickfix        +wildmenu
+cursorshape     +localmap        +reltime         +windows
+dialog_con      -lua             +rightleft       +writebackup
+diff            +menu            +ruby            -X11
+digraphs        +mksession       +scrollbind      -xfontset
-dnd             +modify_fname    +signs           -xim
-ebcdic          +mouse           +smartindent     -xsmp
+emacs_tags      -mouseshape      +startuptime     -xterm_clipboard
+eval            +mouse_dec       +statusline      -xterm_save
+ex_extra        -mouse_gpm       -sun_workshop    -xpm
+extra_search    -mouse_jsbterm   +syntax          
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H     -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1      
Linking: gcc   -L. -Wl,-Bsymbolic-functions -Wl,-z,relro -L/build/buildd/ruby1.9.1-1.9.3.484/debian/lib -rdynamic -Wl,-export-dynamic  -L/usr/local/lib -Wl,--as-needed -o vim        -lm -ltinfo -lnsl   -ldl    -L/usr/lib/python2.7/config -lpython2.7   -lruby-1.9.1 -lpthread -lrt -ldl -lcrypt -lm  -L/usr/lib    
```

## Provide a minimal .vimrc with less than 50 lines (Required!)
I use vim plug, hope that is ok when reporting errors.
```vim
" Your minimal .vimrc
set nocompatible                                                       
filetype off                                                                                                    
call plug#begin('~/.vim/plugged')                                                                                                                                                    Plug 'Shougo/unite.vim'
Plug 'Shougo/vimproc.vim', { 'do': 'make -f make_cygwin.mak' }                                       
call plug#end()                                              
filetype plugin indent on                                            
nnoremap <Leader>f :Unite -no-split file_rec/async<cr>  
```

## The reproduce ways from Vim starting (Required!)

 1. `:Unite file_rec/async<cr>`
 2. select file, hit `<tab>`
 3. typing 'vsplit'
 4. hit enter

## Screen shot (if possible)
![hafswi_0 7-2016-04-13-09-50-48](https://cloud.githubusercontent.com/assets/2410802/14518779/8a302a58-021a-11e6-9a95-10c4f7cf0794.png)

## Upload the log messages by `:redir` and `:message`

```
Messages maintainer: Bram Moolenaar <Bram@vim.org>
"pgenfile.py" 100L, 3425C
[unite.vim] vsplit            ! -- (openable)           vertical split open items(action)
[unite.vim] No such action : do
E475: Invalid argument: 

```

**Comment by Shougo** [comment]
@m42e Your minimal .vimrc and screenshot is not minimal.
I cannot reproduce the problem.  So, I think it is the configuration conflict.
Please create real minimal .vimrc like this without vim-plug.

```vim
" Your minimal .vimrc
set nocompatible                                                       
set rtp+=~/.vim/plugged/unite.vim
set rtp+=~/.vim/plugged/vimproc.vim                                     
filetype plugin indent on                                            
nnoremap <Leader>f :Unite -no-split file_rec/async<cr> 
```

**Comment by m42e** [comment]
Ok, so I improved the setup, calling `vim --cmd 'set rtp^=/home/vagrant/.vim_minimal' -u ~/.dotfiles/common/vim/vimrc.minimal`
where `/home/vagrant/.vim_minimal/` is an empty folder, and the `vimrc.minimal` is exacly what you suggested.

Here are the screenshots:

![screenshot from 2016-04-15 10 38 01](https://cloud.githubusercontent.com/assets/2410802/14556139/e05bf4a2-02f6-11e6-865d-c29fa8c123a8.png)
![screenshot from 2016-04-15 10 38 07](https://cloud.githubusercontent.com/assets/2410802/14556142/e05cb9d2-02f6-11e6-8c21-fad6a48f597d.png)
![screenshot from 2016-04-15 10 38 13](https://cloud.githubusercontent.com/assets/2410802/14556144/e06d1606-02f6-11e6-9e00-40ec986233f3.png)
![screenshot from 2016-04-15 10 38 19](https://cloud.githubusercontent.com/assets/2410802/14556145/e0705492-02f6-11e6-876e-1f84e82cecfa.png)
![screenshot from 2016-04-15 10 38 25](https://cloud.githubusercontent.com/assets/2410802/14556138/e0594982-02f6-11e6-8c83-f8d7cbed76dc.png)
## :repr
![screenshot from 2016-04-15 10 41 15](https://cloud.githubusercontent.com/assets/2410802/14556143/e05c86b0-02f6-11e6-9e9a-63a41b32d819.png)
## :messages
![screenshot from 2016-04-15 10 42 10](https://cloud.githubusercontent.com/assets/2410802/14556141/e05c826e-02f6-11e6-9475-9c5db6545190.png)

**Comment by Shougo** [comment]
I cannot reproduce the error...

**Comment by m42e** [comment]
Ok, I updated my vim sources and compiled it again and the error disapeared, sorry bothering you.

**Comment by Shougo** [comment]
Oh, I get it.
