### ISSUE TITLE
Is it possible to cut a new release?

### ISSUE THREAD

**Issue by mbaldessari** [Shougo/unite.vim#1149]
# Problems summary
I am packaging unite for Fedora and was wondering if you could cut a new release, since the
last one was more than a year ago. Thanks again for unite, I love it ;)

**Comment by Shougo** [comment]
Thanks.  I need some fix for unite.
After that, I will add the tag release.

**Comment by mbaldessari** [comment]
Thanks a lot!

**Comment by Shougo** [comment]
Released 6.2.
