### ISSUE TITLE
NeoVim 0.1.3 + unite.vim </3

### ISSUE THREAD

**Issue by iammerrick** [Shougo/unite.vim#1150]
# Problems summary

Trying to run unite.vim in neovim is throwing an error.

## Expected

It was working, this appears to be a regression between either unite or neovim. 

## Environment Information
 * OS: OSX 10.11.4
 * Vim version: NVIM 0.1.3

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
" Your minimal .vimrc
let $NVIM_TUI_ENABLE_TRUE_COLOR=1

" Vundle
set nocompatible
filetype off

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'gmarik/Vundle.vim'
Plugin 'Shougo/unite.vim'
Plugin 'Shougo/vimproc.vim'
Plugin 'Shougo/deoplete.nvim'
Plugin 'benekastah/neomake'

call vundle#end()

filetype plugin indent on
```

## The reproduce ways from Vim starting (Required!)

1. Fresh install of Neovim
2. Fresh install of python3
3. Fresh install of neovim from pip

## Screen shot (if possible)
![screen shot 2016-04-14 at 4 57 02 pm](https://cloud.githubusercontent.com/assets/109635/14546365/31a68740-0262-11e6-9950-050ece6a7999.png)

## Upload the log messages by `:redir` and `:message`

NERDTree: 1 file(s) could not be loaded into the NERD tree
Error detected while processing function <SNR>22_call_unite[33]..unite#start[1]..unite#start#standard[39]..unite#init#_current_unite[97]..remote#define#CommandBootstrap:
line    5:
no request handler registered for "/Users/Merrick/.vim/bundle/unite.vim/rplugin/python3/unite.py:command:UniteInitializePython"
Encountered ImportError loading plugin at /Users/Merrick/.vim/bundle/unite.vim/rplugin/python3/unite.py: No module named 'unite'
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/neovim/plugin/host.py", line 118, in _load
    file, pathname, descr = find_module(name, [directory])
  File "/usr/local/lib/python3.5/site-packages/neovim/compat.py", line 29, in find_module
    return original_find_module(fullname, path)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named 'unite'

**Comment by iammerrick** [comment]
It is also useful to note that the same setup works in VIM 7.4.1724

**Comment by Shougo** [comment]
@iammerrick Your unite.vim is old.
Please update unite.vim.

**Comment by iammerrick** [comment]
I uninstalled unite.vim (by removing it from my vimrc and running BundleClean) and then added it and installed and get the same error. Thank you for the timely reply but are there any other possibility? BundleUpdate also didn't do the trick.

**Comment by iammerrick** [comment]
On a separate note this has made me realize how much I depend on Unite. :-)

**Comment by chemzqm** [comment]
I'm not quite suer, but it could be a bug of vundle with neovim, I used to have some problem when using vundle with neovim and python plugins.

**Comment by iammerrick** [comment]
Interesting, I switched to dein and that seems to of solved actually launching unite but now I am getting an error saying vimproc isn't installed despite manually building vimprocs native extensions. Thanks for your help by the way!

**Comment by wsdjeg** [comment]
please see vimproc readme,you need add build option to your vimrc
also you can have a look at my dotfiles repo

**Comment by iammerrick** [comment]
@wsdjeg I made a pull request this morning adding dein to the instructions for it. :-) And thanks!

**Comment by wsdjeg** [comment]
LGTM

**Comment by Shougo** [comment]
> 

Interesting, I switched to dein and that seems to of solved actually launching unite but now I am getting an error saying vimproc isn't installed despite manually building vimprocs native extensions. Thanks for your help by the way!

Please see the comment.
https://github.com/Shougo/vimproc.vim/pull/250
