### ISSUE TITLE
File candidate list not updated with directory contents

### ISSUE THREAD

**Issue by joshgummersall** [Shougo/unite.vim#1151]
# Problems summary

Candidate list not properly updating when typing path. I tracked down the issue to [this commit](https://github.com/Shougo/unite.vim/commit/21b6c8846b4c8fb62761e1470cbad8d2fc08ce6c). Using the previous commit works as expected.

```
:Unite -start-insert file
```

Say I have the following folder structure:
```
a:
  b:
    foo.txt
```

Typing "a/" into Unite yields an empty candidate list.

## Expected
Candidate list should update to have files in directory when typing a path to a file.

## Environment Information
 * OS: Mac OS X
 * Vim version: 7.4

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
" Your minimal .vimrc
set runtimepath+=~/path/to/unite.vim/
```

## The reproduce ways from Vim starting (Required!)

 1. `:Unite -start-insert file`
 2. Type path to file

## Screen shot (if possible)

With https://github.com/Shougo/unite.vim/commit/21b6c8846b4c8fb62761e1470cbad8d2fc08ce6c
![screen shot 2016-04-15 at 5 18 25 pm](https://cloud.githubusercontent.com/assets/1235378/14577822/28913804-032e-11e6-9e94-f382c2e69748.png)

With https://github.com/Shougo/unite.vim/commit/8772648d551c75adeeeed82fd115253617845b97
![screen shot 2016-04-15 at 5 17 45 pm](https://cloud.githubusercontent.com/assets/1235378/14577823/29e6593c-032e-11e6-9ce8-ef85224638fc.png)

## Upload the log messages by `:redir` and `:message`

Nothing relevant.

**Comment by delphinus35** [comment]
I think this issue is not fixed. With c4af317, I can reproduce this.

```sh
$ tree
.
└── a
    └── b
        └── foo.txt

2 directories, 1 file

$ cat /tmp/test-unite/.vimrc
set runtimepath+=/tmp/unite.vim

$ vim -N -u /tmp/test-unite/.vimrc -U NONE -i NONE
```

```vim
Unite -start-insert file
```

then...


![2016-04-18 14 09 57](https://cloud.githubusercontent.com/assets/1239245/14594256/801fa284-056f-11e6-8649-0b29529407c2.png)

and insert `a<CR>`...

![2016-04-18 14 10 15](https://cloud.githubusercontent.com/assets/1239245/14594259/89a42726-056f-11e6-825d-32a046b4b7d6.png)

It is desirable to see `b/` here.

**Comment by Shougo** [comment]
Fixed.
