### ISSUE TITLE
Using arguments with `get_candidates()` like `:Unite source -path=`

### ISSUE THREAD

**Issue by rafi** [Shougo/unite.vim#1156]
# Problems summary
How to only get candidates with a specific argument, for example: `unite#get_candidates([['file_mru', '-path', getcwd()]])`

However this returns all paths, instead of specific path like with `:Unite file_mru -path=...`

## Expected
The candidates of
```vim
:Unite file_mru -path=`getcwd()`
```
Should be the same as
```vim
:echo unite#get_candidates([['file_mru', '-path', getcwd()]])
```
or any other format?

## Environment Information
 * OSX 10.11.4 (15E65)
 * Vim version: Neovim v0.1.4

## Provide a minimal .vimrc with less than 50 lines (Required!)
```vim
set runtimepath+=~/.cache/vim/dein/repos/github.com/Shougo/dein.vim
call dein#begin('~/.cache/vim/dein')
call dein#add('Shougo/dein.vim')
call dein#add('Shougo/vimproc.vim',{'build' : 'make'})
call dein#add('Shougo/unite.vim')
call dein#end()
if dein#check_install()
    call dein#install()
endif
```

## The reproduce ways from Vim starting (Required!)
```vim
:echo map(unite#get_candidates([['file_mru', '-path', getcwd()]]), 'v:val["action__directory"]')
```

**Comment by Shougo** [comment]
`call unite#get_candidates(['file_mru'], {'path': getcwd()})`
