### ISSUE TITLE
Feature request: add unique tail converter

### ISSUE THREAD

**Issue by petobens** [Shougo/unite.vim#1157]
Is it possible to add a unique tail converter? [vim-airline](https://github.com/vim-airline/vim-airline/blob/410429a95c67eed8eeb26681838d3766a2437806/autoload/airline/extensions/tabline/formatters/unique_tail_improved.vim) has this nice functionality that can be seen in the screenshot below:

![screen shot 2016-05-07 at 12 36 51](https://cloud.githubusercontent.com/assets/2583971/15093001/67b29978-1450-11e6-9b71-7505bf362485.png)

It displays the tail of the filename, unless there is another file of the same name (such as `query.py` in the screenshot above) , in which case it will display it along with the containing parent directory, suppressing common parts of paths.
I find that this would be particularly useful for the buffer source. Thanks!!

**Comment by wsdjeg** [comment]
you mean show 
```
.../DPA/.../queries.py
.../PublisherQualityIndex/.../queries.py
```
in the unite buffer? it is really nice featue.

**Comment by petobens** [comment]
@wsdjeg yep, exactly that. I also think it would be nice.

**Comment by wsdjeg** [comment]
but I can see the whole buffer name here,I think unite have this featue, we just need some config.
![2016-05-07-23 53 15](https://cloud.githubusercontent.com/assets/13142418/15093088/0680c418-14af-11e6-8163-5cf817017a30.png)

**Comment by petobens** [comment]
@wsdjeg I can also see full path or relative paths changing the converter like this:
```vim
call unite#custom#source('buffer', 'converters', 'converter_relative_abbr')
```
But I in order to display the buffers the way I want, I believe a new converter must be created.

**Comment by wsdjeg** [comment]
ok, I see, I using vim-rooter, and it make getcwd() has same result in the git repo. now it is `~/DotFiles`.
and I also I have `set noautochdir` in my vimrc, so in th above pic,
`config/nvim/init.vim` and `config/nvim/config/init.vim` is just that two files in my dofiles repo.

**Comment by Shougo** [comment]
Implemented.

**Comment by petobens** [comment]
Thank but this is not quite working as expected. Consider the following screenshot:
![screen shot 2016-05-15 at 15 45 04](https://cloud.githubusercontent.com/assets/2583971/15276094/100cb1e4-1ab4-11e6-8778-e32e56a7b2f2.png)

I expect the Unite buffer to simply show:

```
.../python/queries.py
.../Desktop/queries.py
vimrc
```

**Comment by Shougo** [comment]
@petobens You must disable the candidates abbr.
I have added `converter_word_abbr`.
Please use it.

**Comment by petobens** [comment]
Mmm I tried using `converted_word_abbr` and `converter_tail` but I still get:
![screen shot 2016-05-17 at 12 30 43](https://cloud.githubusercontent.com/assets/2583971/15328460/5188da9e-1c2b-11e6-8ee2-23b629da4e14.png)

I expect to see (if possible):

```
.../Desktop/queries.py
.../python/queries.py
vimrc
```

**Comment by Shougo** [comment]
`['converter_word_abbr', 'converter_uniq_word']`

**Comment by petobens** [comment]
With your change I still don't get the desired output:

![screen shot 2016-05-21 at 12 20 51](https://cloud.githubusercontent.com/assets/2583971/15449244/8f89de08-1f4e-11e6-93ba-208caedd73cb.png)

**Comment by Shougo** [comment]
@petobens I cannot reproduce the behaviour.
Please create new issue with the minimal reproduce ways.

**Comment by petobens** [comment]
Thank you! Now it is almost working as expected. Consider the following screenshot:

![screen shot 2016-05-21 at 23 47 53](https://cloud.githubusercontent.com/assets/2583971/15451857/82a6d564-1fae-11e6-9a26-6b8e978ff4d5.png)

Currently full paths are shown:

```
   .../OneDrive/jampp/github-repos/analytics/PublisherQualityIndex/python/queries.py
   .../Desktop/queries.py
   vimrc
```

Ideally it would be nice to only show up to the first directory where the paths differ:
```
   .../python/queries.py
   .../Desktop/queries.py
   vimrc
```
Thanks!

**Comment by Shougo** [comment]
I don't want to add the feature.
My next work is to development denite.
The pull request is wellcome.

**Comment by petobens** [comment]
Ok. Thank anyway.

One extra question. Will you add Unite support to dein soon? I want to switch from Neobundle to dein but I really like the unite log viewer.

**Comment by Shougo** [comment]
> One extra question. Will you add Unite support to dein soon? I want to switch from Neobundle to dein but I really like the unite log viewer. 

Unite log viewer is on the todo list.

**Comment by Shougo** [comment]
I have improved it.

**Comment by Shougo** [comment]
> One extra question. Will you add Unite support to dein soon? I want to switch from Neobundle to dein but I really like the unite log viewer. 

Implemented.

**Comment by petobens** [comment]
You are awesome!!! Thank you!!! :)
