### ISSUE TITLE
The file_rec/neovim source does not use g:unite_source_rec_async_command

### ISSUE THREAD

**Issue by PonderingGrower** [Shougo/unite.vim#1158]
# Problems summary
The `file_rec/neovim` source does not seem to return the same results as the command
specified in the `g:unite_source_rec_async_command` variable.

## Expected
I expected the same results from `file_rec/neovim` as when I run the `g:unite_source_rec_async_command` command manually from shell.

Quoting from the documentation:
```
file_rec/neovim Similar to |unite-source-file_rec|, but get files
                asynchronously by neovim job APIs with
                |g:unite_source_rec_async_command|.
```

## Environment Information
 * OS: `Ubuntu 12.04.5 LTS`
 * Vim version: `NVIM 0.1.5-dev`
 * Unite commit: 7ae5ee37578349c32d542d3d43f053455b72daf4

## minimal .vimrc

`/tmp/test_nvim.init`:
```vim
call plug#begin('~/.config/nvim/bundle')
Plug 'Shougo/unite.vim'
call plug#end()

call unite#custom#source('file_rec/neovim', 'max_candidates', 300)

let g:unite_source_rec_async_command =
    \ ['ag', '--follow', '--nocolor', '-p', '~/.agignore', '-g', '']

nnoremap <c-i> :Unite -no-split file_rec/neovim:~/<CR>
```

`.agignore`:
```
.config/
.cache/
.wine/
...(ommitted)...
```

## The reproduce ways from Vim starting

 1. `nvim -u /tmp/test_nvim.init`
 2. Hit `<c-i>`
 3. Run `ag --follow --nocolor -p ~/.agignore -g ''` from home(`~/`).
 4. Compare the results, see that they are different.

Main issue is that the results include, for example, `.cache` dir that is ignored in my `.agignore`.

## Screencast

https://asciinema.org/a/1aiuqm1z6dqrbnyt855vwooml

**Comment by Shougo** [comment]
https://github.com/Shougo/unite.vim/issues/398#issuecomment-58877594

Please check your ag version.  Old ag has the bug.

**Comment by PonderingGrower** [comment]
Interesting. 

Okay, so originally I had `ag` in version `0.19.2-1`, now I tested `0.30.0-1` and `0.31.0-2` on [ubuntu](http://packages.ubuntu.com/trusty/silversearcher-ag). All give the same effect. When running them from shell the ignoring works, when running from `file_rec/neovim` I still see files that should be ignored, as if I was passing the `--unrestricted` but I do not.

I'll try compiling the most recent version and see where that leads me.

**Comment by PonderingGrower** [comment]
Nope, just compiled the most recent commit: ggreer/the_silver_searcher@0c55a13514e340cd5f8ed6f1fec799c2ece36eb7

Same thing.

**Comment by PonderingGrower** [comment]
Oh wait! I now used `<c-l>` in Unite and it refreshed the results. Now it looks correct.

What weird behaviour. I'll have to read the docs and see if I can disable this caching, it's very annoying.

**Comment by PonderingGrower** [comment]
I guess this can be closed. Looks like when testing changes to unite config it's essential to use `<Plug>(unite_redraw)` to make sure you are getting the actual results. It might be worth pointing this out more clearly in the docs.

Cheers Shougo!

**Comment by chemzqm** [comment]
Since `ag` is very fast , I have
```
let g:unite_source_rec_min_cache_files = 1200
```
in my `.vimrc`

**Comment by PonderingGrower** [comment]
Thanks, I'll try that out!

**Comment by Shougo** [comment]
OK.
