### ISSUE TITLE
Support regex filter for 'line' source

### ISSUE THREAD

**Issue by sasq64** [Shougo/unite.vim#1160]
Adding an option so that the "line" source can pre-filter lines on a regex before showing would be super useful for implementing things like "Jump to any function in file".

Note that this is different from setting an initial narrowing pattern. In fact pre filtering may be useful in many other situtations...

**Comment by Shougo** [comment]
Why this feature is really useful?
Please describe it more generally with the examples.

**Comment by sasq64** [comment]
`:Unite line -prefilter=<regexp>` could be used for showing a list of things in the current file and let user jump to it. Those things could be:
* functions
* class definitions
* imports
* TODO markers
etc

**Comment by wsdjeg** [comment]
@sasq64 I do think it is needed, for func and class, you can use unite-outline

**Comment by sasq64** [comment]
Well unite-outline uses ctags and that's a whole other can of worms.
I think a 'prefilter' option should apply to all matchers as a global option.

**Comment by Shougo** [comment]
I don't understand the reason.
Please create the examples.

Why don't use `-input`?

**Comment by Shougo** [comment]
No response.
