### ISSUE TITLE
Neovim: Unite is broken.

### ISSUE THREAD

**Issue by vort3x** [Shougo/unite.vim#1163]
# Problems summary
Updated to latest unite and now it doesn't work in NeoVim.

## Expected
:Unite should run unite.

## Environment Information
 * OS: OS X 10.11.5
 * Vim version: Neovim 0.1.4

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
nnoremap <C-p> :Unite file_rec/neovim -start-insert<cr>
```

## The reproduce ways from Vim starting (Required!)

 1. Start Neovim
 2. :Unite

## Screen shot (if possible)
![screen shot 2016-05-27 at 20 10 17](https://cloud.githubusercontent.com/assets/883328/15615449/18c76846-2447-11e6-8245-4c1d4862c98b.png)

## Upload the log messages by `:redir` and `:message`
```
Error detected while processing function <SNR>71_call_unite[33]..unite#start[1]..unite#start#standard[79]..unite#init#_unite_buffer:
line   94:
E216: No such group or event: unite CursorHoldI <buffer> * call unite#handlers#_on_cursor_hold_i()
```

**Comment by Shougo** [comment]
https://github.com/Shougo/unite.vim/issues/1161

**Comment by vort3x** [comment]
@Shougo, now when you start typing in Unite:
![screen shot 2016-05-27 at 20 35 02](https://cloud.githubusercontent.com/assets/883328/15616145/84c5fa14-244a-11e6-95a9-319b074998f9.png)
