### ISSUE TITLE
Error CursorHoldI Auto commands for "<buffer=3>"

### ISSUE THREAD

**Issue by vort3x** [Shougo/unite.vim#1164]
# Problems summary
When typing file name in :Unite you'll get error messages in Neovim.

## Expected
No error messages when typing file name.

## Environment Information
 * OS: OS X 10.11.5
 * Vim version: Neovim 0.1.4

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
nnoremap <C-p> :Unite file_rec/neovim -start-insert<cr>
```

## The reproduce ways from Vim starting (Required!)

 1. Start Neovim
 2. Run :Unite
 3. Go to insert mode
 4. Start typing 

## Screen shot (if possible)
![screen shot 2016-05-27 at 20 35 02](https://cloud.githubusercontent.com/assets/883328/15616247/2d791524-244b-11e6-8998-fb7c45e11695.png)

## Upload the log messages by `:redir` and `:message`
```
Error detected while processing CursorHoldI Auto commands for "<buffer=3>":
E20: Mark not set
```

**Comment by Shougo** [comment]
Fixed.
