### ISSUE TITLE
grep source results copy paste issue

### ISSUE THREAD

**Issue by squfrans** [Shougo/unite.vim#1165]
# Problems summary

When using the grep source, it is possible to yank text easily, but when selecting result text with mouse for copy paste, the selection is not "accurate" (off by a couple of characters)

## Expected

Select text with mouse and copy selected text into clipboard

## Environment Information
 * OS: OS X 101.11
 * Vim version: VIM - Vi IMproved 7.4 Included patches: 1-1831

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
" Your minimal .vimrc
set runtimepath+=~/path/to/unite.nvim/
```

## The reproduce ways from Vim starting (Required!)

 1. :Unite -no-start-insert grep
 2. Pattern: pattern_for_existing text
 3. in the result panel highlight some text with mouse cursor

**Comment by Shougo** [comment]
The text is concealed.  So it is feature.

**Comment by squfrans** [comment]
i am sorry, could you elaborate why is it a feature that the text is "concealed"?  it is still possible to copy paste it, it is just much harder...

i prefer not to make my system clipboard the vim unnamed register.
so yanking is good inside one vim session but what about multiple vim windows, or when i want to use that text outside of vim?

**Comment by Shougo** [comment]
It is the Vim feature.
I cannot fix it.

**Comment by squfrans** [comment]
thanks. this is a known vim bug:
http://vim.1045645.n5.nabble.com/behavior-of-mouseclick-positioning-cursor-with-concealed-chars-td4489865.html
