### ISSUE TITLE
[Feature Proposition] Include UniteDo command to execute command over each entry in Unite list

### ISSUE THREAD

**Issue by thalesmello** [Shougo/unite.vim#1166]
## Motivation for the Feature

A frequent use case for me is to populate a Unite buffer with the quickfix list, filter it with a narrowing text and then use `UniteNext` together with a macro in order iterate in order to apply it to each of the entries in the Unite buffer. I think a `UniteDo` command would be pretty handy in this situation, very similar to the way `argdo` is.

## Discussion

I've managed to come up with a prototype implementation, and I would like to discuss `UniteDo` command would be relevant feature to Unite.vim. I could open a pull request in case this would of interest.

## Prototype implementation

    function! UniteDoFunc(cmd)
        silent! UniteFirst
        " silent! mark u <-- Was a mistake. Not necessary for the implementation.
        while 1
            silent! execute a:cmd
            let current_pos = getpos('.')
            silent! UniteNext
            if current_pos == getpos('.')
                break
            endif
        endwhile
    endfunction
    command! -nargs=1 UniteDo call UniteDoFunc(<q-args>)

## Environment Information

 * OS: Mac OS X El Captain
 * Vim version: NVIM v0.1.5-230-g1fabc63

Edit: Comment out `silent! mark u` in the prototype implementation.

**Comment by Shougo** [comment]
Why this feature is needed?  What is the use case?  I don't understand it.

`silent! mark u`

Why it breaks u register?

**Comment by thalesmello** [comment]
The `silent! mark u` isn't necessary. It was a mistake of my part.

A common use case for me would be when filtering linter messages.

Suppose you have the following JavaScript code.

```
/* jshint unused: true */

var variable = 1;

function foo () {
	console.log('Hello foo!')
}

function bar () {
	console.log('Good bye bar!')
}
```

If we use [JsHint](http://jshint.com/docs/) to lint the code, it's going to output the following to output the following.

```
test.js: line 6, col 30, Missing semicolon.
test.js: line 10, col 33, Missing semicolon.
test.js: line 3, col 5, 'variable' is defined but never used.
test.js: line 5, col 10, 'foo' is defined but never used.
test.js: line 9, col 10, 'bar' is defined but never used.

5 errors
```

A screenshot of how it looks like in my VIM is:

![image](https://cloud.githubusercontent.com/assets/1127394/15764566/24dde14a-2902-11e6-9097-2cfc4dc88e72.png)

Now let's suppose I want all of the semicolon warnings at once.

Since [Neomake](https://github.com/neomake/neomake) and other linters populate the localtion list, I can vizualize the errors using [Unite Quickfix](https://github.com/osyo-manga/unite-quickfix). It looks like this after I run `:Unite location_list`.

![image](https://cloud.githubusercontent.com/assets/1127394/15764614/9d9848fa-2902-11e6-8b72-b683e3f7b2fc.png)

Now, after I input `semicolon` as my narrowing text, it looks like this:

![image](https://cloud.githubusercontent.com/assets/1127394/15764669/20a982d6-2903-11e6-8aad-c9eb6ff1da9c.png)

After I press enter, it takes me to the first item of my filtered list. Because I have defined a `UniteDo` command in my `.vimrc`, I can simply type `:UniteDo normal! A;` and hit enter.

![image](https://cloud.githubusercontent.com/assets/1127394/15764729/a282f08a-2903-11e6-9bf9-97b79ac8c74c.png)

Now, I've solved the warnings all at once, which makes it extremely convenient when you have longer files.

Notice this workflow could be expanded to perform operations on all sorts of sources, such as files that match a specific pattern, the result of a `grep` search, etc.

**Comment by Shougo** [comment]
OK.  I get it.

It should be:

```vim
function! UniteDoFunc(cmd)
    silent! UniteFirst
    let current_pos = []
    while current_pos != getpos('.')
        silent! execute a:cmd
        let current_pos = getpos('.')
        silent! UniteNext
    endwhile
endfunction
```

Please create the pull request.

**Comment by tex** [comment]
Great command. I used it and it is superb!
