### ISSUE TITLE
Quick way of changing cwd

### ISSUE THREAD

**Issue by GuillaumeLeclerc** [Shougo/unite.vim#1167]
Hello,

I'm a new Unite user and it looks great. The only small problem is almost all source rely on the current working directory. And it's not very user friendly to use the `:cd` command. Is there a way to switch directories without using NerdTree or `:cd`. (Maybe somthing like helm find file to select the directory and automatically change the cwd to the selected directory).

Thank you for you help.

**Comment by Shougo** [comment]
You can use "lcd" action for it.

**Comment by GuillaumeLeclerc** [comment]
Thank you !
