### ISSUE TITLE
Unable to find exact match in file_rec/async

### ISSUE THREAD

**Issue by GuillaumeLeclerc** [Shougo/unite.vim#1170]
Hello,

In big projects I can't find files even If I don't type the exact filename. 

I read the documentation and saw that the problem could come from the `max_candidate` option but it is said that the default is infinity so I don't have a clue.

Thank you for your help

**Comment by Shougo** [comment]
@GuillaumeLeclerc No.
file_rec/async's max_candidates is 50.
You can change the value by `unite#custom#source()`.
Or `<Plug>(unite_disable_max_candidates)` mapping.
