### ISSUE TITLE
UniteDo does not work when positions are same in different files

### ISSUE THREAD

**Issue by lervag** [Shougo/unite.vim#1172]
If I use `Unite` with a file listing, do some narrowing, then run `UniteDo`, I would expect the following command to run on all the files. However, because of the `while current_pos != getpos('.')`, the loop will break IMHO unexpectedly if the cursor is located at the first byte of two files.

I think the loop logic needs to be updated so that the current position includes the buffer file name or something like that.

Ref.: #1166, #1169.

@thalesmello

**Comment by Shougo** [comment]
Fixed.

**Comment by lervag** [comment]
Thanks, although, it seems that it will not do the command for the first candidate in the list. I try the following:

1. `:Unite file_rec/async:~/.vim<cr>`

2. Narrow with `unite.vim plugin`, get the following list (including the prompt):
    
    ```
    > unite.vim plugin
      bundle/unite.vim/plugin/unite/window.vim
      bundle/unite.vim/plugin/unite/bookmark.vim
      bundle/unite.vim/plugin/unite/buffer.vim
      bundle/unite.vim/plugin/unite.vim
    ```

3. I select the first entry.

4. Finally, I do `:UniteDo unsilent echom expand('%')`. This outputs the filenames of the last three files, but not for `window.vim`.

**Comment by Shougo** [comment]
Fixed again.

**Comment by lervag** [comment]
Nah, I think there is still a [minor bug left](https://github.com/Shougo/unite.vim/commit/d5dd626d299e702a5223d2365ab0e52f28613f18#commitcomment-17786352). But I like how the code has ended up!

**Comment by Shougo** [comment]
Fixed.

**Comment by lervag** [comment]
Thanks!
