### ISSUE TITLE
Cannot bind normal mode movements to Unite menu

### ISSUE THREAD

**Issue by tecfu** [Shougo/unite.vim#1175]
# Problems summary

I wrote a function to open the Unite file_mru menu, go to the second line of the menu, and open it as a new tab.

I can't seem to get the Unite menu to obey the following command given within my function to do this: 

		exe "normal 2gg<CR>"

## Expected

I expect that using the command given above, the cursor will move to the second line in the Unite menu and select the item on that line.

## Environment Information
 * OS: Ubuntu 14.04 
 * Vim version: 7.4

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
" Your minimal .vimrc

" Undo close tab using Shougo/Unite to get MRU file

NeoBundle 'Shougo/unite.vim'

function! UndoCloseTab()
	:tabnew	
	:tabm -1	
	:Unite file_mru
	exe "normal 2gg<CR>"
endfunction

nmap <C-u> :call UndoCloseTab()<CR><ESC>


```

## The reproduce ways from Vim starting (Required!)

tabclose
<C-u>

**Comment by wsdjeg** [comment]
you should use `exe "normal! 2gg<CR>"`

**Comment by tecfu** [comment]
@wsdjeg Applied this, same result. Cursor just sits on 2nd row but does not select it.

**Comment by wsdjeg** [comment]
2gg will not select anything ,you can use 2ggV select second row

**Comment by tecfu** [comment]
Same result using 2ggV.

**Comment by wsdjeg** [comment]
How do you let the func works well in other buffer instead of unite?
in normal mode ,if you type 2gg,what will happen?

BTW, I will test it tonight.

**Comment by wsdjeg** [comment]
```vim
function! UndoCloseTab()
    :tabnew 
    :tabm -1    
    :Unite file_mru
    normal! 2ggf/gf
endfunction
```

this func works well for me ,I have test it, 

and in unite buffer, each line looks like this
`(04-29-2016 22:38:52) /home/wsdjeg/sources/JavaUnit.vim/autoload/javaunit.vim`

so I need use `2gg` to jump to line 2, `f\` to move cursor to the begin of file name, then `gf` open current file.

**Comment by tecfu** [comment]
@wsdjeg That's brilliant. Your fix works. Thank you. 

What process did you use to solve this problem? Did you read through the source, use vim docs, or simply apply existing knowledge?

**Comment by wsdjeg** [comment]
that is the useage about viml. I do not read src of unite.
