### ISSUE TITLE
file_rec/async not working on windows 8.1

### ISSUE THREAD

**Issue by ri-aje** [Shougo/unite.vim#1176]
# Problems summary
`file_rec/async` not working on windows 8.1
start vim/gvim in any directory on windows and issue `:Unite -buffer-name=files   file_rec/async:!` command.
no files listed, got this error message:
[unite.vim] [file_rec/async] The filename, directory name, or volume label syntax is incorrect.

I installed vimproc.vim and built it with mingw32 following the instruction for 32-bit vim and I see the `vimproc.vim/lib/vimproc_win32.dll` generated.

removing the `:!` from the above command repros the same problem.

in the meanwhile, `file_rec` or `file_rec:!` all works, i.e., without the `/async`

## Expected
unite lists all files under the directory.

## Environment Information
 * OS: windows 8.1
 * Vim version: 7.4.1641 32-bit

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
" Your minimal .vimrc
set nocompatible

" I used vim-plug(https://github.com/junegunn/vim-plug) to manage my plugins.
call plug#begin('~/.vim/bundle')
 Plug 'Shougo/unite.vim'
 Plug 'Shougo/vimproc.vim'
call plug#end()

let g:unite_source_rec_async_command = ['cmd.exe ', ' /c ', ' dir /s /b ']
```

## The reproduce ways from Vim starting (Required!)

 1. vim.exe
 2. type `:`
 3. type `Unite -buffer-name=files   file_rec/async:!` with or without the `:!` at the end.
 4. type `Enter`

## Screen shot (if possible)
not sure how to post image.

## Upload the log messages by `:redir` and `:message`
[unite.vim] [file_rec/async] The filename, directory name, or volume label syntax is incorrect.

pressing ctrl-a in the unite window gives me this:
[file_rec/async] directory: `my_absolute_dir`
[file_rec/async] Command-line: ['cmd.exe ', ' /c ', ' dir /s /b ', '`my_absolute_dir`']

**Comment by Shougo** [comment]
cmd.exe is not supported as file_rec/async.
Please use other command.

**Comment by ri-aje** [comment]
two questions:
1. where does unite doc say cmd.exe is not supported? can you put it somewhere under unite_source_rec_async_command so people don't spend a lot of time on a doomed attempt.
2. since cmd.exe is not supported, any practical recommendation for unite_source_rec_async_command on windows platform?

**Comment by Shougo** [comment]
> 1. where does unite doc say cmd.exe is not supported? can you put it somewhere under unite_source_rec_async_command so people don't spend a lot of time on a doomed attempt.

OK.  I will add it.

> 2. since cmd.exe is not supported, any practical recommendation for unite_source_rec_async_command on windows platform?

`ls.exe` is recommended.
But file_rec/async is slow in Windows platform.
I don't recommend to use it in Windows.

**Comment by tex** [comment]
Yeah, it is slow as hell on windows. On Linux it is reasonable quick. I switch to use gtags/path on Windows instead of file_rec / (async). It is really very quick.

**Comment by ri-aje** [comment]
what is `gtags/path`? is it an unite mode or a different plugin? I cannot seem to find it either way.

**Comment by Shougo** [comment]
@ri-aje https://github.com/hewes/unite-gtags

**Comment by shitfSign** [comment]
I meet same error: file_rec/async not working on window7 64
in the meanwhile, file_rec or file_rec:! all works, i.e., without the /async

VIM : v8.0.0005
ag   : https://github.com/kjk/the_silver_searcher

my config
" unite {{{
nnoremap [unite] <Nop>
nmap <space> [unite]
nnoremap <C-p> :Unite -start-insert file_rec/async:!<CR>
call unite#filters#matcher_default#use(['matcher_fuzzy'])
call unite#custom#source('file_rec', 'sorters', 'sorter_length')

" Open in bottom right
let g:unite_split_rule = "botright"
"let g:unite_enable_split_vertically = 1
" Shorten the default update date of 500ms
let g:unite_update_time = 500
let g:unite_source_file_mru_limit = 300
let g:unite_cursor_line_highlight = 'TabLineSel'

let g:unite_source_file_mru_filename_format = ':~:.'
let g:unite_source_file_mru_time_format = ''

let g:unite_source_grep_max_candidates = 200

if executable('ag')
  let g:unite_source_grep_command = 'ag'
  let g:unite_source_grep_default_opts =
        \ '-i --vimgrep --hidden --ignore ' .
        \ '''.hg'' --ignore ''.svn'' --ignore ''.git'' --ignore ''.bzr'''
  let g:unite_source_rec_async_command =
                \ ['ag', '-p', '--follow', '--nocolor', '--nogroup',
		\  '--hidden', '-g', '']
  let g:unite_source_grep_recursive_opt = ''
  let g:unite_source_grep_search_word_highlight = 1
endif
" }}}
