### ISSUE TITLE
Feature Request: Grep git submodules

### ISSUE THREAD

**Issue by darcyparker** [Shougo/unite.vim#1177]
# Problems summary

grep/git currently does not include results of submodules.

## Expected

grep/git uses `git submodule foreach` to include submodule's grep results too.

## Initial work

I tried this and I think I am on the right track, but probably have some escaping issues. Any help finishing this would be appreciated. (Or some hints.) -- Thanks.

> Notice that I am prepending the submodule's path which is provided by git's ` submodule foreach` as `$path`.

```
  let cmdline = printf("git grep -n --no-color %s %s -- %s ; git --no-pager submodule --quiet foreach 'git grep -n --no-color %s %s | while read _gitGrep; do echo $path/$_gitGrep; done'",
    \   a:context.source__extra_opts,
    \   string(a:context.source__input),
    \   unite#helper#join_targets(a:context.source__targets),
    \   a:context.source__extra_opts,
    \   string(a:context.source__input),
    \)
```

Another improvement would be to use `git submodule foreach --recursive`, but building the `$path` to prepend will be a bit more complex.  I only have submodules nested one level.  So the above would be nice.

**Comment by Shougo** [comment]
I have tested your code but it does not work.  It seems wrong.

Unfortunately, it seems not easy and I don't use `grep/git` source.
It is from @lambdalisue .
@lambdalisue What do you think?

**Comment by Shougo** [comment]
It must be work in https://github.com/zchee/deoplete-clang repository.

**Comment by lambdalisue** [comment]
I'm not really sure but is [`vimproc#plineopen3()`](https://github.com/Shougo/unite.vim/blob/master/autoload/unite/sources/grep_git.vim#L107) support such sequential commands?

Additionally, I'm not really comfortable with parsing submodules which would slow the response a lot if the repository has tons of submodules. In my opinion, this feature is required to be controlled by options or whatever at least.

**Comment by Shougo** [comment]
> I'm not really sure but is vimproc#plineopen3() support such sequential commands?

Yes.

> Additionally, I'm not really comfortable with parsing submodules which would slow the response a lot if the repository has tons of submodules. In my opinion, this feature is required to be controlled by options or whatever at least.

I agree with you.

**Comment by darcyparker** [comment]
I wrote a better script:
https://gist.github.com/darcyparker/d5b9168ada88d0527564a11d9d9899c4

I also agree with @lambdalisue that this feature of searching submodules should be configurable.

Perhaps the best solution is something along these lines... Asks users who want this capability to:
* Put the [gitgrep](https://gist.github.com/darcyparker/d5b9168ada88d0527564a11d9d9899c4) script in their `$path`
* Create an alias in their `~/.gitconfig` like this: `grepall = "!f() { gitgrep "$1" "$2" "$3"; }; f"`
* Create a new unite source that uses the `git grepall` command

What do you think?

**Comment by Shougo** [comment]
I think you should use the script as `g:unite_source_grep_command`.
