### ISSUE TITLE
Exclude Unite from the buffer list if possible

### ISSUE THREAD

**Issue by Somelauw** [Shougo/unite.vim#1178]
## Steps to reproduce
1. $ nvim a b
2. :bn\<CR\>:bn\<CR\>
3. :Unite -no-split file
4. ctrl-g
5. :b #\<CR\>

## Desired behaviour
Typing :b # should toggle between a and b

## Actual behaviour
:b # reopens Unite

## Vimrc
Make sure Unite is installed. For example:

    filetype plugin on

    call plug#begin()
    Plug 'Shougo/unite.vim'
    call plug#end()

**Comment by Shougo** [comment]
Implemented.
