### ISSUE TITLE
perl locale warnings

### ISSUE THREAD

**Issue by seanDot7** [Shougo/unite.vim#1179]
# Problems summary

I use unite to search my file, and sometimes I get some perl warnings say "Setting locale failed". But actually I have set these environment variables. I don't know how to fix this problem. 

## Environment Information
 * OS: OS X 10.11.5
 * Vim version: 7.4

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
" Your minimal .vimrc
set runtimepath+=~/path/to/unite.nvim/
```

## The reproduce ways from Vim starting (Required!)

 1. foo
 2. bar
 3. baz

## Screen shot (if possible)
![image](https://cloud.githubusercontent.com/assets/5859702/16791300/324243a4-48f0-11e6-930b-3b0b51174435.png)

**Comment by Shougo** [comment]
It is not unite.vim problem.
It is your environment error.

http://blogs.agilefaqs.com/2014/01/12/fixing-perl-warning-setting-locale-failed-on-mac-osx/

**Comment by seanDot7** [comment]
Thanks. I see.
