### ISSUE TITLE
Regexp for word boundaries in Unite vimgrep does not work

### ISSUE THREAD

**Issue by balta2ar** [Shougo/unite.vim#1180]
Hello. I'm trying to search for a complete word in current buffer as follows:
``` vim
:Unite vimgrep:%:\<pattern\>
```
But it does not find anything. If I remove `\<` and `\>` it finds words, but it finds too many. I need word boundaries for a reason.
On the other hand, it's working fine if I use native vim's vimgrep:
``` vim
:vimgrep /\<impname\>/ %
```
But it lacks awesome Unite interface. Could you check please?

**Comment by balta2ar** [comment]
The same applies to Unite grep command, but I think it's not relevant because that's for the underlying grepper to support, which in my case is `ag`.

**Comment by Shougo** [comment]
Please escape backslash.

```vim
:Unite vimgrep:%:\\<pattern\\>
```
