### ISSUE TITLE
switching out of terminal buffer in neovim causes errors

### ISSUE THREAD

**Issue by aeyakovenko** [Shougo/unite.vim#1181]
# Problems summary
if i am focused on a terminal buffer in neovim and then run `:Unite buffer` and pick any buffer i see these errors
```
Error detected while processing function unite#action#do[57]..unite#all_quit_session[1]..unite#view#_quit:
line   79:
E86: Buffer 2 does not exist
```

## Expected

switch to a buffer

## Environment Information
 * OS: osx
 * Vim version:
 vi --version
NVIM 0.1.3
Build type: RelWithDebInfo
Compilation: /usr/local/Library/ENV/4.3/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/tmp/neovim20160417-6834-i6b3ty/neovim-0.1.3/build/config -I/tmp/neovim20160417-6834-i6b3ty/neovim-0.1.3/src -I/tmp/neovim20160417-6834-i6b3ty/neovim-0.1.3/deps-build/usr/include -I/tmp/neovim20160417-6834-i6b3ty/neovim-0.1.3/deps-build/usr/include -I/tmp/neovim20160417-6834-i6b3ty/neovim-0.1.3/deps-build/usr/include/luajit-2.0 -I/tmp/neovim20160417-6834-i6b3ty/neovim-0.1.3/deps-build/usr/include -I/tmp/neovim20160417-6834-i6b3ty/neovim-0.1.3/deps-build/usr/include -I/tmp/neovim20160417-6834-i6b3ty/neovim-0.1.3/deps-build/usr/include -I/tmp/neovim20160417-6834-i6b3ty/neovim-0.1.3/deps-build/usr/include -I/usr/local/opt/gettext/include -I/usr/include -I/usr/include -I/tmp/neovim20160417-6834-i6b3ty/neovim-0.1.3/build/src/nvim/auto -I/tmp/neovim20160417-6834-i6b3ty/neovim-0.1.3/build/include
Compiled by anatolyy@anatolys-MacBook.local

Optional features included (+) or not (-): +acl   +iconv    +jemalloc 
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.1.3/share/nvim"

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
" Your minimal .vimrc
if &compatible
   set nocompatible
endif
set runtimepath^=~/.dein/repos/github.com/Shougo/dein.vim

call dein#begin(expand('~/.cache/dein'))

call dein#add('~/.dein/repos/github.com/Shougo/dein.vim')
call dein#add('Shougo/neocomplete.vim')
call dein#add('Shougo/vimproc.vim', {'build' : 'make'})
call dein#add('Shougo/unite.vim')
call dein#add('moll/vim-bbye')
call dein#add('derekwyatt/vim-scala')
call dein#end()
```

## The reproduce ways from Vim starting (Required!)

 1. nvim
 2. :terminal
 3. :Unite file
 4. pick a file and try to open it

## Upload the log messages by `:redir` and `:message`
```
Messages maintainer: Bram Moolenaar <Bram@vim.org>
"build.sbt" 12L, 365C
"term://.//19096:/bin/bash" line 25 of 46 --54%-- col 1
Error detected while processing function unite#action#do[57]..unite#all_quit_session[1]..unite#view#_quit:
line   79:
E86: Buffer 1 does not exist
```

sometimes it works

**Comment by Shougo** [comment]
Fixed.

**Comment by aeyakovenko** [comment]
wow, thats quick!  I am seeing the terminal buffer being killed still, and sometimes i see this message:
```
[unite.vim] function unite#action#do[70]..69, line 2
[unite.vim] Vim(buffer):E86: Buffer 1 does not exist
[unite.vim] Error occurred while executing "open" action!
```
1. start nvim
2. :terminal
3. :Unite file
4. pick a non terminal file
5. terminal buffer is gone, not in the `ls` list or `Unite buffer` list

**Comment by Shougo** [comment]
> wow, thats quick! I am seeing the terminal buffer being killed still, and sometimes i see this message:

Do you know vim-bbye feature?
It kills all unfocused buffers including the terminal buffer.
It introduces unexpected behavior for plugins like this.
I don't recommend to use it.

**Comment by aeyakovenko** [comment]
Thanks for your help, but it seems to fail even with all the other plugins disabled.
```
call dein#add('Shougo/vimproc.vim', {'build' : 'make'})
call dein#add('Shougo/unite.vim')
```

so if i run just the terminal buffer i can select it in the `Unite buffer` menu, but as soon as i switch to a non terminal buffer it disappears.  I also see this message
```
[unite.vim] function unite#action#do[70]..138, line 2
[unite.vim] Vim(buffer):E86: Buffer 1 does not exist
[unite.vim] Error occurred while executing "open" action!
```
1. run nvim
2. :terminal
3. :Unite buffer file
4. select a non terminal buffer
5. :Unite buffer
6. try selecting the terminal buffer

**Comment by Shougo** [comment]
@aeyakovenko Please execute `:call dein#recache_runtimepath()`.

**Comment by aeyakovenko** [comment]
no luck :(, but i saw a different error message this time:
```
Messages maintainer: Bram Moolenaar <Bram@vim.org>
"build/delete_ccm_cluster.sh" 17L, 322C
[unite.vim] function unite#action#do[70]..183, line 2
[unite.vim] Vim(buffer):E86: Buffer 1 does not exist
[unite.vim] Error occurred while executing "open" action!
Press ENTER or type command to continue
```

the terminal dies sometimes when you switch out to a different file/buffer

**Comment by Shougo** [comment]
@aeyakovenko Please read the below issue.
It is neovim bug.
https://github.com/neovim/neovim/issues/5122
