### ISSUE TITLE
When trying to open tags (pressing <C-]>)"unite buffer "tag" candidates are empty"

### ISSUE THREAD

**Issue by rodrigomaia17** [Shougo/unite.vim#1182]
# Problems summary
I get the message "unite buffer "tag" candidates are empty" when I trying to jump to tag (pressing `<C-]>`).

I can open the tag unite buffer using `:Unite tag`, but when running the command it does not happen.

The mapping for this command now is: ( seems that it was set by the plugin)  
```
 n  <C-]>       *@:<C-U>UniteWithCursorWord -buffer-name=tag -no-start-insert -immediately tag<CR>
```

## Environment Information
 * OS: OSX El Capitan
 * Vim version: NVIM 0.1.4

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
Plug 'Shougo/vimproc.vim', { 'do': 'make' }
Plug 'Shougo/unite.vim'
Plug 'rstacruz/vim-fastunite'
"Plug 'Shougo/neomru.vim'
"Plug 'Shougo/unite-outline'
Plug 'tsukkee/unite-tag'
"Plug 'Shougo/neoinclude.vim'
map <C-p> [unite]p
```

## The reproduce ways from Vim starting (Required!)

 1. Open vim
 2. Go to any word in code
 3. press C-]

**Comment by Shougo** [comment]
Please upload your tag file.
And please upload the real reproduce ways.
Note : `Go to any word in code` is very fuzzy.  Please read other issues.
Do you think other people can reproduce it using the uploaded reproduce ways?
I cannot reproduce it.

**Comment by Shougo** [comment]
And please upload real minimal .vimrc.
Your minimal .vimrc is invalid.
It must be executed by `vim -u your_minimal_vimrc`.
Please read other issues.

**Comment by Shougo** [comment]
No response.
