### ISSUE TITLE
output/shellcmd does not change directory for UniteWithBufferDir and UniteWithProjectDir

### ISSUE THREAD

**Issue by nilsboy** [Shougo/unite.vim#1186]
# Problem summary

When a shell command is run using output/shellcmd the command's current working directory (pwd) is always vim's current working directory - which is fine for :Unite - but should differ when using :UniteWithBufferDir or :UniteWithProjectDir.

## Expected
It is expected that the script's pwd be the directory of the file in the buffer with UniteWithBufferDir and the project root with UniteWithProjectDir.

## Environment Information
 * OS: Ubuntu 14.04
 * Vim version: 7.4

## Minimal .vimrc

```vim
set nocompatible

let g:plugin_dir = expand('~/.vim/dein')
let g:dein_dir = g:plugin_dir . '/repos/github.com/Shougo/dein.vim'
execute 'set runtimepath+=' . g:dein_dir

if !isdirectory(g:dein_dir)
  call mkdir(g:dein_dir, 'p')
  silent execute printf('!git clone %s %s', 'http://github.com/Shougo/dein.vim', g:dein_dir)
endif

call dein#begin(g:plugin_dir)

" Let dein manage dein
call dein#add('Shougo/dein.vim')
call dein#add('Shougo/vimproc.vim', {'build': 'make'})
call dein#add('Shougo/unite.vim')

call dein#end()

if dein#check_install() 
  call dein#install()
endif

filetype plugin indent on
```

### UniteWithBufferDir

 1. mkdir -p test/buffer_dir
 2. touch test/buffer_dir/{a,b}
 3. vi test/buffer_dir/a
 4. :UniteWithBufferDir output/shellcmd:ls

=> expected: a b
=> but no result

### UniteWithProjectDir

 1. mkdir -p test/project/.git
 2. touch test/project/{c,d}
 3. vi test/project/c
 4. :UniteWithProjectDir output/shellcmd:ls

=> expected: c d
=> but no result

Thank you for looking into this.

**Comment by Shougo** [comment]
Fixed.
