### ISSUE TITLE
Support open action for output/shellcmd

### ISSUE THREAD

**Issue by nilsboy** [Shougo/unite.vim#1187]
# Problems summary
I have an external command that produces a list of file names.
I like to use it with the output/shellcmd source.
The default kind of output/shellcmd seems to be "word" so I can not use the "open" action on the file name.

## The reproduce ways from Vim starting (Required!)

 1. :Unite output/shellcmd:find

Would it be possible to add the file kind to the output/shellcmd source?

Thank you.

**Comment by Shougo** [comment]
I don't want to add it.
You can add it.
Closing.
