### ISSUE TITLE
How to wait for a Unite command to finish?

### ISSUE THREAD

**Issue by HaleTom** [Shougo/unite.vim#1189]
# Problems summary

I want to wait for a Unite command to finish before the next command is executed.

Eg, I want to automate the install of all bundles:

```
vim '+echom "Installing unite and vimproc..."' '+NeoBundleInstall unite vimproc' '+echom "Installing all bundles..."' '+Unite neobundle/install' +qall
```

## Expected

vim quits only after the command has finished rather than straight away.
## Environment Information
 * OS: Linux Mint 17.2
 * Vim version: VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Aug 05 2016 16:48:20)        

## Provide a minimal .vimrc with less than 50 lines (Required!)

Nil - Should work without a `.vimrc`

## The reproduce ways from Vim starting (Required!)

 1. `vim '+echom "Installing unite and vimproc..."' '+NeoBundleInstall unite vimproc' '+echom "Installing all bundles..."' '+Unite neobundle/install' +qall`

 2.  I can't get the following to work either: `vim '+Unite neobundle/install|qall'`
Output:
> [unite.vim] Invalid source name "neobundle/install|qall" is detected.                                                                                                                                   
> [unite.vim] unite.vim: Invalid source                                                                                                                                                                   
> Press ENTER or type command to continue

**Comment by Shougo** [comment]
You should use neoinstall command.
https://github.com/Shougo/neobundle.vim/blob/master/bin/neoinstall

**Comment by HaleTom** [comment]
This is highly awesome!!! Thanks heaps!!
