### ISSUE TITLE
file_rec/neovim not showing candidates

### ISSUE THREAD

**Issue by petobens** [Shougo/unite.vim#1191]
Consider the following minimal init.vim file:
```vim
let $DOTVIM = expand('$HOME/.vim')

set runtimepath+=$DOTVIM/bundle/repos/github.com/Shougo/unite.vim
filetype plugin indent on

call unite#custom#profile('default', 'context', {
            \ 'start_insert' : 1, 'auto_resize' : 1,
            \ 'direction' : 'botright', 'prompt_direction': 'top',
            \ })
nnoremap ,ls :Unite -buffer-name=fuzzy-search file_rec/neovim<CR>
```

Now open neovim sourcing that file and then do the following (as in the GIF):
1. `cd` to some directory other than the starting one; for example `:cd /Users/Pedro/Desktop`
2 . press `,ls`. You will see that no candidates are shown.
3. press some letter to start filtering (for example `i`): candidates are shown

I expect candidates to be shown on step 2 i.e immediately after pressing `,ls`.

![sep-13-2016 00-46-49](https://cloud.githubusercontent.com/assets/2583971/18460874/98745a3c-794b-11e6-8c6e-9c18b29a3dd7.gif)

**Comment by Shougo** [comment]
#1079 

You should denite.nvim instead.

**Comment by petobens** [comment]
@Shougo but denite.nvim still doesn't have all of unite's features.... Right? From the readme I see that future work is "implement some sources".

**Comment by Shougo** [comment]
Yes, but file_rec source is implemented.

**Comment by petobens** [comment]
Ahh okok. Thanks.
