### ISSUE TITLE
Purpose of <C-u> in mappings

### ISSUE THREAD

**Issue by ssidorchick** [Shougo/unite.vim#1193]
Looking into docs I have found that `<C-u>` command is used in pretty much any mapping, for instance `nnoremap <leader>f :<C-u>Unite file<CR>`. I have removed it and didn't notice any changes. Could you please clarify why it's needed?

**Comment by chemzqm** [comment]
It's needed to clear the existing command.

**Comment by ssidorchick** [comment]
But when typing command, key mappings are not available. I actually don't see the use case. Could you give an example?

**Comment by itchyny** [comment]
The `<C-u>` is used to clear the range. Type `5<leader>f` to see the difference.

**Comment by ssidorchick** [comment]
heh, have never used ranges. Thanks for explanation.
