### ISSUE TITLE
file_rec/async not working on windows7 64

### ISSUE THREAD

**Issue by shitfSign** [Shougo/unite.vim#1194]
I meet same error: file_rec/async not working on window7 64 no files listed
I found file, file/async, file_rec all works, i.e.. file_rec/async not work.

VIM : v8.0.0005
ag : https://github.com/kjk/the_silver_searcher

Plug 'Shougo/unite.vim'
Plug 'Shougo/vimproc.vim'

my config
" unite {{{
nnoremap [unite] 
nmap [unite]
nnoremap :Unite -start-insert file_rec/async:!
call unite#filters#matcher_default#use(['matcher_fuzzy'])
call unite#custom#source('file_rec', 'sorters', 'sorter_length')

" Open in bottom right
let g:unite_split_rule = "botright"
"let g:unite_enable_split_vertically = 1
" Shorten the default update date of 500ms
let g:unite_update_time = 500
let g:unite_source_file_mru_limit = 300
let g:unite_cursor_line_highlight = 'TabLineSel'

let g:unite_source_file_mru_filename_format = ':~:.'
let g:unite_source_file_mru_time_format = ''

let g:unite_source_grep_max_candidates = 200

if executable('ag')
let g:unite_source_grep_command = 'ag'
let g:unite_source_grep_default_opts =
\ '-i --vimgrep --hidden --ignore ' .
\ '''.hg'' --ignore ''.svn'' --ignore ''.git'' --ignore ''.bzr'''
let g:unite_source_rec_async_command =
\ ['ag', '-p', '--follow', '--nocolor', '--nogroup',
\ '--hidden', '-g', '']
let g:unite_source_grep_recursive_opt = ''
let g:unite_source_grep_search_word_highlight = 1
endif
" }}}

**Comment by Shougo** [comment]
I don't want to support ag in Windows.
files is better.
https://github.com/mattn/files

**Comment by shitfSign** [comment]
Thank you for your help.

**Comment by wsdjeg** [comment]
ag.exe works well for me. and the version is 0.29.

**Comment by wsdjeg** [comment]
@shitfSign please see the pic below
![qq 20160919171853](https://cloud.githubusercontent.com/assets/13142418/18627375/3117af78-7e8d-11e6-8d16-98b00e2536f6.png)

**Comment by shitfSign** [comment]
@wsdjeg Thank you.
I will try it.

**Comment by shitfSign** [comment]
@wsdjeg 
ag: https://github.com/ggreer/the_silver_searcher
I compile it in mingw64, I try 0.29, 0.30,0.31,0.32.
I found 0.29, 0.30 it works for me.
But for the larger project speed is relatively slow.

so, it will try files
files is better.
https://github.com/mattn/files
