### ISSUE TITLE
file_list source: relative path problem

### ISSUE THREAD

**Issue by lymslive** [Shougo/unite.vim#1195]
# Problems summary
I've use cscope in one CPP project, and manually create a file_list named `cscope.files`.
When I want to use the unite source of `file_list`, occur a problem with relative file path.
The `cscope.files` is in root of project, and the file list is relative to this root path.
But I feel convenient to `set autochdir`, so in most of time my vim is not in the root directory, and then `Unite file_list` has problem to find the right file listed in `cscope.files`, fails to default `<enter>` action.

## Expected
`Unite file_list` support relative path to the location of the list file itself, just the cscope supports.
Thanks.

## Environment Information
 * OS: CenterOS
 * Vim version: 7.4

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
set autochdir
nnoremap <C-p>p :<C-u>Unite file_list:!/cscope.files<CR>
```

**Comment by Shougo** [comment]
Fixed

**Comment by lymslive** [comment]
In `file_list.vim:58`, you mean use `if !filereadable(file_list) `? you forge the `!`.

**Comment by Shougo** [comment]
Fixed.
