### ISSUE TITLE
file_list:myfilelist is failing to open myfilelist

### ISSUE THREAD

**Issue by jkerian** [Shougo/unite.vim#1196]
# Problems summary
Unite doesn't seem to find my specified filelist when I use :Unite file_list:myfilelist . Prior to commit 44d66296f85ed7d8c28fd73db639249550e10e03 (the Fix for #195), this worked fine, and reverting that change locally fixes the issue.

## Expected
Unite to open with the file_list for options, instead a red error message flashes on the screen and then an empty Unite split opens. (:messages tells me the error is `[unite.vim] [file_list] filelist open failed.`

## Environment Information
 * OS:WinX
 * Vim version: gVim8, including patches 1-3 (64bit)

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
" Your minimal .vimrc
set nocp
set rtp+=$HOME/.vim/bundle/unite.vim
```

## The reproduce ways from Vim starting (Required!)

 1. gvim -u bustedunitevimrc code.cpp
 2. :Unite filelist:myfilelist

## Upload the log messages by `:redir` and `:message`
```[unite.vim] [file_list] filelist open failed.```

**Comment by Shougo** [comment]
Fixed.
