### ISSUE TITLE
Is it possible to fill in text from a defined list?

### ISSUE THREAD

**Issue by dahanbn** [Shougo/unite.vim#1197]
Currently I'm looking for an easy way to have in snippets fields that contain a list of values where I can choose one upon completion. As snippet engine I use snipmate because I need a Vim only solution.

Therefore I'm looking for a nice way to choose an item from a text list. I guess it should be possible with Unite. But I don't have any clue. 

Let's assume the list contains multiple strings and if the function is invoked from within Vim or the snippet upon expansion it would show me all text strings (like a file list) and I could use Unites capabilities to narrow the list down and choose a string. The chosen value should be inserted in the current buffer or within the snippet.

I hope my question is understandable.

**Comment by Shougo** [comment]
You should read neosnippet source implementation.

https://github.com/Shougo/neosnippet.vim/blob/master/autoload/unite/sources/neosnippet.vim

**Comment by lambdalisue** [comment]
In case, have a look https://github.com/lambdalisue/unite-linephrase
