### ISSUE TITLE
`ripgrep` results replace search result highlighting with `--`

### ISSUE THREAD

**Issue by sodiumjoe** [Shougo/unite.vim#1198]
# Problems summary
I'm trying to use [rg](https://github.com/BurntSushi/ripgrep) as a source and i'm getting slightly weird output in the selection list.

## Expected
The matching part of the result should be highlighted instead of `--`.

## Environment Information
 * OS: mac osx el capitan 10.11.6
 * Vim version:
```bash
➤  nvim -v
NVIM 0.1.5
Build type: RelWithDebInfo
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/tmp/neovim-20160924-26015-18f5ixr/neovim-0.1.5/build/config -I/tmp/neovim-20160924-26015-18f5ixr/neovim-0.1.5/src -I/tmp/neovim-20160924-26015-18f5ixr/neovim-0.1.5/deps-build/usr/include -I/tmp/neovim-20160924-26015-18f5ixr/neovim-0.1.5/deps-build/usr/include -I/tmp/neovim-20160924-26015-18f5ixr/neovim-0.1.5/deps-build/usr/include -I/tmp/neovim-20160924-26015-18f5ixr/neovim-0.1.5/deps-build/usr/include -I/tmp/neovim-20160924-26015-18f5ixr/neovim-0.1.5/deps-build/usr/include -I/tmp/neovim-20160924-26015-18f5ixr/neovim-0.1.5/deps-build/usr/include -I/usr/local/opt/gettext/include -I/usr/include -I/usr/include -I/tmp/neovim-20160924-26015-18f5ixr/neovim-0.1.5/build/src/nvim/auto -I/tmp/neovim-20160924-26015-18f5ixr/neovim-0.1.5/build/include
Compiled by jmoon@jmoon

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.1.5/share/nvim"

```

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
" Your minimal .vimrc
set runtimepath+=~/path/to/unite.nvim/
call plug#begin('~/.vim/plugged')
Plug 'Shougo/vimproc.vim', { 'do': 'make' }
Plug 'Shougo/unite.vim'
call plug#end()
let g:unite_source_grep_command = 'rg'
let g:unite_source_grep_default_opts = '--hidden --no-heading --vimgrep -S'
let g:unite_source_grep_recursive_opts = ''
```

## The reproduce ways from Vim starting (Required!)

 1. `:Unite grep:.`
 2. `foo<enter>`

## Screen shot (if possible)

```<Panel.--ter>
</Panel.--ter>
```

<img width="1276" alt="screenshot 2016-09-26 21 06 04" src="https://cloud.githubusercontent.com/assets/845857/18859877/0fdc5494-842d-11e6-80cd-abab1bd51bae.png">

Note: when I just do `:!rg --hidden --no-heading --vimgrep -S foo`, the output looks normal:

```
examples/ui/src/containers/Grid.jsx:89:15:       <Panel.Footer>
examples/ui/src/containers/Grid.jsx:99:16:       </Panel.Footer>
```

<img width="1276" alt="screenshot 2016-09-26 21 07 13" src="https://cloud.githubusercontent.com/assets/845857/18859896/42861740-842d-11e6-892c-4f3200aaadc4.png">

## Upload the log messages by `:redir` and `:message`
nothing in `:message`

**Comment by thelamb** [comment]
I can't fully reproduce this now (not infront of a PC), but I think it might have to do with a typo in your .vimrc:

` let g:unite_source_grep_recursive_opts = ''`

This should be 
` let g:unite_source_grep_recursive_opt = ''` (singular `opt`)

The default value for the recursive option is `-r`, which does replace in `rg`

**Comment by Shougo** [comment]
`:Unite grep:. -wrap`
