### ISSUE TITLE
Typing is extremely laggy

### ISSUE THREAD

**Issue by synic** [Shougo/unite.vim#1199]
# Problems summary

I am using MacVim, when I type using `file_rec/async`, it is very laggy to update the results, to the point of being unusable.

## Expected

It should be a bit snappier ;-)

## Environment Information
 * OS:  OS X 10.11.6
 * Vim version: `VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Sep 14 2016 03:42:03)`

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
" Your minimal .vimrc
set runtimepath+=~/.vim/bundle/unite.vim
set runtimepath+=~/.vim/bundle/vimproc.vim
if executable('ag')
  let g:unite_source_grep_command = 'ag --ignore-dir node_modules'
  let g:unite_source_grep_default_opts = '--column --nogroup --nogroup'
  let g:unite_source_grep_recursive_opt = ''
endif
let g:unite_source_rec_max_cache_files = 0
let g:unite_source_history_yank_enable = 1
" Start in insert mode
let g:unite_enable_start_insert = 1
let g:unite_split_rule = 'bot'
call unite#filters#matcher_default#use(['matcher_fuzzy'])
call unite#filters#sorter_default#use(['sorter_rank'])
let g:unite_source_rec_async_command = ['ag', '-l', '-g', '', '--nocolor', '--python']
```

## The reproduce ways from Vim starting (Required!)

 1.  Open VIM
 2.  Type something like this: `:Unite  -buffer-name=files -start-insert buffer file_rec/async:/Users/synic/Projects/`   
 3.  Start typing filenames.  I feel like the actual searching part is fast, it's the filtering down part that's very slow

## Screen shot (if possible)

It wouldn't be relevant.  There's no way to screenshot it.

## Upload the log messages by `:redir` and `:message`

`:redir` said invalid argument, `:message` only had my two `:redir` entries ;-)

**Comment by synic** [comment]
So, I tried the following:  `:Unite -buffer-name=files -start-insert buffer file_rec:/Users/synic/Projects/`.  Now it is MUCH faster.

**Comment by synic** [comment]
Nevermind.  I figured out how to use `ignore_pattern`, seems to have sorted me out.

**Comment by Shougo** [comment]
Additional info:  You can enable if_lua.  It is faster.

My recommendation:  Use denite.nvim.

https://github.com/Shougo/denite.nvim
