### ISSUE TITLE
How to make Unite search smarter?

### ISSUE THREAD

**Issue by musaffa** [Shougo/unite.vim#1200]
This is the search result I get in unite file search:

![screenshot from 2016-10-02 17-57-17](https://cloud.githubusercontent.com/assets/294616/19020416/00e4c2fe-88ca-11e6-98bc-c98d72c3f0dc.png)

But I want `part-form/template.em` and `part-form/component.js` to be on the top.

Currently, this is my source setup for Unite:

```Vim
" Unite sources
call unite#custom#source('file_rec/neovim,buffer', 'matchers', ['converter_relative_word', 'matcher_fuzzy'])
call unite#custom#source('file_rec/neovim,buffer', 'sorters', 'sorter_rank')

" Unite keymaps
nnoremap <leader>f :<C-u>Unite -no-split -buffer-name=files   -start-insert -ignorecase file_rec/neovim:!<cr>
nnoremap <leader>b :<C-u>Unite -no-split -buffer-name=buffer  -start-insert -ignorecase buffer<cr>
.....
```

As you can see `fuzzy` is one of the matchers. I need the fuzzy search but, at the same time, it should also prioritize those files which match more closely to the query.

**Comment by Shougo** [comment]
You can create the original sorter and set it.

**Comment by musaffa** [comment]
@Shougo This is the result of the same search with `ctrlp.vim`:

![screenshot from 2016-10-02 20-32-48](https://cloud.githubusercontent.com/assets/294616/19021269/987f3ff8-88df-11e6-9d57-a6addb4108fa.png)

It looks like ctrlp's fuzzy matcher/sorter is quite smart by default.


> You can create the original sorter and set it

Shouldn't Unite support this? It affects all of us. As a ctrlp replacement, the sorting in unite should be at least as smart as ctrlp.

**Comment by Shougo** [comment]
```
call unite#custom#source('file_rec/neovim,buffer', 'sorters', 'sorter_selecta')
```

**Comment by musaffa** [comment]
`sorter_selecta` is noticably slower than ctrlp. But it works nonetheless. Thanks.

**Comment by Shougo** [comment]
If you need faster unite.vim, you should test denite.nvim.

https://github.com/Shougo/denite.nvim

**Comment by musaffa** [comment]
:+1: I will test this out.
