### ISSUE TITLE
can not open the remote samba file by use ag

### ISSUE THREAD

**Issue by fcying** [Shougo/unite.vim#1201]
I use `ag` for find file, it work well in local folder.

In remote samba folder, it can list the files, but open it error.

![1](https://cloud.githubusercontent.com/assets/106934/19302937/21ed81a8-9099-11e6-9726-ade7e7d68055.jpg)
![2](https://cloud.githubusercontent.com/assets/106934/19302938/21f0b436-9099-11e6-81ac-746e8543051a.jpg)

the following is my vimrc
```vim
        let g:unite_source_rec_async_command = [
        \ 'ag', '--follow', '--nocolor', '--nogroup', '--hidden',
        \ '--ignore','lib*', '--ignore','obj', '--ignore','out',
        \ '--ignore','tags', '--ignore','GTAGS', '--ignore','GRTAGS', '--ignore','GPATH',
        \ '-g', '']
        nnoremap <silent> [unite]f :<C-u>Unite -silent -start-insert file_rec/async<CR>
```

**Comment by Shougo** [comment]
Samba is not supported.  Because I have not Samba environment.
The pull request is wellcome though.
You can test denite.nvim instead.
https://github.com/Shougo/denite.nvim

**Comment by fcying** [comment]
I tried use `mattn/files` instead of `ag`, it work well in remote samba.
