### ISSUE TITLE
Feature Request: Input again the last search ( like the up arrow key on bash )

### ISSUE THREAD

**Issue by ccolorado** [Shougo/unite.vim#1202]
# Problems summary
Having to retype the filename/filter after accidentally picking the wrong result
or wanting to repeat an edited version of the previous search

## Expected
A way to recover the last filtering instructions. like bash (up arrow) brings the last executed command into the input filed 

## Environment Information
 * OS:all
 * Vim version: 7

## Provide a minimal .vimrc with less than 50 lines (Required!)
N/A

**Comment by Shougo** [comment]
:UniteResume
