### ISSUE TITLE
Unite preview window replaces current open window

### ISSUE THREAD

**Issue by nilsboy** [Shougo/unite.vim#1203]
# Problems summary
When I use the -auto-preview option with unite - already open windows can get replaced by unite. This results in unite wanting to close the last open window when closing unite. This triggers the vim error "E444: Cannot close last window".

I trigger this problem several times a day and am so far not able to reproduce my direct use case.
But I was able to come up with a scenario that has the same effect - see below.

Thank you for looking into this.

## Expected
Unite closes.

## Environment Information
 * OS: Ubuntu 14.04
 * Vim version: 7.4 (2013 Aug 10, compiled Jan  2 2014 19:39:59)

## Provide a minimal .vimrc (Required!)

This is a runnable vimrc - see Test() for the "test case".
Please run  this then press Q.

```vim
let g:plugin_dir = expand('~/.vim/dein')
let g:dein_dir = g:plugin_dir . '/repos/github.com/Shougo/dein.vim'
execute 'set runtimepath+=' . g:dein_dir

if !isdirectory(g:dein_dir)
  call mkdir(g:dein_dir, 'p')
  silent execute printf('!git clone --depth 1 %s %s', 'http://github.com/Shougo/dein.vim', g:dein_dir)
endif

call dein#begin(g:plugin_dir)

" Let dein manage dein
call dein#add('Shougo/dein.vim')

call dein#add('Shougo/unite.vim')

call dein#end()

if dein#check_install() 
  call dein#install()
endif

autocmd VimEnter * call dein#call_hook('post_source')

autocmd VimEnter * call Test()

function! Test() abort
  lcd /etc
  Unite -auto-preview file_rec
  normal Q
  buffer unite
  " Now press Q
endfunction

filetype plugin indent on

finish
```

## The reproduce ways from Vim starting (Required!)

 1. Run the supplied vimrc
 2. press Q

## Screen shot (if possible)

![Screenshot](https://nilsboy.github.io/files/vim-unite-preview-error.png)

## Upload the log messages by `:redir` and `:message`

None

**Comment by Shougo** [comment]
Fixed.

**Comment by nilsboy** [comment]
Thank you for the quick fix! :)
Could you also make sure that if a buffer that was open before Unite was called will be shown again instead of a new buffer?
I extended the the test case above to include the line "edit hosts". So the "hosts" file should be shown again once Unite gets closed.
Thank you.

**Comment by Shougo** [comment]
> Could you also make sure that if a buffer that was open before Unite was called will be shown again instead of a new buffer?

I don't want to add the feature.
Because, unite.vim development is already finished.
