### ISSUE TITLE
Highlight candidates

### ISSUE THREAD

**Issue by Btheo** [Shougo/unite.vim#1204]
# Problems summary
I would like to change the highlight of the candidates in the Unite window.
The highlight groups uniteStatusNormal uniteStatusSourceCandidate etc. do not change anything.

## Expected

No highlight of candidates.

## Environment Information
 * OS: archlinux
 * Vim version: 
vim 8.0 compiled with feature normal and with python

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
" Your minimal .vimrc
set runtimepath+=~/path/to/unite.nvim/
```

## The reproduce ways from Vim starting (Required!)

1. call unite with any source

## Screen shot (if possible)

![2016-11-06-154951_1920x1080_scrot](https://cloud.githubusercontent.com/assets/6988119/20039310/9540f924-a439-11e6-915c-7b49c94ce367.png)

**Comment by Shougo** [comment]
```vim
autocmd FileType unite call s:on_unite()

function! s:on_unite()
  highlight highlight_name Normal
endfunction
```

**Comment by TheoBrasseur** [comment]
Thank you for your answer.

Unfortunately I still haven't managed to sort the issue.
Is highlight_name just a place holder I should replace with one of uniteStatusNormal or uniteStatusSourceCandidate... or should I use it literally.
What highlight group is used in the screenshot I provide that makes everything go green'ish'?

**Comment by Shougo** [comment]
You should check the highlight names by `:syntax list` in unite buffer.
