### ISSUE TITLE
Cursor jumps when deleting a buffer from the buffer list

### ISSUE THREAD

**Issue by languitar** [Shougo/unite.vim#1206]
# Problems summary

When using the buffers sources with `let g:unite_split_rule = 'botright'`, deleting a buffer via a `d` press, the cursor jumps back to the initial position (bottom) instead of staying at the closest position. This makes deleting multiple buffers quite tedious because you have to move across the lines multiple times.

## Expected

After deleting an entry, the cursor stays at the entry above or below.

## Environment Information
 * OS: Linux
 * Vim version: Master neovim

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
set runtimepath+=/home/languitar/.local/share/nvim/bundle/unite.vim

let g:unite_split_rule = 'botright'
```

## The reproduce ways from Vim starting (Required!)

 1. open a few buffers
 2. `:Unite buffers`
 3. move in the middle of the buffer list
 4. press `d`

**Comment by Shougo** [comment]
This is feature.

> This makes deleting multiple buffers quite tedious because you have to move across the lines multiple times.

You should select multiple candidates and press `d`.

unite.vim development is done.
So, I don't want to change it.

**Comment by languitar** [comment]
But there is an obvious difference in behavior. If I don't use that splitting rule, then the cursor doesn't jump.

**Comment by Shougo** [comment]
Because, it has different implementation.
The reversed implementation is very complicated.
I don't want to change.
