### ISSUE TITLE
UniteNext/UnitePrevious no longer work for jump_list kind

### ISSUE THREAD

**Issue by wilywampa** [Shougo/unite.vim#1207]
# Problems summary
`UniteNext` and `UnitePrevious` should go to the next/previous item in the jumplist. Instead they echo the name of the next/previous item but don't actually jump to it. This problem started in https://github.com/Shougo/unite.vim/commit/85a91c5

## Expected
If `persist_open` is the default action for `grep` source, `UniteNext` and `UnitePrevious` should go to the next/previous item in the jumplist.

## Environment Information
 * OS: OS X 10.10.5
 * Vim version: 8.0094

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
set nocompatible hidden backspace=indent,eol,start
set history=5000 undofile undolevels=1000 undoreload=10000
set expandtab shiftwidth=2 softtabstop=2 tabstop=2
set ai bs=indent,eol,start cb=unnamed,unnamedplus et gd hid 
set hls ic is nosmd nosol nowrap nf=hex nu rnu sc si sm sts=4 
set sw=4 wmnu wim=longest:full,full
filetype plugin indent on

if !exists("syntax_on") | syntax enable | endif

set runtimepath+=$HOME/Downloads/unite.vim
set runtimepath+=$HOME/Downloads/vimproc.vim

function! s:UniteSetup()
    call unite#custom#default_action(join(map(filter(keys(unite#get_all_sources()),
                \ 'v:val =~ "grep"'), '"source/" . v:val . "/jump_list"'), ','), 'persist_open')
endfunction
augroup VimrcAutocmds
    autocmd!
    autocmd VimEnter * call s:UniteSetup()
augroup END
```

## The reproduce ways from Vim starting (Required!)

 1. Start Vim
 2. `:Unite grep`
 3. `:UniteNext` (message indicates that the next result was selected, but it either opens a blank new window or gives a preview of whatever result was selected before `:UniteNext`)

**Comment by Shougo** [comment]
Fixed

**Comment by wilywampa** [comment]
Thank you very much! 👍
