### ISSUE TITLE
Files aren't showing up with file_rec/async; doesn't appear to be a limit issue?

### ISSUE THREAD

**Issue by rlpowell** [Shougo/unite.vim#1212]
# Problems summary

file_rec/async is showing *way* less files than it should; 749 out of 10000+

In my tests in particular it's missing ideas.md

As far as I know it should be using find, but here's examples with every
search command I have:

```
rlpowell@stodi> ack -l . | grep hobbies | grep ideas.md
Public/hblog_posts/hobbies/gaming/ideas.md
rlpowell@stodi> pt -l . | grep hobbies | grep ideas.md
Public/hblog_posts/hobbies/gaming/ideas.md
rlpowell@stodi> ag -l . | grep hobbies | grep ideas.md
Public/hblog_posts/hobbies/gaming/ideas.md
rlpowell@stodi> find -L | grep hobbies | grep ideas.md
./Public/hblog_posts/hobbies/gaming/ideas.md
```

And here's more detail with find:

```
rlpowell@stodi> find -L | wc -l
10494
rlpowell@stodi> find -L | grep idea
./src/hblog/scratch/posts_old/personal/writing/story_ideas.md
./src/hblog/_site/tags/hobbies"free_ideas+gaming.html
./src/hblog/_site/tags/free_ideas.html
./src/hblog/_site/tags/free_ideas+gaming.html
./src/hblog/_site/tags/hobbies"free_ideas.html
./src/hblog/_site/posts/hobbies/gaming/ideas.html
./src/hblog/tests/hblog/003_bigger_test/posts/personal/writing/story_ideas.md
./src/hblog/tests/hblog/003_bigger_test/wanted/posts/personal/writing/story_ideas.html
./src/hblog/tests/hblog/003_bigger_test/_site/posts/personal/writing/story_ideas.html
./Public/Writing/story_ideas.txt
./Public/hblog_posts/hobbies/gaming/ideas.md
./Public/city_builder/random_ideas.txt
```

What it actually sees when searching on "idea" is:

```
Public/Writing/story_ideas.txt
Public/city_builder/random_ideas.txt
```

## Expected

It should see the full list of files that "find -L | grep idea" returns.

## Environment Information
 * OS: Fedora 25
 * Vim version: 8.0.118

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
call plug#begin('~/.vim/plugged')

" Unite!  So many things!
Plug 'Shougo/unite.vim'
Plug 'Shougo/neomru.vim'
Plug 'Shougo/vimproc.vim', {'do' : 'make'}
Plug 'Shougo/neoyank.vim'

call plug#end()

" Unlimit the number of files that can be found
let g:unite_source_rec_max_cache_files = 0
let g:unite_source_file_rec_max_cache_files = 0
let g:unite_source_rec_max_cache_files = 0
call unite#custom#source('file_rec,file_rec/async', 'max_candidates', 0)

" The big one: buffers, files most recently used, all files (using find)
nnoremap <Space>uf :Unite -sync file_rec/async<CR>
nmap <Space>f <Space>uf
```

## The reproduce ways from Vim starting (Required!)

 1. <space>uf
 2. iidea

## Screen shot (if possible)

```
idea
Public/Writing/story_ideas.txt
Public/city_builder/random_ideas.txt
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
 file_rec/async(2/749)                                                                                                                   directory: /home/rlpowell/Dropbox 1/3
```

See also https://www.dropbox.com/s/8pcy2571y83pebj/Screenshot%202016-12-31%2010.39.54.png?dl=0

## Upload the log messages by `:redir` and `:message`

:messages has nothing

:redir gives:

```


[file_rec/async] directory: /home/rlpowell/Dropbox
-- INSERT ---- INSERT --
41 fewer lines
41 fewer lines
41 fewer lines
Error detected while processing function unite#handlers#_on_cursor_moved_i[6]..<SNR>64_check_redraw[5]..unite#redraw[1]..unite#view#_redraw[58]..unite#view#_redraw_candidates[22]..unite#view#_set_candidates_lines:
line   15:
E16: Invalid range: 2,$delete _
41 fewer lines
41 fewer lines
40 fewer lines
16 fewer lines-- INSERT --


Error detected while processing function unite#handlers#_on_buf_unload[2]..unite#view#_clear_match_highlight:
line    1:
E803: ID not found: 10
Error detected while processing function unite#action#do[57]..unite#all_quit_session[1]..unite#view#_quit[47]..unite#handlers#_on_buf_unload[2]..unite#view#_clear_match_highlight:
line    1:
E803: ID not found: 10
"Public/Writing/story_ideas.txt"
"Public/Writing/story_ideas.txt" 10L, 3687C

Error detected while processing function unite#handlers#_on_buf_unload[2]..unite#view#_clear_match_highlight:
line    1:
E803: ID not found: 10%                                                                                                                                                       rlpowell@stodi>

```

**Comment by Shougo** [comment]
I cannot reproduce the problem.

> file_rec/async is showing way less files than it should; 749 out of 10000+

But you should not use unite.vim in the huge directory.
You should use denite.nvim instead.

**Comment by Shougo** [comment]
I think you must re-generate the cache by `<Plug>(unite_redraw)` mapping.

**Comment by rlpowell** [comment]
I already tried unite_redraw.  Specifically, I added this:

    nmap <Space>c <Plug>(unite_redraw)

and hit [space]c.  It does nothing that I can see, and makes no difference.

Sorry, I forgot to mention that I tried that already.

Can you tell me where the cache lives so I can delete it manually?

Moving to very recent vim or neovim is extremeley hard for me because my work systems are OEL6 (i.e. RHEL6).

**Comment by rlpowell** [comment]
Ah.

     rm -rf ~/.cache/

clears the problem right up.  CTRL-L and my own mapping both didn't do anything, so it seems that the cache invalidation code in unite_redraw isn't actually invalidating the cache.

**Comment by Shougo** [comment]
```
nmap <buffer> <Space>c <Plug>(unite_redraw)
```

> Moving to very recent vim or neovim is extremeley hard for me because my work systems are OEL6 (i.e. RHEL6).

> Environment Information
>    OS: Fedora 25
>    Vim version: 8.0.118

Hm...

**Comment by rlpowell** [comment]
Yes, that's my home computer; that's not the only place I use vim.

**Comment by rlpowell** [comment]
The documentation says that ctrl-l should activate unite_redraw; it made no difference.

**Comment by rlpowell** [comment]
Using the nmap you just gave didn't help either; touched a new file, and it doesn't show up.

**Comment by Shougo** [comment]
> Using the nmap you just gave didn't help either; touched a new file, and it doesn't show up.

You must execute it in `autocmd FileType unite`.

> The documentation says that ctrl-l should activate unite_redraw; it made no difference.

I cannot reproduce it...
I think you have pressed `<C-l>` in insert mode.
It must be normal mode.

**Comment by Shougo** [comment]
Another solution:  `:Unite -force-redraw file_rec/async`

**Comment by rlpowell** [comment]
Here's a minimal repro using the vimrc I gave above:

```
rm -rf ~/.cache
mkdir /tmp/test
cd /tmp/test
for num in $(seq 1 1000)
do
  touch foo$num
done
vim
touch bar
vim
```

In the first vim session, run file_rec/async, note that foo999 appears; in the second, run it again, note that bar *does not* appear.

Here's a screencast of me running that script:  https://www.youtube.com/watch?v=fc5jHdcMWw8

I'm happy to just slap -force-redraw on everything, but there's definitely a caching problem here.

**Comment by Shougo** [comment]
> In the first vim session, run file_rec/async, note that foo999 appears; in the second, run it again, note that bar does not appear.

This is feature.  file_rec/async cache does not detect file changes outside Vim.

**Comment by rlpowell** [comment]
Oooooh, I see, the <C-l> has to be done in the Unite window.  Yes, that does work; I was doing it in other windows, assuming you'd hooked into the main redraw.
