### ISSUE TITLE
source file_rec/git does not handle git worktrees

### ISSUE THREAD

**Issue by languitar** [Shougo/unite.vim#1213]
# Problems summary

When using the source `file_rec/git` inside a git worktree, files from the git repository are missing and potentially other files are shown.

## Expected

The source lists files from the worktree.

## Environment Information
 * OS: archlinux 64
 * Vim version:

```
NVIM 0.1.7
Build type: Release
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -Wconversion -O2 -DNDEBUG -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.1.7/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser
```

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
" Your minimal .vimrc
set runtimepath+=~/path/to/unite.nvim/
```

## The reproduce ways from Vim starting (Required!)

 1. git clone someUrl
 2. cd someUrl
 3. git worktree add -b tree/master ../project-master origin/master
 4. cd ../project-master
 5. vim
 6. `:Unite file_rec/git`

In my case this lists files from other git repositories that reside parallel to the worktree path.

**Comment by Shougo** [comment]
unite.vim development is done.
I don't think it is bug.

So closing.
