### ISSUE TITLE
`^` doesn't work in syntax `source.hooks.on_syntax`

### ISSUE THREAD

**Issue by sodiumjoe** [Shougo/unite.vim#1216]
# Problems summary

In a plugin, I'm trying to match the first character in the candidate like this:

```vim
function! s:source.hooks.on_syntax(args, context)
  syntax match UniteGitStatusIndexSymbol /^./
        \ contained containedin=uniteSource__uniteGitStatus
```

But that doesn't match anything. I've also tried `/\^./` and `/^\s\+.` and other variations, but the `^` operator doesn't appear to work.

## Expected

I should be able to match using `^`

## Environment Information
 * OS: macOS Sierra 10.12.2 (16C67)
 * Vim version:
```vim
NVIM 0.1.7
Build type: RelWithDebInfo
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-param
eter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/tmp/neovim-20161210-60330-1ace895/neo
vim-0.1.7/build/config -I/tmp/neovim-20161210-60330-1ace895/neovim-0.1.7/src -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include
 -I/usr/local/include -I/usr/local/opt/gettext/include -I/usr/include -I/usr/include -I/tmp/neovim-20161210-60330-1ace895/neovim-0.1.7/build/src/nvim/auto -I/tmp/neovim-20161210-603
30-1ace895/neovim-0.1.7/build/include
Compiled by jmoon@jmoon

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.1.7/share/nvim"
```

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
call plug#begin('~/.vim/plugged')
Plug 'Shougo/unite.vim'
Plug '~/play/unite-git'
call plug#end()
```

## The reproduce ways from Vim starting (Required!)

 1. `:Unite git_status`

**Comment by chemzqm** [comment]
Looks like you haven't define `uniteSource__uniteGitStatus ` in your source definition.
Something like:
```
s:source.syntax = 'uniteSource__uniteGitStatus'
```
is required.

**Comment by sodiumjoe** [comment]
i do have that [here](https://github.com/sodiumjoe/unite-git/blob/master/autoload/unite/sources/git_status.vim#L13)

The thing is, other syntax matches do work. The reason I added `[]` was so I could match against the contents properly as you can see [here](https://github.com/sodiumjoe/unite-git/blob/master/autoload/unite/sources/git_status.vim#L62)

But I only had to do that because I couldn't match against the first character without that. Matches like `.` work, but I couldn't get anything starting with `^` to work.

**Comment by chemzqm** [comment]
The reason is the first charactor of candidate would always be an empty space, you can get the line by `echo getline('.')`

**Comment by sodiumjoe** [comment]
when i `echo getline('.')` I get

```
   [ ~] autoload/unite/sources/git_status.vim
```

If I just paste that into my buffer and search with `/^\s\s\s.` or `/^\s\+.`, it matches correctly, but neither of those work in the syntax match statement.

**Comment by chemzqm** [comment]
Should be a priority problem, I recommend use something like this 
```
  syntax match uniteGitStatusHeader /^.*$/
        \ containedin=uniteSource__uniteGitStatus

  syntax match uniteGitStatusSymbol /^\s\zs\S\+/
        \ contained containedin=uniteGitStatusHeader
```

**Comment by sodiumjoe** [comment]
ah ok, I didn't realize how `contained`/`containedin` worked, thanks for your help!
