### ISSUE TITLE
It's unclear how to use matcher, sorter, converter. 

### ISSUE THREAD

**Issue by hatelove85911** [Shougo/unite.vim#1218]
# Problems summary

There's no documentation to explain:
1. how to use matcher, sorter, converter. 
2. What does it mean to set several default matchers or sorters or converters ? 
3. What are the effects?

## Expected

more clear documentation to explain what are these filters, what are the effects when they are set.
some examples will be helpful.

**Comment by Shougo** [comment]
> how to use matcher, sorter, converter.

Please read the documentation.
`call unite#custom#source()` and the examples.

> What does it mean to set several default matchers or sorters or converters ?

`:help unite-filter-sorter_default`, `:help unite-filter-matcher_default`, `unite-filter-converter_default`
But they are defaults.  Some sources overwrites them.

> What are the effects?

Have you read the documentation and try the customization?

> more clear documentation to explain what are these filters, what are the effects when they are set.
> some examples will be helpful.

unite.vim development is over.
I don't want to add it.  But the pull request is wellcome.
