### ISSUE TITLE
How to do a new search for grep or find source when resume is enabled?

### ISSUE THREAD

**Issue by hatelove85911** [Shougo/unite.vim#1219]
# Problems summary

I have enabled resume in default context.  when I do find or grep once, a unite buffer is created, and I can resume the same buffer again with the same key stroke I defined.  But I don't know how to do a new find or grep.

It's important that I can do re-search for find and grep because these two sources have an extra step is to input search pattern. 

I don't want to define two key mappings: one for do new search and the other for resume. It's kinda clumsy.

## Expected

provide a key mapping in unite buffer to re run the extract same command which created current buffer except resume.

## Provide a minimal .vimrc with less than 50 lines (Required!)
call unite#custom#profile('default', 'context', {
      \   'no_split': 1,
      \   'start_insert': 1,
      \   'quit' : 1,
      \   'resume' : 1
      \ })

**Comment by Shougo** [comment]
You should use `<C-r>` mapping or change the buffer-name.
