### ISSUE TITLE
unite_source_rec_async_command  with the_platinum_searcher not working in win10

### ISSUE THREAD

**Issue by fcying** [Shougo/unite.vim#1220]
# Problems summary
I trying use the_platinum_searcher as unite_source_rec_async_command by this way:
```
let g:unite_source_rec_async_command = ['pt', '--follow', '--nocolor', '--nogroup', '--hidden','-g', '']
nnoremap ff :<C-u>Unite file_rec/async<CR>
```
this can work in ubuntu, but can't work in win10. 
use ag can work both ubuntu and win10.

## Expected
It should works without problems.

## Environment Information
 * OS: windows10
 * Vim version: VIM 8.0 MS-Windows 64-bit GUI version. Included patches: 1-587
 * pt version: 2.1.5

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
set nocompatible

let g:config_dir=$VIM
let g:plugin_dir = g:config_dir . '/plugged'
let g:plugin_manager_dir = g:plugin_dir . '/dein.vim'
exec 'set runtimepath+=' . g:plugin_manager_dir

if dein#load_state(expand(g:plugin_dir))
  call dein#begin(expand(g:plugin_dir))
  call dein#add(expand(g:plugin_manager_dir))
  call dein#add('Shougo/vimproc.vim', {'build' : 'Tools\update-dll-mingw.bat'})
  call dein#add('Shougo/unite.vim')
  call dein#end()
  call dein#save_state()
endif

filetype plugin indent on
syntax enable

let g:unite_source_rec_async_command = ['pt', '--follow', '--nocolor', '--nogroup', '--hidden','-g', '']
nnoremap ff :<C-u>Unite file_rec/async<CR>
```

## The reproduce ways from Vim starting (Required!)

 1. clear unite.vim cache
 2. start vim
 3. hit ff
 4. get nothing

**Comment by fcying** [comment]
my fault, in windows, use `-g:` can work.

**Comment by Shougo** [comment]
> my fault, in windows, use -g: can work.

It can work in Linux?
I think it should be documented.

**Comment by fcying** [comment]
in unite:
only `:g`, `:g=` can work in ubuntu 16.04.
only `:g:` can work in windows 10.

in denite. 
only `:g`, `:g=` can work in ubuntu 16.04.
only `:g`, `:g:`  can work in windows 10.

**Comment by Shougo** [comment]
`-g:` does not work in Ubuntu?  Why?
I don't know pt behavior...

**Comment by fcying** [comment]
I saw the pt help, in ubuntu is `-g=    Print filenames matching PATTERN`, 
in windows is `/g:    Print filenames matching PATTERN`
but `-g` can be used both in `cmd` && `shell`

**Comment by Shougo** [comment]
The complex behavior.
Huh.
