### ISSUE TITLE
Filter files searched by Unite grep

### ISSUE THREAD

**Issue by gotgenes** [Shougo/unite.vim#1223]
I have a simple question but I can not find the answer. How can I filter files searched by `Unite grep`?

For example, if I want to recursively search all JavaScript files under the current directory for the pattern `somePattern`, what would I enter as the value for the prompt of `Target: `? I have tried `*.js`, `**/*.js`, but these result in an error like the following:
```
[unite.vim] [grep] ERR: Error stat()ing: **.js
```

Is it possible to filter files searched?

**Comment by Shougo** [comment]
It cannot.  Because, the globbing is `shell` feature.
Unite.vim does not use `shell`.
It executes the grep command directly.

**Comment by Shougo** [comment]
You should use `--include` option in grep command.

**Comment by gotgenes** [comment]
Good to know. Thank you for your reply.

Thanks very much for Unite!
