### ISSUE TITLE
some file can not be listed.

### ISSUE THREAD

**Issue by wsdjeg** [Shougo/unite.vim#1225]
# Problems summary
can not list `autoload/SpaceVim/mapping/z.vim`

## Expected
all the useful files should be listed

## Environment Information
 * OS: arch
 * Vim version: neovim

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
set rtp+=~/.cache/vimfiles/repos/github.com/Shougo/unite.vim
set rtp+=~/.cache/vimfiles/repos/github.com/Shougo/vimproc.vim


scriptencoding utf-8
call unite#custom#source('codesearch', 'max_candidates', 30)
call unite#filters#matcher_default#use(['matcher_fuzzy'])
call unite#filters#sorter_default#use(['sorter_rank'])
call unite#custom#profile('default', 'context', {
      \   'safe': 0,
      \   'start_insert': 1,
      \   'ignorecase' : 1,
      \   'short_source_names': 1,
      \   'update_time': 200,
      \   'direction': 'rightbelow',
      \   'winwidth': 40,
      \   'winheight': 15,
      \   'max_candidates': 100,
      \   'no_auto_resize': 1,
      \   'vertical_preview': 1,
      \   'cursor_line_time': '0.10',
      \   'hide_icon': 0,
      \   'candidate-icon': ' ',
      \   'marked_icon': '✓',
      \   'prompt' : '➭ '
      \ })

    let g:unite_force_overwrite_statusline = 0
" vim:set et sw=2 cc=80:

```

## The reproduce ways from Vim starting (Required!)

I will test it in spacevim repo, no need install spacevim.

1. `git clone https://github.com/SpaceVim/SpaceVim.git`
2. `cd SpaceVim`
3. `vim -u ~/test/test.vim init.vim`
4.  run `:Unite file_rec/async -start-insert`
5.  type into z.vim

**Comment by Shougo** [comment]
https://github.com/SpaceVim/SpaceVim/tree/dev/autoload/SpaceVim/mapping

z.vim is not exist.

**Comment by wsdjeg** [comment]
oh, I think it is unite cache. in new branch z_prefix there are two z.vim

**Comment by wsdjeg** [comment]
you can see this PR 

https://github.com/SpaceVim/SpaceVim/pull/662

**Comment by Shougo** [comment]
> oh, I think it is unite cache. in new branch z_prefix there are two z.vim

Reproduced.  Please re-generate the cache.

**Comment by wsdjeg** [comment]
thanks.
