### ISSUE TITLE
unite-file で . で始まるディレクトリが候補に出ないことがある

### ISSUE THREAD

**Issue by thinca** [Shougo/unite.vim#1227]
# Problems summary

表題の通り、絞り込み文字列次第で `.` で始まるディレクトリが候補に出ません。

例: ホームディレクトリにある `~/.vim` を候補に出したい

`:Unite file` で開いたあと、`~/.vi` のように入力する
→ `~/.vim` が候補に表示されない

カレントディレクトリを `~` にして、`.vi` と入力すると候補に出ます。

https://github.com/Shougo/unite.vim/blob/ddbb0df1015b11a22a2ca4f6267e4a862911dd18/autoload/unite/sources/file.vim#L323-L326
この部分のフィルターで候補が消えてしまっています。
どう直すのが適切かがわからなかったため、直せませんでした。

## Expected

`~/.vim` が候補に表示される

## Environment Information
 * OS: Linux
 * Vim version: 8.0.563

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
set runtimepath+=~/path/to/unite.nvim/
```

## The reproduce ways from Vim starting (Required!)

 1. `:Unite file`
 2. `i~/.vi` (`i` は挿入モードに入るためのもの)

**Comment by Shougo** [comment]
バグですね。修正します。
