### ISSUE TITLE
Unite -start-insert buffer file_rec/async:! doesn't showw all files

### ISSUE THREAD

**Issue by osleg** [Shougo/unite.vim#1228]
# Problems summary
Starting Unite with `:Unite -start-insert buffer file_rec/async:!` doesn't show all files in all directories

## Expected
When I run above command expected to get list of all files in all subdirectories of current cwd,
Instead I'm getting only part of the files
If I open file it shows, but that's from `buffer` part of the Unite eg:
Searching for `apps/database/models/user.py`
![image](https://user-images.githubusercontent.com/207721/30112429-f6db3696-9343-11e7-89fd-0508e1294752.png)

After file is opened manually through `:e`:
![image](https://user-images.githubusercontent.com/207721/30112464-10ec070e-9344-11e7-9131-528b508cdc4a.png)

## Environment Information
 * OS: Linux
 * Vim version:
Similar happens under both vim 8.0.987 and nvim 0.2.0

## Provide a minimal .vimrc with less than 50 lines (Required!)
```vim
        call unite#filters#matcher_default#use(['matcher_fuzzy'])
        call unite#filters#sorter_default#use(['sorter_rank'])
        nmap <Leader>be :Unite -start-insert buffer file_rec/async:!<CR>
```

## The reproduce ways from Vim starting (Required!)
Start vim from work dir
hit `<leader>be`
get results

**Comment by Shougo** [comment]
Please read FAQ.

```
Q: file_rec and file_rec/async cannot find all files.
https://github.com/Shougo/unite.vim/issues/356
https://github.com/Shougo/unite.vim/issues/370
https://github.com/Shougo/unite.vim/issues/459

A: It is a feature.  cf: |g:unite_source_rec_max_cache_files|.
Also, the default max candidates are limited. You can customize it by
|unite#custom#source()|. >
	let g:unite_source_rec_max_cache_files = 0
	call unite#custom#source('file_rec,file_rec/async',
	\ 'max_candidates', 0)
```

**Comment by osleg** [comment]
@Shougo I tried all of that before reporting and it didn't work.
Tho right now I realized I didn't use `<Plug>(unite_redraw)` correctly. It works like a charm now, thanks for awesomest plugin in vim world! :)

**Comment by Shougo** [comment]
The result is cached.  So `<Plug>(unite_redraw)` is needed after the change.
