### ISSUE TITLE
grep source results parsing problem

### ISSUE THREAD

**Issue by minusf** [Shougo/unite.vim#1229]
# Problems summary

Incorrect parsing of `grep` source results.  Any file containing strings like this (the expanded subversion keyword `$Id$`):

```
$Id: ws.redis.cf 39228 2017-06-09 12:00:31Z hford $
```

Results in incorrect parsing of the results. Selecting this result will create a new buffer called `x:1:9:$Id: ws.redis.cf 39228 2017-06-09 12`.

## Expected

Open correct file at correct line.

## Environment Information
 * OS: macOS 10.12.6
 * Vim version:
```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Nov  7 2017 16:11:21)
macOS version
Included patches: 1-1272
Compiled by Homebrew
Huge version with MacVim GUI.  Features included (+) or not (-):
```

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
" Your minimal .vimrc
set runtimepath+=~/path/to/unite.nvim/

let g:unite_source_grep_command='rg'
let g:unite_source_grep_default_opts='--vimgrep --hidden'
let g:unite_source_grep_recursive_opt=''
```

## The reproduce ways from Vim starting (Required!)

 1. open new file. insert
```
x:1:9:$Id: ws.redis.cf 39228 2017-06-09 12
```
 2. save file
 3. `:Unite grep:.`
 4. Pattern: `redis`
 5. select result

**Comment by Shougo** [comment]
Reproduced.
