### ISSUE TITLE
Incomplete VimFiler Configuration for Windows Users

### ISSUE THREAD

**Issue by OthmanEmpire** [Shougo/unite.vim#1230]
## Summary

Using Gvim + SpaceVim on Windows 10, deleting files via VimFiler does not work out of the box.

The original post which contains more details can be found [here](https://github.com/SpaceVim/SpaceVim/issues/1123#issuecomment-352167099) . The origin of the bug comes from one of the unite.vim files and the solution to the bug is also included in that link.

**Comment by OthmanEmpire** [comment]
Thanks for the very quick fix.

I would like to add though, I just tried moving files using VimFiler and I came across the same issue; would you also please add code for the Windows portion of the `mv` and `cp` commands? The code to be changed is below the code that you just changed.

**Comment by Shougo** [comment]
@OthmanEmpire The PR is wellcome.
