### ISSUE TITLE
Help: How to execute an action on query text when no matching candidates?

### ISSUE THREAD

**Issue by idbrii** [Shougo/unite.vim#1235]
# Problems summary
I wrote a source to [show help for the Unity (game engine) API](https://github.com/idbrii/vim-unityengine-docs/blob/master/autoload/unite/sources/unitydoc.vim). It has a cached map of symbols to URLs.

If I can't find a match in the cache, I'd like to do a web search for the symbol.

## Expected

    :Unite unitydoc
    SceneView
    <CR>

SceneView does not match any candidates, so CR opens https://docs.unity3d.com/ScriptReference/30_search.html?q=SceneView

## Investigation

I'm pretty new at writing sources, but `default_action` is the action on an existing candidate and I don't see any help for empty candidates. I looked through the code and this snippet makes it look like unite disables itself when there are no candidates:

    function! unite#start#standard(sources, ...) abort "{{{
      ...
      if !current_unite.is_async &&
            \ (context.force_immediately
            \ || context.immediately || !context.empty) "{{{
        let candidates = unite#candidates#gather()
    
        if empty(candidates)
          " Ignore.
          call unite#view#_print_warning(
                \ 'unite buffer "'
                \ . current_unite.buffer_name.'" candidates are empty')
          call unite#variables#disable_current_unite()

(However, I don't see that error message.)

So probably Unite doesn't support this empty candidates action feature?

**Comment by Shougo** [comment]
unitydoc source should generate input matched candidate like this.

https://github.com/Shougo/unite.vim/blob/master/autoload/unite/sources/directory.vim#L49

directory_new source create input matched candidate automatically.

**Comment by idbrii** [comment]
Thanks! Taking directory, stripping it down, and figuring out change_candidates (and the format of dictionary it returns) got me there.

For reference, my solution was in this commit: idbrii/vim-unityengine-docs@8d83dbca63dc9eeb565baaa8c029a5880769422c.
