### ISSUE TITLE
Custom source not ignoring globs?

### ISSUE THREAD

**Issue by James-A1** [Shougo/unite.vim#1237]
# Problems summary
Unite file_rec/async still shows files from ignored globs (unite#custom#source ignore_globs) I followed the steps from the documentation (see vimrc) 
Note: `ignore_pattern` works

## Environment Information
 * OS: macOS High Sierra
 * Vim version: NVIM v0.2.3-1-gd6f9d1d

## My minimal vimrc

```vim
set wildignore+=*/tmp/*,*.so,*.swp,*.zip,node_modules/*,vendor/*

call plug#begin()
Plug 'Shougo/vimproc.vim'
Plug 'Shougo/unite.vim'
call plug#end()

call unite#sources#rec#define()
call unite#custom#source('file_rec/async', 'ignore_globs',
			\ split(&wildignore, ','))

nnoremap <C-p> :Unite file_rec/async<cr>
```

## Steps
1. `:Unite file_rec/async`
2. Ignored file still appear

**Comment by Shougo** [comment]
I have tested it in the minimal vimrc and it works.
`node_modules` or `so` files are ignored.
