### ISSUE TITLE
Running into issues trying to get :TW report to work [out of index and other issues}

### ISSUE THREAD

**Issue by arooni** [Shougo/unite.vim#1243]
# Problems summary

## Environment Information
 * OS: ubuntu 18.04
 * Vim version: [I]  ~  vim -v
NVIM v0.3.0
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-rIdblb/neovim-0.3.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -DDISABLE_LOG -Wdate-time -D_FORTIFY_SOURCE=2 -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/build/neovim-rIdblb/neovim-0.3.0/build/config -I/build/neovim-rIdblb/neovim-0.3.0/src -I/usr/include -I/build/neovim-rIdblb/neovim-0.3.0/build/src/nvim/auto -I/build/neovim-rIdblb/neovim-0.3.0/build/include
Compiled by team+vim@tracker.debian.org

Features: +acl +iconv +jemalloc +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info

## Provide a minimal .vimrc with less than 50 lines (Required!)
https://gist.github.com/arooni/e1d5bf4b73ec87e7e20f0480e3c1e0c1
```vim
" Your minimal .vimrc
set runtimepath+=~/path/to/unite.nvim/
```
taskrc file: https://gist.github.com/arooni/d719ddc00e61de10cc8993933234e636 

## The reproduce ways from Vim starting (Required!)

 1. foo
 2. bar
 3. baz

1. launch vim (nvim in my case)
2. run :TW list 
3. see output: "task list report" 23L, 6185C
Error detected while processing function taskwarrior#init[25]..taskwarrior#list:
line   52:
E684: list index out of range: 3
E116: Invalid arguments for function index
Press ENTER or type command to continue

same with 
:TW next

but for some reason :TW minimal ; and :TW ls work ... i was reading in bug reports that sometimes it was an issue with columns/column names not matching up but as far as i can tell with the regular taskwarrior, the reports are fine.

also my :TW best (my preferred custom report) seems to load the tasks but i'm not in the right buffer type.  it appears to be filetype: task_best and doesn't let me edit anything.

**Comment by Shougo** [comment]
It is https://github.com/blindFS/vim-taskwarrior error.
You should report it in vim-taskwarrior issues.
