### ISSUE TITLE
:Unite file をすると一つ上の階層にしかいけない 

### ISSUE THREAD

**Issue by hiro-github** [Shougo/unite.vim#1245]
## 質問・報告の内容
:Unite file を実行すると、
../
がカーソルのすぐ下に出てくるのですが、これを選択して一つ上の階層にいくと、
../
が表示されなくて、これ以上、上の階層にいけません。
何か設定等が必要なのでしょうか？

## Vimのバージョン
Kaoriya GVIM

## OSの種類/ディストリ/バージョン
*   Windows 10 Home 64bit

## 使用している or 関係していそうなプラグイン
Unite.vim

**Comment by Shougo** [comment]
確認しました。が、修正が困難なので仕様となります。
../ を選択するのではなく、../path のように入力を続けるようにしてください。
