### ISSUE TITLE
ディレクトリに対して vimgrep しても何も検索されない。

### ISSUE THREAD

**Issue by hiro-github** [Shougo/unite.vim#1248]
# Problems summary
:Unite directory_mru
でディレクトリを選んでvimgrepしても実行されない
*すでに既出のイシューかもしれませんが、同様のものが見つからなかったので質問させていただきます<〇>

## Expected
Unite directory_mruで選んだディレクトリに対してvimgrepが実行される。

## Environment Information
vim81-kaoriya-win64

**Comment by Shougo** [comment]
Reproduced.
