### ISSUE TITLE
Unite vim error

### ISSUE THREAD

**Issue by Franchium** [Shougo/unite.vim#1249]
Everytime i quit the vim i got this error, it's just pop up in a second.
Seems that coming from the unite plugin.

![62817519-c97c5c80-bb27-11e9-868d-03c8c38c9e97](https://user-images.githubusercontent.com/41231953/63176017-56b33a00-c06f-11e9-85ed-dcbce2da807f.png)
![62817482-3b07db00-bb27-11e9-9d62-46f6b3d70bf7](https://user-images.githubusercontent.com/41231953/63176144-97ab4e80-c06f-11e9-94ad-3bf49f2eec40.png)

The error message reads:

`Error detected while processing functionunite#sources#mru#_save[7]..218[7]..219[24]..220:`
`line    1:`
`E892: Using a String as a Float`

**Comment by Shougo** [comment]
It is not unite.vim's error.

You need to use the latest version of neomru plugin.
The problem is fixed.
