### ISSUE TITLE
Unite directory等で表示されたファイルをwindows既定のプログラムで開けるか？

### ISSUE THREAD

**Issue by hiro-github** [Shougo/unite.vim#1250]
# Problems summary
Unite directory等で表示されたファイルをwindows既定のプログラムで開くことは可能でしょうか？
Netrwでいうところのx:specialに当たります。
*初歩的な質問でしたらすみません。。

## Environment Information
vim81-kaoriya-win64

**Comment by Shougo** [comment]
Sorry.  It is not supported.

**Comment by Shougo** [comment]
vimfiler/defx supports that feature.
I recommend for you to use them.
