### ISSUE TITLE
findコマンドがきかない。

### ISSUE THREAD

**Issue by hiro-github** [Shougo/unite.vim#1251]
# Problems summary
添付画像のようにfindのコマンドを入力しこの後Enterを押しても、uniteバッファに何も表示されません。
2枚目のようにコマンドプロントではfindコマンドは問題なく実行されます。

何から確認していけばよいでしょうか？
初歩的な質問ですみません。。

## Environment Information
vim81-kaoriya-win64

## Screen shot (if possible)
![vim_find](https://user-images.githubusercontent.com/12881647/64169752-7036ed00-ce89-11e9-83f1-d03ec42b1378.png)
![cmd_find](https://user-images.githubusercontent.com/12881647/64169764-74fba100-ce89-11e9-8cf2-a805e499cb3a.png)

**Comment by Shougo** [comment]
残念ながら、Windows 環境での find source は動作保証していません。
Windows 環境での動作にはいろいろと難があるのです。

ただ、この例に関してはちゃんとあなたが実行しているコマンドラインを確認してみてください。

"find" "DUO3.0" -name '*.txt' になっていますね？

しかし、あなたがコマンドプロンプトで実行しているのは

"find" "." -name '*.txt' です。

当然結果は異なります。

**Comment by Shougo** [comment]
ヒント: "DUO3.0" ディレクトリ中から "DUO3.0" ディレクトリの '*.txt' を検索しようとしています。

**Comment by hiro-github** [comment]
回答ありがとうございます。ご指摘の通りです。。
添付のようにやり直しましたが、やはり何も表示されません。
何か思い当たるようなことがあれば、教えていただきたいです。
Windowsは動作保証外とのことなので、2,3日どなたからも返信がなければCloseします＜〇>

![vim_find2](https://user-images.githubusercontent.com/12881647/64258965-202c5900-cf63-11e9-878e-723ec6a1d534.png)

**Comment by Shougo** [comment]
そのコマンドラインを vimproc#system() で実行してみて、
ちゃんと結果が返ってくるか確認してください。

`:echo vimproc#system('"find" "パス" -name "*.txt"')`

**Comment by Shougo** [comment]
あと、`:Unite find` を直接実行して動作の確認してください。

**Comment by hiro-github** [comment]
お返事ありがとうございます。

:echo vimproc#system('"find" "パス" -name "*.txt"')
を試しました。
![09_05_1](https://user-images.githubusercontent.com/12881647/64343060-c7be8f80-d026-11e9-8820-fea5a632c876.png)
上記画面からEnterを押すと下記の画面になりました。
![09_05_2](https://user-images.githubusercontent.com/12881647/64343085-d5741500-d026-11e9-9e64-3570ba30b2f7.png)

:Unite find
も実行しましたが、下記のように何も表示されませんでした。
![09_05_3](https://user-images.githubusercontent.com/12881647/64343199-0d7b5800-d027-11e9-9ca8-127d8f5c28dd.png)

#本当は自分で解析ができればよいのですが、知識がなくShougoさんのご指示を仰ぐしかありません。。ご教授ありがとうございます＜〇＞

**Comment by Shougo** [comment]
あー、それだと vimproc からの実行に対応してないコマンドなんだと思いますね。
Windows 環境だとコマンドが展開するのでグロブの展開がとても難しいのです。

もうしわけありませんが対応不能です。

http://www.hachim.jp/linux-command/find_wildcard_escape.html

**Comment by Shougo** [comment]
二重クォートとかエスケープを工夫すればできるかもしれませんが……

**Comment by hiro-github** [comment]
回答ありがとうございました！
ここ最近いろいろと自分なりに試行錯誤していましたが、これで潔くあきらめることができます＜〇＞
