### ISSUE TITLE
I can not open a file that contains LF in the name

### ISSUE THREAD

**Issue by rkuchumov** [Shougo/unite.vim#1253]
When I create a file that contains LF:

```
echo aaa > "$(printf 'aa\nbb')"
```

I can not use unite to open it.

One of the workaround that I've found is to use `:edit **/*` instead of unite

**Comment by Shougo** [comment]
You have not upload the reproduce instruction.

It works for me.

**Comment by Shougo** [comment]
Please read other issues and don't ignore issue template.
