### ISSUE TITLE
How to get selected item using unite

### ISSUE THREAD

**Issue by SivanagBalla** [Shougo/unite.vim#1255]
This is not an issue but a query on how to use unite.

I have a file with list of bugs. I want to use Unite to select one from this list. I want to do something like this
```
  function! Aeng_func()
      " Tried below code but doesn't work as intended, it tries to open the selected item as file
      " :Unite -prompt-direction="below" -start-insert file_list:/users/siballa/cis/data/buglist

      " this is what I want to do
       x = <some unite function that return the selected item from buglist>
       
      "do somethign with 'x'

  endfunction!       
```

**Comment by Shougo** [comment]
Unfortunately, it is not supported.  And it cannot be supported.
Because unite does not lock all inputs like command line mode.

**Comment by Shougo** [comment]
To use custom action is better for it.
