### ISSUE TITLE
Problems to find all files with file_rec

### ISSUE THREAD

**Issue by cpfaff** [Shougo/unite.vim#156]
He

I am using vim unite recently a lot for ruby on rails development. I call the plugin for recursive file selection with the following vim mapping:

```
nnoremap [unite_key] <Nop>
   nmap <leader>f [unite_key]         
   nnoremap <silent> [unite_key]c :<C-u>Unite -buffer-name=files file_rec<CR>
```

I noticed that it in some projects it does not find all files for me. Even if I restart vim the files can not be found. But I can access them via:

```
:tabe /../path/to/file.txt
```

Any Ideas about what could be wrong?

**Comment by brennancheung** [comment]
How can I tell if  `<Plug>(unite_redraw)` has run?  I press `Ctrl l` but I'm not sure it did anything.  No confirmation or output exists.  Also, how can I set up a keybinding for this.  Or better yet, how can I call it directly outside of a key binding?

**Comment by Shougo** [comment]
@brennancheung `:Unite -redraw file_rec/async`

**Comment by brennancheung** [comment]
Thanks.  This is good to know.  I would recommend including it in the doc as well for people who aren't as familiar with vim scripting.
