### ISSUE TITLE
How to define a mapping that does action or resumes if buffer exists?

### ISSUE THREAD

**Issue by skeept** [Shougo/unite.vim#160]
I have the mapping 

nnoremap ,uc :<C-U>Unite -buffer-name=colorscheme colorscheme<CR>

but each time I use this mapping I start from the top of the list again. 
I would like to have a mapping to do the following
if the unite buffer colorscheme does not exist run 
Unite -buffer-name=colorscheme colorscheme
otherwise run
:UniteResume colorscheme

is there an option that make make this possible?

Thank you.

**Comment by euoia** [comment]
@Shougo when trying to -resume a buffer that doesn't exist I get an error "Invalid unite buffer(-1) is detected". If there any way I can check if it exists so I can use the same mapping for both *resume* (if it exists) and *create new* (for when it doesn't exist)?

**Comment by Shougo** [comment]
@euoia This feature is already implemented.  Please explain the reproduce ways.

**Comment by Shougo** [comment]
@euoia Please read the issue template.

https://github.com/Shougo/unite.vim/issues/584

**Comment by euoia** [comment]
@Shougo I got it working, sorry about that. I re-read the help and noticed that I need to use the -buffer-name option with -resume.
