### ISSUE TITLE
hot key to switch/select matcher? 

### ISSUE THREAD

**Issue by zhaocai** [Shougo/unite.vim#184]
( I hope I did not miss it in the doc. ) 

Is there a key to popup small unite window ( or just loop through) and switch matchers? sometimes I want to use the regexp or fuzzy matcher for better candidates filtering.

**Comment by Shougo** [comment]
Implemented.

**Comment by rosshadden** [comment]
I tried the following to toggle fuzzy matching, but it did not seem to do what was asked about in the OP:

```
nnoremap <buffer><expr> cof unite#mappings#set_current_matchers(
	\ empty(unite#mappings#get_current_matchers())
	\ ? ['matcher_fuzzy']
	\ : []
\ )
```

Is this what you were referring to when you said "Implemented", above?

**Comment by Shougo** [comment]
I tried it, and it works.
Please read the issue template.
You should create another issue.
