### ISSUE TITLE
サブアクション機能がほしい

### ISSUE THREAD

**Issue by osyo-manga** [Shougo/unite.vim#217]
unite.vim への機能追加の要望です。
かなり前に Twitter でも話したことがあると思うんですが覚えているうちに issues に書いておきたいと思います。

unite.vim にデフォルトアクションと同じような動作をするサブアクション機能が欲しいです。
これは、どのような機能かというとデフォルトアクションが ```<CR>``` で発動するのに対して ```<Leader><CR>```（仮）で発動する事が出来るアクションです。

```
" 設定イメージ
" <CR> → open
" <Leader><CR> → tabopen
:Unite file -default-action=open -sub-actiont=tabopen
```

もう1つデフォルトアクションが設定できると思ってもらえればわかりやすいと思います。

この機能でどういう利点があるのかというと、例えば ```unite-neobundle``` で
『デフォルトでは ```update``` でいいけど ```vimfiler``` を使いたいことも多い』
という場合、
```
:Unite neobundle -default-action=update -sub-action=vimfiler
```
このように設定することで

* ```<CR>``` → update
* ```<Leader>``` → vimfiler

という感じで簡単にアクションを使い分ける事が出来ます。

『今すぐ欲しい機能！』と言うわけではないのですが利便性が上がると思うので検討してもらえると助かります！

**Comment by lambdalisue** [comment]
+1

**Comment by osyo-manga** [comment]
自分が立てて置いてすっかり忘れていましたが、起動時に設定するのを除けば以下のような設定でもよい気しました。

```vim
" 共通した適当な名前のアクションを作っておく
call unite#custom#alias('file', 'sub1', 'tabopen')
call unite#custom#alias('directory', 'sub1', 'tabvimfiler')

" その名前のアクションを呼び出すようなキーマッピングを
" "filetype=unite で設定しておく
nmap <silent><expr><buffer> <C-CR> unite#do_action("sub1")
```

**Comment by Shougo** [comment]
確かにその通りですね。本体を拡張する理由付けが薄いので close します。
