### ISSUE TITLE
Sorting Buffers by Most Recently Used

### ISSUE THREAD

**Issue by csexton** [Shougo/unite.vim#253]
I dont' think Unite supports this currently, but I was wondering if there would be a good way to sort by the most recently used (MRU) buffer.

If this is not something that should be in the default `buffer` source I could look into adding a `buffer/mru` source.

To implement this we may need to track which buffers are being used, and keep that list up to date.

A few plugins that support this sort of thing already are [LustyExplorer](http://www.vim.org/scripts/script.php?script_id=1890), [BufSurf](https://github.com/ton/vim-bufsurf/blob/master/plugin/bufsurf.vim) and [BufExplorer](http://www.vim.org/scripts/script.php?script_id=42)

**Comment by polarlights** [comment]
I'm confused by the buffer sorted way. As you wrote " In default, buffer source is sorted by MRU."， however I got this:

    f   6 %a  d (06-09-2016 10:16:45)
    d   1 h   a (06-09-2016 10:09:35)
    s   4 h   b (06-09-2016 10:09:36)
    a   5 #h  c (06-09-2016 10:16:45)

I think the right order should be:

    f   6 %a  d (06-09-2016 10:16:45)
    d   5 #h  c (06-09-2016 10:16:45)
    s   4 h   b (06-09-2016 10:09:36)
    a  1 h   a (06-09-2016 10:09:35)

My configrations: 

```viml
[[plugins]]
repo = 'Shougo/unite.vim'
depends = 'neomru.vim'
hook_post_source = '''
  call unite#custom#source('codesearch', 'max_candidates', 30)
  call unite#filters#matcher_default#use(['matcher_fuzzy'])
  call unite#filters#sorter_default#use(['sorter_rank'])
  call unite#custom#profile('default', 'context', {
              \   'safe': 0,
              \   'start_insert': 1,
              \   'ignorecase' : 1,
              \   'short_source_names': 1,
              \   'update_time': 200,
              \   'direction': 'rightbelow',
              \   'winwidth': 40,
              \   'winheight': 15,
              \   'max_candidates': 100,
              \   'no_auto_resize': 1,
              \   'vertical_preview': 1,
              \   'cursor_line_time': '0.10',
              \   'hide_icon': 0,
              \   'candidate-icon': ' ',
              \   'marked_icon': '✓',
              \   'prompt' : ' ➭'
              \ })
'''

nnoremap <leader>b :<C-u>Unite -no-split -buffer-name=buffer -quick-match buffer<cr>
```

**Comment by Shougo** [comment]
```vim
nnoremap <leader>b :<C-u>Unite -no-split -buffer-name=buffer -quick-match -promt-direction=top buffer<cr>
```

**Comment by polarlights** [comment]
@Shougo Thank you! I think I know its sort behaviour. The last modified one is at the bottom of the buffer, and the order of others are descending by open time.
