### ISSUE TITLE
case insensitive filtering

### ISSUE THREAD

**Issue by justone** [Shougo/unite.vim#277]
I've been using fuzzyfinder for quite a while and I'd like to start using unite as I like it's interaction and structure much better.  One sticking point is that when I type my filtering text it is matched in a case sensitive manner.  For instance, for the following set of files:

```
Git.pm
Subversion.pm
Perforce.pm
```

If I do `:Unite -start-insert file` and type 'git' it doesn't find Git.pm.  I have to type 'Git'.  I've tried putting the following lines in my .vimrc, but that doesn't help:

```
call unite#custom#profile('files', 'ignorecase', 1)
call unite#custom#profile('files', 'smartcase', 0)
```

Is there any way to make the filtering case insensitive?

**Comment by geraldus** [comment]
> case insensive is "files" unite buffer only(You can custom it).

Does this mean that I can't setup case insensitive search for `files_rec` source? E.g. haskell is case sensitive for source filename:
```
/Handler
   /Forms
     Login.hs
     SignUp.hs
  HomeR.hs
  SignUp.hs
```
I suppose it's very common to write fuzzy pattern by typing suffixes of filenames. Thus, to quickly find `SignUp.hs` I have to type, say `HaSig`, it would be very good to allow type just `hsig`.

My default Unite call is
```vim
call unite#custom#profile('ignorecase','context.ignorecase',1)
call unite#custom#profile('ignorecase','context.smartcase',1)
:Unite -buffer=files -profile-name=ignorecase file file_res/async:! file_mru 
```

_Sorry for bumping such old stuff_

**Comment by Shougo** [comment]
> Does this mean that I can't setup case insensitive search for files_rec source? E.g. haskell is case sensitive for source filename:

Unfortunatelly, Yes.

```vim
call unite#custom#profile('ignorecase','ignorecase',1)
call unite#custom#profile('ignorecase','smartcase',1)
```

is correct.

**Comment by brettc** [comment]
Case insensitive searching seems to have changed (it no longer works for me).
```
call unite#custom#profile('ignorecase', 'ignorecase', 1)
nnoremap <leader>o :<C-u>Unite -no-split -no-auto-resize -profile-name=ignorecase -start-insert outline<cr>
```
What am I doing wrong?

**Comment by Shougo** [comment]
Yes, please read the error message.

You can specify the ignorecase in unite options.

```vim
nnoremap <leader>o :<C-u>Unite -no-split -no-auto-resize -ignorecase -start-insert outline<cr>
```
