### ISSUE TITLE
file_rec/async command not working/not respecting git ignore

### ISSUE THREAD

**Issue by derekleverenz** [Shougo/unite.vim#398]
I recently upgraded to the latest version, and now file_rec/async is much much slower and no longer ignores files in my .gitignore. I noticed that was intentional, since the command now defaults to having --skip-vcs-ignores, so I tried setting `let g:unite_source_file_rec_async_command='ag --nocolor --nogroup -g '` in my vimrc
but that didn't change anything at all. I am not sure it is even using ag now, it doesn't show up in my process list at least.

I have just switched back to ver.5.0 for now since it works there.

**Comment by brennancheung** [comment]
Can someone please provide SIMPLE instructions without obscure references on how to make Unite use `ag` and ignore files.  Ideally I want it to ignore files from `.gitignore` and `.agignore`.

I've been trying for hours to get unite to ignore my `node_modules` folder.  It works fine on my other system but I can't figure out why it is not working on my new system.

How do I re-create cache files?  I found some folder called  `~/.cache` and deleted it.  That didn't solve the problem.

When I run `ag` from the command line it works fine.  It doesn't have the 100,000+ files that seems to be there in Unite.  But when I use it from vim it reads everything and takes about 10 seconds and has a bunch of files I don't want to see.

Here are the relevant sections in my `.vimrc`.

    nnoremap <Leader><Space> :Unite -no-split -buffer-name=filenav -start-insert bookmark buffer file_rec/async:!<cr>
    let g:unite_source_rec_async_command='ag --nocolor --nogroup --hidden -g ""'
    let g:unite_source_grep_command='ag'
    let g:unite_source_grep_default_opts='-i --line-numbers --nocolor --nogroup --hidden -p /Users/brennan/.agignore'

I also have the ignores set up in my `~/.agignore` and it is not respecting that either.

**Comment by brennancheung** [comment]
I'm not sure what I did to fix it but it seems to be working now.

I completely wiped out my `~/.vim` folder and copied it from another system.

Then I added the following line:

    let g:unite_source_file_rec_max_cache_files = 200000

I deleted the `~/.cache` folder.

At first when I brought up the fuzzy finder search (`file_rec/async:!`) it showed the files that were supposed to be ignored.  I hit `C-l` and they went away.  I closed vim and reloaded it and it seems to be working going forward now.

I'm not sure what change made it happen or even what is going on behind the scenes but if someone can explain what step made it work and why that would really help for the next time I encounter this issue.

**Comment by p3rsist** [comment]
@brennancheung I have the same problem here. It used to work on Fedora 21. Now I'm using CentOS 7 1503 and it's no longer working. I keep getting thousands of files even though when I run Ag from the command line the .agignore file is used and therefore I get the correct number of files.

**Comment by carlesandres** [comment]
@brennancheung <https://github.com/brennancheung> , @p3rsist For some
reason that I can't recall right now,  `unite-vim` (or maybe `ag.vim`) was
not honouring `.agignore` for me either.

I have found that the best way to force the use `.agignore` by unite.vim
was to add the `--skip-vcs-ignores` flag to the unite grep commands
configuration. That forces me to keep my `.agignore` manually in sync with
`.gitignore`, but once a project is setup there are usually very few
changes to `.gitignore` and, with this setup, I have a lot more flexibility
to decide which files and folders I want `unite.vim` to look for (or look
into).

Thus, I have the following in my `.vimrc` at the moment:

```
if executable('ag')
  let g:unite_source_rec_async_command= 'ag --follow --skip-vcs-ignores
--nocolor --nogroup --ignore ".hg" --ignore ".svn" --ignore ".git" --ignore
".bzr" -g ""'
  let g:unite_source_grep_command = 'ag'
  let g:unite_source_grep_default_opts = '--column --nogroup --nocolor
--follow --skip-vcs-ignores'
  let g:unite_source_grep_recursive_opt = ''
endif
```

Not sure this is the best config I can achieve yet, but it does the trick
nicely for me at the moment.

Once added, restart vim (better if you can start afresh, not from a saved
session) and refresh vim unite's cache vim hitting `Ctrl+l` when doing your
next file search.

By the way, if you want avoid having to add `.agignore` to `.gitignore`,
consider adding it to `.git/info/exclude` which is never added to git's
source control.

**Comment by chrisfid** [comment]
Every single person seems to have a different solution. How can it be that ag ignores fine when run from command line, but not from Unite, but only for some people, and only on some days!?

**Comment by Shougo** [comment]
I think unite cache is not updated.
To update the cache, you must press `<Plug>(unite_redraw)` key.

**Comment by p3rsist** [comment]
@Shougo I can confirm that cleaning the cache worked. No need to add the --skip-vcs-ignores flag.
Thanks :)

Also, I can also confirm how quicker is Unite with Vim with Lua flag enabled...

**Comment by brennan-si** [comment]
Got a new system and even with the previous steps I am running into the exact same problem.  I can't figure it out.  I copy and paste the exact code from `let g:unite_source_rec_async_command='ag --nocolor --nogroup --hidden -g ""` and it works fine from the command line.  I followed all the steps above.  Nothing working.  I even added the --ignore and -p options to the command still nothing.  I'm not sure `unite_source_rec_async_command` is even being used at this point.  Nothing seems to matter.

**Comment by brennan-si** [comment]
I hid the ag executable.  It seems like it is not even being invoked.  That answers that question.  How do I force it to go through ag?  I have this added already.

    let g:unite_source_file_rec_max_cache_files = 2000000
    let g:unite_source_rec_async_command='ag --nocolor --nogroup --hidden -g ""'
    let g:unite_source_grep_command='ag'
    let g:unite_source_grep_default_opts='-i --line-numbers --nocolor --nogroup --hidden -p /Users/brennan/.agignore'

**Comment by Shougo** [comment]
@brennan-si Please read the issue template.

**Comment by brennan-si** [comment]
I gave up and switched to file_rec/git.  It doesn't show files that haven't been staged yet but at least it is more usable than seeing nothing but node_modules/*.

Even when using `:Unite file_rec/async` or with the `:!` part and with `g:unite_source_rec_async_command` defined to use `ag` it isn't using `ag`.

**Comment by p3rsist** [comment]
@brennan-si Did you try to clean the cache?

**Comment by brennan-si** [comment]
I can confirm the cache is cleared.  I saw a fresh when hitting Ctrl-l and I also deleted the `~/.cache` folder.  However it is getting it, it is not using `ag`.

**Comment by Shougo** [comment]
> I gave up and switched to file_rec/git. It doesn't show files that haven't been staged yet but at least it is more usable than seeing nothing but node_modules/*.

`:Unite file_rec/git:--cached:--others:--exclude-standard`

**Comment by Shougo** [comment]
> I can confirm the cache is cleared. I saw a refresh when hitting Ctrl-l and I also deleted the ~/.cache folder. However it is getting it, it is not using ag.

You should check the command line by `<Plug>(unite_print_message_log)`.

**Comment by Skinney** [comment]
I got this in my .vimrc:

```
call unite#filters#matcher_default#use(['matcher_fuzzy'])
let g:unite_source_rec_async_command=\['ag', '--nocolor', '--nogroup', '--hidden', '-g', '']
nnoremap <leader>f :Unite -start-insert -ignorecase -smartcase buffer file_rec/async:!<CR>
```

Message log is:
```
[file_rec/async] directory: /Users/skinney/Workspace/Jarvis
[file_rec/async] Command-line: ['find', '-L', '/Users/skinney/Workspace/Jarvis', '-path', '*/.git/*', '-prune', '-o', '-type', 'l', '-pri
nt', '-o', '-type', 'f', '-print'] 
```
