### ISSUE TITLE
A way to always jump to existing file/window/buffer.

### ISSUE THREAD

**Issue by jordwalke** [Shougo/unite.vim#410]
For each of the Unite actions (such as opening in new tab/split/vsplit) I'd like it to always jump to any existing buffer wherever it may be open. Is there a way to configure Unite as such?

**Comment by jordwalke** [comment]
Why was this diff never merged in @Shougo ?

**Comment by Shougo** [comment]
> Why was this diff never merged in, @Shougo ?

What's the problem?
I don't understand it.
Please explain the more detail.

**Comment by jordwalke** [comment]
Oh, I accidentally assumed it was never merged because I found no grep for `splitdrop`. I see it has been renamed to `splitswitch`. All is well.

**Comment by Shougo** [comment]
OK.
