### ISSUE TITLE
window source: provide windows from all tabs

### ISSUE THREAD

**Issue by blueyed** [Shougo/unite.vim#508]
This could be a new source, but I think it belongs to the window source, and there should be a new option/argument to loop over all tabs, e.g. `-tabs`, `-all`, `-with-tabs` ...

**Comment by blueyed** [comment]
I came across this already: it would be useful to have a window switcher across all tabs: the default for the window source should include all windows.
To provide backward compatibility the `-current-tab` option could be provided.

But in general you can easily switch between windows in the current tab (and there are usually not many), while it's useful to re-use an existing window to avoid tab-cluttering.

What do you think?

**Comment by Shougo** [comment]
Yes.  It is better behavior.
But I have not much time for it.  And I don't like window splits.
Pull request is wellcome.

**Comment by Shougo** [comment]
Implemented.

**Comment by blueyed** [comment]
Thanks!
