### ISSUE TITLE
Can't add ignore pattern

### ISSUE THREAD

**Issue by vito-c** [Shougo/unite.vim#523]
In my vimrc:

```
call unite#filters#matcher_default#use(['matcher_fuzzy'])
call unite#custom#source('file_rec', 'ignore_pattern', '\.meta$')
nnoremap <leader>r :<C-u>Unite -start-insert -no-split -auto-preview file_rec/async:!<CR>
```

Expected outcome: .meta files shouldn't show up in my search list
Result: they show up :(

**Comment by youchihwang** [comment]
Hi
    I use gnu global.
    I have a file list on gtags.files
    The ProjectConfig.mk is on gtags.files.
    But I can't find ProjectConfig.mk using :Unite gtags/path:
thanks

**Comment by Shougo** [comment]
I don't know `gtags/path` source.
You should ask it to the source author.
