### ISSUE TITLE
Winheight ignored with no-split

### ISSUE THREAD

**Issue by vito-c** [Shougo/unite.vim#530]
``` viml
let g:unite_winheight=20
nnoremap <leader>r :<C-u>Unite -start-insert -auto-preview -winheight=20 -no-split file_rec/async:!<CR>
```

I realize that winheight is the height used to split the current window. But how can I then split the window when I have the file preview enabled? I would like to specify a size for the file browsing portion so that I can see a little bit more of the file in the preview. Is there a way to do this?

**Comment by rainerborene** [comment]
@Shougo I had the same problem today. It took me some time to figure out that was `previewheight` problem. I think you should include this on documentation.
