### ISSUE TITLE
Source highlighting customization

### ISSUE THREAD

**Issue by WscriChy** [Shougo/unite.vim#537]
I try to customize highlighting of existing sources

    
    let s:variables = {
      \ 'syntax' : 'uniteSource__FileRec',
      \ 'hooks' : {},
      \ }
    function! s:variables.hooks.on_syntax(args, context)
      syntax match uniteSource__FileRecFileName /\[.\+\]/ contained containedin=uniteSource__FileRec
      highlight default link uniteSource__FileRecFileName Type
    endfunction
    let s:variables.syntax = 'uniteSource__FileRec'
    call unite#custom#source('file_rec', 'variables', s:variables)

But seems like I cant change hooks.

**Comment by JohannesZiegenbalg** [comment]
+1

**Comment by Shougo** [comment]
Implemented.
