### ISSUE TITLE
-keep-focusオプション使用時は、アクション実行後にupdatetimeがリセットされないようにしたい

### ISSUE THREAD

**Issue by supermomonga** [Shougo/unite.vim#574]
アクション実行後はupdatetimeがrestoreされると思いますが、`-keep-focus`オプション付きでUniteを実行していた場合はUniteのバッファからフォーカスが外れないので、updatetimeのrestoreが行わなれないようになれば良いと思いました。

**Comment by Shougo** [comment]
最近 updatetime の変更方法が変わったので問題ないはずです。
クローズします。
