### ISSUE TITLE
-no-quitなUniteバッファに再びフォーカスした際、updatetimeを設定しなおして欲しい

### ISSUE THREAD

**Issue by supermomonga** [Shougo/unite.vim#575]
`-no-quit`オプションを使用した場合、アクション実行後もUniteバッファが開かれたままになるかと思います。アクション実行後はupdatetimeがresumeされるかと思いますが、再びUniteバッファにフォーカスを移した際、`-update-time`オプションや`g:unite_update_time`で指定した値でupdatetimeが再設定される様になると便利だと思いました。

**Comment by Shougo** [comment]
この機能は既に実装されています。クローズします。
