### ISSUE TITLE
Add breadth first search algorithm to file_rec.

### ISSUE THREAD

**Issue by ironhouzi** [Shougo/unite.vim#579]
As far as I can tell, unite uses a depth first search for file_rec and in my humble opinion, this is probably not the most beneficial to the user.

If my assumptions are mistaken, I wholeheartedly excuse myself and hope this issue is removed from the issue tracker.

My assumptions arise from the observation that whenever I do an asynchronous file search with sorter_rank enabled or disabled, I get matches from files that are many directory levels deep before I get the matches I am trying to find, which are only a couple of directory levels deep. This leads me to believe that a depth first search algorithm is used and for these reasons, I think many users might benefit of having the option to use a breadth first search algorithm, in order to find what one is most likely looking for more quickly.

Thank you for all the great plugins. They are extremely helpful to me.

**Comment by brglng** [comment]
I also want this feature. It looks like `find <dir> -depth` uses breadth first searching. And `-maxdepth` can even limit the depth of searching. However I cannot find a unite.vim option to add these options to the `file_rec/async` source.

Thanks!

**Comment by brglng** [comment]
I am sorry. `-depth` is still not real breadth first searching. However I think breadth first searching can be achieved by calling a sequence of `find <dir> -mindepth 0 -maxdepth 1`, `find <dir> -mindepth 1 -maxdepth 2`, ... Is it possible for Unite to support this?

**Comment by Shougo** [comment]
OK.  I added `g:unite_source_rec_find_args`.
Please use it.

**Comment by brglng** [comment]
Thanks, Shougo. However this still does not completely solve the problem. I am now considering to write my own "find" program.

**Comment by Shougo** [comment]
> Thanks, Shougo. However this still does not completely solve the problem.

Why?  You can use `-mindepth 0 -maxdepth 1` arguments.

**Comment by brglng** [comment]
What I actually want is something like this:
```shell
for i in $(seq 50) ; do find -mindepth $((i - 1)) -maxdepth $i ; done
```
I could use a shell script. However this still has drawbacks. `find` will spend much time skipping depth from 0 to `$((i - 1))` when `i ` is not small. That's why I want to write a new tool to do the real breadth first search to achieve the maximum speed.

**Comment by Shougo** [comment]
Thanks.  I get it.
