### ISSUE TITLE
[Important] Please read Issues template

### ISSUE THREAD

**Issue by Shougo** [Shougo/unite.vim#584]
* Problems summary
 
* Expected
 
* Environment Information
 * OS:
 * Vim version:
 * Enabled lua interface?:  (It is important!)
 
* Minimal vimrc less than 50 lines

 ```
 " Your vimrc
 set nocompatible
 
 set runtimepath+=~/path/to/unite.vim/
 ```
 
* Reproducable ways from Vim starting

 0.startup vim.
 1.
 2.
 3.

* Screen shot (if possible)

#### markdown template

    * Problems summary
    
    * Expected
    
    * Environment Information
     * OS:
     * Vim version:
    
    * Minimal vimrc less than 50 lines
    
    ```
    " Your vimrc
    set nocompatible
    
    set runtimepath+=~/path/to/unite.vim/
    ```
    
    * Reproducable ways from Vim starting
    
     0.startup vim.
     1.
     2.
     3.
    
    * Screen shot (if possible)

**Comment by Shougo** [comment]
I updated the template.
if_lua information is needed.

**Comment by wsdjeg** [comment]
This is really a good way to manage the issue!!

**Comment by Shougo** [comment]
github officially supported the feature.
