### ISSUE TITLE
Speed of file source

### ISSUE THREAD

**Issue by tex** [Shougo/unite.vim#625]
Look at the FZF.
https://raw.githubusercontent.com/junegunn/i/master/fzf-commandt-ctrlp-unite.gif

I use vim over a large directory structure - big project. It takes a realy lot of time to get the list of files with unite file_rec,file_rec/async. The FZF is almost instant. Very quick.

This issue is more like a feature request or a note that things can be much faster.

**Comment by ldong** [comment]
@tex Thank you, I was going to migrate from unite to fzf as well, then I saw this comment.
