### ISSUE TITLE
unite_source_rec_async_command with the_platinum_searcher

### ISSUE THREAD

**Issue by LK4D4** [Shougo/unite.vim#633]
I trying use [the_platinum_searcher](https://github.com/monochromegane/the_platinum_searcher) as `unite_source_rec_async_command` by this way:

```
let g:unite_source_rec_async_command= 'pt --nocolor --nogroup -g .'
```

But `file_rec/async` doesn't find anything. Similar ag command works fine.
Any ideas?

**Comment by soyuka** [comment]
Hi, this is no longer working:

```
  let g:unite_source_rec_async_command = 'pt --nogroup --nocolor -S -g .'
```

Any clue? Results are just empty.

**Comment by Shougo** [comment]
@soyuka Please update unite.vim and vimproc.

**Comment by soyuka** [comment]
omg that's fast! Thanks, working now!
