### ISSUE TITLE
Possible to use the action menu on the current file?

### ISSUE THREAD

**Issue by garymh** [Shougo/unite.vim#650]
* Problems summary

I would love to be able to use the action menu (rename, open in split, etc.) on the current file. The FAQ mentions the following:

> Q: How to make direct action (or choose action menu) to current file or given
> path?

> A: >
>	call unite#do_candidates_action('some_action',
> 	\  unite#get_candidates([['file', expand('%')]]))
> <

But that seems to be limited to only one action per mapping, and I couldn't actually get a rename action to work. My vimrc has:

```VimL
nnoremap <silent> <leader>r :<C-u>call unite#do_candidates_action('rename', unite#get_candidates([['file', expand('%')]]))<CR>
```

and the result is:

> E117: Unknown function: unite#do_candidates_action

Is there a newer way to do this with recent versions of Unite.vim? And is there any way to just bring up the action menu instead of a specific action?

Thanks!

**Comment by Shougo** [comment]
It works.

**Comment by garymh** [comment]
Thanks! :smiley:
