### ISSUE TITLE
untie-function ソースのキャッシュ機能についての提案

### ISSUE THREAD

**Issue by supermomonga** [Shougo/unite.vim#676]
`untie-function`は最初に起動した時の結果をキャッシングし、
以降そのデータを表示しているのですが、これはパフォーマンス上の理由からですか？

autoload 関数などが読み込まれるタイミングは不定のため、
この仕様では`unite-function`を起動した際、結果が最新でない場合が多々あると思います。

実際、2回目以降に`unite-function`を起動した時に autoload 関数が列挙されず、
しばらく原因がわかりませんでした。
その度に`<C-l>`で再取得する必要があるのは少し手間に感じます。

手元で候補列挙の処理時間を計測してみたところ、
私の環境では関数が 1348個で `0.10s`、
@osyo-manga さんの環境では 2005個で `0.26s` でした。

これぐらいの処理時間であれば、
キャッシングを行わず毎回取得しても問題ないのではないでしょうか。

キャッシングによるパフォーマンス向上のメリットよりも、
上記の様なデメリットの方が大きいと思います。

そういった理由から、キャッシュ機能については削除してしまっても良いかと思うのですが、いかがでしょうか。

**Comment by Shougo** [comment]
実装しました。キャッシュするのは組み込みコマンドのみに限定しました。

**Comment by supermomonga** [comment]
やったー、ありがとうございます！
