### ISSUE TITLE
100% cpu usage 

### ISSUE THREAD

**Issue by brandonbloom** [Shougo/unite.vim#701]
This is effectively re-opening #685. I'm experiencing the same problem.

Latest unite, macvim, and vimproc. Occurs after using `file_rec/async` at least once. Shortly after closing the unite window, vim becomes completely unresponsive for 5 to 10 seconds. Activity monitory shows 100% CPU usage.

Only seems to be a problem for very large trees (mine has about 17,000 files). Smaller trees work great.

**Comment by Shougo** [comment]
Fixed in Vim 7.4.615

https://groups.google.com/forum/#!topic/vim_dev/pXjj7rww5RY
