### ISSUE TITLE
opening file_rec and file_rec/async slow when opening for the second time

### ISSUE THREAD

**Issue by prabirshrestha** [Shougo/unite.vim#705]
We have lot of files in the source control and using both file_rec and file_rec/async seems to be slow.

Ctrlp seems to be really fast after the caching compared to unit.vim. Ctrlp takes few milliseonds to open after cache while unit.vim takes few seconds. Wondering if it retains the cache in memory after it closes. (I haven't looked at the internal details for both ctrlp and unite.vim). Might be unit.vim should have persist cache in memory option? You can try reproducing this by comparing unit.vim vs ctrlp in the windows directory or any large folders.

using ag under windows when executing  `:Unite file_rec/async`

``` viml
 let g:unite_source_rec_async_command = 'ag --follow --nocolor --nogroup --hidden -g ""'
```

**Comment by Shougo** [comment]
Fixed in Vim 7.4.615

https://groups.google.com/forum/#!topic/vim_dev/pXjj7rww5RY

**Comment by prabirshrestha** [comment]
awesome. will try it out when v7.4.615+ gets released at https://bintray.com/veegee/generic/vim_x64

**Comment by prabirshrestha** [comment]
using vim 7.4.617.

Opening unite.vim for the first time seems faster and more responsive then CtrlP but when I open the second time it is slow and not so responsive.

While unite.vim does use cache does it read from the cache file everytime or only for the first time?

**Comment by prabirshrestha** [comment]
seems like i was missing `-resume` option. This makes it very fast even with sync `file_rec` the second time. `:Unite file_rec -input= -resume`

```
call unite#filters#matcher_default#use(['matcher_fuzzy'])
call unite#filters#sorter_default#use(['sorter_rank'])

nnoremap <C-P> :<C-u>Unite -buffer-name=files -start-insert buffer -input= -resume file_rec:!<cr>
```
