### ISSUE TITLE
Unite -no-split opens in all windows if `:pwd` matches `wildignore`

### ISSUE THREAD

**Issue by justinmk** [Shougo/unite.vim#710]
This started happening in the last couple weeks, I think. If the same buffer is open in multiple windows, and `:Unite buffer -no-split` is invoked, the unite interface is shown in all windows for that buffer. This is an undesirable change from the old behavior.

1. start new Vim
2. `:help help`
3. `:vsplit`
    - two windows now show the same help buffer
4. ~~`:Unite buffer -no-split`~~
5. ~~Unite list is shown in both windows.~~ These steps aren't correct.

**Comment by Shougo** [comment]
@justinmk Any news?

**Comment by justinmk** [comment]
No, sorry.

**Comment by Shougo** [comment]
Oh,...

**Comment by Shougo** [comment]
I have tested it in Windows.

> Unite opens in both windows, and canceling out of Unite returns to an empty file instead of foo/bar.txt.

I can reproduce 2nd problem.  I cannot reproduce 1st problem.
I fixed 2nd problem.  It seems Vim's bug though...

**Comment by justinmk** [comment]
Thanks!

**Comment by Shougo** [comment]
I don't fix the problem.
It is Vim's bug and to set buflisted occurs the problems.
