### ISSUE TITLE
Show buffer number and sort by number

### ISSUE THREAD

**Issue by petobens** [Shougo/unite.vim#722]
If I have three  buffers `foo.txt`, `bar.txt` and `baz.txt` and I use the following settings

```
call unite#custom#source('buffer', 'converters', 'converter_tail_abbr')
let g:unite_source_buffer_time_format = ''
```

The Unite buffer source, when run with the `quick-match` flag, shows

```
a|baz.txt
s|foo.txt
d|bar.txt
```

This can be seen in the image below.

 I would like the Unite buffer source to display buffer numbers and sort the buffers according to those numbers. i.e I want to Unite buffer source to display buffers as:

```
a| 1:bar.txt
s| 4:baz.txt
d| 5:foo.txt
```

![screenshot-02-09-2014_16-42-53](https://cloud.githubusercontent.com/assets/2583971/4124572/c7598314-32d9-11e4-8d05-d7c9c19e6b70.png)

**Comment by erichaase** [comment]
Whats the suggested full solution for this? I'd also like to sort buffers by id number.

**Comment by Shougo** [comment]
You should create new converter.
