### ISSUE TITLE
Error messages after latest update for buffer and file_mru sources

### ISSUE THREAD

**Issue by coaxmetal** [Shougo/unite.vim#727]
Hi,

After updating Unite today or yesterday, I have started getting the following error messages when I am using :Unite buffer and :Unite file_mru, but not with file_rec/async

```
[unite.vim] Custom filters feature is removed.  You must use matchers/sorters/converters feature.
[unite.vim] Custom filters feature is removed.  You must use matchers/sorters/converters feature.  
```

I assume this is something wrong with my configuration, but I can't tell what it is. All of what I have has examples in the docs, I think.

This is what my unite configuration looks like in my .vimrc, do you know what might be the issue?
```
let g:unite_data_directory="~/.vim/.cache/unite"
let g:unite_source_rec_max_cache_files=5000
let g:unite_source_file_mru_limit = 200
let g:unite_source_history_yank_enable = 1
let g:unite_prompt='» '
let g:unite_source_grep_default_opts='--nocolor --nogroup'
let g:unite_source_grep_recursive_opt=''
if executable('ag')
    let g:unite_source_rec_async_command='ag --nocolor --nogroup -g ""'
    let g:unite_source_grep_command='ag'
endif

call unite#custom#profile('files', 'smartcase', 1)
call unite#custom#profile('files', 'ignorecase', 1)
call unite#filters#matcher_default#use(['matcher_fuzzy'])
" call unite#filters#sorter_default#use(['sorter_rank'])
call unite#custom_source('file_rec,file_rec/async', 'filters',
            \ ['converter_relative_word', 'matcher_default', 'converter_relative_abbr'])
call unite#custom_source('file_rec,file_rec/async', 'sorters', ['sorter_rank', 'sorter_selecta'])

au FileType unite call s:unite_buffer_settings()
function! s:unite_buffer_settings()
    setl norelativenumber
    nmap <buffer> <C-r> <Plug>(unite_narrowing_input_history)
    imap <buffer> <C-r> <Plug>(unite_narrowing_input_history)
    let unite = unite#get_current_unite()
    if unite.profile_name ==# 'search'
        nnoremap <silent><buffer><expr> r unite#do_action('replace')
    else
        nnoremap <silent><buffer><expr> r unite#do_action('rename')
    endif
endfunction
```

thanks

**Comment by rafaelnp** [comment]
Unfortunately I am still having this issue, bellow my unite config. Any suggestions ?

" The prefix key.
nnoremap [unite] <Nop>
nmap <space> [unite]

let g:unite_prompt = '» '
let g:unite_source_history_yank_enable = 1
let g:unite_data_directory="~/.vim/.cache/unite"
let g:unite_source_grep_command = 'ag'
let g:unite_source_grep_default_opts =
          \ '--line-numbers --column --nocolor --nogroup --hidden --ignore ' .
          \  '''.hg'' --ignore ''.svn'' --ignore ''.git'' --ignore ''.bzr'''
let g:unite_source_grep_recursive_opt = ''

call unite#custom_source('file_rec,file_rec/async', 'matchers',
            \ ['converter_relative_word', 'matcher_default'])
call unite#custom_source('file_rec,file_rec/async', 'converters',
            \ 'converter_relative_abbr')

" Custom mappings for the unite buffer
autocmd FileType unite call s:unite_settings()
function! s:unite_settings()
"   Runs "split" action by <C-s>.
    imap <silent><buffer><expr> <C-s>     unite#do_action('split')
	imap <buffer> <C-j> <Plug>(unite_select_next_line)
	imap <buffer> <C-k> <Plug>(unite_select_previous_line)
	imap <buffer> <c-a> <Plug>(unite_choose_action)
	imap <buffer> <ESC> <Plug>(unite_exit)
	nmap <buffer> <ESC> <Plug>(unite_exit)
endfunction

" General purpose - list all sources
nnoremap [unite]<space> :Unite -no-split -start-insert source<cr>
nnoremap [unite]p :Unite file_rec/async<cr>
nnoremap [unite]/ :Unite grep:.<cr>
nnoremap [unite]y :Unite history/yank<cr>
nnoremap [unite]b :Unite buffer<cr>
nnoremap [unite]r :<C-u>Unite -start-insert file_rec/async:!<CR>
nnoremap [unite]M :Unite -quick-match colorscheme<CR>
nnoremap [unite]t :<C-u>Unite -buffer-name=buffer  buffer<cr>
" show document outline
nnoremap [unite]o :Unite -no-split -auto-preview outline<CR>

" line search
nnoremap [unite]l :Unite -no-split -start-insert line<cr>

nnoremap <silent> [unite]c  :<C-u>UniteWithCurrentDir
        \ -buffer-name=files buffer bookmark file<CR>

" list mappings
nnoremap <silent> [unite]ma :<C-u>Unite mapping<CR>

nnoremap [unite]F :Unite -no-split buffer tab file_mru directory_mru<cr>
" Quickly switch between recent things
nnoremap <silent> [unite]m :Unite -buffer-name=recent -winheight=15 file_mru<cr>

nnoremap <silent> [unite]f :<C-u>Unite -buffer-name=resume resume<CR>
nnoremap <silent> [unite]me :<C-u>Unite output:message<CR>

**Comment by Shougo** [comment]
@rafaelnp Please read the issue template.

https://github.com/Shougo/unite.vim/issues/584

**Comment by rafaelnp** [comment]
* Error messages using any Unite command/source

[unite.vim] Custom filters feature is removed.  You must use matchers/sorters/converters feature.
[unite.vim] Custom filters feature is removed.  You must use matchers/sorters/converters feature.

* Expected: No error messages

* Environment Information
 * OS: Linux 3.16.6 x86_64 (Arch Linux)
 * Vim version:
 ```
 VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jan 14 2015 20:16:36)
Included patches: 1-580
Compiled by Arch Linux
Huge version with GTK2 GUI.  Features included (+) or not (-):
+acl             +cscope          +folding         +menu            +netbeans_intg   -sniff           +virtualedit
+arabic          +cursorbind      -footer          +mksession       +path_extra      +startuptime     +visual
+autocmd         +cursorshape     +fork()          +modify_fname    +perl            +statusline      +visualextra
+balloon_eval    +dialog_con_gui  +gettext         +mouse           +persistent_undo -sun_workshop    +viminfo
+browse          +diff            -hangul_input    +mouseshape      +postscript      +syntax          +vreplace
++builtin_terms  +digraphs        +iconv           +mouse_dec       +printer         +tag_binary      +wildignore
+byte_offset     +dnd             +insert_expand   +mouse_gpm       +profile         +tag_old_static  +wildmenu
+cindent         -ebcdic          +jumplist        -mouse_jsbterm   +python          -tag_any_white   +windows
+clientserver    +emacs_tags      +keymap          +mouse_netterm   -python3         -tcl             +writebackup
+clipboard       +eval            +langmap         +mouse_sgr       +quickfix        +terminfo        +X11
+cmdline_compl   +ex_extra        +libcall         -mouse_sysmouse  +reltime         +termresponse    -xfontset
+cmdline_hist    +extra_search    +linebreak       +mouse_urxvt     +rightleft       +textobjects     +xim
+cmdline_info    +farsi           +lispindent      +mouse_xterm     +ruby            +title           +xsmp_interact
+comments        +file_in_path    +listcmds        +multi_byte      +scrollbind      +toolbar         +xterm_clipboard
+conceal         +find_in_path    +localmap        +multi_lang      +signs           +user_commands   -xterm_save
+cryptv          +float           +lua             -mzscheme        +smartindent     +vertsplit       -xpm
```

* My .vimrc:

```vim
set nocompatible
set runtimepath+=~/path/to/unite.vim/
call neobundle#begin(expand('~/.vim/bundle'))
NeoBundle 'Shougo/unite.vim'

nnoremap [unite]
nmap [unite]
let g:unite_prompt = '» '
let g:unite_source_history_yank_enable = 1
let g:unite_data_directory="~/.vim/.cache/unite"
let g:unite_source_grep_command = 'ag'
let g:unite_source_grep_default_opts =
\ '--line-numbers --column --nocolor --nogroup --hidden --ignore ' .
\ '''.hg'' --ignore ''.svn'' --ignore ''.git'' --ignore ''.bzr'''
let g:unite_source_grep_recursive_opt = ''

call unite#custom_source('file_rec,file_rec/async', 'matchers',
\ ['converter_relative_word', 'matcher_default'])
call unite#custom_source('file_rec,file_rec/async', 'converters',
\ 'converter_relative_abbr')

autocmd FileType unite call s:unite_settings()
function! s:unite_settings()
imap unite#do_action('split')
imap (unite_select_next_line)
imap (unite_select_previous_line)
imap (unite_choose_action)
imap (unite_exit)
nmap (unite_exit)
endfunction

nnoremap [unite] :Unite -no-split -start-insert source
nnoremap [unite]p :Unite file_rec/async
nnoremap [unite]/ :Unite grep:.
nnoremap [unite]y :Unite history/yank
nnoremap [unite]b :Unite buffer
nnoremap [unite]r :Unite -start-insert file_rec/async:!
nnoremap [unite]M :Unite -quick-match colorscheme
nnoremap [unite]t :Unite -buffer-name=buffer buffer
nnoremap [unite]o :Unite -no-split -auto-preview outline
nnoremap [unite]l :Unite -no-split -start-insert line
```

* Reproducable ways from Vim starting

 0. startup vim.
 1. execute any Unite command
 2. error messages are shown

**Comment by Shougo** [comment]
Thanks.  I will check the .vimrc.

**Comment by Shougo** [comment]
@rafaelnp I tested it.  But I cannot reproduce it.
You should reinstall unite.vim.  And you should check extra script by `:scriptnames` command.

**Comment by Shougo** [comment]
No response.
