### ISSUE TITLE
-quick-match : letters are not shown, "Cancelled" is shown

### ISSUE THREAD

**Issue by yzatod** [Shougo/unite.vim#770]
Hello.
I would like to use  -quick-match in buffer search
nnoremap [unite]b :Unite buffer -quick-match <cr>
but the letters for the selection are not shown.  instead command line shows red Cancelled.

Yanking 
nnoremap [unite]y :Unite history/yank -quick-match<cr>
works fine, letters are shown.

please help,
yzatod

**Comment by beardedprojamz** [comment]
* Problems summary

I have the exact same problem. My current unite.vim commit is at c300a76a6af48265d783e0626eafb84e680d6bb3. The problem doesn't exist if I rollback to cce4b6c222cdb0b88b72af1e81f2001a63ce1bc3 (before quick match was edited).

* Expected

I expected for the quick match behavior not to display 'Canceled' after choosing the quick match.

* Environment Information
 * OS: Mac OS X 10.10.1 (Yosemite)
 * Vim version: 7.4.258 (homebrew macvim)
 * Has Lua: Yes

* Minimal vimrc less than 50 lines

`~/testrc`

```
" Your vimrc
set nocompatible

set runtimepath+=~/.vim/bundle/unite.vim/
```

* Reproducible way from Vim starting

 0. vim -u testrc
 1. :Unite buffer -quick-match
 2. select 'a'
 3. 'Canceled' message appears and the Unite window stays open

* Screen shot

![unite vim bug](https://cloud.githubusercontent.com/assets/877908/5971096/0cc038ea-a804-11e4-9883-2f83b5225ea6.gif)
