### ISSUE TITLE
Default insert mode mappings are not completion friendly

### ISSUE THREAD

**Issue by DXist** [Shougo/unite.vim#777]
DISCLAIMER: I switched to unite from CtrlP and used <Tab> to complete file directories.

Unite maps `<tab>`, `<c-n>` and `<c-p>` by default and makes unexpected actions when I try to use completion.

Completion is very useful for files/new source when one need to quickly type directory prefix for new file.
Probably it can be solved providing an example of unite configuration for filename completion support.

**Comment by tecfu** [comment]
@Shougo Thanks for recommending: 

```
imap <buffer> <Tab>   <Plug>SuperTabForward
```
I also tried 

```
imap <buffer> <S-Tab>   <Plug>SuperTabBackward
```
but this immediately exits Unite. Can you think of a quick workaround?

**Comment by Shougo** [comment]
I don't know SuperTab behavior sorry.

**Comment by tecfu** [comment]
[1] Supertab's \<S-Tab> command immediately exits Unite given the following conditions:

```
nmap <buffer> <ESC> <Plug>(unite_exit)
imap <buffer> <ESC> <Plug>(unite_exit)
```
I simply commented these out and Supertab's <Tab> and <S-Tab> functions both work fine for me. I now use the following to exit Unite: 

```
imap <buffer> qq <Plug>(unite_exit)
```

[2] <b>Thank you</b> for the quick reply and for all of your <b>incredible work</b>, Shougo. Your hard work makes my life better every day.
