### ISSUE TITLE
matcher_project_ignore_files does not seem to do anything

### ISSUE THREAD

**Issue by svenstaro** [Shougo/unite.vim#802]
So I have this in my .vimrc:

`call unite#custom#source('file_rec', 'matchers', 'matcher_project_ignore_files')`

Then in my project which has a .gitignore with lots of entries I start vim and type `:Unite file_rec`.

The output shows many of the ignored subdirs in the outdir. I think this is the wrong behavior.

**Comment by balta2ar** [comment]
Confirm that.

Steps to reproduce:

```
$ git clone git://git.samba.org/rsync.git
$ mkdir build
$ cp -r rsync build
$ echo "build" > .uniteignore
$ echo "build*" >> .uniteignore
$ echo "build/*" >> .uniteignore
$ cat .uniteignore 
build
build*
build/*
$ cat .vimrc
if has('vim_starting')
   set nocompatible               " Be iMproved
   set runtimepath+=~/.vim/bundle/neobundle.vim/
endif

call neobundle#rc(expand('~/.vim/bundle/'))
NeoBundleFetch 'Shougo/neobundle.vim'
NeoBundle 'Shougo/vimproc'
NeoBundle 'Shougo/unite.vim'

call unite#custom#source('file_rec/async', 'matchers',
  \ ['matcher_project_ignore_files', 'matcher_default'])
$ ls -1a
.
..
build
rsync
.uniteignore
.vimrc
$ vim -u .vimrc
:Unite -buffer-name=files -start-insert file_rec/async
type: syscall
```

After that I see the following. `build` is not excluded:
```
syscall
 build/syscall.c
 rsync/syscall.c
```

Could you also add an example configuration with option to documentation?

**Comment by Shougo** [comment]
Confirmed.

`build/*` pattern does not ignore the files in the subdirectories.

You should use `build/**`.
I think .gitignore have same spec.
If I have a mistake, please correct me.

**Comment by Shougo** [comment]
```
syscall
 build/rsync/syscall.c
 rsync/syscall.c
```

is correct.

**Comment by balta2ar** [comment]
I tried putting simple "build" (without asterisks and slashes) into `.hgignore` and `.gitignore`. Both hg and git understand it and filter out build directory.

**Comment by Shougo** [comment]
Yes.  It filters "build" directory.  But it does not filter the subdirectory files in "build".
I will check the behavior.

**Comment by Shougo** [comment]
I added "build/" pattern support.
