### ISSUE TITLE
Regression in grep window look and feel

### ISSUE THREAD

**Issue by balta2ar** [Shougo/unite.vim#815]
There has been a lot of changes to grep window during the last two weeks. Tastes differ, but there are certain new things that seem to have degraded.

Here is how it looked two weeks ago:
ccafd5f (Fix #620 implement buffers and args features in line source)
![ccafd5f](http://i.imgur.com/5oUiPIY.png)

Here is how it looks now:
bccb695 (Fix #814 sort problem in grep source)
![bccb695](http://i.imgur.com/GB2Sy7k.png)

I did not change anything in my configuration to take these screenshots, I just did `git checkout <rev>` to two different revisions.

Here is a list from most annoying to less annoying:
1. In Insert mode a single white space in inserted right after the cursor in the beginning of the current line. It shifts current line to the right when you go up and down and this is **very** distracting. (this bug exists in other sources, e.g. file_rec)
2. File names are not colored anymore.
3. There is space between line numbers and file names. I find it more convenient to be the way it was before when they were close.
4. Current line is not highlighted with gray but is underlined now (maybe this is configurable?)

**Comment by Shougo** [comment]
> 4. Current line is not highlighted with gray but is underlined now (maybe this is configurable?)

It is feature.

https://github.com/Shougo/unite.vim/issues/803

**Comment by Shougo** [comment]
Fixed the problem.  Please check it.

> I assume this was intentional, but yeah, it drives me crazy too. It's a bit too ambitious as a default behavior. An indicator (e.g., >) in the left column column would be more agreeable.

I don't understand the problem.

**Comment by balta2ar** [comment]
Thank you, @Shougo! Everything is great now.
