### ISSUE TITLE
Weird behaviour when using "-no-quit -auto-preview -no-split"

### ISSUE THREAD

**Issue by JCavallo** [Shougo/unite.vim#816]
When using "Unite grep" with "-no-quit -auto-preview -no-split" flags set, the result feels weird.

What I am trying to achieve is to grep for a pattern, then :

  - Open the candidates in the current split
  - Preview the selected candidate in the current split, still keeping the focus on the unite buffer
  - Hitting enter to switch to the current selected candidate, without closing the unite buffer

What feels wrong :

  - When I hit "Enter" to switch to the currently selected buffer split, the buffer is still a "Preview" buffer, which is linked to the unite window. So if I :UniteClose, the selected buffer split is also closed.

I tried a few option combinations on the :Unite grep command, but none that behaved as I want to. I am not sure if there is a bug somewhere, or if the behaviour I am trying to achieve is not possible.

Environment : 
Linux Mint 17 / KDE / Konsole + bash + tmux
Vim 7.4.537

Vimrc : 

```VimL
if has('vim_starting')
	set nocompatible
	set runtimepath+=~/.cache/neobundle/unite.vim/
	set runtimepath+=~/.cache/neobundle/vimproc.vim/
endif
```

How to reproduce : 

1.   Open an existing file
2.   :Unite grep -buffer-name=grep -no-split -no-quit -auto-preview
3.   Input something which will match
4.    browse candidates in the Unite buffer => The preview window will replace the buffer opened at 2
5.    Hit enter for a candidate => The focus switches to the preview window
6.   :UniteClose => All buffer are closed

**Comment by Shougo** [comment]
Thanks.  I will check it.

**Comment by Shougo** [comment]
Fixed.

**Comment by JCavallo** [comment]
I do not know if I should reopen this issue or not, I tested with the latest version (which includes your patch), and I am getting the following behaviour:

When opening one of the candidates, the Unite split is resized to half the screen.

```
+---------------+              +---------------+
|               |              |               |
|   Preview     |              |   Candidate   |
|               |       ==>    +---------------+
+---------------+              |               |
|    Unite      |              |     Unite     |
+---------------+              +---------------+

```

Also, when switching back to the unite window, switching to another candidate opens another Preview window (the previously opened candidate being still opened), but opening the candidate replaces the previous candidate.

```
+---------------+              +---------------+
|  Candidate 1  |              |               |
+---------------+              |   Candidate 2 |
|    Preview    |       ==>    +---------------+
+---------------+              |               |
|    Unite      |              |     Unite     |
+---------------+              +---------------+
```

**Comment by Shougo** [comment]
> When opening one of the candidates, the Unite split is resized to half the screen.

It is feature.  You should set `-winheight` option.

> Also, when switching back to the unite window, switching to another candidate opens another Preview window (the previously opened candidate being still opened), but opening the candidate replaces the previous candidate.

It is feature.  To open candidate in another window, you must execute another action like `split`.

**Comment by JCavallo** [comment]
>> When opening one of the candidates, the Unite split is resized to half the screen.

> It is feature. You should set -winheight option.

I tried with -winheight=20 (which is the default valueif I'm right). The height is ok while previewing, but when I open a candidate, the Unite window sizes changes to equalize the split sizes.

>> Also, when switching back to the unite window, switching to another candidate opens another Preview >> window (the previously opened candidate being still opened), but opening the candidate replaces the >> previous candidate.

> It is feature. To open candidate in another window, you must execute another action like split.

I do not want to open in another window. The current behaviour on opening is fine IMO. What is weird is that I would expect the Preview window to replace the Candidate1 when I switch back to the Unite window.

**Comment by Shougo** [comment]
> I tried with -winheight=20 (which is the default valueif I'm right). The height is ok while previewing, but when I open a candidate, the Unite window sizes changes to equalize the split sizes.

OK.  I will fix it.

> I do not want to open in another window. The current behaviour on opening is fine IMO. What is weird is that I would expect the Preview window to replace the Candidate1 when I switch back to the Unite window.

I don't think so.  "-auto-preview" is not the feature.

**Comment by JCavallo** [comment]
>> I tried with -winheight=20 (which is the default valueif I'm right). The height is ok while previewing, but when I open a candidate, the Unite window sizes changes to equalize the split sizes.

> OK. I will fix it.

Do you want that I create another issue ?

**Comment by Shougo** [comment]
Fixed.

**Comment by JCavallo** [comment]
:+1: 

Thank you !
