### ISSUE TITLE
Action list vs start_temporary

### ISSUE THREAD

**Issue by JCavallo** [Shougo/unite.vim#818]
Hi,

I created a custom source, and a custom kind. The custom kind I use has one possible action, which is basically a call to unite#start_temporary(...) .

When I try to call the custom action on a candidate, the behaviour depends on how I make the call. If I use the "default" key (Enter), it works as expected. If I use the action menu on a selected candidate, nothing happens.

So, calls to unite#do_action('my_action') work properly, but using the action list on the current candidate to select the action does nothing (even though the action's function is called).

It would be hard to provide a full reproduction environment, so I would just want to know where to look for a bug :/

Thanks.

**Comment by Shougo** [comment]
Please upload your custom source and kind files.
I will check it.

**Comment by JCavallo** [comment]
You may have a look here : 
https://github.com/JCavallo/tryton-vim/commit/af7a9382bc0bc9a03732dae987e963ba7bafd6ec

The candidates are all gathered properly, my only problem is that calling any action on the tryton_model kind works if the action is the default action (or mapped to a key), but not if I use the action menu on a candidate.

(This is currently WIP, so sry no doc yet. Feel free to ask for more info)

**Comment by Shougo** [comment]
You should use `unite#start_script()` instead of `unite#start_temporary()`.
It may your source error.  You can check it by using another source.

**Comment by JCavallo** [comment]
I tried with unite#start_script, and that changed nothing.

I replace the call to my custom source to one of yours (process), and I had the same behaviour (i.e. works properly when hitting "Enter", but not when using the action menu to select it).

I notice that after using the action menu, the header line of the process sources was echoed : 

[process] USER           PID  %CPU  %MEM               etc...

If you think it may be a setting in my vimrc, you can find my unite relating settings here : 

(If you notice some similarities with yours, it's normal, I build my latest vimrc based on TerryMa's and yours)

https://github.com/JCavallo/dotfiles/blob/master/vim_rc_files/plugins/unite.rc.vim

**Comment by Shougo** [comment]
Unfortunatelly, I cannot try tryton-vim plugin.
Please create minimal .vimrc less than 50 lines and the sample source and kind I can test it.
If it is unite problem, I can reproduce it by other sources.

**Comment by JCavallo** [comment]
I will try to do that.

Btw, I noticed that if I set the is_quit flag of the action to 1, it behaves as expected.

Thanks for your time.

**Comment by Shougo** [comment]
Oh, I get it.  It is feature.  You must set "is_quit" flag to 1.
