### ISSUE TITLE
Do not show Unite window if user canceled request

### ISSUE THREAD

**Issue by balta2ar** [Shougo/unite.vim#819]
Say, I start grep with this command `Unite grep:.:` and press `Enter`. Next, Unite asks me for the Pattern. Now I change my mind and I decide that I don't want to run grep right now. I press `<Esc>` or `<C-c>` to cancel the search request. However, after that Unite shows me empty window without any results, and I need to close this window manually with extra key strokes.

Is it possible to detect early that user canceled request and do not show output window (if we already know that user doesn't want to see it)?

**Comment by Shougo** [comment]
`:Unite grep:.: -auto-quit` or `:Unite grep:.: -no-empty`.

**Comment by balta2ar** [comment]
Thanks, that kinda works but semantics is different for these two use cases. If I cancel the search, I should not see Unite window. However, if I search for a string that cannot be found, I should see Unite window but it should be empty.

Anyway, I guess I can live with `-no-empty`.

**Comment by Shougo** [comment]
Unfortunatelly, unite cannot know cancel or empty candidates.
