### ISSUE TITLE
prompt の変更を行いたい

### ISSUE THREAD

**Issue by osyo-manga** [Shougo/unite.vim#820]
以前はコマンド引数の `-prompt=` で変更できたと思うのですが、最新版では動作しなくなっているようです。
最新版で prompt を変更したい場合はどうすればよいのでしょうか。

**Comment by Shougo** [comment]
現在は出来ません。後ほど再実装しますのでしばらくお待ちください。

**Comment by osyo-manga** [comment]
了解です。

**Comment by Shougo** [comment]
一応機能を実装しました。

**Comment by itchyny** [comment]
オプションで設定するにはどうすればいいのですか。

**Comment by Shougo** [comment]
`:Unite -prompt=> file`

**Comment by Shougo** [comment]
制限事項

* 二文字幅までしか認識せず、一文字のプロンプトも強制的に二文字幅が確保されます
* 下プロンプトで使うと表示がちらつきます

**Comment by itchyny** [comment]
間違えた、グローバル変数はないんですか。

**Comment by Shougo** [comment]
> 間違えた、グローバル変数はないんですか。 (コマンドの引数じゃなくて。)

グローバル変数は廃止されました。default_context の prompt を変更してください。

> 長いこと使ってきたUIが変わると違和感が。

違和感があるのも承知していますが、変更した理由もあるので……。

**Comment by itchyny** [comment]
その理由が知りたいです。

**Comment by frace** [comment]
Thank you for re-implementing this! ^^

**Comment by Shougo** [comment]
I'm re-implementing the feature in prompt branch.
You can test it.

https://github.com/Shougo/unite.vim/tree/prompt

**Comment by osyo-manga** [comment]
> 一応機能を実装しました。

遅れましたが、こちらでも確認しました。
ありがとうございます。

**Comment by Shougo** [comment]
prompt ブランチをマージしました。ご確認ください。

**Comment by itchyny** [comment]
:100:
