### ISSUE TITLE
プロンプトの入力文字の頭と候補の頭が一文字分ずれていて見難い

### ISSUE THREAD

**Issue by itchyny** [Shougo/unite.vim#821]
![screen shot 2015-01-14 at 8 33 26 pm](https://cloud.githubusercontent.com/assets/375258/5738181/bfb5b4ea-9c2c-11e4-9637-948bfe24e36c.png)
![screen shot 2015-01-14 at 8 35 40 pm](https://cloud.githubusercontent.com/assets/375258/5738208/e9d3f868-9c2c-11e4-9608-0c2dcc1ffccb.png)
頭は揃っていて欲しいです。

**Comment by itchyny** [comment]
と言うかプロンプトも候補も頭のスペースをとっちゃえばいいかもしれないです。(未確認)

**Comment by itchyny** [comment]
プロンプトも候補も頭のスペースをとっちゃえばいいかもしれないです。

候補の頭にあった「- 」や、複数選択はsignにしてはどうでしょう。

**Comment by Shougo** [comment]
> プロンプトも候補も頭のスペースをとっちゃえばいいかもしれないです。

これは考えましたが、現在の実装上 例えば quick match を使うとやはりずれることになるので無理です。

> 候補の頭にあった「- 」や、複数選択はsignにしてはどうでしょう。

これは現在 conceal になっています。プロンプトが空の時のことを考えると、sign にするつもりはないです。unite バッファの conceal が無効になっていませんか。確認してください。

**Comment by itchyny** [comment]
そもそもどうしてプロンプト文字をsignにしてしまったのですか

**Comment by itchyny** [comment]
次の思いがあります。

1. プロンプト文字をグローバル変数で設定したい。
2. 候補のアイコンをグローバル変数で設定したい。
3. プロンプト文字と候補のアイコンは揃っていて欲しい。
4. プロンプトの入力の最初と候補の最初は揃っていて欲しい。

**Comment by itchyny** [comment]
ちなみに確認ですが、デフォルトの候補アイコンは" "ですよね？ (見えないけど)

**Comment by Shougo** [comment]
> ちなみに確認ですが、デフォルトの候補アイコンは" "ですよね？ (見えないけど)

はい。

**Comment by Shougo** [comment]
> 候補のアイコンをグローバル変数で設定したい。

残念ながらこれはできません。アイコンは conceal すること前提となっているからです。

> プロンプト文字をグローバル変数で設定したい。

グローバル変数はサポートしていません。default_context を設定してください。

```vim
" Default configuration.
let default_context = {
      \ 'vertical' : 0,
      \ 'short_source_names' : 1,
      \ 'prompt' : '',
      \ }
call unite#custom#profile('default', 'context', default_context)
```

**Comment by Shougo** [comment]
> そもそもどうしてプロンプト文字をsignにしてしまったのですか

ここに書くのが適当かどうか分かりませんが、一応理由を説明しておきます。

* 既存のプロンプト文字列は実装が複雑になっていた
* 編集中にプロンプトを破壊してしまうことができるのが問題となった
* プロンプト文字列がなくても実装できる目処が経った
* 候補バッファの幅を最適化した結果、候補とプロンプトがずれるようになった

sign だと既存のバッファに干渉しないので最適だったのです。

**Comment by itchyny** [comment]
> 編集中にプロンプトを破壊してしまうことができるのが問題となった

のに一つのスペースを置いているのは自分には理解できなくて、
https://github.com/Shougo/unite.vim/blob/master/autoload/unite/helper.vim#L196
https://github.com/Shougo/unite.vim/blob/master/autoload/unite/view.vim#L38
このスペースが問題なく動いているならプロンプトをsignにする必要性は理解できないです。

        diff --git a/autoload/unite/helper.vim b/autoload/unite/helper.vim
        index fcf1042..2c6e3c9 100644
        --- a/autoload/unite/helper.vim
        +++ b/autoload/unite/helper.vim
        @@ -188,17 +188,17 @@ function! unite#helper#get_input(...) "{{{
           endif

           " Prompt check.
        -  if getline(unite.prompt_linenr)[:0] != ' '
        +  if getline(unite.prompt_linenr)[:1] != '> '
             let modifiable_save = &l:modifiable
             setlocal modifiable

             " Restore prompt.
        -    call setline(unite.prompt_linenr, ' ')
        +    call setline(unite.prompt_linenr, '> ')

             let &l:modifiable = modifiable_save
           endif

        -  return getline(unite.prompt_linenr)[1:]
        +  return getline(unite.prompt_linenr)[2:]
         endfunction"}}}

         function! unite#helper#get_source_names(sources) "{{{
        diff --git a/autoload/unite/view.vim b/autoload/unite/view.vim
        index 81669b0..8408dba 100644
        --- a/autoload/unite/view.vim
        +++ b/autoload/unite/view.vim
        @@ -35,7 +35,7 @@ function! unite#view#_redraw_prompt() "{{{
           let modifiable_save = &l:modifiable
           try
             setlocal modifiable
        -    call setline(unite.prompt_linenr, ' ' . unite.context.input)
        +    call setline(unite.prompt_linenr, '> ' . unite.context.input)

             if unite.context.prompt != ''
               execute printf(

として

      call unite#custom#profile('default', 'context', { 'prompt_direction': 'top',
        \ 'prompt': '', 'candidate_icon': '-' })

こうした方が私はUIが好きなのです。(これがプロンプトだったはずなのだけど)

**Comment by Shougo** [comment]
> のに一つのスペースを置いているのは自分には理解できなくて、

このスペースは本来のプロンプトというより、画面端にスペースがないと入力文字列が見づらいので付けているだけです。

**Comment by itchyny** [comment]
> 編集中にプロンプトを破壊してしまうことができるのが問題となった

のにそのスペースが破壊されない自信があるのがよく分からないです。

**Comment by Shougo** [comment]
では、こうしてみました。

https://github.com/Shougo/unite.vim/tree/prompt

プロンプトと候補のスペースを廃止しています。スペースが破壊されることはありません。

**Comment by itchyny** [comment]
その実装は上のほうで私が言った

> プロンプトも候補も頭のスペースをとっちゃえばいいかもしれないです。

だと思いますが、その実装のほうが私はいいと思います。そうなると話が最初に戻って

> 候補の頭にあった「- 」や、複数選択はsignにしてはどうでしょう。

という話になってしまいます。

**Comment by Shougo** [comment]
https://github.com/Shougo/unite.vim/tree/prompt

sign を使わないように直しました。

**Comment by itchyny** [comment]
デフォルトで
![screen shot 2015-01-15 at 12 13 11 pm](https://cloud.githubusercontent.com/assets/375258/5751992/416e5b9e-9cb0-11e4-91db-9a14787a9ce7.png)
となりました。
ここで、
```vim
  call unite#custom#profile('default', 'context', {
        \ 'prompt': '> ',
        \ })
```
とすると
![screen shot 2015-01-15 at 12 14 07 pm](https://cloud.githubusercontent.com/assets/375258/5751997/51f9c430-9cb0-11e4-9cb8-bc7657653176.png)
となりますが、マークしても
![screen shot 2015-01-15 at 12 14 44 pm](https://cloud.githubusercontent.com/assets/375258/5752001/60b86cd8-9cb0-11e4-9502-ac45e3a43f6d.png)
「*」が見えません。
更に、候補のアイコンも変更しようとして
```vim
  call unite#custom#profile('default', 'context', {
        \ 'prompt': '> ',
        \ 'candidate_icon': '- ',
        \ })
```
としても、
![screen shot 2015-01-15 at 12 15 25 pm](https://cloud.githubusercontent.com/assets/375258/5752008/7564e67a-9cb0-11e4-998b-2c2b12f547a7.png)
変化がありません。

**Comment by Shougo** [comment]
修正しました。 `:Unite -no-hide-icon` を使ってください。

**Comment by itchyny** [comment]
修正ありがとうございます。
```vim
call unite#custom#profile('default', 'context', {
      \ 'prompt_direction': 'top',
      \ 'prompt': '> ',
      \ 'candidate_icon': '- ',
      \ 'hide_icon': 0 })
```
で自分の思い通りのUIになりました。

**Comment by Shougo** [comment]
はい。おそらく、従来の機能よりもアイコンとプロンプトに関して柔軟に設定ができるようになったと思います。

**Comment by itchyny** [comment]
hide-iconがデフォルト1な理由はありますか？

**Comment by Shougo** [comment]
アイコンを隠して見た目をスッキリとさせるためです。
