### ISSUE TITLE
How to save file_rec buffer to session?

### ISSUE THREAD

**Issue by sbutts** [Shougo/unite.vim#822]
I work on projects with a large number of files so building the cache takes awhile, but once it's built using UniteResume works perfectly. The only problem is that the buffer is lost when a new vim instance is started, even when the session is restored. Is it possible to save the file_rec buffer to the session and be able to restore it later?

**Comment by Shougo** [comment]
Nothing.  Unite.vim buffer is not supported for the session.
Sorry.
