### ISSUE TITLE
<Plug>(unite_disable_max_candidates) after <Plug>(unite_restart) prompts for target with file_rec source

### ISSUE THREAD

**Issue by kballard** [Shougo/unite.vim#826]
* Problems summary

When using the `file_rec` (or `file_rec/async`) source, if I press the binding for `<Plug>(unite_disable_max_candidates)` after having already restarted Unite at least once with `<Plug>(unite_restart)`, I get prompted for a new Target, like I normally do with `<Plug>(unite_restart)`.

* Expected

It shouldn't be prompting me for a new target. I tried a few other sources without seeing this problem, so far I've only found it with `file_rec` and `file_rec/async`.

* Environment Information
 * OS: OS X 10.10.1 (14B25)
 * Vim version: Vim 7.4.258

* Minimal vimrc less than 50 lines

```
set nocompatible
set runtimepath+=~/.vim/neobundle/unite.vim
```

* Reproducable ways from Vim starting

 1. Startup vim: `vim -u minimal.vimrc`
 2. `:Unite file_rec`
 3. Press `<C-r>`
 4. Accept or cancel the target prompt
 5. Press `M`

**Comment by Shougo** [comment]
OK.  I will check the issue.
