### ISSUE TITLE
No Unite candidate highlighting since f4c8aa5

### ISSUE THREAD

**Issue by kopischke** [Shougo/unite.vim#827]
* **Problems summary**

  Candidates in Unite buffers are not highlighted anymore since commit https://github.com/Shougo/unite.vim/commit/f4c8aa5e563ae321729df3c717083ba79d0b8b5d (according to my `git-bisect` run).

* **Expected**

  Unite candidates should be highlighted according to their source.

* **Environment Information**
 * OS: OX X 10.10.1, German locale
 * Vim version: MacVim 7.4-patch579

* **Minimal vimrc less than 50 lines**

  ```vim
  set nocompatible

  " Minimal bundles to load
  let $VIMBUNDLES = expand('~').'/.config/vim/bundles'
  set rtp+=$VIMBUNDLES/unite.vim/

  " Minimal config
  filetype plugin indent on
  syntax enable
  ```

* **How to reproduce**

 0. start Vim with a minimal `.vimrc` equivalent to the above: `vim -u /path/to/minimal/vimrc`
 1. edit two files (any files, doesn’t matter)
 2. `:Unite buffer`

* **Screen shot**

  ![bildschirmfoto 2015-01-20 um 12 45 53](https://cloud.githubusercontent.com/assets/80906/5816611/4dd459a6-a0a2-11e4-8bd2-8a2a6d51c5b6.png)

**Comment by Shougo** [comment]
Fixed.

**Comment by kopischke** [comment]
Thanks!
