### ISSUE TITLE
Request: Add a sorter for most recently used

### ISSUE THREAD

**Issue by danielfalk** [Shougo/unite.vim#828]
It would be great if there were a way to sort file_rec results by most recently used.  This would be especially handy to use as a secondary sort, after selecta.

**Comment by Shougo** [comment]
I think neomru creates new sorter is better.

**Comment by danielfalk** [comment]
I cannot find any new sorters created by neomru.  I've looked through the documentation of it.  But maybe you could tell me if it's possible for me to list file_rec results ordered first by match, then by recent use:  

`call unite#custom#source('file_rec', 'filters', ['sorter_selecta', 'sorter_recent'])`

Does neomru create a new filter that allows for this?

Thanks

**Comment by Shougo** [comment]
> I cannot find any new sorters created by neomru. I've looked through the documentation of it.

Yes.  It is not exists yet.  To create new mru sorter, "sorter_neomru" is better.  I think.

```vim
call unite#custom#source('file_rec', 'filters', ['sorter_recent', 'sorter_selecta'])
```

is better.   But "sorter_selecta" is Pull Requested feature.  I don't know it can mix.

https://github.com/Shougo/unite.vim/pull/544
