### ISSUE TITLE
Weird background in Unite views

### ISSUE THREAD

**Issue by tbastos** [Shougo/unite.vim#829]
All of my Unite views have this weird dark-red background in "empty" areas:

![unite_weird_bg2](https://cloud.githubusercontent.com/assets/150480/5833446/2f8dc2a8-a14b-11e4-823f-17c114920d15.jpg)

It happens in every colorscheme. I tried changing many settings but nothing fixed it.
I'm relatively new to Vim so I have no idea how to debug this. Any hints?

Thanks!

**Comment by itchyny** [comment]
You should disable trailing-whitespace plugin.
```vim
let g:extra_whitespace_ignored_filetypes = [ 'unite' ]
```

**Comment by tbastos** [comment]
Many thanks! Sorry for the noise... maybe this should be added to the FAQ?
