### ISSUE TITLE
ignore_globs doesn't appear to be ignoring anything

### ISSUE THREAD

**Issue by dwb** [Shougo/unite.vim#830]
`ignore_globs` doesn't ignore patterns expected.

## Expected

When I set `ignore_globs` to, say, a file `install.sh`, it should be hidden from the results.

## Environment Information
OS: Mac OS X Yosemite
Unite version: f7797945465c8fcb49d8519d1e122e680ae673a8
Vim version: from [Homebrew](http://brew.sh).
```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Dec  4 2014 17:35:04)
MacOS X (unix) version
Included patches: 1-488
Compiled by Homebrew
Huge version without GUI.  Features included (+) or not (-):
+acl             +cscope          +folding         +menu            +netbeans_intg   -sniff           +virtualedit
+arabic          +cursorbind      -footer          +mksession       +path_extra      +startuptime     +visual
+autocmd         +cursorshape     +fork()          +modify_fname    +perl            +statusline      +visualextra
-balloon_eval    +dialog_con      -gettext         +mouse           +persistent_undo -sun_workshop    +viminfo
-browse          +diff            -hangul_input    -mouseshape      +postscript      +syntax          +vreplace
++builtin_terms  +digraphs        +iconv           +mouse_dec       +printer         +tag_binary      +wildignore
+byte_offset     -dnd             +insert_expand   -mouse_gpm       +profile         +tag_old_static  +wildmenu
+cindent         -ebcdic          +jumplist        -mouse_jsbterm   +python          -tag_any_white   +windows
-clientserver    +emacs_tags      +keymap          +mouse_netterm   -python3         -tcl             +writebackup
+clipboard       +eval            +langmap         +mouse_sgr       +quickfix        +terminfo        -X11
+cmdline_compl   +ex_extra        +libcall         -mouse_sysmouse  +reltime         +termresponse    -xfontset
+cmdline_hist    +extra_search    +linebreak       +mouse_urxvt     +rightleft       +textobjects     -xim
+cmdline_info    +farsi           +lispindent      +mouse_xterm     +ruby            +title           -xsmp
+comments        +file_in_path    +listcmds        +multi_byte      +scrollbind      -toolbar         -xterm_clipboard
+conceal         +find_in_path    +localmap        +multi_lang      +signs           +user_commands   -xterm_save
+cryptv          +float           -lua             -mzscheme        +smartindent     +vertsplit       -xpm
```

## .vimrc

```
set nocompatible

set runtimepath+=~/.vim/plugged/unite.vim

call unite#custom#source('file_rec', 'ignore_globs', ['install.sh'])
```

Nothing else being autoloaded.

## Steps

 0. Start vim
 1. Run `:Unite file_rec`
 2. `install.sh` shows

## Also

Modifying the `unite#custom#source` line to the following hides the file as I'd expect:

```
call unite#custom#source('file_rec', 'ignore_pattern', 'install\.sh')
```

Sorry if I'm missing something obvious but I've been fiddling with this for a while!

**Comment by Shougo** [comment]
I tried.  But I cannot reproduce the problem.
"ignore_globs" works properly.

**Comment by dwb** [comment]
That's odd; I stripped config down to the bare minimum. Check my `:version` output: I noticed it doesn't include `lua`: could that be an issue?

**Comment by itchyny** [comment]
I could reproduce the problem with a vim without lua. The problem exists at the code https://github.com/Shougo/unite.vim/blob/master/autoload/unite/filters.vim#L224, the function `unite#filters#vim_filter_patterns`.
The variables are
```
pattern = '/install\.sh$'
white = ''
```
Therefore if `action__path` is `/some/path/install.sh`, `get(v:val, 'action__path', v:val.word) =~? white` is `1` thus it is included to the candidates. Shougo, you seem to be in a hurry to close all the issues but you should not miss the polite issue report like this; you'll find new bugs.

**Comment by Shougo** [comment]
> Shougo, you seem to be in a hurry to close all the issues but you should not miss a polite issue report like this; you'll find new bugs. Otherwise your resolute replies will wither issue reporters.

Yes.  To close the issues may too hurry.   But the reporter may be gone.
I want to clean the repository issues.

OK.  If I cannot reproduce the problem in minimal environment, I will wait it in one week.
But if the reporter is no response, I will close the issue.

**Comment by dwb** [comment]
@Shougo Thanks, your recent commit fixed this for me :)

I think maybe just make doubly sure you're trying to reproduce with the exact same vim build as reported in the issue: I posted full feature flag information as I suspected it might matter.

Thanks for responding so quickly anyway, and @itchyny, thanks for the extra analysis!

**Comment by Shougo** [comment]
I will improve the issue template later.

**Comment by Shougo** [comment]
I improved the issue template.  if_lua information is needed.
