### ISSUE TITLE
matcher_project_ignore_files shows full path

### ISSUE THREAD

**Issue by LukeMauldin** [Shougo/unite.vim#836]
When I set the variable matcher_project_ignore_files like: 
call unite#custom#source('file_rec,file_rec/async', 'matchers', ['matcher_project_ignore_files', 'matcher_default'])

When I do :Unite file then all of the results are returned with the full path, so /Users/lmauldin/.../projectdir/filename
When I comment out the line to use matcher_project_ignore_files then the results are returned like projectdir/filename

**Comment by Shougo** [comment]
It is feature.

Source rec set matchers like this:

```
" Source rec.
let s:source_file_rec = {
      \ 'name' : 'file_rec',
      \ 'description' : 'candidates from directory by recursive',
      \ 'hooks' : {},
      \ 'default_kind' : 'file',
      \ 'max_candidates' : 50,
      \ 'ignore_globs' : [
      \         '.', '*~', '*.o', '*.exe', '*.bak',
      \         'DS_Store', '*.pyc', '*.sw[po]', '*.class',
      \         '.hg/**', '.git/**', '.bzr/**', '.svn/**',
      \         'tags', 'tags-*'
      \ ],
      \ 'matchers' : [ 'converter_relative_word',
      \                'matcher_default', 'matcher_hide_hidden_files' ],
      \ }
```

'converter_relative_word' is convertion.
If you set matchers, this feature is disabled.

You should use like this:

```vim
call unite#custom#source('file_rec,file_rec/async', 'matchers', ['converter_relative_word', 'matcher_project_ignore_files', 'matcher_default'])
```

**Comment by LukeMauldin** [comment]
You are correct, that converted the matches to the correct format.  However, now if I uncomment the line below for matcher_project_ignore_files, then ':Unite file_rec/async' is much slower than before.  This is on a Git project with 3000 files.  

"Map Unite
"call unite#custom_source('file_rec/async,file_mru,file,buffer,grep', 'max_candidates', 0)
"let g:unite_source_rec_async_command="find . -follow -type f"
call unite#custom#source('file_rec,file_rec/async,file_mru,file,buffer,grep', 'max_candidates', 0)
call unite#custom#source('file_rec,file_rec/async,file_mru,file,grep',
      \ 'ignore_pattern', join([
      \ '\.git/',
      \ 'bootstrap/',
      \ 'node_modules/',
      \ 'app/assets/vendor',
      \ 'app/storage',
      \ 'docs/',
      \ 'vendor/',
      \ '\.idea/',
      \ '\.cache/',
      \ '\.atom/',
      \ '\.codeintel/',
      \ ], '\|'))
"call unite#custom#source('file_rec,file_rec/async', 'matchers', ['converter_relative_word', 'matcher_project_ignore_files', 'matcher_default'])
call unite#filters#matcher_default#use(['matcher_fuzzy'])
call unite#filters#sorter_default#use(['sorter_rank'])
let g:unite_source_rec_max_cache_files = 0
let g:unite_source_history_yank_enable = 1
nnoremap <Leader>uf :Unite file_rec/async:!<CR>
nnoremap <Leader>ub :Unite buffer<CR>
nnoremap <Leader>ur :Unite file_mru<CR>
nnoremap <Leader>uo :Unite outline<CR>

" Use ag in unite grep source.
let g:unite_source_grep_command = 'ag'
let g:unite_source_grep_default_opts =
            \ '-i --line-numbers --nocolor --nogroup --hidden --ignore ' .
            \  '''.hg'' --ignore ''.svn'' --ignore ''.git'' --ignore ''.bzr'''
let g:unite_source_grep_recursive_opt = ''

**Comment by Shougo** [comment]
> You are correct, that converted the matches to the correct format. However, now if I uncomment the line below for matcher_project_ignore_files, then ':Unite file_rec/async' is much slower than before. This is on a Git project with 3000 files. 

It is feature.  Because, it is project ignore filter cost.
You should filter files by ag command instead of unite.

**Comment by LukeMauldin** [comment]
How would I filter based on ag instead?

**Comment by Shougo** [comment]
" Using ag as recursive command.
		let g:unite_source_rec_async_command =
                \ 'ag --follow --nocolor --nogroup --hidden -g ""'

But I think to use "file_rec/git" source is better.

**Comment by LukeMauldin** [comment]
Is there any way to change the behavior of file_rec/git to not include
results from git repositories underneath the root.  Example:

/root (app lives here and this is a git repository)
     /vendor
         /dependencyA (also a git repository)

If I have a file open in the /root of my project, and I use "file_rec/git",
it also includes records from dependencyA.  I would want to exclude
dependencyA from the results.

**Comment by Shougo** [comment]
You can use `git ls-files` arguments for it.

git ls-files [-z] [-t] [-v]
                       (--[cached|deleted|others|ignored|stage|unmerged|killed|modified])*
                       (-[c|d|o|i|s|u|k|m])*
                       [-x <pattern>|--exclude=<pattern>]
                       [-X <file>|--exclude-from=<file>]
                       [--exclude-per-directory=<file>]
                       [--exclude-standard]
                       [--error-unmatch] [--with-tree=<tree-ish>]
                       [--full-name] [--abbrev] [--] [<file>...]
