### ISSUE TITLE
-quick-match buffer does not work

### ISSUE THREAD

**Issue by mjirik** [Shougo/unite.vim#837]
* :Unite -quick-match buffer does not work. Key shortcut is opening other buffer then expected. 

* Ubuntu
 * OS:
 * Vim version: 7.4

* How to reproduce

 0. startup vim (Write with option arguments if necessary).
 1. open few buffers
 2. :Unite -quick-match buffer
 3. press 's' for example. Vim will open wrong buffer

**Comment by makedonian** [comment]
I'm seeing the same thing. Basically, issue #592 has come back again

**Comment by m42e** [comment]
Same here, 
 * Vim 7.4.182
 * OS: Win/Cygwin

**Comment by liujoey** [comment]
Have the same issue here in Ubuntu. The short cut letters are one shift to below, just as the above screenshots, when `s` "marked" `3.txt`, but when I hit `s` it actually opens `2.txt`

**Comment by Shougo** [comment]
Thank you.  Fixed.

**Comment by nkalvi** [comment]
With
```
let g:unite_enable_start_insert = 1
```

quick match is still selecting the one before the selected letter. I have the latest unite.vim.

**Comment by Shougo** [comment]
It is already reported.

https://github.com/Shougo/unite.vim/issues/843

**Comment by nkalvi** [comment]
Thanks. I just wanted to let you know, in my case, it works as expected when 
g:unite_enable_start_insert = 0; I thought it might be helpful.
