### ISSUE TITLE
cannot remove or move cursor to the first character entered in filter

### ISSUE THREAD

**Issue by tex** [Shougo/unite.vim#838]
:Unite file_rec<CR>
i
FileIWantToSee

Then I cannot move cursor to the F character. I cannot even remove it with backspace. It only scrolls ower ileIWantToSee.

**Comment by Shougo** [comment]
> Then I cannot move cursor to the F character. I cannot even remove it with backspace. It only scrolls ower ileIWantToSee.

Please explain more key strokes concretely.
Input "FielWantToSee" is OK.

**Comment by Shougo** [comment]
Please upload minimal .vimrc.

https://github.com/Shougo/unite.vim/issues/584

**Comment by tex** [comment]
Minimal .vimrc:
  set nocompatible
  set runtimepath+=~/.vim/bundle/unite.vim

vim
:Unite file_rec<CR>
i  (to insert mode)
File1

Now with left arrow key to get cursor to F. You can't. It scrolls ower ile1. And now you even can't backspace to delete any of File1. You could that before you hit left arrow key.

**Comment by tex** [comment]
Interesting about the backspace. If you delete any char with delete key, you can again delete chars with backspace.

**Comment by Shougo** [comment]
OK.  I get it.  I will check it.

**Comment by tex** [comment]
my vim is 7.4.580

**Comment by tex** [comment]
The fix works. Thank you very much!
