### ISSUE TITLE
Run line source with narrowed search

### ISSUE THREAD

**Issue by WscriChy** [Shougo/unite.vim#840]
I tried with

     Unite -input="<C-R>"" line<Cr>

But if there are multiple words in the register, tan it issues error about non-existing  source which is all the words after the first one in the register. What do I do wrong?

**Comment by Shougo** [comment]
You must escape ` ` and `\` characters in `<C-r>`.

```
Unite -input=<C-R>=escape(@", ' \')<CR> line<Cr>
```
