### ISSUE TITLE
UniteWithProjectDir show absolute/full path when used in directories below project root

### ISSUE THREAD

**Issue by albertnetymk** [Shougo/unite.vim#842]
== How to reproduce the problem

```shell
git clone https://github.com/heroku/ruby-rails-sample
cd ruby-rails-sample
cd app
vim
```

Using <c-p> to start unite, see the mapping below, start typing `Gemfile`, and it shows the absolute/full path for Gemfile. However, if I start vim from the project root, it works OK, no absolute/full path. Reading the doc of unite.vim, I assume this is not intended behavior. Hope I understand it correctly.

The part related to unite in my .vimrc:
```vimscript
call unite#filters#converter_default#use(['converter_relative_word'])
call unite#filters#matcher_default#use(['matcher_fuzzy'])
call unite#filters#sorter_default#use(['sorter_length'])
nmap <c-p> :UniteWithProjectDir -start-insert file_rec/async<cr>
```
Using commit 8460f65 of unite.vim.

**Comment by Shougo** [comment]
It is feature.

You are not in `Gemfile` directory(ruby-rails-sample).

**Comment by albertnetymk** [comment]
OK, then is there a way to use relative path when used with `UniteWithProjectDir`? I thought the converter `converter_relative_word` would do the trick; I guess I was wrong.

**Comment by Shougo** [comment]
No.

`fnamemodify(path, ':.')` is same behavior.

**Comment by albertnetymk** [comment]
Just had one looked at the doc for `fnamemodify` and `:.`, specifically. `:.` only works if the file is below the current directory.

Could `:s?pat?sub?` be used to eliminate the absolute/full path prefix? The end result would be:
`Gemfile` instead of `~/github/ruby-rails-sample/Gemfile`. The main argument behind this is that `unite_ignores` would filter out the good candidates as well if some word in the prefix matches one of the ignores.

**Comment by Shougo** [comment]
I don't want to change the behavior.
And it is too complex to implement.

**Comment by Shougo** [comment]
> The main argument behind this is that unite_ignores would filter out the good candidates as well if some word in the prefix matches one of the ignores.

Please explain it more clearly.

**Comment by albertnetymk** [comment]
== How to reproduce the problem

```
git clone https://github.com/heroku/ruby-rails-sample
mkdir test
mv ruby-rails-sample
cd test/ruby-rails-sample
cd app
vim
```
Starting unite using `<c-p>` doesn't provide any candidates, for it's filtered out because of the word `test` in the absolute path.

```
call unite#filters#converter_default#use(['converter_relative_word'])
call unite#filters#matcher_default#use(['matcher_fuzzy'])
call unite#filters#sorter_default#use(['sorter_length'])
nmap <c-p> :UniteWithProjectDir -start-insert file_rec/async<cr>

let s:unite_ignores = ['test']

call unite#custom#source('file_rec,file_rec/async,file_mru,file,buffer,grep',
  \ 'ignore_pattern', unite#get_all_sources('file_rec')['ignore_pattern'] .
  \ join(s:unite_ignores, '\|'))
```
Hope this depicts the problem clearly.

**Comment by Shougo** [comment]
It is feature.  You should use other pattern or ignore_globs.

**Comment by Shougo** [comment]
You should use "./test" pattern.

**Comment by albertnetymk** [comment]
Using commit de3f80a with `let s:unite_ignores = ['./test']` doesn't fix the issue, it seems. I reused the test case from above.

**Comment by Shougo** [comment]
Please explain the behavior.
Yes, "./test" ignores test directory under current directory.

**Comment by albertnetymk** [comment]
Using the same procedure from above:

== How to reproduce the problem

```
git clone https://github.com/heroku/ruby-rails-sample
mkdir test
mv ruby-rails-sample
cd test/ruby-rails-sample
cd app
vim
```
Starting unite using `<c-p>` doesn't provide any candidates.

```
call unite#filters#converter_default#use(['converter_relative_word'])
call unite#filters#matcher_default#use(['matcher_fuzzy'])
call unite#filters#sorter_default#use(['sorter_length'])
nmap <c-p> :UniteWithProjectDir -start-insert file_rec/async<cr>

let s:unite_ignores = ['./test']

call unite#custom#source('file_rec,file_rec/async,file_mru,file,buffer,grep',
  \ 'ignore_pattern', unite#get_all_sources('file_rec')['ignore_pattern'] .
  \ join(s:unite_ignores, '\|'))
```

**Comment by Shougo** [comment]
```vim
let s:unite_ignores = ['./test']
call unite#custom#source('file_rec,file_rec/async,file_mru,file,buffer,grep',
  \ 'ignore_pattern', unite#get_all_sources('file_rec')['ignore_globs'] .
  \ s:unite_ignores)
```

**Comment by albertnetymk** [comment]
```
E730: using List as a String
E116: Invalid arguments for function unite#custom#source
```
My vim is:

VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jan  2 2014 19:39:32)
Included patches: 1-52

**Comment by albertnetymk** [comment]
Hello, fixed it by reading the [doc](https://github.com/Shougo/unite.vim/blob/de3f80a72a6361be0393c3db04379772675c40d1/doc/unite.txt). I should have used `ignore_globs`.

The complete script for reference.
```
call unite#custom#source('file_rec,file_rec/async,file_mru,file,buffer,grep',
  \ 'ignore_globs', unite#get_all_sources('file_rec')['ignore_globs'] +
  \ s:unite_ignores)
```
Thank you very much for the help.

**Comment by Shougo** [comment]
Ah, thanks.  I made the mistake.

**Comment by albertnetymk** [comment]
Hello, it seems that `ignore_globs` doesn't work any more.
Using the same test example with following configuration, unite still provides `test` as candidates. I am not using `./` prefix in this case.

```
let s:unite_ignores = ['test']
call unite#custom#source('file_rec,file_rec/async,file_mru,file,buffer,grep',
  \ 'ignore_globs', unite#get_all_sources('file_rec')['ignore_globs'] +
  \ s:unite_ignores)
```

**Comment by Shougo** [comment]
You must use `./` prefix in this case.

**Comment by albertnetymk** [comment]
It would be great if you could elaborate the meaning of the following:

```
'test'
'./test'
'test/'
'./test/'
```
I am totally confused now.

**Comment by Shougo** [comment]
```
'test' : test file/directory.
'./test' : test file/directory in current directory.
'test/' : test file/directory and the inner files.
'./test/' test file/directory and the inner files in current directory.
```

**Comment by albertnetymk** [comment]
Not sure I understand it correctly:

```
mkdir gittest; cd gittest
git init
touch helllo
mkdir test; cd test; touch world;cd ..
vim
```
Following the above command sequence, I could still see `test/world` among the candidates.
```
let s:unite_ignores = ['./test/']
call unite#custom#source('file_rec,file_rec/async,file_mru,file,buffer,grep',
  \ 'ignore_globs', unite#get_all_sources('file_rec')['ignore_globs'] +
  \ s:unite_ignores)
```

**Comment by Shougo** [comment]
> Following the above command sequence, I could still see test/world among the candidates.

Your current directory is "test".  In test, "test" directory is not found.

**Comment by albertnetymk** [comment]
The output from `tree`:
```
.
├── hello
└── test
    └── world

1 directory, 2 files
```
I am starting vim from the root of this git repo.

The candidates from `unite` is:
```
hello
test/world
```
I expect `test/world` not to show up.

**Comment by Shougo** [comment]
OK.  I will check it.

**Comment by Shougo** [comment]
It is bug.  Fixed.

**Comment by albertnetymk** [comment]
Thank you very much.
