### ISSUE TITLE
Buffer -quick-match odd behavior with Start Insert enabled

### ISSUE THREAD

**Issue by beardedprojamz** [Shougo/unite.vim#843]
* Problems summary

I have a problem with the quick match behavior not always opening up the right buffer or sometimes showing cancelled when it shouldn't.

* Expected

I expected for the quick match behavior not to display 'Canceled' after choosing the quick match or to open the correct buffer corresponding to the letter displayed.

* Environment Information
 * OS: Mac OS X 10.10.1 (Yosemite)
 * Vim version: 7.4.258 (homebrew macvim)
 * Has Lua: Yes

* Minimal vimrc less than 50 lines

`~/testrc`

```
" Your vimrc
set nocompatible
set laststatus=2
set statusline=%f

set runtimepath+=~/.vim/bundle/unite.vim/
call unite#custom#profile('default', 'context', {'start_insert' : 1, 'winheight': 10})
```

* Reproducible way from Vim starting

 0. vim -u testrc
 1. :e foo
 2. :e bar
 3. :e baz
 4. :Unite buffer -quick-match
 5. select 's'
 6. Buffer foo isn't shown (baz still selected)
 7. :Unite buffer -quick-match
 8. select 'd'
 9. 'Canceled' is displayed - maybe because the buffer is already displayed? But the Unite window is still open.

* Screen shot

![unite vim bug](https://cloud.githubusercontent.com/assets/877908/6082447/350ec7ec-ade7-11e4-9fdd-32b686468fd7.gif)

**Comment by Shougo** [comment]
I get it.  It is fatal bug...

**Comment by Shougo** [comment]
Thanks.  Fixed.
