### ISSUE TITLE
vim-haystack integration

### ISSUE THREAD

**Issue by rainerborene** [Shougo/unite.vim#844]
@Shougo is it possible to integrate unite with [vim-haystack](https://github.com/tpope/vim-haystack) plugin?

**Comment by Shougo** [comment]
Unfortunatelly, I don't have time for it.

**Comment by ReneFroger** [comment]
We all completely understand. You did a great job with the Vim plugins. Well done on your tremendous job, Shougo!

**Comment by Shougo** [comment]
You can create matcher for it.
But vim-haystack is not fast...

> Note that the algorithm is slow enough to feel sluggish with larger data sets. You might consider a hybrid approach that uses a different algorithm above a certain number of items.

I don't know what is the advantage.

**Comment by rainerborene** [comment]
Hey Shougo

```viml

function! unite#filters#haystack#define()
  return s:matcher
endfunction

let s:matcher = {
  \ 'name': 'haystack',
  \ 'description': 'fuzzy matching algorithm'
  \ }

function! s:matcher.pattern(input)
  echom input
  return input
endfunction

function! s:matcher.filter(candidates, context)
  echo candidates
  echo context
  return candidates
endfunction
```
I have tried to execute the above code but it seems `unite.vim` does not recognize haystack custom matcher.

**Comment by Shougo** [comment]
I don't want to support it.
