### ISSUE TITLE
caching of grep results

### ISSUE THREAD

**Issue by acornejo** [Shougo/unite.vim#847]
I use unite as a frontend to grep strings on my project. For the most part it works great, I use the following binding:

    map <leader>a :Unite -start-insert -buffer-name=ag grep:.<CR>    

However, a lot of times I grep a pattern, then use unite to go to a particular location. If I want to see other matches in unite, I currently have to perform the grep again and search for the same pattern. It would be great if it were possible to reopen the unite window with the previous grep command, but I don't know if this is possible or how to do it.

PS: To be more clear. I know about UniteResume, but I would like to have a binding that allows me to either open the last grep window, or search for a new term if a previous unite search window doesn't exist.

**Comment by ujihisa** [comment]
* `:h unite-options-no-quit`
* `:h :UniteResume`

**Comment by acornejo** [comment]
Thank you!

no-quit was exactly what I wanted. an unrelated question:

why does it take half a second or more for unite to prompt me for a "pattern"? I would expect this to be instantaneous, since it doesn't need to call external programs, but there is a noticable delay.

**Comment by ujihisa** [comment]
Because of your key mapping.

I guess there are more than 2 results from `:map <leader>a`

**Comment by Shougo** [comment]
> PS: To be more clear. I know about UniteResume, but I would like to have a binding that allows me to either open the last grep window, or search for a new term if a previous unite search window doesn't exist.

`:Unite -resume grep` is better.
