### ISSUE TITLE
Using `d` in :Unite buffer makes bufferlist reorder

### ISSUE THREAD

**Issue by idbrii** [Shougo/unite.vim#849]
I use buffer mode to clean up my buffer list, but deleting any file except the last one re-orders the buffers list. 

* Open four files: `gvim A B C D`.
* Switch to the next: `:next`
* Use `:Unite buffer`.
 * The first file in the list is the alternate file (A) and the last file is the one I had open (B).
 * If I use the `d` key (`unite#smart_map('d', unite#do_action('delete'))`) to bdelete the file A, then B moves into the first row. The same occurs if I delete any buffer except for B.
 * Instead, I would expect all lines to shift up one like deleting a line in a normal vim buffer. 

Before:

	1 #   A (2015/02/12 12:43:40)                                               
	4     D                                                                     
	3     C                                                                     
	2 %a  B (2015/02/12 12:43:42)                                               

After deleting A:

	2 a   B (2015/02/12 12:43:42)                                               
	4     D                                                                     
	3     C                                                                     

Desired after deleting A (order is unchanged):

	4     D                                                                     
	3     C                                                                     
	2 a   B (2015/02/12 12:43:42)                                               

Tested using 8460f6502e3961db1acb972b9b888db2b43327cf on Vim 7.4.0 (from vim.org) on Win7 x64 with:

	gvim -Nu minimal.vimrc +'source ~/.vim/bundle/sensible/plugin/sensible.vim'  A B C D

**Comment by wilywampa** [comment]
@Shougo,

Before this patch, the current buffer was placed at the bottom of the buffer list which I think is useful behavior. I made a pull request to solve the problem described in this issue while keeping the old order.

**Comment by Shougo** [comment]
OK.
