### ISSUE TITLE
[Request] Unite grep において 'Pattern: ' に何も入力されなかった場合は Unite インターフェイスを表示しないでほしい

### ISSUE THREAD

**Issue by lambdalisue** [Shougo/unite.vim#850]
タイトルでご理解いただけると思いますが `Unite grep:.` を実行後に「あ、やっぱいいや」と思った際に自然と `<Esc>` をタイプするのですが、その場合 candidate が 0 の Unite インターフェイスが表示され、手間がかかります。

仕組み的に `<Esc>` の入力がキャッチできないことは理解しているので `Pattern: ` インターフェイスにおいて「何も入力されなかった場合」は Unite インターフェイスを表示せずキャンセル処理をするように変更していただけると助かります（空 candidate なインターフェイスが表示される意味は殆ど無いと思うので）。

PRしたほうが良い場合はお申し付けください。

関連: https://github.com/lambdalisue/unite-grep-vcs/issues/3

**Comment by Shougo** [comment]
`:Unite grep -no-empty` で十分だと思います。
残念ながら、unite 本体は入力がキャンセルされたかどうか判断する方法がありません。
特に複数の source を処理している場合には更にややこしくなります。

**Comment by lambdalisue** [comment]
`-no-empty` オプションを知りませんでしたorz お騒がせしました....
