### ISSUE TITLE
Is it expected when use both direction and prompt_direction?

### ISSUE THREAD

**Issue by keitee** [Shougo/unite.vim#854]
Hi all,

Not sure if it's expected or not. Thing is when use the direction option only, unite buffer is placed at below. (suppose that it's expected)

call unite#custom#profile('default', 'context', {'direction': 'below'})

However, when use the prompt_direction as well, that goes to top.

call unite#custom#profile('default', 'context', {'prompt_direction': 'below'})

Is it expected or something wrong? 

Many thanks,
Kit

**Comment by Shougo** [comment]
Please read the issue template.
I will check it.

https://github.com/Shougo/unite.vim/issues/584

**Comment by Shougo** [comment]
I think it is feature.  You must set direction and prompt_direction like this:

```
call unite#custom#profile('default', 'context', {'prompt_direction': 'bottom', 'direction': 'below'})
```
