### ISSUE TITLE
UniteNext not getting updated buffer candidate

### ISSUE THREAD

**Issue by pinkchry** [Shougo/unite.vim#857]
So I'm using buffer source (which is sorting by the last access time). When I choose a buffer and then do a :UniteNext, it does not seem to have updated the list, so I don't get the previous buffer. If I choose  the buffer and then browse the buffers again with Unite buffer, then the list is updated and UniteNext works as expected. 

Hope that makes sense.

**Comment by Shougo** [comment]
It is feature.

**Comment by pinkchry** [comment]
Well. that's a pity. Some sort of rationale would be nice, as I cannot make sense of how one would use this in a normal workflow.

**Comment by Shougo** [comment]
This feature is slow and complicated.
It is useful for limited workflow.
