### ISSUE TITLE
'sorter_rank' has poor sorting – prioritizes short match over good match

### ISSUE THREAD

**Issue by roryokane** [Shougo/unite.vim#858]
#### Problem summary

For a certain search of the `file_rec` source, using `matcher_fuzzy` and `sorter_rank`, the results are wrongly ordered.

The query is “mithstor”. These two results are shown in this order, the wrong order:

1. `examples/mithril/js/controllers/todo.js`
2. `examples/mithril/js/models/storage.js`

#### Expected

The file that most matches my query, `storage.js`, should be at the top.

I want `storage.js` to be selected even though “mithril/js/controller” is a shorter string than “mithril/js/models/stor”. This is because the “stor” part is more likely to refer to the “<b>stor</b>” in the `storage.js` path than “<b>s</b>/con<b>t</b>r<b>o</b>lle<b>r</b>” in the `todo.js` path.

#### Environment Information

* OS: OS X 10.9.5
* Vim version: 7.4 with patches 1-488

#### Minimal `vimrc`

```VimL
set nocompatible
syntax enable
set runtimepath+=~/.vim/bundle/unite.vim/

call unite#filters#matcher_default#use(['matcher_fuzzy'])
call unite#filters#sorter_default#use(['sorter_rank'])
```

#### How to reproduce

1. Create a project in which the results are badly sorted:
    * If you have a slow internet connection, create a fake project:

        ```sh
        mkdir todomvc && cd todomvc
        mkdir -p examples/mithril/js/controllers/
        mkdir -p examples/mithril/js/models/
        touch examples/mithril/js/controllers/todo.js
        touch examples/mithril/js/models/storage.js
        ```

    * If you want a more realistic test, download the real project where this problem occurs (about 100MB):

        ```sh
        git clone https://github.com/tastejs/todomvc.git
        cd todomvc
        git checkout f5e0debd9ca4645e6936df383187a513f6bae4a7
        ```
2. Start Vim with `vim -u ../minimal.vimrc`
3. Run the command `:Unite -start-insert file_rec`
4. Type “mithstor”
5. Now `examples/mithril/js/controllers/todo.js` will be at the top. But the file I was actually searching for, which is a better match, is `examples/mithril/js/models/storage.js`.

#### Screen shot

![Unite file_rec search results for “mithstor”](https://cloud.githubusercontent.com/assets/79168/6321029/1fce33da-babd-11e4-8fca-409ef63c475e.png)

**Comment by Shougo** [comment]
Yes, it is feature.  You should use "mith stor" query.  I don't want to change the bahvior.
But pull request is wellcome.
