### ISSUE TITLE
unite-output での Vim のシンタックスハイライトを無効にしたい

### ISSUE THREAD

**Issue by osyo-manga** [Shougo/unite.vim#860]
unite-output 時に設定される Vim のシンタックスハイライトを無効にすることは可能なのでしょうか。
わたしの環境で `:Unite output:mes` 時に以下のようなハイライトされてしまいとても見づらいので無効にしたいです。

![](http://gyazo.com/83deaf7a3e765c521e591b9fc015083b.png)

そもそも unite-output の出力に対して Vim のシンタックスハイライトを行う必要はあるのでしょうか？

**Comment by Shougo** [comment]
それはちょっとひどいハイライトですね……。
source のハイライトを無効にするためのオプションを追加しようと思います。

> そもそも unite-output の出力に対して Vim のシンタックスハイライトを行う必要はあるのでしょうか？

理由なしにそういう変更をやるわけがないので、何か理由があったと思うのですが
history をチェックしても理由はよく分かりませんでした。

**Comment by osyo-manga** [comment]
> source のハイライトを無効にするためのオプションを追加しようと思います。

ありがとうございます :)

> history をチェックしても理由はよく分かりませんでした。

ふむ。
`:messages` の出力に限っていえば Vim script のシンタックスハイライトはそれなりに有効だとは思うので（上のはさすがにひどいですが）そのあたりですかねぇ。

**Comment by Shougo** [comment]
```vim
call unite#custom#source('output', 'syntax', '')
```

**Comment by osyo-manga** [comment]
こちらでも動作することを確認しました。
ありがとうございます。
