### ISSUE TITLE
Feature request: directory alias for files_async

### ISSUE THREAD

**Issue by zerodogg** [Shougo/unite.vim#863]
When I open files_async within my ~/ it is very slow (listing 39264 files, it takes several seconds to load, and then several seconds more to filter). The files that I am interested in are almost always in ~/Documents (only 13810 files, taking roughly a second to load). It would be useful to be able to tell files_async that if pwd is ~/, use ~/Documents instead.

I could manually switch to ~/Documents before running vim, or map a key specifically to this, but that breaks the workflow by requiring an extra step. I could also make my file_async open always use ~/Documents, but it *is* useful to limit it when inside some project directory.

* Environment Information
 * OS: ArchLinux
 * Vim version: 7.4.617
 * Unite with neomru and vimproc, installed with neobundle, all up to date at the time of submission

**Comment by Shougo** [comment]
`:Unite file_rec/async:~/Documents`

**Comment by zerodogg** [comment]
I realize the functionality you listed exists. The request was for an alias feature that can replace one directory with another. Ie. if the current directory is ~/, use ~/Documents instead, if the current directory is anything else, continue as per usual.

**Comment by zerodogg** [comment]
I solved it with some vimscript. This is what I wanted to do:

````VIML
nnoremap <expr> <Leader>o expand('~') == getcwd() ? ':Unite file_rec/async:~/Documents<cr>' : ':Unite file_rec/async:!<cr>'
````

**Comment by Shougo** [comment]
> I realize the functionality you listed exists. The request was for an alias feature that can replace one directory with another. Ie. if the current directory is ~/, use ~/Documents instead, if the current directory is anything else, continue as per usual. 

I get it.  But it is not easy.
