### ISSUE TITLE
feature request (or is already available?)

### ISSUE THREAD

**Issue by maikelmeyers** [Shougo/unite.vim#864]
If I understood correctly, the source 'file_rec' uses the 'find' command to find candidates recursively.
As the first argument I can deliver the directory to search for, i.e. Unite file_rec:/foo/bar.
But the native 'find' is able to retrieve multiple paths, i.e. find /foo/bar /bar/foo -name *.baz
How are multiple input directorys possible with Unite? Same for grep.
I know that I could use Unite file_rec:/dir1 file_rec:/dir2 but this would invoke 'find' or 'grep' multiple times I think and this could be slow if there are hundreds of directorys to search for. I ask because our project tree is strayed to many different directorys.

**Comment by Shougo** [comment]
No.  But I don't want to add the feature.
I think this advantage is very limited.

**Comment by maikelmeyers** [comment]
It helped out that I simply removed "string(" from .vim/bundle/unite.vim/autoload/unite/sources/find.vim

So now I can use: Unite find:/foo/bar\ /bar/foo:-type\ f

This results to: find /foo/bar /bar/foo -type f
before: find '/foo/bar /bar/foo' -type f
internally.


let cmdline = printf('"%s" %s %s %s',
        \ g:unite_source_find_command, g:unite_source_find_default_opts,
        \   string(a:context.source__target), a:context.source__input)

**Comment by Shougo** [comment]
> It helped out that I simply removed "string(" from .vim/bundle/unite.vim/autoload/unite/sources/find.vim

Unfortunatelly, it is not good.
If the directory contains spaces?

**Comment by maikelmeyers** [comment]
This works for me, since I have no spaces in directorys.

But Unite handles this problem a little bit inconsistent.

Assume the following Unite Call:

`Unite find:/foo/dir\ with\ spaces/:-type\ f`
This leads to this command line call:
`"find" '/foo/dir with spaces/' -type f`

So it seems that all backslashes are deleted and the path argument is single quoted. This way I can have dirs with spaces **but you can never use more than one path and also no globbing**. This is bad!

The Unite grep handles it different. A call like this:
`Unite grep:/foo/dir\ with\ spaces/:-i\ -r:search\ foo`
expands to:
`"grep" -i -r 'search foo' /foo/dir\ with\ spaces`

Here, the backslashes of the path argument are not deleted and it gets not single quoted. This way I can also use spaces in a dir path and globbing is also possible, **but still I can not use more than one path**.

My question is, why is the following call not possible?
`Unite grep:'/dir1\ with\ spaces/ /dir2\ with\ spaces/ ~/dir3/*.txt':'-i -r':'search foo'`
This could be processed to the command line:
`grep -i -r 'search foo' /dir1\ with\ spaces/ /dir2\ with\ spaces/ ~/dir3/*.txt`

Would be the same for Unite find.

You could keep being downward compatible with the old method without single quotes.
This approach would be more consistent and enables all possibilities.

But apart from this issue, I want you to thank for this great plugin. It needs some time to come into, but it is such a great and flexible piece of work. Thanks very much :)

**Comment by Shougo** [comment]
> My question is, why is the following call not possible?

```help
						*unite-source-grep*
grep		Nominates "grep" command output as candidates.
		Note: This source is created by Sixeight.

		Note: This source requires |vimproc|.  Please install.
		http://github.com/Shougo/vimproc

		Source arguments:
		1. the target directory.
		2. "grep" options.
		3. the narrowing pattern (if you omit it, |unite-options-input|
		or input prompt is used).
		Max candidates: |g:unite_source_grep_max_candidates|
```

See the interfaces.  Yes, grep supports multiple directories internally.
But you must set the target directories by list.

**Comment by Shougo** [comment]
> but you can never use more than one path and also no globbing

You should not use globbing for unite-grep.
It is not the feature.

**Comment by Shougo** [comment]
I have read the code.
I don't want to add this feature.
file_rec source supports cache feature.
If I support multiple directories, the routine will be complex.

**Comment by maikelmeyers** [comment]
> You should not use globbing for unite-grep.
> It is not the feature.

globbing works fine with unite-grep as I showed, but it does not work in unit-find, because the parsing is different there.

I use globbing very often with grep. This is how grep works on the command line. It would be horrible if grep could not be used with globbing.

But OK, if you find it too hard to implement, I have to live with my small patch. Works fine for unite-find. Since I can not use multiple paths in unite-grep because of the different parsing, I have a workaround which "emulates" this with the help of globs. See this example:

`Unite grep:{/dir1/,/dir2/}*.txt:-ir:searchFoo`

It would be enough, if unite-find is changed to the same implementation as unite-grep, meaning not deleting all backslashes and single quoting the path argument.

**Comment by Shougo** [comment]
> I use globbing very often with grep. This is how grep works on the command line. It would be horrible if grep could not be used with globbing.

I don't want to support globbing.
Because, it is shell depends behavior and conflicts the filenames.

**Comment by maikelmeyers** [comment]
> I don't want to support globbing.
Uhm? You already support it in unite-grep! I was only confused that you support it in unite-grep, but not in unite-find. I am really happy that you support it in unite-grep, otherwise unite-grep would be unusable for this purpose.

Everyone who uses globs knows what he is doing and that it is shell dependent. To forbid the use of globs by implementation takes a big bunch of Unites flexibility away.

But OK, you are the decider and you decided. I see that there is no way to convince you. :)

**Comment by Shougo** [comment]
I removed unintended glob feature from grep.
But I will implement eval arguments feature and new line separated list feature.
You can use multiple directories in unite in the future.

**Comment by Shougo** [comment]
I may support multiple directories in file_rec source.
But it is after those features are implemented.

**Comment by Shougo** [comment]
I will implement the features if the features are useful for other sources.

**Comment by maikelmeyers** [comment]
OH NO!!!! WHAT HAVE I DONE? You removed glob support for grep? You did the opposite from waht I wanted? I can't believe!!!!

**Comment by maikelmeyers** [comment]
Now it's time to make a personal patch file otherwise Unite gets unusable for me. I can't understand you, sorry!

**Comment by Shougo** [comment]
> But I will implement eval arguments feature and new line separated list feature.

See the previous comment.
I think the general globbing features are better.

```vim
Unite grep:`=glob('/dir1/*.txt')."\n".glob('/dir2/*.txt')`:-ir:searchFoo
```

**Comment by Shougo** [comment]
> Now it's time to make a personal patch file otherwise Unite gets unusable for me. I can't understand you, sorry!

You are too hurry.  If you want to use the old glob feature, you should not update unite.vim now.

**Comment by maikelmeyers** [comment]
What's about this general globbing feature? I never saw this before! Is it in the documentation?

**Comment by Shougo** [comment]
It is under development.  It is not implemented now.

**Comment by Shougo** [comment]
I think the features are better.  Because, you can use the features in other sources.

**Comment by maikelmeyers** [comment]
But could you let the unintended unite-grep globbing as it was before, until this unite globing features are implemented? :D

**Comment by Shougo** [comment]
No.
You can use the old version.

**Comment by maikelmeyers** [comment]
I am looking forward for your globbing implementation!

**Comment by maikelmeyers** [comment]
I am really shure your wheel will be rounder when you reinvent it. I look forward to it!

**Comment by Shougo** [comment]
I implemented eval feature in unite.vim.

**Comment by Shougo** [comment]
Implemented.

**Comment by maikelmeyers** [comment]
Many Thanks!
But seems not to work for Unite find?!

**Comment by Shougo** [comment]
If the problem is exists, please open new issue.

**Comment by balta2ar** [comment]
@Shougo, looks like something got broken. I have this:
``` vim
let g:unite_source_rec_async_command =
      \ 'ag --follow --nocolor --nogroup --hidden -g ""'
```

When I call file_rec/async for the first time after vim startup, it's fine. However, all later calls show this message:

```
[file_rec/async] directory: /home/ybochkarev/dev/cs/trunk
function <SNR>106_call_unite_empty..unite#start..unite#start#standard..unite#candidates#_recache..<SNR>190_recache_candidates_loop..<SNR>190_get_source_candidates..508..vimpr
oc#popen3..<SNR>192_plineopen..<SNR>192_convert_args..vimproc#get_command_name, line 15
vimproc#get_command_name: File "ag --follow --nocolor --nogroup --hidden -g """ is not found.
[unite.vim] Error occurred in gather_candidates!
[unite.vim] Source name is file_rec/async
Press ENTER or type command to continue
```

It's still working fine at f4049ac. Could you please take a look at this?

**Comment by Shougo** [comment]
https://github.com/Shougo/unite.vim/issues/896

It is bug.  I will fix it later.

**Comment by Shougo** [comment]
@balta2ar Fixed it.

**Comment by maikelmeyers** [comment]
I was too fast. Multiple directorys in Unite grep still do not work because

```Unite grep:`glob('/dir1/*.txt')."\n".glob('/dir2/*.txt')`:-ir:searchFoo```

results in a weird command line like this:

`"grep" -ir 'searchfoo' "/dir1/a.txt" "/dir1/b.txt\n/dir2/c.txt"`

which does not work.

The workaround is:
```Unite grep:`glob('/dir1/*.txt').'" "'.glob('/dir2/*.txt')`:-ir:searchFoo```

but is this the expected behavior?

**Comment by Shougo** [comment]
Unfortunatelly, I cannot reproduce problem.
Please read the issue template and reproduceable ways.

**Comment by maikelmeyers** [comment]
Please do in a shell:

```
mkdir ~/UniteGrepTestDir1
mkdir ~/UniteGrepTestDir2
touch ~/UniteGrepTestDir1/foo1
touch ~/UniteGrepTestDir1/foo2
touch ~/UniteGrepTestDir2/bar
echo "baz" > ~/UniteGrepTestDir1/foo1
echo "baz" > ~/UniteGrepTestDir1/foo2
echo "baz" > ~/UniteGrepTestDir1/bar
```
now start vim and enter the command:

```:Unite grep:`glob('~/UniteGrepTestDir1/*') . '" "' . glob('~/UniteGrepTestDir2/*')::baz```

and you see that works, but

```:Unite grep:`glob('~/UniteGrepTestDir1/*') . "\n" . glob('~/UniteGrepTestDir2/*')::baz```

does not because the 2 globs are merged in a weird way. The call to grep, generated by unite looks like this:
```grep 'baz' "~/UniteGrepTestDir1/foo1" "~/UniteGrepTestDir1/foo2\n~/UniteGrepTestDir2/bar"```
The last element of the first glob and the first element of the second glob are merged together into doublequotes. This can not work.

**Comment by Shougo** [comment]
I tested it.  But it cannot reproduced.
Please check below code in your environment.

https://github.com/Shougo/unite.vim/blob/master/autoload/unite/sources/grep.vim#86

Please check `target` and `targets` results.

**Comment by maikelmeyers** [comment]
Sorry. Forget about it. It works now, but I don't know what was wrong here. Maybe grep.vim was merged in some way with my modification to it. I also can not reproduce this. Sorry to bother you!

**Comment by maikelmeyers** [comment]
But I noticed another problem. Since I use now the glob() function, it takes a lot of time until the grep command is called. It is totally slow!
My call looks like this: ```Unite grep:`glob('/project/units/*/source/**/*.v')`:-i:foo```
Before your modification it was ```Unite grep:/project/units/*/source/**/*.v:-i:foo```
and this was 10 times faster!! It is really a pain now to wait 7 seconds until Unite is ready to call grep and grep itself only needs some milliseconds to grep thru hundreds of files.

**Comment by Shougo** [comment]
> But I noticed another problem. Since I use now the glob() function, it takes a lot of time until the grep command is called. It is totally slow!

It is Vim's problem.  You can request it in vim_dev.
I cannot fix it.

**Comment by maikelmeyers** [comment]
There is no reason why it takes so long. Calling ```echo glob('/project/units/*/source/**/*.v')``` gives the result instantly in milliseconds. Why does Unite need 7 seconds to pipe it to the grep call?

**Comment by maikelmeyers** [comment]
I think this is not a vim problem.

**Comment by Shougo** [comment]
@maikelmeyers You can profile it.

**Comment by maikelmeyers** [comment]
How to do this?

**Comment by Shougo** [comment]
`:help :profile`

**Comment by maikelmeyers** [comment]
So I found the one that is slow: It is:

 ```call unite#print#source_message('Command-line: ' . cmdline, s:source.name)```

Possibly because the command line gets really long when the globs are unwinded.

**Comment by Shougo** [comment]
OK.  I will improve it.
