### ISSUE TITLE
Confused about Unite's features

### ISSUE THREAD

**Issue by azure-satellite** [Shougo/unite.vim#865]
Hey @Shougo. As I'm reading the documentation (and even the source code a little bit) I did not find that a good explanation of what matchers/filters/converters/sorters do. 

I can kind of infer from their names but it is not clear. I'm willing to update the docs and write a short tutorial on it if you explain to me the differences. I think it's good to make these algorithms orthogonal to each other so that they don't duplicate functionality and confuse people when one should be used over the other. Thanks!

**Comment by Shougo** [comment]
filter: Generic types of matcher, sorter and converters.
matcher: It filters candidates.  It is called in first.
sorter: It sorts candidates.   It is called in second.
converter: It changes candidates attribute.  It is called in third.
