### ISSUE TITLE
:Unite file_rec cache gets corrupted from :Unite grep

### ISSUE THREAD

**Issue by brennancheung** [Shougo/unite.vim#867]
I've been struggling trying to set up Unite to work with my project.  I want it to exclude certain folders from `:Unite file_rec` and `:Unite grep`.

I have set up a `wildignore` and also `.agignore`.

`ag` works fine from the command line and respects the `.agignore`.

`file_rec` works fine until I use `grep`.  Once I use `grep` then I notice `~/.cache/unite/file/[long-filename]` contains files that are supposed to be ignored.  The weird part is that when I check that file manually it doesn't get populated with the invalid entries until I use `file_rec` again.  That is, `file_rec` then `grep` doesn't populate it.  But `file_rec` then `grep` then `file_rec` does populate it.  It doesn't seem to matter whether I am using `ag` or not; `grep` always corrupts the `file_rec` list—even though `grep` shows the correct list.

I have tried with and without the following 4 files.  They both exhibit the same issue:

    let g:unite_source_rec_async_command='ag --nocolor --nogroup -p /Users/brennan/.agignore --hidden -g ""'
    let g:unite_source_find_command='ag --nocolor --nogroup -p /Users/brennan/.agignore --hidden -g ""'
    let g:unite_source_grep_command='ag'
    let g:unite_source_grep_default_opts='-i --line-numbers --nocolor --nogroup --hidden -p /Users/brennan/.agignore'

I have also added tried `:Unite grep:./src` but it still seems to add stuff outside the `./src` folder when I use `file_rec` after I use `grep`.

`file_rec` works fine no matter how many times I invoke it, up until I use `grep`.  At that point `file_rec` contains entries that are supposed to be ignored.  In other words, the following sequence yields:

`file_rec` contains the proper list.
`grep:./src` contains the proper list.
`file_rec` contains the incorrect list (and stuff outside of `./src` now show up).

**Comment by brennancheung** [comment]
I switched to using `file_rec/async:!` and it seems to have fixed the issue.  Also looks like the `-p` option for `ag` is redundant and not needed.

Still seems like there is an issue with the normal `file_rec` but I can work around it.  Not sure if you want to leave this ticket open or just close it out since it is easy to work around (once you know the solution).

**Comment by Shougo** [comment]
Please read the issue temaplate.

https://github.com/Shougo/unite.vim/issues/584

Please upload the minimal .vimrc and the reproduce ways.
I will test it.

**Comment by Shougo** [comment]
No response.

**Comment by brennan-si** [comment]
I'm not a vim expert and this is not something I am comfortable doing.  It took me a week to get my vim setup and that was going through vundle.  I put my .vimrc up at https://gist.github.com/brennancheung/4e69ab6edff1c08dc7af

**Comment by Shougo** [comment]
@brennan-si It is not minimal .vimrc.
Unfortunately, you have not read the issue template...

**Comment by brennan-si** [comment]
Sorry, but as I already stated I'm not a vim expert and am going through vundle.  I would need to spend several days to learn how to set up vim, unite, ag, and all the other relevant plugins without vundle just to get a minimal config.  That's too much time for something that may or may not provide any benefit.

I can however run any commands to output variables, drill into things, or look things up.

No Lua.  OS X Yosemite.  Vim 7.4

**Comment by Shougo** [comment]
Hmmm...
I think you  should learn Vim and VimL before using unite.
Unite.vim is the most difficult/complicated plugin.
So, I don't recommend to use it by beginner.
