### ISSUE TITLE
-no-split options always moves the input window(prompt) goes upwards 

### ISSUE THREAD

**Issue by keitee** [Shougo/unite.vim#869]
* Problems summary
When use both direction:below and -no-spilt, input windows goes upwards.

* Expected
Not sure about the expected. However, since there is prompt at below, it is not eye-friendly to see window goes to opposite.

* Environment Information
 * OS: Debian 3.2.63-2+deb7u2 x86_64 GNU/Linux
 * Vim version: 7.4

* Minimal vimrc less than 50 lines

  call unite#custom#profile('default', 'context', {
        \ 'direction': 'top',
    \ 'start_insert' : 1,
    \ 'smartcase' : 1,
    \ 'prompt' : '>> '
    \ })

:Unite -no-split -toggle -buffer-name=files buffer file_mru file_rec/async<cr>

* How to reproduce

 0. startup gvim (Write with option arguments if necessary).
 1. run file search as shown above.
 2.
 3.

* Screen shot (if possible)
NA.

**Comment by Shougo** [comment]
> When use both direction:below and -no-spilt, input windows goes upwards.

You must use "prompt_direction:below".

```vim
call unite#custom#profile('default', 'context', {
\ 'prompt_direction': 'below',
\ 'start_insert' : 1,
\ 'smartcase' : 1,
\ 'prompt' : '>> '
\ })
```

**Comment by keitee** [comment]
Thanks. In that case, better to be documented?

**Comment by Shougo** [comment]
```
						*unite-options-prompt-direction*
		-prompt-direction="top" or "below"
		Specify the prompt direction.
		Note: If it is "below", |unite-options-auto-resize| is used
		automatically.  To disable it, you must set "-no-auto-resize"
		option.
		Default: "below" (if |unite-options-direction| contains "below")
```
