### ISSUE TITLE
Action results after unite#start_complete and :Unite are different for ultisnips source

### ISSUE THREAD

**Issue by leonidborisenko** [Shougo/unite.vim#870]
For expanding snippet, mapping to `:Unite ultisnips` works correctly and produces expected result, but mapping to `unite#start_complete(['ultisnips'])` also outputs some normal mode commands into buffer instead of executing them to select snippet placeholder.

* Environment Information
  * OS: Linux
  * Vim version:
```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Feb 12 2015 03:42:11)
Included patches: 1-488
```
  * Enabled lua interface?
```
:echo has('lua')
1
```
* Minimal vimrc less than 50 lines:
```vim
set nocompatible

" Directory where this minimal vimrc file is located.
let s:rcdir = expand('<sfile>:p:h')

let &runtimepath .= ','.s:rcdir.'/ultisnips'
let &runtimepath .= ','.s:rcdir.'/unite.vim'

runtime! 'plugin/UltiSnips.vim'
runtime! 'plugin/unite.vim'

" Snippet 'x' will expand to placeholder with 'test' as default text.
call UltiSnips#AddSnippetWithPriority('x', '${1:test}', 'x', {}, 'all', 100)

inoremap <F5> <C-o>:Unite ultisnips<CR>
inoremap <expr><silent> <F6> unite#start_complete(['ultisnips'])
```
* Reproducable ways from Vim starting
```
ix<F5><CR><Tab>ox<F6><CR>
```
Expected:
```
test
test
```
Actual:
```
test
v2G4|o2G1|otest
```
In Ultisnips plugin code Vim's `mode()` returns `n` after selecting Unite candidate and then UltiSnips [won't prepend `<Esc>`](https://github.com/SirVer/ultisnips/blob/c1bde18cdf6be73517158f27073fb01027946924/pythonx/UltiSnips/_vim.py#L141).

**Comment by Shougo** [comment]
Unfortunatelly, it is UltiSnips source problem.  And in insert mode, unite features are very limited.
I cannot support it.
