### ISSUE TITLE
-no-split options do not close buffer

### ISSUE THREAD

**Issue by keitee** [Shougo/unite.vim#872]
* Problems summary
When use -no-spilt, buffer remains open when use 'q' to quit. If not use this option, works as expected.

* Expected
The buffer gets closed and back to the previous.

* Environment Information
 * OS: Debian 3.2.63-2+deb7u2 x86_64 GNU/Linux
 * Vim version: 7.4

* Minimal vimrc less than 50 lines
:Unite -no-split -toggle -buffer-name=files buffer file_mru file_rec/async<cr>
:Unite -no-split -auto-resize -auto-preview gtags/def

* How to reproduce

 0. startup gvim (Write with option arguments if necessary).
 1. run file search or others with no-split option as shown above.
 2.
 3.

* Screen shot (if possible)
NA.

**Comment by Shougo** [comment]
> Minimal vimrc less than 50 lines

No.  Please upload .vimrc.

```vim
:Unite -no-split -auto-resize -auto-preview gtags/def
```

Please don't use non-standard source for testing.

**Comment by Shougo** [comment]
Unfotunatelly, I cannot reproduce the problem.
You must upload minimal .vimrc.

**Comment by Shougo** [comment]
> The buffer gets closed and back to the previous.

What's the previous buffer?
Unite does not return to unite buffer when quit.

> startup gvim (Write with option arguments if necessary).

If you startup gvim, it returns to blank buffer.

**Comment by keitee** [comment]
Thanks for replies. More tries and clarifications. This does happen when use 'standard' source as well like:

:Unite -no-split -toggle -buffer-name=files buffer file_mru file_rec/async<cr>

What I mean by the previous is the '[No Name]' buffer and it get created only when quits the unite window (pressing ESC and q) but not when make a selction. After see this and make a selection again, then this no-named gets removed. 

![untitled](https://cloud.githubusercontent.com/assets/6106173/6548112/530ac522-c5e6-11e4-9cab-6c145e07ce79.jpg)

However, this doesn't happen when not use -no-split.

Hope this is clear and you can see what I see. If needed, will try to upload the vimrc used.

Many thanks

**Comment by Shougo** [comment]
It is Vim's feature.
If Vim edit file in noname buffer, Vim overwrites the buffer.
unite.vim can split for the behavior.  Should I implement the behavior?

**Comment by keitee** [comment]
Not sure what you mean and if it's nesseary feature to implement since I don't have much knowledge as you have. Simply wondered why I see this when use -no-split and wanted to have bigger windows for a huge result like grep search. If it's vim feaure, then have not to use -no-split. ;-)

**Comment by Shougo** [comment]
You should not use noname buffer.
It can be overwrite easily.

**Comment by keitee** [comment]
Many thanks. Just to be clear. What I meant is that noname buffer is automatically created.
