### ISSUE TITLE
-winwidth option when use vertical window

### ISSUE THREAD

**Issue by keitee** [Shougo/unite.vim#875]
Hi,

When use vslpit, want to have full size unite buffer rather than a small fitted to one of vim windows. 

*unite-options-winwidth*
-winwidth={window-width}
Specify the width of a unite buffer.
Default: "90"

Tried as help said:

  call unite#custom#profile('default', 'context', {
    \ 'prompt' : '>> ',
    \ 'winwidth' : 180
    \ })

However, see no changes. Is it possible to say "max" or something else?

Many thanks

**Comment by Shougo** [comment]
Please read the issue template and upload minimal .vimrc and upload the reproduce ways from Vim starting.

https://github.com/Shougo/unite.vim/issues/584

**Comment by keitee** [comment]
Thought it's better to draw.

Expected(or wish ;-))
------------------------------
|             ||             |
|             ||             |
|             ||             |
|  win 01     ||     win 02  |
|             ||             |
|             ||             |
|             ||             |
------------------------------
|                            |
|       unite window         |
|                            |
|                            |
------------------------------

But what I see is:
------------------------------
|             ||             |
|             ||             |
|             ||             |
|  win 01     ||     win 02  |
|             ||             |
|             ||             |
|             ||             |
---------------|             |
|             ||             |
| unite       ||             |
| window      ||             |
|             ||             |
|             ||             |
------------------------------

Hope this help you see what I meant. Thanks.

**Comment by Shougo** [comment]
Please use direction option.

```vim
call unite#custom#profile('default', 'context', {
\ 'prompt' : '>> ',
\ 'winwidth' : 180,
\ 'direction' : 'botright'
\ })
```

**Comment by keitee** [comment]
That's works and many thanks.
