### ISSUE TITLE
file_rec/git paths corrupted and show "--cached" at the beginning 

### ISSUE THREAD

**Issue by smackesey** [Shougo/unite.vim#876]
Sometime in the last few commits a change was made that makes all of my previous file_rec/git mappings broken. The path candidates in the unite menu now all have `--cached` prefixed to them.  It probably is related to the fact that I use this to wrapper function to call file_rec/git:

    function! UniteFileRecGitWrapper(path)
      exec 'cd ' . a:path
      exec 'Unite file_rec/git:--cached:--others:--exclude-standard:' . a:path . ' file/new:' . a:path
    endfunction

The breaking change is in one of the below commits (I know because I reverted to the commit just prior to these and it works fine).

>commit 854e39769a0b1c6d8093cc4f76b4d31b9f2c092d
Author: Shougo Matsushita <Shougo.Matsu@gmail.com>
Date:   Mon Mar 9 23:14:55 2015 +0900

>commit 6a26ba1081a471775b1def4bc400c599012fdbb6
Author: Shougo Matsushita <Shougo.Matsu@gmail.com>
Date:   Mon Mar 9 22:48:48 2015 +0900

>commit 710457917b0e59b9aabb82a145353eb395f1530d
Merge: 66b1b0b f0c0e22
Author: Shougo <Shougo.Matsu@gmail.com>
Date:   Mon Mar 9 21:39:09 2015 +0900

>commit f0c0e22273ac6bc2c00320387a7668acf4623b64
Author: wuranbo <wuranbo@gmail.com>
Date:   Mon Mar 9 15:34:22 2015 +0800

**Comment by Shougo** [comment]
Please explain the problem.  I don't understand it.

**Comment by Shougo** [comment]
I confirmed it.  I will check it.

**Comment by Shougo** [comment]
Fixed.  It is #874 degrade.
