### ISSUE TITLE
Inconsistent behavior of '-no-split' is given

### ISSUE THREAD

**Issue by bbchung** [Shougo/unite.vim#877]
What I saw:
When there is only one window in vim, invoke "Unite buffer -no-split", then quit(type 'q'), vim will leave a "No Name" buffer, and this situation not happens when there are more the one windows.

Expect:
Vim should not leave a "No Name" buffer no matter how many windows is opening.

**Comment by Shougo** [comment]
https://github.com/Shougo/unite.vim/issues/872
