### ISSUE TITLE
file_rec/git のファイルへのパスの不具合

### ISSUE THREAD

**Issue by koara-local** [Shougo/unite.vim#878]
* Problems summary
カレントディレクトリがgitのルートにいない場合でも
Unite file_rec/git のファイルへのパスが、ルートからのパスになります

* Environment Information
 * OS: Linux
 * Unite commit: e6ddf49ce4bda9db5e00252a5503a5eeb75f7027
 * Vim version: 7.4.389

* Minimal vimrc less than 50 lines

```VimL
" Your vimrc
set nocompatible
set runtimepath+=~/path/to/vimproc.vim/
set runtimepath+=~/path/to/unite.vim/
```

* How to reproduce

project tree before
```
.
`-- hogedir
    `-- hoge.txt
```

 0. startup vim (Write with option arguments if necessary).
 1. cd hogedir
 2. Unite file_rec/git
 3. select hogedir/hoge.txt
 4. see message ""/path/to/gitroot/hogedir/hogedir" does not exist. Create? [yes/no]:"
 5. select "yes"

project tree after
```
.
`-- hogedir
    |-- hogedir
    |   `-- hoge.txt
    `-- hoge.txt

```

**Comment by Shougo** [comment]
これで直ったと思うので確認してください

**Comment by koara-local** [comment]
@Shougo 直りました。ありがとうございます！
