### ISSUE TITLE
how to make `:Unite history/yank` append (not insert)?

### ISSUE THREAD

**Issue by sunaku** [Shougo/unite.vim#879]
Hello,

Right now `:Unite history/yank` inserts the chosen candidate at the cursor position (it's the same as pressing `i` in normal mode, typing in the chosen candidate, and finally typing `<Esc>`).

How can I make `:Unite history/yank` _append_ the chosen candidate at the cursor position?  That would be the same as pressing `a` in normal mode, typing in the chosen candidate, and finally typing `<Esc>`.

Thanks for your consideration.

**Comment by Shougo** [comment]
Not implement it yet.

**Comment by sunaku** [comment]
How about adding an **-append** option?  So I can use `:Unite -append` like this:

```vim
nnoremap <silent> <leader>p :Unite -append -no-split history/yank<Return>
nnoremap <silent> <leader>P :Unite -no-split history/yank<Return>
```

**Comment by Shougo** [comment]
I will add append action.  Not append option.
Please wait.

**Comment by sunaku** [comment]
:sparkles: Cool, thank you! :bow:

**Comment by Shougo** [comment]
Implemented.

**Comment by sunaku** [comment]
Thanks Shougo, but it seems the `-default-action=append` flag is having the opposite effect.  Using the leader+p/P bindings you defined above, I'm getting appending behavior on leader+P (no `-default-action=append` present) and inserting behavior on leader+p (with `-default-action=append` present).

Could you please verify? :confused:

**Comment by Shougo** [comment]
Thank you.  Fixed.

**Comment by sunaku** [comment]
:+1: Verified, thanks! :bow:
