### ISSUE TITLE
How to search content of open buffers? 

### ISSUE THREAD

**Issue by anuraj-rp** [Shougo/unite.vim#882]
Hi, 
I would like to search the content of open buffers. I took the command from reddit but it gives me error. 
http://www.reddit.com/r/vim/comments/2306xg/can_i_use_unite_to_search_file_contents_of_open/
```
[grep] Command line: "grep" -inH -r 'main' "main.c source2.c"
[grep] /usr/bin/grep: main.c source2.c: No such file or directory
```
The command I use is 
```
:Unite grep:$buffers
```

Also is there a way to search content of files inside directories with :UniteWithInputDirectory?

**Comment by Shougo** [comment]
Sorry.  It is bug.  I will fix it later.

**Comment by balta2ar** [comment]
@Shougo I'm not sure if this issue is the right one, but after recent grep-related fixes, Unite grep prompt has become two-lined instead of one-lined as before. Could you make it one-line again?
![](http://i.imgur.com/2qo5TSg.png)

**Comment by Shougo** [comment]
It is fixed in latest version.
