### ISSUE TITLE
bug?: returning to buffer from which unite was called does not work properly

### ISSUE THREAD

**Issue by maikelmeyers** [Shougo/unite.vim#883]
If you start a unite buffer i.e.
`:Unite grep:/home/user::foo`
you can quit unite and return to the editing buffer by pressing 'q'.

But if you again do a unite grep inside the unite buffer
`:Unite grep:/home/user::foo`
`:Unite grep:/home/user::bar` (inside the unite grep-result buffer)
pressing 'q' does not return to the correct buffer if more than one buffer is loaded. It gets even more a mess if the preview window is used (-vertical-preview -auto-preview)

**Comment by Shougo** [comment]
> pressing 'q' does not return to the correct buffer if more than one buffer is loaded. It gets even more a mess if the preview window is used (-vertical-preview -auto-preview)

It is feature.  The unite buffer is already overwrited.
And unite does't return to the unite buffer.
So unite cannot return the previous buffer.

**Comment by maikelmeyers** [comment]
Is it possible that unite remembers the buffer from which it was called (only if not a unite buffer)?
So it could return to the calling buffer on quit? This way it does not matter how often a nested call was done.

**Comment by Shougo** [comment]
OK.  Please upload the test case.  I will test it.

**Comment by maikelmeyers** [comment]
Testcase:

1. start vim (do no unite settings in vimrc)
2. type:
`itest<esc>:enew<cr>itest2<esc>:unite -no-split buffer<cr><esc>:unite -no-split buffer<cr><esc>q`

As you see now, vim shows the buffer with 'test1' inside not the buffer with 'test2' which was the calling buffer.

**Comment by maikelmeyers** [comment]
Makes no sense with Unite buffer, but just to show you...
With Unite grep it makes more sense, because often I search for a function and do a further grep in the preview window to narrow down to the core. But after that its not easy to return to the calling buffer, that I was editing.

**Comment by Shougo** [comment]
OK.  It seems fixed.

**Comment by maikelmeyers** [comment]
Thank you. But it seems to still not work with preview windows. I forgot to include them in the last test case. Again a test case with preview-options:

1. start vim (do no unite settings in vimrc)
2. type:
`itest<esc>:enew<cr>itest2<esc>:unite -no-split -vertical-preview -auto-preview buffer<cr><esc>:unite -no-split -vertical-preview -auto-preview buffer<cr><esc>q`

Without nesting the preview window gets closed. With nesting the preview window stays open.

**Comment by Shougo** [comment]
OK.  Fixed.

**Comment by maikelmeyers** [comment]
Great!! Thanks a lot. So fast!
