### ISSUE TITLE
Unite slow when used in first buffer ([No Name])

### ISSUE THREAD

**Issue by PonderingGrower** [Shougo/unite.vim#888]
Hi,

I've encountered this in both vim and neovim. When I start a new vim instance and try to use Unite when the first empty buffer named `[No Name]` is focused Unite seems much slower than if I tried using it with, for exmaple, my `.vimrc` focused.

This is a profile when attempting this in vim:
https://dl.dropboxusercontent.com/u/1973208/vim_profile.log

The function that takes the longest to finish is `unite#filters#lua_filter_patterns()` - 0.745 s.

This is a profile from neovim when doing the same thing
https://dl.dropboxusercontent.com/u/1973208/nvim_profile.log

This time `unite#filters#vim_filter_patterns()` (since neovim does not have `if_lua`) is the one that takes the longest - 2.57 s.

And this is the same but Unite was executed with a split with my `.vimrc` was focused:
https://dl.dropboxusercontent.com/u/1973208/nvim_normal_profile.log

Here `unite#filters#vim_filter_patterns()` takes only 0.033 s, which is much better.

I'm not sure what this is about but it does get annoying.

**Comment by Shougo** [comment]
I don't know why the slow routine...
But please read the issue template.  I must reproduce the problem.

https://github.com/Shougo/unite.vim/issues/584

**Comment by PonderingGrower** [comment]
Sorry, I should have done this better. Here you go.

* Problems summary

Unite seems to be much slower when used in two different locations:

1. Home - `~/`    - 18894 files - Average search time: 0.20 s
2. Work - `~/work` - 18819 files - Average search time: 0.17 s

These results are from calling `time ag --nogroup --nocolor -g ''`. As you can see there's little difference.

I have an .agignore file that ignores most contents of ~/ except for the work directory and a few others that aren't that big.

* Expected

* Environment Information
 * OS: Debian Jessie
 * Vim version: 7.4.684
 * NeoVim version: 0.0.0-alpha+201504021746 (dfdc6a76b1eaf7542e0ed96244c610cf61ea2594)

* Minimal vimrc less than 50 lines

```
if has('vim_starting')
    set rtp+=~/.vim/bundle/neobundle.vim/
    set nocompatible
endif

call neobundle#begin(expand('~/.vim/bundle/'))
NeoBundle 'Shougo/unite.vim'
NeoBundle 'Shougo/vimproc.vim', { 'build': { 'unix': 'make -f make_unix.mak'}}
call neobundle#end()

if executable('ag')
    " Use ag in unite file_rec/async source
    let g:unite_source_rec_async_command = 'ag --nocolor --nogroup -g ""'
endif

nnoremap <c-i>     :execute('Unite file_rec/async:~/')<CR>
nnoremap <c-u>     :execute('Unite file_rec/async:~/work')<CR>
```

Also I use this for performance profiling:
```
nnoremap <silent> <LocalLeader>dd :exe ":profile start /tmp/profile.log"<cr>
                                \ :exe ":profile func *"<cr>
                                \ :exe ":profile file *"<cr>
                                \ :exe "echo 'Profiling vim performance...'"<cr>
nnoremap <silent> <LocalLeader>dq :exe ":profile pause"<cr>
                                \ :exe ":!urxvtc -e vim /tmp/profile.log"<cr>
                                \ :exe ":noautocmd qall!"<cr>
```

* Reproducable ways from Vim starting

 0. start vim
 1. Try using `<c-i>`
 2. notice delay

Profile: https://dl.dropboxusercontent.com/u/1973208/logs/vim_slow.log

And:

 0. start vim
 1. try using `<c-u>`
 2. notice almost no delay

Profile: https://dl.dropboxusercontent.com/u/1973208/logs/vim_fast.log

* Reproducable ways from NeoVim starting

 0. start vim
 1. Try using `<c-i>`
 2. notice delay

Profile: https://dl.dropboxusercontent.com/u/1973208/logs/nvim_slow.log

And:

 0. start vim
 1. try using `<c-u>`
 2. notice almost no delay

Profile: https://dl.dropboxusercontent.com/u/1973208/logs/nvim_fast.log

**Comment by Shougo** [comment]
Please check unite#filters#lua_filter_patterns arguments.
I think `a:candidates` is very big in slow state.

I get it.
In default, unite.vim does not recognize .agignore.
Because, file_rec/async uses "find" command instead of ag.
To use ag, you must add below configuration.

```vim
		" Using ag as recursive command.
		let g:unite_source_rec_async_command =
                \ 'ag --follow --nocolor --nogroup --hidden -g ""'
```

> I have an .agignore file that ignores most contents of ~/ except for the work directory and a few others that aren't that big.

So, it is big candidates.

**Comment by tony** [comment]
In https://github.com/Shougo/unite.vim/issues/890#issuecomment-89846125 I am using:

```viml

  let g:unite_source_rec_async_command = 'ag --follow --nocolor --nogroup --hidden ' .
        \ '--ignore ''.hg'' --ignore ''.svn'' --ignore ''.git'' --ignore ''.bzr'' ' .
        \ '--ignore ''**/*.pyc'' -g ""'
```

```
FUNCTIONS SORTED ON SELF TIME
count  total (s)   self (s)  function
    3             15.001524  unite#filters#lua_filter_patterns()
    2              2.815643  unite#filters#vim_filter_pattern()
    2   1.344312   1.186561  <SNR>131_get_ignore_results()
    2   0.928173   0.927553  neobundle#autoload#insert()
    1              0.602585  <SNR>145_SetUpPython()
 1221   0.124681   0.122903  <SNR>126_glob2_pattern()
    1   0.109866   0.070147  unite#view#_quit()
    1   0.093932   0.062141  <SNR>119_init_continuation()
    1   0.032812   0.032679  unite#sources#history_unite#add()
  178              0.028033  <SNR>131_parse_ignore_file()
   11   0.033344   0.027353  <SNR>106__build_module()
    1              0.026483  unite#helper#paths2candidates()
    2   0.017931   0.017923  unite#filters#converter_relative_word#lua()
   28   0.020976   0.015644  neobundle#autoload#function()
   17   0.058965   0.014250  unite#init#_default_scripts()
   14   0.017893   0.009048  <SNR>106__get_sid_by_script()
    1   0.109329   0.008657  42()
   17              0.008195  <SNR>106__redir()
    6   0.130666   0.005985  unite#filters#globs2lua_patterns()
   33              0.005802  neobundle#config#get_autoload_bundles()
```

I still get big performance drops with filtering and ignoring, even through ``g:unite_source_rec_async_command`` is set.

How is it that ``ctrlp.vim`` with ag is able to do this do fast?  I've tried ctrlp.vim with and without vcs but it is relatively slow the first round (2-3 seconds on a big project) but then cache makes is instant afterwards. Of course, ctrlp.vim with git-ls is faster yet.

**Comment by Shougo** [comment]
@tony You use `matcher_ignore_project_files` in your .vimrc.  It is too slow.

**Comment by tony** [comment]
@Shougo If I remove ``matcher_ignore_project_files``:

```
FUNCTIONS SORTED ON TOTAL TIME
count  total (s)   self (s)  function
    1   3.606190   0.000363  <SNR>66_call_unite_empty()
    1   3.598913   0.000274  unite#start()
    1   3.597134   0.000788  unite#start#standard()
    1   3.534837   0.000325  unite#candidates#_recache()
    1   3.533270   0.000757  <SNR>125_recache_candidates_loop()
    2   3.493968   0.006005  <SNR>125_get_source_candidates()
    2   3.360088   0.001313  <SNR>125_ignore_candidates()
    2   2.848638             unite#filters#vim_filter_pattern()
    2   0.918248   0.917695  neobundle#autoload#insert()
   32   0.917720   0.000329  neobundle#config#source_bundles()
    1   0.917391   0.000688  neobundle#config#source()
    3   0.909333   0.004596  <SNR>7_on_source()
    1   0.605224   0.000692  youcompleteme#Enable()
    1   0.603490             <SNR>143_SetUpPython()
    1   0.507965   0.000021  unite#filters#filter_patterns()
    1   0.507923             unite#filters#lua_filter_patterns()
    1   0.284347   0.000188  syntastic#util#system()
    1   0.127592   0.009122  42()
    1   0.108736   0.069343  <SNR>119_init_continuation()
   15   0.050747   0.012687  unite#init#_default_scripts()

FUNCTIONS SORTED ON SELF TIME
count  total (s)   self (s)  function
    2              2.848638  unite#filters#vim_filter_pattern()
    2   0.918248   0.917695  neobundle#autoload#insert()
    1              0.603490  <SNR>143_SetUpPython()
    1              0.507923  unite#filters#lua_filter_patterns()
    1   0.108736   0.069343  <SNR>119_init_continuation()
    1              0.032165  unite#helper#paths2candidates()
   11   0.029091   0.023596  <SNR>106__build_module()
    2   0.016954   0.016946  unite#filters#converter_relative_word#lua()
   26   0.018324   0.013688  neobundle#autoload#function()
   15   0.050747   0.012687  unite#init#_default_scripts()
    1   0.127592   0.009122  42()
   14   0.016313   0.008223  <SNR>106__get_sid_by_script()
   17              0.007208  <SNR>106__redir()
    1   0.006998   0.006941  <SNR>120_readfile()
    2   3.493968   0.006005  <SNR>125_get_source_candidates()
   31              0.005041  neobundle#config#get_autoload_bundles()
   11   0.049746   0.004763  <SNR>106__import()
    3   0.909333   0.004596  <SNR>7_on_source()
    1              0.004316  <SNR>141_InitializePythonBuiltin()
   63              0.003467  <SNR>106__unify_path()
```

This is a significant improvement.

**Comment by tony** [comment]
@Shougo That is enough to make me bring back unite.vim to my config. Thank you.

I would like to take it further. It would be nice to have a feature to use just ``file_rec/git`` but have a failsafe fallback option.

Is there any other tweaks I can make to my ``unite.vim`` to make it faster / more responsive?

**Comment by Shougo** [comment]
> I would like to take it further. It would be nice to have a feature to use just file_rec/git but have a failsafe fallback option.

file_rec/git is not file_rec/async.  The source behavior is not same.
You should create fallback mapping.

> Is there any other tweaks I can make to my unite.vim to make it faster / more responsive?

Well, you can disable `ignore_globs` feature in file_rec/async.

```vim
call unite#custom#source('file_rec/async', 'ignore_globs', [])
```

**Comment by tony** [comment]
https://github.com/Shougo/unite.vim/issues/890#issuecomment-89942505:

>> Yes, file_rec/git is faster. Can you make a feature where file_rec/git is tried and if not in a git project, falls back to file_rec/async / something else?
> I don't want to implement the feature

> file_rec/git is not file_rec/async. The source behavior is not same.
>You should create fallback mapping.

How could I do that?

**Comment by Shougo** [comment]
> That's ok. I'm curious as to why? Would it break intended functionality? 

> file_rec/git is not file_rec/async. The source behavior is not same.
> You should create fallback mapping.

> How could I do that?

Please consider it...
You can get the git project by `finddir('.git', ';')`.

**Comment by tony** [comment]
@Shougo : already on it.

Here is what I came up, any obvious improvements I could make VimL wise?

```viml

function! s:ExtractGitProject()
  let b:git_dir = finddir('.git', ';')
  return b:git_dir
endfunction

function! UniteGetSource()
  " If inside git dir, do file_rec/git, else file_rec/async
  if exists('b:git_dir') && (b:git_dir ==# '' || b:git_dir =~# '/$')
    unlet b:git_dir
  endif

  if !exists('b:git_dir')
    let dir = s:ExtractGitProject()
    if dir !=# ''
      let b:git_dir = dir
    endif
  endif

  if strlen(b:git_dir)
      return "file_rec/git"
    else
      return "file_rec/async:!"
  endif

endfunction


function! UniteGenericSource()
   let unite_source = UniteGetSource()
   let unite_command = "Unite -no-split -no-empty -start-insert " .
     \ "-buffer-name=files buffer " .
     \ unite_source
   exe unite_command
endfunction

" General fuzzy search
nnoremap <silent> [unite]<space> :execute "Unite -no-split -no-empty -start-insert " .
     \ "-buffer-name=files buffer " .
     \ UniteGetSource()<CR>
```

**Comment by Shougo** [comment]
Unfortunatelly, I have not much time to review your code.
But, ...

```vim
function! UniteGetSource()
  " If inside git dir, do file_rec/git, else file_rec/async
  if exists('b:git_dir') && (b:git_dir ==# '' || b:git_dir =~# '/$')
    unlet b:git_dir
  endif

  if !exists('b:git_dir')
    let dir = s:ExtractGitProject()
    if dir !=# ''
      let b:git_dir = dir
    endif
  endif
  return b:git_dir == '' ? return "file_rec/git" : "file_rec/async:!"
endfunction
```

is better.

**Comment by tony** [comment]
Here is a performance report of ``file_rec/async`` and ``file_rec/git`` with https://raw.githubusercontent.com/tony/vim-config/52d0e4c4ebad09e38b9bd8826cfdccccd21e0ee9/settings/unite.vim.

file_rec async Profile:  https://gist.github.com/tony/7fad2981b320febaeda4/raw/ed8143b9d097c40ed78815b642a4d74732894752/file_rec-async.log

file_rec git Profile: https://gist.githubusercontent.com/tony/7fad2981b320febaeda4/raw/90b5b41710d699159cbff1430b62495a881b1616/file_rec-git.log

Date: 2015-04-06
vim: 7.4.691
uname: 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt7-1 (2015-03-01) x86_64 GNU/Linux
Unite Config Settings: https://raw.githubusercontent.com/tony/vim-config/52d0e4c4ebad09e38b9bd8826cfdccccd21e0ee9/settings/unite.vim
file_rec/async.log is docutils (svn project repo)
file_rec/git.log is freebsd (github freebsd mirror)

```bash

$ vim --version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Apr  5 2015 13:16:22)
Included patches: 1-691
Compiled by tony@yoga
Huge version without GUI.  Features included (+) or not (-):
+acl             +farsi           +mouse_netterm   +syntax
+arabic          +file_in_path    +mouse_sgr       +tag_binary
+autocmd         +find_in_path    -mouse_sysmouse  +tag_old_static
-balloon_eval    +float           +mouse_urxvt     -tag_any_white
-browse          +folding         +mouse_xterm     -tcl
++builtin_terms  -footer          +multi_byte      +terminfo
+byte_offset     +fork()          +multi_lang      +termresponse
+cindent         +gettext         -mzscheme        +textobjects
+clientserver    -hangul_input    +netbeans_intg   +title
+clipboard       +iconv           +path_extra      -toolbar
+cmdline_compl   +insert_expand   -perl            +user_commands
+cmdline_hist    +jumplist        +persistent_undo +vertsplit
+cmdline_info    +keymap          +postscript      +virtualedit
+comments        +langmap         +printer         +visual
+conceal         +libcall         +profile         +visualextra
+cryptv          +linebreak       +python          +viminfo
+cscope          +lispindent      -python3         +vreplace
+cursorbind      +listcmds        +quickfix        +wildignore
+cursorshape     +localmap        +reltime         +wildmenu
+dialog_con      +lua             +rightleft       +windows
+diff            +menu            -ruby            +writebackup
+digraphs        +mksession       +scrollbind      +X11
-dnd             +modify_fname    +signs           +xfontset
-ebcdic          +mouse           +smartindent     -xim
+emacs_tags      -mouseshape      -sniff           +xsmp_interact
+eval            +mouse_dec       +startuptime     +xterm_clipboard
+ex_extra        -mouse_gpm       +statusline      -xterm_save
+extra_search    -mouse_jsbterm   -sun_workshop    -xpm
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H     -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1      
Linking: gcc   -L/usr/local/lib -Wl,--as-needed -o vim    -lSM -lICE -lXt -lX11 -lXdmcp -lSM -lICE  -lm -ltinfo -lnsl   -ldl  -L/usr/lib -llua5.2  -L/usr/lib/python2.7/config -lpython2.7    
```

**Comment by tony** [comment]
@Shougo Thank you!

My investment in unite.vim configuration wise is enough that tweaking performance is worth it.  I'm here for you in the mean time if you want to get benchmark results.

With https://github.com/tony/vim-config/blob/52d0e4c4ebad09e38b9bd8826cfdccccd21e0ee9/settings/unite.vim, both ``file_rec/git`` and ``file_rec/async`` is slow on first load as well as subsequent load. The lag time is about 5 or more seconds.

The ``file_rec/async`` project is docutils via SVN (http://svn.code.sf.net/p/docutils/code/trunk)

The ``file_rec/git`` project is freebsd (https://github.com/freebsd/freebsd.git)

**Comment by Shougo** [comment]
@tony You don't disable "matcher_project_ignore_files" in file_rec/git.
You should disable "ignore_globs" in file_rec/async and file_rec/git.

```vim
call unite#custom#source('file_rec/async,file_rec/git', 'ignore_globs', [])
```

**Comment by tony** [comment]
Latest vim config: https://github.com/tony/vim-config/blob/6d1f5f18c55367c33e6a230a1931db677d6cd8a9/settings/unite.vim

file_rec/async profile: https://gist.github.com/tony/876586124ecf7b8d0675/raw/file_rec%20async.log
file_rec/git profile: https://gist.github.com/tony/876586124ecf7b8d0675/raw/file_rec%20git.log

Much faster.

**Comment by Shougo** [comment]
```vim
call unite#custom#source(
      \ 'buffer,file_rec,file_rec/git', 'matchers',
      \ ['converter_relative_word', 'matcher_fuzzy',
      \  'matcher_project_ignore_files'])
```

You use "matcher_project_ignore_files". This is slower.

**Comment by tony** [comment]
@Shougo Sorry, I linked to a commit that didn't have the code I profiled with. https://github.com/tony/vim-config/blob/a07b669c3b5256e3af8e0f3aff5ce9fef5c2e5af/settings/unite.vim, that was fixed at the time.

I re-ran the profile just to be safe:

```
FUNCTIONS SORTED ON TOTAL TIME
count  total (s)   self (s)  function
    1   3.056172   0.000441  <SNR>66_call_unite_empty()
    1   3.046582   0.000359  unite#start()
    1   3.043756   0.000855  unite#start#standard()
    1   2.966317   0.000644  unite#candidates#_recache()
    1   2.955037   0.000818  <SNR>124_recache_candidates_loop()
   12   2.506838   0.000234  unite#helper#call_filter()
    4   2.505102   0.000399  unite#helper#call_source_filters()
    1   2.333099   0.000076  58()
    1   2.332700   2.328160  <SNR>130_get_ignore_results()
    2   1.124573   1.123453  neobundle#autoload#insert()
   37   1.123524   0.000387  neobundle#config#source_bundles()
    1   1.123137   0.000740  neobundle#config#source()
    3   1.113969   0.004111  <SNR>7_on_source()
    1   0.625995   0.000418  youcompleteme#Enable()
    1   0.624562             <SNR>147_SetUpPython()
    1   0.469812   0.000156  syntastic#util#system()
    2   0.447040   0.028407  <SNR>124_get_source_candidates()
    1   0.410860   0.036695  46()
    1   0.367501   0.236205  <SNR>118_init_continuation()
    1   0.271709   0.000032  <SNR>143_exit()

FUNCTIONS SORTED ON SELF TIME
count  total (s)   self (s)  function
    1   2.332700   2.328160  <SNR>130_get_ignore_results()
    2   1.124573   1.123453  neobundle#autoload#insert()
    1              0.624562  <SNR>147_SetUpPython()
    1   0.367501   0.236205  <SNR>118_init_continuation()
    1   0.271589   0.187394  unite#view#_quit()
    1              0.118265  unite#helper#paths2candidates()
    1   0.080240   0.080166  unite#sources#history_unite#add()
    2   0.067485   0.067477  unite#filters#converter_relative_word#lua()
    1   0.410860   0.036695  46()
    1   0.083669   0.032298  67()
    2   0.447040   0.028407  <SNR>124_get_source_candidates()
   11   0.031664   0.025965  <SNR>106__build_module()
 2000              0.024853  <SNR>140_convert_to_abbr()
 1221              0.017291  <SNR>107_truncate()
   31   0.022696   0.016767  neobundle#autoload#function()
   17   0.064922   0.016417  unite#init#_default_scripts()
    1   0.012865   0.012823  <SNR>119_readfile()
   14   0.019542   0.009854  <SNR>106__get_sid_by_script()
    2   0.009002   0.008952  unite#init#_candidates_source()
   17              0.008423  <SNR>106__redir()
```

**Comment by tony** [comment]
Stackoverflow post on unite.vim and huge projects: http://stackoverflow.com/questions/24962356/navigating-through-a-huge-project-with-vim-and-unite-vim-plugin

**Comment by balta2ar** [comment]
Just for the record, this might be related: https://github.com/Shougo/unite.vim/issues/848.

In fact, if you really want to use `matcher_project_ignore_files`, its performance can be dramatically improved as @Shougo and me determined in the #848. That requires making a simple external plugin that uses ![re2](https://github.com/google/re2) for filtering and integrating that with Unite. I already started developing a hacky solution but I can't finish it due to lack of time. You can easily build it yourself, all the necessary code was provided in the above mentioned ticket. Contributions are welcome, though. 

And yes, I should probably try using fzf, it's really nice and fast.
