### ISSUE TITLE
Unite grep to accept several parameters

### ISSUE THREAD

**Issue by carlesandres** [Shougo/unite.vim#889]
I am using `ag` as my `grep` replacement with `unite` with little problem so far.

However, although the following works perfectly fine for me in vim:
```
:Ag --sass --css something
```

I get an error when using this:
```
nnoremap <leader>sc :<C-u>Unite -no-split -no-quit grep:--css --sass<cr>
```

The error is:
```

unite.vim: Invalid option "--sass" is detected.
```

I understand that this might not be an issue but me using the wrong syntax. However I couldn't find the documentation to solve it by myself.

**Comment by Shougo** [comment]
You must escape spaces.

```vim
nnoremap <leader>sc :<C-u>Unite -no-split -no-quit grep:--css\ --sass<cr>
```

**Comment by carlesandres** [comment]
Thanks @Shougo . Now I have to figure out this other error: 

```
[grep] Command-line: "ag" --column --nogroup --nocolor --follow   'some' "--css --sass"
[grep] ag: unrecognized option `--css --sass'
```

**Comment by rgrinberg** [comment]
@carlesandres FWIW I gave up on using unite directly for search like this. I just search with `:Ag` and then https://github.com/osyo-manga/unite-quickfix the results

**Comment by carlesandres** [comment]
@rgrinberg Not a bad advice. Thanks! I am also struggling to make the `--css` flag in `ag` to support `.scss` files by default as there is, apparently, nothing similar to `.ackrc` in `ag`. 

Could you manage to figure that out by any chance?

**Comment by rgrinberg** [comment]
@carlesandres I think you're out of luck. You can just ack for this use case though and it will work just fine. What I do is just search with `:Ag! -G '\.s?css$' query` if I really need this feature. You can always create some keymap for it...
