### ISSUE TITLE
Display dotfiles in search results

### ISSUE THREAD

**Issue by tecfu** [Shougo/unite.vim#894]
I use the following two .vimrc key mappings to do my unite searches:

```
nnoremap <silent> <leader>j :Unite buffer file file_mru<CR>
nnoremap <silent> <leader>f :<C-u>Unite
      \ -buffer-name=files file_rec/async<CR>
```

However, I can't get dotfiles to display in the results. Neither directories beginning with a dot i.e. ".vim" or files beginning with a dot i.e. ".vimrc". 

I didn't find any issues mentioning this nor did I see any reference to the issue in the docs or via Google search. Can this be implemented?

**Comment by Shougo** [comment]
It is implemented.  But you must insert character ".".

```
				*unite-filter-matcher_hide_hidden_files*
matcher_hide_hidden_files
		Hide hidden files filter.  If your input contains ".", hidden
		files will be appeared.
```

**Comment by tecfu** [comment]
That's fine for when you start in insert mode. However, what about when you are scrolling through the split window using shortcuts? In that case, once you type "." you are no longer able to scroll through the list and open a directory (i.e. ".vim") using a keyboard shortcut.  

```
nnoremap <silent> <leader>j :Unite buffer file file_mru<CR>
```
Is there a way to see the dot files while retaining the ability to <b>scroll select</b> in the unite search results?

**Comment by tecfu** [comment]
Also, my vimrc does not invoke "matcher_hide_hidden_files". It only invokes fuzzy finder.

```
call unite#filters#matcher_default#use(['matcher_fuzzy'])
```

**Comment by Shougo** [comment]
If you want to disable "matcher_hide_hidden_files", you must use `unite#custom#source()`.
Because, the sources use "matcher_hide_hidden_files" like below.

```vim
let s:source_file = {
      \ 'name' : 'file',
      \ 'description' : 'candidates from file list',
      \ 'ignore_globs' : [
      \         '.', '..', '*~', '*.o', '*.exe', '*.bak',
      \         'DS_Store', '*.pyc', '*.sw[po]', '*.class',
      \         '.hg/**', '.git/**', '.bzr/**', '.svn/**',
      \ ],
      \ 'default_kind' : 'file',
      \ 'matchers' : [ 'matcher_default', 'matcher_hide_hidden_files' ],
      \ 'hooks' : {},
      \}
```

`[ 'matcher_default', 'matcher_hide_hidden_files' ]` is `call unite#filters#matcher_default#use(['matcher_fuzzy'])` and "matcher_hide_hidden_files".
So dot files supposed to be hidden by default.

```vim
call unite#custom#source('file', 'matchers', 'matcher_default')
```

**Comment by tecfu** [comment]
That's exactly what I wanted to know. Thanks!

**Comment by albertnetymk** [comment]
@tecfu What's the final config you ended up using? I have basically the same requirement as you.

I could use the following to show the dotfiles by default, but they show up with absolute path, instead of relative path I got if I use the default config and type '.'.
```
call unite#filters#matcher_default#use(['matcher_fuzzy'])
call unite#custom#source('file_rec,file_rec/async,file_mru,file,buffer,grep',
  \ 'matchers', ['matcher_default'])
```

**Comment by albertnetymk** [comment]
@tecfu Never mind. I didn't config it properly. The config, showing dotfiles by default with relative path, if anyone is interested:

```
call unite#filters#matcher_default#use(['matcher_fuzzy'])
call unite#custom#source('file_rec,file_rec/async,file_mru,file,buffer,grep',
  \ 'matchers', ['converter_relative_word', 'matcher_default'])
```
