### ISSUE TITLE
history_yank: only write the file if it's changed

### ISSUE THREAD

**Issue by blueyed** [Shougo/unite.vim#895]
With `history_yank` enabled, the `g:unite_source_history_yank_file` file gets written on every cursor moved.

I've noticed this when using [fatrace](http://www.piware.de/2012/02/fatrace-report-system-wide-file-access-events/) to monitor filesystem events.

It should be written only when it has changed and then maybe only during other events, which are not triggered so often, e.g. when inserting/leaving insert mode and on CursorHold/CursorHoldI maybe?!

**Comment by Shougo** [comment]
I tested it.  But it is not save in every cursor move.
Please see below routine.

```vim
function! unite#sources#history_yank#_append() "{{{
  call s:load()

  let prev_histories = copy(s:yank_histories)

  call s:add_register('"')

  if g:unite_source_history_yank_save_clipboard
    " Skip if registers are identical.
    if @" !=# @+
      call s:add_register('+')
    endif
  endif

  if prev_histories !=# s:yank_histories
    " Updated.

    if g:unite_source_history_yank_limit < len(s:yank_histories)
      let s:yank_histories =
            \ s:yank_histories[ : g:unite_source_history_yank_limit - 1]
    endif

    call s:save()
  endif
endfunction"}}}
```

`call s:save()` is called if prev_histories is changed.  It is not every.
If I'm wrong, please correct me.

**Comment by blueyed** [comment]
Sorry for the confusion.

What I've actually meant is that `s:load()` gets called then, which checks if the file is readable and  looks at its modification time.
I don't think this should get done on every cursor move.  I can see that this might be necessary in some cases, if you want to keep the history in sync as much as possible.  But for the common use case, this could be done only with `CursorHold` etc instead.

**Comment by blueyed** [comment]
btw: I've used `unsilent echom "LOAD"` to visualize it.

**Comment by Shougo** [comment]
I improved it.
