### ISSUE TITLE
"Unite find" does not implement the new Eval Feature #864

### ISSUE THREAD

**Issue by maikelmeyers** [Shougo/unite.vim#897]
"Unite grep" works like a charm with the new eval feature (#864), which allows globs and multiple directorys, i.e. ```Unite grep:`glob('/dir1/*.txt')."\n".glob('/dir2/*.txt')`:-ir:searchFoo```

But "Unite find" does not support this. For example:
```Unite find `"/dir1\n/dir2"`:-type\ f```

**Comment by Shougo** [comment]
Unite find supports eval feature.  But it does not support multiple directories feature.
I will implement it later.
