### ISSUE TITLE
Move cursor when new item is inserted by async source.

### ISSUE THREAD

**Issue by ikeji** [Shougo/unite.vim#898]
Hi,

I usually use unite.vim with multiple sources.
:Unite source1 source2
And source1 needs longer time (ex file_rec/async) than source 2 (ex. buffer).

At first, unite.vim will show the list from source 2 only.
```
> 
  source2 foo
  source2 bar
  source2 buzz
```
I'd like to select "bar" by push the "Esc" and "jj".
```
> 
  source2 foo
  source2 bar  <-- cursor is here.
  source2 buzz
```
Then I'll hit a enter, but before it source1 response.

Expected behavior:
```
> 
  source1 hoge
  source1 fuga
  source1 piyo
  source2 foo
  source2 bar  <-- cursor is here.
  source2 buzz
```

Current behavior:
```
> 
  source1 hoge
  source1 fuga  <-- cursor is here. moved from bar to fuga.
  source1 piyo
  source2 foo
  source2 bar
  source2 buzz
```

Can we move cursor with candidate when insert new candidate before cursor?
Or can we wait insert candidate few msec when user move cursor?

**Comment by Shougo** [comment]
> Can we move cursor with candidate when insert new candidate before cursor?

Yes.  But it is not easy to implement.

> Or can we wait insert candidate few msec when user move cursor?

It cannot.

**Comment by ikeji** [comment]
I agree this is not easy change.

> > Can we move cursor with candidate when insert new candidate before cursor?

> Yes. But it is not easy to implement.

That's sad :(

> > Or can we wait insert candidate few msec when user move cursor?

> It cannot.

I guess you can use CursorHold.
1. Setup CursorHold and switch to pending mode when cursor move.
2. If source make more candidate in this mode, pending update.
3. Update and revert mode when CursorHold is fired.

**Comment by Shougo** [comment]
> I guess you can use CursorHold.

Unfortunatelly, it is already implemented.

**Comment by Shougo** [comment]
I have more important issues.

I think https://github.com/Shougo/unite.vim/issues/825 is important than it.
So it is low priority.
