### ISSUE TITLE
Grep command cancelled

### ISSUE THREAD

**Issue by carlesandres** [Shougo/unite.vim#899]
Hi @Shougo 

I've recently updated my vim plugins and this command:
```
Unite -no-split grep:--js
```

which used to work fine is not working anymore for me. I just get a `[grep] canceled` message and no results.

Do you think it can be related to `unite`? (I am using `ag`). Let me know if you need me to send you my unite configuration.

**Comment by Shougo** [comment]
```
						*unite-source-grep*
grep		Nominates "grep" command output as candidates.
		Note: This source is created by Sixeight.

		Note: This source requires |vimproc|.  Please install.
		http://github.com/Shougo/vimproc

		Source arguments:
		1. the target directories splitted by newlines.
		2. "grep" options.
		3. the narrowing pattern (if you omit it, |unite-options-input|
		or input prompt is used).
		Max candidates: |g:unite_source_grep_max_candidates|
```

You should use `Unite -no-split grep::--js`.

**Comment by Shougo** [comment]
What's the "--js"?  I tested it in ag command.  But "unrecognized option '--js'" is displayed.

**Comment by carlesandres** [comment]
`--js` is the option to say `only look in filetype js` , which, by deault, is files with the `.js` extension.

This used to work for me until recently. I know for a fact because I am using the exact same mapping from my `.vimrc` file.

**Comment by carlesandres** [comment]
The equivalent `ag.vim` command would be:
```
:Ag --js somepattern
````

or from the shell:
```
ag --js somepattern
```

I don't need to specify the folder in this case because I just want to search in all my current working directory.

**Comment by Shougo** [comment]
OK.  In ubuntu 14.04, ag does not support the feature.

Can you try `Unite -no-split grep::--js`?

**Comment by Shougo** [comment]
> which used to work fine is not working anymore for me. I just get a [grep] canceled message and no results.

It is because you specified "--js"  as target directory.
grep source ignores "-" options.

**Comment by carlesandres** [comment]
It works. :+1:  However, it now asks for the `Target` folder which didn't happen before. 

Not a big deal, but it was nice to have it working with one less keystroke. :-)

Anyway, thanks for your feedback and for your work on `unite` I use it all the time in many different ways. It is essential in my workflow.

**Comment by carlesandres** [comment]
I see. Would there be a way to call it so that I don't have to enter the `Target`?

**Comment by Shougo** [comment]
Please specify target directory like this: `Unite -no-split grep:.:--js`

**Comment by carlesandres** [comment]
Amazing! Thanks a lot!!
