### ISSUE TITLE
Can we remove the extra space characters?

### ISSUE THREAD

**Issue by concise** [Shougo/unite.vim#902]
Hi,

In Unite buffers, I wonder whether or not the space characters (highlighted in yellow below) at the end of each line are necessary.

![unite-extra-space-characters](https://cloud.githubusercontent.com/assets/830849/7254048/1d2dd386-e873-11e4-9513-12cea38f1fb9.png)

Because I have a small Vim script that highlights all the characters beyond the Nth column (e.g. by matching `.\%>81v.*` for N=80) for all buffers/windows by default, I always get a block of space characters highlighted when I enter a Unite buffer using a wide split window.

I know I can explicitly exclude Unite buffers based on filetype or something, but if those space characters are not necessary, it might be nice to just remove them.  Thanks!

##### How to reproduce

Assuming we have `/tmp/unite.vim`, start `vim` with the following command in a `bash` shell:

```
vim -Nu NORC --cmd 'se hls rtp=/tmp/unite.vim,$VIMRUNTIME' '+sil! / \+'
```

In vim, list all files under unite.vim directory using the Unite source `file`

```
:Unite -no-split file:/tmp/unite.vim
```

**Comment by concise** [comment]
Although I have not look into the source code yet, maybe the space characters are for padding purpose, so that selected candidates can be highlighted in a consistent way?

Maybe I miss something important, but the default window-local option `'cursorline'` is quite enough for me if I want to know where the cursor is.

**Comment by Shougo** [comment]
No.  It cannot.
This feature is to highlight whole line in unite buffer.

**Comment by Shougo** [comment]
> Maybe I miss something important, but the default window-local option 'cursorline' is quite enough for me if I want to know where the cursor is, and I wouldn't care too much about how to highlight other non-cursor lines.

No.  It is not same behavior.  If your cursor is on input line, unite.vim will be highlight first candidate line.
And The 'cursoline' feature has same problem(cannot highlight not paddinged line).

**Comment by concise** [comment]
Dear Shougo, thanks for your reply!  But what I meant is that: we only need to `:setlocal nocursorline` when the cursor is right at the input line and inside insert mode.

When the cursor is not in the situation, we can set `cursorline` option based on the user's preference.

If we do so, the selected candidates can still be highlighted using `uniteMarkedLine` as before (but without trailing white space characters) and we are able to highlight **the whole line** where our cursor is using `CursorLine`.

**Comment by Shougo** [comment]
> Because I have a small Vim script that highlights all the characters beyond the Nth column (e.g. by matching .\%>81v.* for N=80) for all buffers/windows by default, I always get a block of space characters highlighted when I enter a Unite buffer using a wide split window.

You should use 'colorcolumn' feature.

> Dear Shougo, thanks for your reply! But what I meant is that: we only need to :setlocal nocursorline when the cursor is right at the input line and inside insert mode.

It changes the behavior.  I don't agree with you.

**Comment by Shougo** [comment]
Well, I may change the behavior.

**Comment by concise** [comment]
Thanks for taking that into consideration!  Maybe we can have a new Unite option, so that Unite could change this little behavior only when the user needs it, and Unite continues to behave in a backward-compatible way for other people.

By the way, though a little bit off topic, to indicate whether we have some lines that are **too long** in the current buffer, the `'colorcolumn'` option added in Vim 7.3 a few years ago is in fact far from optimal...  Because most of the time, we don't want to be **distracted** by a vertical bar with a different color all the time.

We would like to be notified only when some character goes beyond the allowed column number.  And when we are writing in a language like Japanese or Chinese, a character that occupies **more than one column** can not reliably be highlighted by a 'colorcolumn'.  (Or we have to use something like `:set colorcolumn=80,81`.)

The only way to reliably do that without distracting the user, is by highlighting text matched by the pattern `.\%>81v.*` only.

##### :set colorcolumn=80 (not good enough for Japanese/Chinese characters)
![with-colorcolumn](https://cloud.githubusercontent.com/assets/830849/7269154/9c29c5d8-e903-11e4-90df-ecf029cb88dd.png)

##### match /.\%>81v.*/
![with-custom-match](https://cloud.githubusercontent.com/assets/830849/7269155/a0f5ae2e-e903-11e4-9dc3-3bdecace9f0c.png)

**Comment by Shougo** [comment]
> Thanks for taking that into consideration! Maybe we can have a new Unite option, so that Unite could change this little behavior only when the user needs it, and Unite continues to behave in a backward-compatible way for other people.

I don't want to add option.  I consider the problem for performance perspective.

> We would like to be notified only when some character goes beyond the allowed column number. And when we are writing in a language like Japanese or Chinese, a character that occupies more than one column can not reliably be highlighted by a 'colorcolumn'. (Or we have to use something like :set colorcolumn=80,81.)

OK.  I get it.
