### ISSUE TITLE
Cursorline highlight behavior will be change

### ISSUE THREAD

**Issue by Shougo** [Shougo/unite.vim#905]
I will change cursorline highlight behavior for performance purpose.

* Use cursorline feature.
* Don't highlight cursorline in input line.
* Don't add padding spaces in candidates.   It is faster.

Related issue: https://github.com/Shougo/unite.vim/issues/902

**Comment by Shougo** [comment]
Implemented.

**Comment by petobens** [comment]
Is it possible to still use the previous behavior? I would like to highlight the cursor line with `PMenuSel` highlight group as I used to. Thanks

**Comment by Shougo** [comment]
You can change the highlight by changing `hl-CursorLine`.

**Comment by petobens** [comment]
@Shougo , yes I know that. Is it possible to change it only for the unite buffer? How should I do it?

**Comment by Shougo** [comment]
Unfortunatelly, I don't know.  You should use autocmd.
I don't restore the behavior by performance purpose.

**Comment by mrbiggfoot** [comment]
Sorry for possible irrelevant question, but I have a trouble with cursor line highlighting. It works only when I press 'j' or 'k' in a single keystroke, i.e. move up or down only one line. When I hold 'j' or 'k' for a while, the cursor goes up/down, but the cursor line highlighting disappears. It reappears only when I press a single 'j' or 'k' keystroke again. How do I fix that? (I tried remapping <Up> to "<Up>:redraw", but it did not work).

**Comment by petobens** [comment]
@Shougo  using 
```vim
    au Filetype unite hi! link CursorLine PmenuSel
```
works but the first match is not  highlighted. I don't know if that can be (or can't be) fixed. 
What type of event should I use for the autocommand?

**Comment by Shougo** [comment]
@mrbiggfoot `:help g:unite_cursor_line_time`

> works but the first match is not highlighted. I don't know if that can be (or can't be) fixed.
What type of event should I use for the autocommand?

Unfortunatelly, it is (Vim's cursorline) feature.

**Comment by mrbiggfoot** [comment]
@Shougo That worked, thank you.

**Comment by petobens** [comment]
@Shougo okay. Can you please consider adding back (at least as an option) the previous highlight behavior?  I found really nice and useful to be able to highlight the unite buffer cursorline using my `PmenuSel` hl group.

**Comment by Shougo** [comment]
>  okay. Can you please consider adding back (at least as an option) the previous highlight behavior? I found really nice and useful to be able to highlight the unite buffer cursorline using my PmenuSel hl group.

No.

**Comment by mrbiggfoot** [comment]
@petobens 
```vim
autocmd FileType unite hi! link CursorLine PmenuSel
```

**Comment by petobens** [comment]
@mrbiggfoot  thank you. I actually tried using that autocommand but it doesn't work well (it doesn't highlight the first candidate and it is inconsistent/buggy):

![hl](https://cloud.githubusercontent.com/assets/2583971/7446178/d0e932d0-f1a6-11e4-979d-773698329553.gif)

**Comment by mrbiggfoot** [comment]
@petobens Yeah, I have that too. I think it's because the cursor is not actually on the first candidate when you type a file name (it's one line above). It could be fixed I think, but I don't care much. Did it use to work differently?

**Comment by mrbiggfoot** [comment]
@Shougo please remove "unite-options-cursor-line-highlight" from the doc as apparently it does not work anymore.

**Comment by Shougo** [comment]
@mrbiggfoot Thanks.  I removed it.

**Comment by Shougo** [comment]
> @mrbiggfoot thank you. I actually tried using that autocommand but it doesn't work well (it doesn't highlight the first candidate and it is inconsistent/buggy):

Yes.  It is feature.  Because, unite.vim skips first candidate in next line.
I can change the behavior, but you must press twice key to select second candidate.
It is intended behavior?

**Comment by Shougo** [comment]
I removed skip first candidate behavior.

**Comment by mrbiggfoot** [comment]
@Shougo I think the complaint was that the first line is not highlighted while you are typing a file name one line above. I agree that it's not aesthetically correct, but it's a minor issue.

**Comment by mrbiggfoot** [comment]
> I removed skip first candidate behavior.

@Shougo I'd rather have it back. Reason: I have "Tab" mapped to "Down" in Unite window's insert mode, so that the keyboard shortcuts are consistent with YouCompleteMe. Now imagine what happens: I'm typing a file name and I see that the file I want is the second match. Now to select it I have to press "Tab" twice, which is not correct. The first match should be selected by default, whether it's highlighted or not. I hope this justifies bringing the old behavior back.

**Comment by petobens** [comment]
>@Shougo I think the complaint was that the first line (the topmost match) is not highlighted while you are typing a file name one line above. I agree that it's not aesthetically correct, but it's a minor issue.

@mrbiggfoot , @Shougo yes, that was exactly my issue. Along the fact that when I use the highlight autocommand sometimes when I leave the unite buffer the cursorline is still highlighted with PmenuSel group instead of the regular CursorLine hl group.

**Comment by Shougo** [comment]
@mrbiggfoot OK.  I reverted it.

**Comment by chieping** [comment]
@petobens 

> @mrbiggfoot , @Shougo yes, that was exactly my issue. Along the fact that when I use the highlight autocommand sometimes when I leave the unite buffer the cursorline is still highlighted with PmenuSel group instead of the regular CursorLine hl group.]

```vim
autocmd BufEnter,BufWinEnter \[unite\]* highlight! link CursorLine PmenuSel
autocmd BufLeave \[unite\]* highlight! link CursorLine NONE
```

This might help you. Thanks!
