### ISSUE TITLE
:Unite -resume sometimes opens a small window

### ISSUE THREAD

**Issue by rstacruz** [Shougo/unite.vim#907]
There are times when I invoke :Unite and the window is just one line in height. I don't know how to reproduce it, but thought I'd just put it out ther.

**Comment by Shougo** [comment]
Unfortunately, I cannot reproduce it
So, I cannot fix it...
You should search the reproduce ways.

**Comment by mrbiggfoot** [comment]
I've got a repro:

1. start vim
2. \:Unite file
3. \:Unite -toggle
4. \:vs
5. \:UniteResume

Step 5 opens Unite window with 1 row height.

**Comment by Shougo** [comment]
Fixed.
