### ISSUE TITLE
Cursor movement without looping

### ISSUE THREAD

**Issue by mrbiggfoot** [Shougo/unite.vim#912]
There are unite_loop_cursor_up/down actions that move the cursor *and* jump to the bottom/top respectively when the boundary is reached. I have not found simple cursor movement actions without looping, e.g. unite_move_cursor_up/down that would just stop at the first/last line.
Can you please add them?

**Comment by Shougo** [comment]
Unfortunatelly, I don't want to add the mapping.
You can remove the loop mapping by `nunmap <buffer>j`.

**Comment by mrbiggfoot** [comment]
It does not work. Here's what I have in my .vimrc:

autocmd FileType unite call s:unite_settings()
function! s:unite_settings()
        nmap <buffer> p <Plug>(unite_toggle_auto_preview)
        nunmap <buffer> j
        nunmap <buffer> k
endfunction


When the unite window pops up I see the following:

Error detected while processing function <SNR>1_unite_settings:
line    2:
E31: No such mapping
line    3:
E31: No such mapping
line    2:
E31: No such mapping
line    3:
E31: No such mapping
line    2:
E31: No such mapping
line    3:
E31: No such mapping
line    2:
E31: No such mapping
line    3:
E31: No such mapping
line    2:
E31: No such mapping
line    3:
E31: No such mapping
line    2:
E31: No such mapping
line    3:
E31: No such mapping

**Comment by mrbiggfoot** [comment]
Well, actually I lied. It does work in the sense that it disables the looping, but those annoying messages make it impractical.

**Comment by mrbiggfoot** [comment]
Never mind, I just prepended "nunmap" with "silent!". I'm still learning :)
