### ISSUE TITLE
Default action not working with unite-gtags and -direction=below

### ISSUE THREAD

**Issue by mrbiggfoot** [Shougo/unite.vim#913]
When I invoke unite-gtags as "Unite gtags/ref" (while the cursor is pointing to a word), it works.
But when I use "Unite -direction=below gtags/ref", the window opens at the bottom but when I select a line and hit Enter nothing happens. The default action does not work.

**Comment by Shougo** [comment]
Please update unite.vim in latest version.   The problem is fixed.

**Comment by mrbiggfoot** [comment]
Yep, it's working now. Thanks for the quick response!
