### ISSUE TITLE
Close buffers after auto-preview

### ISSUE THREAD

**Issue by mrbiggfoot** [Shougo/unite.vim#914]
If one enables auto-preview and browses a lot of items in the unite window, there will be many opened buffers left even after the unite window is closed (the buffers that are opened by preview and never closed). The ideal behavior would be to close the buffer if it was not open before as soon as it goes out of the preview window.

**Comment by Shougo** [comment]
Implemented.

**Comment by mrbiggfoot** [comment]
This is a lot better, thanks! Though the last previewed buffer still remains open even if I close the auto-preview window. I don't know if it it is possible to handle <C-w>q on the preview window, but I think <Plug>(unite_toggle_auto_preview) should close the last opened preview buffer too.

There are couple more minor issues:
1. When I toggle (enable) auto preview, the preview window does not appear immediately. I have to press j or k after enabling preview, then the preview shows up.
2. When I toggle (disable) auto preview, the preview window disappears, but the height of the unite window becomes (original height of the unite window) + (height of the preview window which has been just closed). After I press j or k the unite window's height goes back to the original.

**Comment by mrbiggfoot** [comment]
There's one more problem with auto preview: its speed seems to depend linearly on the number of results in the unite window. Why is that? Opening a small file should take nearly constant time regardless of the number of items, right?

**Comment by Shougo** [comment]
@mrbiggfoot Your issue report is not easy to understand.
Please split the issue and read the issue template.
I have not much time to understand and reproduce the issues.

https://github.com/Shougo/unite.vim/issues/584

**Comment by Shougo** [comment]
> Though the last previewed buffer still remains open even if I close the auto-preview window. I don't know if it it is possible to handle <C-w>q on the preview window, but I think <Plug>(unite_toggle_auto_preview) should close the last opened preview buffer too.

I improved `<Plug>(unite_toggle_auto_preview)`.
Please don't close preview buffer by `<C-w>q`.

**Comment by mrbiggfoot** [comment]
@Shougo Thank you, sir! I truly appreciate all the work you've been doing.

**Comment by Shougo** [comment]
> 1. When I toggle (enable) auto preview, the preview window does not appear immediately. I have to press j or k after enabling preview, then the preview shows up.
>2. When I toggle (disable) auto preview, the preview window disappears, but the height of the unite window becomes (original height of the unite window) + (height of the preview window which has been just closed). After I press j or k the unite window's height goes back to the original.

Please update unite.vim and separate the issues.
I will try it.

**Comment by Shougo** [comment]
> When I toggle (enable) auto preview, the preview window does not appear immediately. I have to press j or k after enabling preview, then the preview shows up.

I think it is fixed.  Please update it.

> When I toggle (disable) auto preview, the preview window disappears, but the height of the unite window becomes (original height of the unite window) + (height of the preview window which has been just closed). After I press j or k the unite window's height goes back to the original.

I think it is feature.

**Comment by Shougo** [comment]
Because, original unite window size is `auto-previewed unite window size` + `preview window size`.
It is just become to original window size.
So your thought is wrong.

**Comment by mrbiggfoot** [comment]
I'm sorry, but I don't get it. I'll try to explain it in more details...
1. Bring up unite window, its height is X.
2. Enable auto-preview (<Plug>(unite_toggle_auto_preview)). The height of the auto-preview window is Y.
3. Disable auto-preview. The auto-preview window disappears, but the unite window's height becomes X+Y! That's just ugly, although I can live with it.
4. Then I press 'j' or 'k' and the unite window height goes back to X again. Can it go back to X right after the preview window is closed? I don't understand the "feature".

Thanks for the other fixes though!

**Comment by Shougo** [comment]
> I'm sorry, but I don't get it. I'll try to explain it in more details...

Please read issue template and create new issue.
I must reproduce it.

**Comment by Shougo** [comment]
> @Shougo Thank you, sir! I truly appreciate all the work you've been doing.

> Thanks for the other fixes though!

Please give me the minimal .vimrc and reproduce ways if you sympathize with me.
