### ISSUE TITLE
New "filelist" source?

### ISSUE THREAD

**Issue by mrbiggfoot** [Shougo/unite.vim#915]
Basically the problem (and even the solution!) is described here:
http://stackoverflow.com/questions/24962356/navigating-through-a-huge-project-with-vim-and-unite-vim-plugin

In a nutshell: for really big projects with complex dir structure I want to have a list of newline-separated file names generated by "find" or similar utility. It could be used for tags/ID generation and fast navigation.
So it would be great if we could have the "filelist" source integrated into the mainstream.

**Comment by Shougo** [comment]
Implemented.
