### ISSUE TITLE
Auto-preview speed depends on the number of items in the unite window

### ISSUE THREAD

**Issue by mrbiggfoot** [Shougo/unite.vim#916]
I search gtags with "Unite gtags/ref". If I have small number of tags to browse in the unite window, the auto-preview is fast. Otherwise, when there are thousands of references, the auto-preview becomes terribly slow. When I turn off auto-preview, I can navigate the unite window pretty quickly.

Essentially preview just opens a file under cursor, so it should not depend on the number of items in the unite window.

**Comment by Shougo** [comment]
I think it is just memory usage problem.
And "-auto-preview" feature is slow.
I cannot fix it.
