### ISSUE TITLE
Feature request: tree freature

### ISSUE THREAD

**Issue by mrbiggfoot** [Shougo/unite.vim#918]
It would be nice if we could have generic version of the unite-gtags 'treelize' behavior (see https://github.com/hewes/unite-gtags section 'treelize')

Let's say we search for something that exists in many files. Now we have output:
File1 LineNum1 something
File1 LineNum2 something
File1 LineNum3 something
File2 LineNum4 something

When editing source code with screen width 80 it, quite honestly, sucks.
Can we have an option to group items by file name, as follows:

File1
LineNum1 something
LineNum2 something
LineNum3 something
File2
LineNum4 something

And (it's important!) during navigation the cursor would skip lines with file names, i.e. when I press "down" on LineNum3 it would jump to LineNum4, not File2. Oh, and please, don't surround LineNum with bars in this case (like |15|, just 15 is good).

**Comment by Shougo** [comment]
Yes.  Tree feature is good and useful for several sources.
But it is not easy to implement.

**Comment by Shougo** [comment]
You should rename the title to "Feature request: tree freature".

Related issue: https://github.com/Shougo/unite.vim/issues/499

**Comment by mrbiggfoot** [comment]
Well, it's not a full-fledged tree... in the sense that it's depth is always 2. I don't think further grouping by parent directory name makes any sense in this case, since it would increase the indentation of the actual matches. And that's what I'm trying to avoid in the first place.
But if you want to call it a tree, fine.
