### ISSUE TITLE
-select=0 does not work and sorting order depends on the window position

### ISSUE THREAD

**Issue by mrbiggfoot** [Shougo/unite.vim#921]
There are two connected problems.

1. "\:Unite -select=0 -direction=botright file" selects the bottom candidate (should select the top one). While -select=1 selects the second from the top, -select=2 - the third etc., as they should (it's all about -direction=botright).

2. The -direction option affects the sorting order. I.e. "Unite -direction=topleft file" prints this:
file1
file2
file3
While "Unite -direction=botright file" prints the reverse:
file3
file2
file1

This is wrong. The sorting order should not depend on the window position.

**Comment by Shougo** [comment]
> This is wrong. The sorting order should not depend on the window position.

No.  Please see `:help unite-options-prompt-direction`.

**Comment by Shougo** [comment]
Fixed.

**Comment by mrbiggfoot** [comment]
> No. Please see :help unite-options-prompt-direction.

And where does it say that? Having sort order dependent on window position is WRONG. Like that, wrong in caps. Here's the section from the doc that you are referring to, just for completeness:

                                               unite-options-prompt-direction
                -prompt-direction="top" or "below"
                Specify the prompt direction.
                Note: If it is "below", unite-options-auto-resize is used
                automatically.  To disable it, you must set "-no-auto-resize"
                option.
                Default: "below" (if unite-options-direction contains "below")

Also, selection is still broken. Now -select=-1 does not work.
I want to be able to open a botright window with reverse search (since it's the new "normal") and select the topmost item automatically.

**Comment by Shougo** [comment]
> Also, selection is still broken. Now -select=-1 does not work.

No.  It is not broken.  Please use positive value ex: `-select=1`.

> Having sort order dependent on window position is WRONG. Like that, wrong in caps

I don't think so.  Please see ctrlp's plugin behavior(it is reversed order).
You can change the bahavior by `-prompt-direction` option.

**Comment by mrbiggfoot** [comment]
@Shougo Maybe ctrlp also does it wrong :) I have not checked. I can live with that as long as there is a way to select topmost candidate in a botright window using "-select".
-select=1 selects the bottom candidate. How do I select the top one?

**Comment by Shougo** [comment]
You should change `-prompt-direction` default option.

```vim
	call unite#custom#profile('default', 'context', {
	\   'prompt_direction': 'top'
	\ })
```

**Comment by mrbiggfoot** [comment]
Ok, that works. Thank you!
Although the Unite window height is always the same regardless of the number of candidates in it. But it's not a huge problem for me.

**Comment by Shougo** [comment]
> Although the Unite window height is always the same regardless of the number of candidates in it.

```vim
    call unite#custom#profile('default', 'context', {
    \   'prompt_direction': 'top',
    \   'auto_resize': 1,
    \ })
```

**Comment by mrbiggfoot** [comment]
Thank you, sir. Finally it's perfect for me! Now I think I'll stop filing bugs for a while :) Thank you once again and keep up the great work!
