### ISSUE TITLE
action__path に環境変数を含んだパスを開きたい

### ISSUE THREAD

**Issue by osyo-manga** [Shougo/unite.vim#923]
__[Twitter で言っていた要望です。](https://twitter.com/pink_bangbi/status/596628633134837760)__
`open` 等でファイルを開く場合に `expand()` を適用した状態（環境変数を展開して）でファイルを開くようにしてもらえると助かります。
これは `action__path` を設定するときに `expand()` すれば解決はするのですが、候補が数千ある source に対して `expand()` を行うとパフォーマンスに影響するので『ファイルを開くタイミング』で `expand()` の適用を行ないたいのです。

**Comment by Shougo** [comment]
実装しました

**Comment by osyo-manga** [comment]
ありがとうございます。
最新版で試してみたのですが、環境変数を含んだファイルを `open` しようとした場合に以下のようなメッセージが表示されます。

![](http://i.gyazo.com/b4a6560b4d5f1ecad77f80829386baf9.png)

`no` を選択すれば環境変数が展開された状態のファイルが開かれます。
このメッセージを消すことは可能なのでしょうか。

**Comment by Shougo** [comment]
修正しました

**Comment by osyo-manga** [comment]
こちらでも動作することを確認しました。
ありがとうございます。
