### ISSUE TITLE
file_rec/async doesn't resolve symbolic-linked directories

### ISSUE THREAD

**Issue by louispan** [Shougo/unite.vim#927]
`:Unite file_rec/async:FULL_PATH_TO_SYMLINKED_DIR` will end up opening the symlink as a file, instead of resolving the symbolic link

NB. `file` is working as expected `:Unite file:FULL_PATH_TO_SYMLINKED_DIR`

**Comment by louispan** [comment]
`file_rec` also works as expected `:Unite file_rec:FULL_PATH_T_SYMLINKED_DIR`

**Comment by Shougo** [comment]
I think you should include the change for it in https://github.com/Shougo/unite.vim/pull/926 change.
You can use `resolve()` function to implement it.
