### ISSUE TITLE
Unite buffer does not play well with <C-I> / <C-O>

### ISSUE THREAD

**Issue by yannack** [Shougo/unite.vim#929]
* Summary : Unite buffer sometimes appears when using `<C-O>` and then stays in the list of open buffers, even if closed using :UniteClose . 

* Expected: Unite buffer should only reappear using :UniteResume ,not when scrolling back using `<C-O>`. Also the behaviour is not consistent : sometimes `<C-O>` skips to the previous buffer directly, sometimes it shows the intermediate :Unite used.

* Environment. 
  - GNU/Linux 
  - Distro : Ubuntu 14.04 64 bits
  - Vim : 7.4.052

* Minimal vimrc less than 50 lines

```
set nocompatible
filetype off                   " required for Vundle
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'gmarik/Vundle.vim'
Plugin 'Shougo/unite.vim'
call vundle#end()            " required
set laststatus=2
let mapleader="\<Space>"
syntax on
set number
set hlsearch
set cursorline
set autowrite		" Automatically save before commands like :next and :make
set hidden		" Hide buffers when they are abandoned

" Unite settings
silent! call unite#filters#matcher_default#use(['matcher_fuzzy'])
silent! call unite#filters#sorter_default#use(['sorter_rank'])
nnoremap <leader>b :Unite buffer -buffer-name=buffers -no-split <CR>
autocmd FileType unite call s:unite_settings()
function! s:unite_settings()
  " Quit unite on backspace from normal mode, or using leader-q
  nnoremap <buffer> <BS> :UniteClose<CR>
  nnoremap <buffer> <leader>q :UniteClose<CR>
endfunction
```

* Reproducible way, from Vim's start:

0. cd /tmp
1. vi test1.c test2.c test3.c
2. type some stuff in test1.c
3. using :Unite buffer , go to test2.c
4. type some stuff in test2.c
5. using :Unite buffer , go to test3.c
6. type some stuff in test3.c
6. type `<C-O>` -> moves back to test2.c (this is OK)
7. type `<C-O>` -> *should* move back to test1.c, but opens a Unite buffer (the one with the buffers). A few more `<C-o>` will go to test1.c but the behaviour is not consistent. 

* Side issues 
  - Also, in stage 7. , the Unite buffer does not really disappear anymore (whether selecting a buffer, doing `<C-o>` or using :UniteClose) , it is still in the list of open buffers (using :ls lists it as a buffer).
  - `<C-I>` is remapped by Unite, so if you `<C-O>` into unite, there is no way to move forward...

**Comment by Shougo** [comment]
Unfortunatelly, I cannot fix it.
You should use `Unite jump`.

Please see the issue.
https://github.com/Shougo/unite.vim/issues/278

**Comment by yannack** [comment]
OK I understand. Thanks for the link, using the -wipe option is actually a workable solution for me in most cases. I could not find much documentation about :Unite jump, but it also looks interesting. I am pretty sure we could remap `<C-O>` and `<C-i>` using :Unite jump, but for now, the -wipe is enough. Thanks, @Shougo !
