### ISSUE TITLE
file_rec/async is not showing new file without clearing cache

### ISSUE THREAD

**Issue by jithin1987** [Shougo/unite.vim#930]
I have a git project directory for which Unite is working fine, till I added a new file. Unite was unable to list that in it's search until I deleted ~/.cache/unite directory. Restarting vim also didn't help.
Is this the way it's supposed to work, am I missing any settings ? These are my relevant settings

```
let g:unite_source_rec_async_command = 'ag --follow --nocolor --nogroup --hidden -g ""'
nnoremap <leader>t :<C-u>Unite -no-split -buffer-name=files   -start-insert file_rec/async:`projectroot#guess()` <cr>
```

**Comment by Shougo** [comment]
You should use `-force-redraw`.

```vim
nnoremap <leader>t :<C-u>Unite -no-split -buffer-name=files   -start-insert -force-redraw file_rec/async:`projectroot#guess()` <cr>
```

**Comment by gunar** [comment]
Uh, excuse me. I had the same problem. My question being, without `-force-redraw`, when does the cache get updated? I couldn't find the answer anywhere. Thanks :)

**Comment by wsdjeg** [comment]
by default,you can use `<c-l>` in unite buffer to update the cache

**Comment by gunar** [comment]
Cool. Thanks! Any drawback to using `-force-redaw`? It's fast enough here on NeoVim.

**Comment by Shougo** [comment]
@gunar It is the same.
