### ISSUE TITLE
Unite can't find source

### ISSUE THREAD

**Issue by orlp** [Shougo/unite.vim#931]
I'm trying to make a custom Unite source. This is my current code (only boilerplate, to find the command): https://github.com/orlp/unite-git-root/blob/bce05b34afe70df64a04997ba486c82a18078462/autoload/unite/sources/git_root.vim

When I run `:Unite file_rec/git_root`, it doesn't work. However, if I type `:Unite file_rec/git` and then press TAB, it finds `git_root`, and then it does work.

I'm puzzled - am I doing something wrong or is this a bug?

---

I'm using vim-plug to load the plugins, using:

    Plug 'Shougo/unite.vim'
    Plug 'orlp/unite-git-root'

**Comment by Shougo** [comment]
Please consider your file name:

```
CREATE SOURCE					*unite-create-source*

The files in autoload/unite/sources are automatically loaded and it
calls unite#sources#{source_name}#define() whose return value is the source.
Each return value can be a list so you can return an empty list to avoid
adding undesirable sources.  To add your own sources dynamically, you can use
|unite#define_source()|.

Note: To optimize load source files, if "buffer/rec" source name is detected,
unite.vim loads "autoload/unite/sources/buffer*.vim" or
"autoload/unite/sources/rec*.vim" files.  The source file name must have
source name prefix(Ex: buffer) or source name postfix(Ex: rec).
```

**Comment by Shougo** [comment]
Unite searches "file*.vim" and "root*.vim" and "rec*.vim".
But unite does not search "git_root*.vim".

**Comment by Shougo** [comment]
You should use "gitroot.vim" as filename.

**Comment by orlp** [comment]
> You should use "gitroot.vim" as filename and change source name to "file_rec/gitroot".

Why would that work, but not `git_root.vim` and `file_rec/git_root`?

**Comment by Shougo** [comment]
unite.vim use "/" or "_" as name separators.
But "file_rec/git_root" uses both of them.

**Comment by orlp** [comment]
@Shougo That means I could also keep using `file_rec/git_root` and name my file `root.vim`, right?

It seems to work - is there anything wrong with it?

**Comment by Shougo** [comment]
> @Shougo That means I could also keep using file_rec/git_root and name my file root_orlp.vim, right?

Yes.

**Comment by orlp** [comment]
@Shougo  All right, thanks for your help, that solves my problem.
