### ISSUE TITLE
cannot open subdirs in file/async

### ISSUE THREAD

**Issue by BimbaLaszlo** [Shougo/unite.vim#932]
I know, that this question already have to be somewhere on the net, but i didn't find it.
In the `:Unite file` command i can enter in to the directories inside the hitting `<CR>`. This not works in `:Unite file/async` and i can't find the cause of this - is it possible to navigate to subdirs like in the `:Unite file` or the async mode is usefull only for `file_rec/async`?

**Comment by Shougo** [comment]
It is feature.
If you want to navigate subdirectories, you can use `edit` action in file.

**Comment by Shougo** [comment]
You can use `:Unite directory/rec` source.

**Comment by Shougo** [comment]
I get it.  It is bug.

**Comment by Shougo** [comment]
Fixed it.
