### ISSUE TITLE
Feature request: dynamic Unite window width

### ISSUE THREAD

**Issue by mrbiggfoot** [Shougo/unite.vim#933]
Here's the propsal: add two more "direction" types for dynamic Unite window width, e.g. "-direction=dynamictop" and "-direction=dynamicbottom".

The behavior for "dynamicbottom" would be:
- if all the items in the Unite window can fit within the current window's width, the direction becomes "below". Otherwise it becomes "botright".

- Similarly for "dynamictop": if each item's length is less than the current window's width, the direction becomes "aboveleft", otherwise - "topleft".

The idea is to always make best effort to show all items without shortening.

On a side note: is there a way to display candidates as-is, one candidate per line, without wrapping and shortening? Shortening items to fit window always makes the items useless because it throws out important parts.

**Comment by Shougo** [comment]
> On a side note: is there a way to display candidates as-is, one candidate per line, without wrapping and shortening? Shortening items to fit window always makes the items useless because it throws out important parts.

I changed the truncate option behavior.
You can change truncate option to 0.

**Comment by mrbiggfoot** [comment]
Thank you, sir! The plugin becomes more and more amazing :)
