### ISSUE TITLE
select_next_line skips first line in the items list

### ISSUE THREAD

**Issue by zoresvit** [Shougo/unite.vim#938]
When `C-n` is pressed in `insert` mode, Unite skips the first line in the list of files or buffers.

For illustration, this is what Unite does after pressing `C-n` on the list of files:
![select_next_line](http://s2.postimg.org/vn7b9gde1/2015_05_17_222726_1919x381_scrot.png)
However the cursor is expected to highlight `CONTRIBUTING.md` file instead.

**Comment by Shougo** [comment]
It is feature.  But you can change the behavior by `g:unite_enable_auto_select` option.

```
g:unite_enable_auto_select		*g:unite_enable_auto_select*
		If it is 1, unite skip first candidate when cursor is on the
		prompt line.

		The default value is 1.
```

**Comment by Shougo** [comment]
> However the cursor is expected to highlight CONTRIBUTING.md file instead.

It cannot by implementation reason.

**Comment by zoresvit** [comment]
Ahh, I see. Thanks for the clarification and fast response! And for the awesome plugin of course  — just switched from `command-t` :)
