### ISSUE TITLE
gitignore negate pattern not supported

### ISSUE THREAD

**Issue by albertnetymk** [Shougo/unite.vim#943]
This [SO](http://stackoverflow.com/questions/2820255/how-do-negated-patterns-work-in-gitignore) talks about the negate pattern support in gitignore, but it seems unite doesn't recognize it.

The setup:

```
gittest :: (master*) » tree                                                                
.
└── test
    ├── hello
    └── hello.enc

1 directory, 2 files
gittest :: (master*) » cat .gitignore
test/*
!test/*.enc
gittest :: (master*) »
```

Starting `vim` in root of this git project, `untie` returns zero candidates.

**Comment by Shougo** [comment]
Unfortunatelly, it works.
test/hello.enc and .gitignore is displayed.

Please read the issue template.
https://github.com/Shougo/unite.vim/issues/584

**Comment by albertnetymk** [comment]
OK, after some debuging, I have narrowed it down to the condition `ag` section :

```
" unite
call unite#filters#matcher_default#use(['matcher_fuzzy'])
call unite#filters#sorter_default#use(['sorter_length'])

nmap <c-p> :Unite -start-insert buffer file_rec/async:!<cr>
nmap <leader>x :Unite -start-insert file_mru<cr>

if executable('ag')
  let g:unite_source_grep_command = 'ag'
  let g:unite_source_grep_default_opts =
        \ '-i --line-numbers --nocolor --nogroup --hidden --ignore ' .
        \  '''.hg'' --ignore ''.svn'' --ignore ''.git'' --ignore ''.bzr'''
  let g:unite_source_grep_recursive_opt = ''
  let g:unite_source_rec_async_command= 'ag --follow --nocolor --nogroup --hidden -g ""'
endif

call unite#custom#source('file_rec,file_rec/async,file_mru,file,buffer,grep',
  \ 'matchers', ['converter_relative_word',
  \ 'matcher_default', 'matcher_project_ignore_files'])

```
It works as you said if the `ag` section is removed. However, as soon as I put it back, only `.gitignore` is show in the candidate list using the original setup.

**Comment by Shougo** [comment]
I get it. It is `ag`'s problem.  `ag` does not support the pattern.
You should use `--skip-vcs-ignores` option.

```vim
let g:unite_source_rec_async_command= 'ag --follow --nocolor --nogroup --hidden -g "" --skip-vcs-ignores'
```

**Comment by albertnetymk** [comment]
Works like a charm. Thank you very much. Does it make sense to update the [doc](https://github.com/Shougo/unite.vim/blob/master/doc/unite.txt#L531) as well?

**Comment by Shougo** [comment]
I don't change it.  Because, "matcher_project_ignore_files" is slow..
