### ISSUE TITLE
Possible values for g:unite_source_grep_search_word_highlight

### ISSUE THREAD

**Issue by juanghurtado** [Shougo/unite.vim#947]
I can't find a list of possible values for `g:unite_source_grep_search_word_highlight`. I just see that the default values for this option is `Search`.

Specifically I want to disable search word highlighting in my `:Unite grep` commands.  But I can't find a way.

**Comment by Shougo** [comment]
If you want to disable the highlight, please set to `None`.

**Comment by Shougo** [comment]
You should read `:highlight` documentation.

**Comment by juanghurtado** [comment]
Thank you so much, Shougo. I will read `:highlight` docs.

2015-05-21 4:28 GMT+02:00 Shougo <notifications@github.com>:

> You should read :highlight documentation.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Shougo/unite.vim/issues/947#issuecomment-104105236>.
>



-- 
Juan G. Hurtado
juan.g.hurtado@gmail.com
