### ISSUE TITLE
UniteResume to restore top visible line

### ISSUE THREAD

**Issue by balta2ar** [Shougo/unite.vim#951]
At the moment it looks like `UniteResume` is restoring the cursor at the line where selection (action) was made. However, it does not restore the top line that was visible at the moment of action (jump). This becomes confusing when I go through grep results, selected line is **second to first** line of the window, and then I jump. When I do `UniteResume`, cursor is put on the previously selected line, but now it's **second to last** line of Unite window, which messes up the view and takes me a couple of moments to understand where I am now.

**Comment by Shougo** [comment]
```vim
:UniteResume -no-restore
```

**Comment by balta2ar** [comment]
@Shougo This does not solve my problem, I need exactly the opposite. This option disables cursor restoration, but I need it. In addition to cursor position, I need to restore the exact **view** (which line was first in Unite window before the jump).

**Comment by balta2ar** [comment]
Please see the example below.

Before the jump current line is at the top of the window. I press Enter.
![](http://i.imgur.com/DqtAgp6.png)

Now I do UniteResume and current line is at the bottom of the window (it was at the top before the jump).
![](http://i.imgur.com/GJUZWk6.png)

**Comment by balta2ar** [comment]
By the way, if I simply start grep search for the same pattern again, cursor and the view are restored exactly as I want and expect them to.

**Comment by Shougo** [comment]
OK.  I get it.
I will improve the behavior.

**Comment by balta2ar** [comment]
Sorry, but nothing's changed :( Current line is still at the bottom after UniteResume no matter where it was before the jump.

**Comment by Shougo** [comment]
@balta2ar Please create minimal .vimrc and upload reproduce ways.  I will test it.

**Comment by balta2ar** [comment]
Minimal vimrc:
``` vimrc
if has('vim_starting')
   set nocompatible               " Be iMproved
   set runtimepath+=~/.vim/bundle/neobundle.vim/
endif

call neobundle#begin(expand('~/.vim/bundle/'))
NeoBundleFetch 'Shougo/neobundle.vim'
NeoBundle 'Shougo/vimproc'

NeoBundle 'Shougo/unite.vim'
call neobundle#end()
NeoBundleCheck
```

Steps to reproduce:
``` bash
# get rsync source to test on
wget -O- https://download.samba.org/pub/rsync/src/rsync-3.1.1.tar.gz | tar xz
# run vim with custom vimrc
vim -u vimrc-min
```

Now do: `:Unite grep:rsync-3.1.1`, `Pattern: buffer`. You should see something like this:
![](http://i.imgur.com/JOxw31y.png)

Now press `PageDown` three times, notice that cursor is at the line `rsync-3.1.1/OLDNEWS: 3485`, and it is the top line in the window:
![](http://i.imgur.com/vXmvHjH.png)

Now do `:UniteResume` and notice that `rsync-3.1.1/OLDNEWS: 3485` is at the bottom:
![](http://i.imgur.com/E0Kzx6C.png)

Exact lines may vary depending on your font/terminal size, of course.

**Comment by Shougo** [comment]
Reproduced.  I will fix it later.

**Comment by Shougo** [comment]
Fixed.

**Comment by balta2ar** [comment]
I hate to say that but it's still working not as expected. Now current line always becomes the line in the middle of the window (it used to be always bottom line before your fixes).

**Comment by Shougo** [comment]
Fixed again.

**Comment by balta2ar** [comment]
Thank you, @Shougo! View is now restored as I described, it's very handy now!

One last thing, though. Window height is not saved/restored. For example, if I enlarge my Unite window with a mouse, then jump, then UniteResume, its height is default again. This might be something to argue about, but I just wanted to let you know about that. Do you think this is an issue worth fixing?

**Comment by Shougo** [comment]
> One last thing, though. Window height is not saved/restored.

It is feature.
