### ISSUE TITLE
Unite buffer first line is skipped when moving cursor down

### ISSUE THREAD

**Issue by balta2ar** [Shougo/unite.vim#953]
My command to raise buffer switch window is as follows: `Unite -buffer-name=buffer  -start-insert buffer`.

When I raise Unite window, first line is always skipped when moving using cursors (down key). Please see the example below.

![](http://i.imgur.com/wRq8Dz6.png)

Here cursor is on the first prompt line (>>). When I press `Down`, current line becomes "rsync.yo" instead of "config.guess".

EDIT: The image shows `file_rec/async` while I mentioned `buffer`. Just to be clear, both have the same problem.

**Comment by Shougo** [comment]
You can disable it by `g:unite_enable_auto_select`.

**Comment by balta2ar** [comment]
@Shougo Thanks, that helps!

However, isn't it a bug that the first line **is not highlighted** when `g:unite_enable_auto_select = 1`. The lack of highlighting confuses me.

**Comment by Shougo** [comment]
No.  It is feature...

> The lack of highlighting confuses me.

Yes.  But it cannot be changed.
