### ISSUE TITLE
Feature request: an API to clear all the caches

### ISSUE THREAD

**Issue by mrbiggfoot** [Shougo/unite.vim#954]
My use case is as follows: I have a vim command that rebuilds the current project's metadata - file list, tags, id database etc. After that, the Unite caches become invalid. It's kind of annoying to remember to press \<C-l\> in each source after such an update. Can we please have an API to purge all the caches in all the sources?

**Comment by Shougo** [comment]
You can use `:Unite -force-redraw {sources}` for the purpose.

**Comment by mrbiggfoot** [comment]
It would mean that I'll need a per-source flag to indicate whether the source's cache should be cleaned, right? And reset it after calling Unite with -force-redraw. Or, alternatively, use -force-redraw each time. Both approaches are not elegant and look more like a hack.

**Comment by Shougo** [comment]
Yes, because unite does not have clear cache API.

**Comment by Shougo** [comment]
And unite cannot clear all the caches.
Why?  Unite cannot load all sources.

> I have a vim command that rebuilds the current project's metadata - file list, tags, id database etc.

If you want to clear current projects' metadata, you don't have to all sources cache.
