### ISSUE TITLE
:UniteNext and :UnitePrevious are not working, though :UniteFirst and :UniteLast are working

### ISSUE THREAD

**Issue by sbhal** [Shougo/unite.vim#959]
:UniteNext and :UnitePrevious not working. I have verified for grep and line sources and its not working for me. FYI, I am not using any other unite-plugin like unite-quickfix.

My .vimrc
```
call unite#custom#profile('default', 'context', {
            \   'start_insert': 1,
            \   'winheight': 10,
            \   'direction': 'botright',
            \   })
nnoremap <Leader>8 :UniteWithCursorWord -no-quit -buffer-name=search grep:.<cr>
```

**Comment by Shougo** [comment]
I tested it.  But it works.
Please read the issue template.

https://github.com/Shougo/unite.vim/issues/584

**Comment by sbhal** [comment]
Problems summary

:UniteNext and :UnitePrevious aren't working

Expected

Both commands should work.

Environment Information

OS:Ubuntu x64 (10.04)
Vim version:Vim 7.4 (+lua)

let g:unite_data_directory='~/.vim/.cache/unite'
let g:unite_source_history_yank_enable=1
let g:unite_prompt='» '

call unite#filters#matcher_default#use(['matcher_fuzzy'])
call unite#custom#source('grep,line', 'matchers', 'matcher_fuzzy')
call unite#custom#profile('default', 'context', {
            \   'start_insert': 1,
            \   'vertical-preview': 1,
            \   'auto-resize': 1,
            \   'previewheight': 30,
            \   'winheight': 30,
            \   })

nnoremap <Leader>o :Unite -toggle -auto-resize -buffer-name=files file_rec/async:! buffer<CR>
nnoremap <Leader>/ :Unite -auto-resize -buffer-name=line line<CR>
nnoremap <Leader>y :Unite -start-no-insert history/yank<cr>
nnoremap <Leader>tt :Unite -auto-resize -start-insert tag<CR>
nnoremap <Leader>t :UniteWithCursorWord -auto-resize tag<CR>
nnoremap <Leader>t :Unite -auto-resize -buffer-name=tag tag tag/file<CR>
nnoremap <Leader>s :Unite -quick-match -no-split buffer<CR>
nnoremap <Leader>m :Unite -auto-resize -buffer-name=mappings mapping<CR>

nnoremap <Leader>/ :Unite -no-quit -auto-resize -auto-highlight -no-start-insert -buffer-name=search grep:.<cr>
nnoremap <Leader>8 :UniteWithCursorWord -no-quit -vertical-preview  -auto-highlight -keep-focus -no-start-insert -buffer-name=search grep:.<cr>

let g:ag_highlight=1
" I am using ag
if executable('ag')
    " Use ag in unite grep source.
    let g:unite_source_grep_command='ag'
    let g:unite_source_grep_default_opts=
                \ '-i --line-numbers --nocolor --nogroup --hidden --ignore ' .
                \  '''.hg'' --ignore ''.svn'' --ignore ''.git'' --ignore ''.bzr'''
    let g:unite_source_grep_recursive_opt=''
elseif executable('ack')
    let g:unite_source_grep_command='ack'
    let g:unite_source_grep_default_opts='--no-heading -C4'
    let g:unite_source_grep_recursive_opt=''
endif

" Custom mappings for the unite buffer
autocmd FileType unite call s:unite_keymaps()
function! s:unite_keymaps()
     " Play nice with supertab
    let b:SuperTabDisabled=1
    " Enable navigation with control-j and control-k in insert mode
    imap <buffer> <C-j> <Plug>(unite_select_next_line)
    imap <buffer> <C-k> <Plug>(unite_select_previous_line)
    imap <silent><buffer><expr> <C-s> unite#do_action('split')
endfunction


0.startup vim.
1.:Open any file.
2. Move to any word 
3. <Leader>8 -> (:UniteWithCursorWord -no-quit -vertical-preview  -auto-highlight -keep-focus -no-start-insert -buffer-name=search grep:.<cr>) 
4.:UniteNext (--> First candidate is selected but thereafter repeated use of UniteNext doesn't move to next candidate)

Do we need to issue :UniteNext cmd from unite buffer only?
I tried and its not working for me either way.
:UnitePrev is working but is skipping one candidate in list.
I hope there is no dependency if candidate's file buffer should already be open.
