### ISSUE TITLE
Error thrown after g?qq if split direction is botright

### ISSUE THREAD

**Issue by kballard** [Shougo/unite.vim#960]
* Problems summary

When using a default `direction` of `botright`, exiting a Unite session after invoking the keyboard shortcuts list (`g?`) throws an error:

> ```
Error detected while processing function <SNR>94_exit..unite#force_quit_session..unite#view#_quit:
line   34:
E16: Invalid range: 2wincmd w
```

In an older version (Vim 7.3, the version shipped as `/usr/bin/vim` on OS X 10.10.3), it doesn't print an error, but it does beep at me.

* Environment Information
 * OS: Mac OS X 10.10.3
 * Vim version: Vim 7.4.712 (installed with `brew install macvim`)

* Minimal vimrc less than 50 lines

```VimL
if has('vim_starting')
    set nocompatible
    set runtimepath+=~/.vim/neobundle/unite.vim/

    runtime! plugin/**/*.vim
    set noloadplugins

    call unite#custom#profile('default', 'context', {
                \ 'direction': 'botright',
                \ })
endif
```

* How to reproduce

 0. startup vim: `vim -u vimrc_minimal`
 1. `:Unite source` (any source works)
 2. Press `g?`. The `mapping` source should be shown.
 3. Press `q`. It should back out to the original source
 4. Press `q` again. It prints the error now.

* Screen shot

![vim](https://cloud.githubusercontent.com/assets/714/8071940/c9d3769c-0ec3-11e5-8504-92b3271a9e9c.gif)

**Comment by Shougo** [comment]
Reproduced.  I will fix it later.
