### ISSUE TITLE
file_rec/neovim doesn't find executable

### ISSUE THREAD

**Issue by gustavo-hms** [Shougo/unite.vim#961]
* There are situations where file_rec/neovim doesn't find the executable to search for files (either "find" or "ag"). In such situations, it fails with the following error:
  ```
  function <SNR>125_call_unite_empty..unite#start..unite#start#standard..unite#candidates#_recache..<SNR>193_recache_candidates_loop..<SNR>193_get_source_candidates..199, line 59
  Vim(let):E902: "find -L" is not an executable
  [unite.vim] Error occurred in gather_candidates!
  [unite.vim] Source name is file_rec/neovim
  ```
  if it is configured to use "find", or
  ```
  Vim(let):E902: "ag --follow --nocolor --nogroup --hidden -g """ is not an executable
  ```
  if configured to use "ag".

* It should work flawlessly

* My environment:
  * OS: Linux (Ubuntu 14.04), with "ag" installed
  * Neovim version: 0.0.0-alpha+201504060149

* My vimrc configuration:
  ```
  Plug 'Shougo/unite.vim'
  let g:unite_enable_start_insert = 1
  let g:unite_split_rule = 'no-split'
  if executable('ag')
    let g:unite_source_rec_async_command = 'ag --follow --nocolor --nogroup --hidden -g ""'
  endif
  call unite#filters#matcher_default#use(['matcher_fuzzy'])
  ```

* There are 2 different situations where the bug can happen: a directory with a previous cache and a directory without any cache
  * First, the case without cache: if you start neovim in a directory without any cache and runs the file_rec/neovim source, you see the bug immediately;
  * If, on the other hand, you start neovim in a directory previously cached by the file_rec/neovim source, the first run of the source works normally, but any subsequent run will fail.

* A screenshot:
![unite-source-problem](https://cloud.githubusercontent.com/assets/1659941/8083427/d4310bb2-0f5a-11e5-94e5-770cbf7215e1.png)

**Comment by Shougo** [comment]
I get it.  It is bug.  I will fix it later.

**Comment by gustavo-hms** [comment]
I’ve tried the last changes and the neovim source is still not working, although this time it fails silently: no error messages are shown. It still fails at the same scenarios: if there’s no cache, it fails immediately; but if there’s a cache, it works the first time and fails on further runs. file_rec/async is working though.

**Comment by Shougo** [comment]
Reproduced.  It seems another bug.

**Comment by gustavo-hms** [comment]
Hi, Shougo!

It’s still not working. But this time there’s a difference: now it doesn’t matter if there’s a cache, it always fails silently. Since it doesn’t print any error, I don’t know exactly what additional info I could provide, but if I can be of any help, please, just say.

Anyway, thanks for your fast responses.

**Comment by Shougo** [comment]
Really?  It works.
I cannot reproduce your behavior.

**Comment by Shougo** [comment]
OK.  Reproduced. "ag" is not works in neovim.
I don't know why?
Please don't use ag in neovim.

**Comment by fmoralesc** [comment]
Perhaps the format of `ag` output changed?

Also, since you are using vimproc functions to process the command args, it seems like using 'ag' turns vimproc as a dependency for Unite.

**Comment by Shougo** [comment]
It seems not.
In vimproc, it works.
But in neovim, it exists immediately.

**Comment by gustavo-hms** [comment]
Ok, you are right! If I don’t use “ag” it works. I’m reverting back to the default.

**Comment by meunierd** [comment]
@Shougo I think the documentation still says that ag works, could that be removed for the time being?

**Comment by Shougo** [comment]
@meunierd Thanks.  Fixed.

**Comment by rygwdn** [comment]
@Shougo I realize this is closed, and I can open a new issue if desired, but I can get `ag` working with `file_rec/neovim` by making `job_start` run `ag` in a shell:
```diff
diff --git i/autoload/unite/sources/rec.vim w/autoload/unite/sources/rec.vim
index 50798fd..bd2488c 100644
--- i/autoload/unite/sources/rec.vim
+++ w/autoload/unite/sources/rec.vim
@@ -476,6 +476,7 @@ function! s:source_file_neovim.gather_candidates(args, context) "{{{
   endif
 
   " Note: "pt" needs pty.
+  let commands = [&shell, &shellcmdflag, join(commands, " ")]
   let a:context.source__job = jobstart(commands, {
         \ 'on_stdout' : function('s:job_handler'),
         \ 'on_stderr' : function('s:job_handler'),
```

**Comment by Shougo** [comment]
Thanks.  Fixed.

**Comment by PonderingGrower** [comment]
I don't know about the fixed part:

```
[file_rec/neovim] directory: /tmp                                                                                                                              
function <SNR>57_call_unite..unite#start..unite#start#standard..unite#candidates#_recache..<SNR>103_recache_candidates_loop..<SNR>103_get_source_candidates..18
6, line 59                                                                                                                                                     
Vim(let):E113: Unknown option: cmdflags                                                                                                                        
[unite.vim] Error occurred in gather_candidates!                                                                                                               
[unite.vim] Source name is file_rec/neovim                                                                                                                     
Press ENTER or type command to continue
```

**Comment by HarmtH** [comment]
https://github.com/Shougo/unite.vim/commit/2c011f4aab3e5fefe8e48389f203f3c7b554a46b

**Comment by Shougo** [comment]
@PonderingGrower Fixed.

**Comment by PonderingGrower** [comment]
This is great. Thanks Shougo! Unite is probably the most important plugin I use(with fugitive right next to it). I really appreciate you doing all of this.

Cheers!

**Comment by HarmtH** [comment]
It is still buggy.

I use the zsh-shell, which gives an error when it cannot expand wildcards passed to it. So 
```
call unite#util#set_default(
      \ 'g:unite_source_rec_find_args',
      \ ['-path', '*/.git/*', '-prune', '-o', '-type', 'l', '-print'])
```
will fail with 'file_rec/neovim' when run under zsh, because zsh tries to expand `*/.git/*` and does not succeed.

I changed it into
```
call unite#util#set_default(
      \ 'g:unite_source_rec_find_args',
      \ ['-path', '\*/.git/\*', '-prune', '-o', '-type', 'l', '-print'])
```
and then it does work (also in Bash). But then it will not behave correctly in 'file_rec/async' mode, because vimproc does not instantiate a shell, so 'find' will see the literal `\*` instead of `*`

I think there are two reasonable solutions:
- Specify 'g:unite_source_rec_find_args' as a String (with escapes), which will be parsed by vimproc#parser#split_args in 'file_rec/async' mode to remove the escapes.

or

- Specify 'g:unite_source_rec_async_command' as a List, which can be almost directly passed to vimproc or jobstart with few changes.

I implemented the last option, so I can now use:
```
let g:unite_source_rec_async_command = ['ag','--follow','--nocolor','--nogroup','--hidden','-g','']
```
which seems to work perfectly.

**Comment by Shougo** [comment]
> which seems to work perfectly. You can see the changes at HarmtH@65ddfd6

It works in neovim?

**Comment by Shougo** [comment]
Fixed.  It seems work in neovim.

**Comment by HarmtH** [comment]
Yes, the reason the `ag` command did not work with 'file_rec/neovim' was that the arguments passed to `ag` were `-g` and `""` instead of `-g` and ` ` (empty argument), so we were searching for files with the literal `""` in it.

Vimproc did not have this issue because vimproc#parser#split_args removed the `""`, just like what happened when passing it through a shell.

**Comment by HarmtH** [comment]
I like the current fix, the only downside seems that a dependency on 'vimproc' is introduced in 'file_rec/neovim' mode when specifying a String. But those who do not want to install 'vimproc' can always specify a List.

**Comment by Shougo** [comment]
@HarmtH  Thanks.  Fixed.

**Comment by musaffa** [comment]
@Shougo I have this settings for `file_async/neovim`:

```vim
call unite#custom#source('file_rec/neovim', 'matchers', ['converter_relative_word', 'matcher_fuzzy'])
call unite#custom#source('file_rec/neovim', 'sorters', 'sorter_rank')

let g:unite_source_rec_async_command = ['ag', '--follow', '--nocolor', '--nogroup', '--hidden', '-g', '']

nnoremap <leader>f :<C-u>Unite -no-split -buffer-name=files   -start-insert -ignorecase file_rec/neovim<cr>
```
It doesn't work with or without vimproc.

**Comment by Shougo** [comment]
@musaffa I cannot reproduce it by below init.vim

```vim
set runtimepath+=~/work/unite.vim/
syntax enable
filetype plugin indent on

call unite#custom#source('file_rec/neovim', 'matchers', ['converter_relative_word', 'matcher_fuzzy'])
call unite#custom#source('file_rec/neovim', 'sorters', 'sorter_rank')

let g:unite_source_rec_async_command = ['ag', '--follow', '--nocolor', '--nogroup', '--hidden', '-g', '']

nnoremap ,f :<C-u>Unite -no-split -buffer-name=files   -start-insert -ignorecase file_rec/neovim<cr>
```
