### ISSUE TITLE
/usr/bin/grep: . : No such file or directory

### ISSUE THREAD

**Issue by bstaint** [Shougo/unite.vim#962]
* Problems summary

map `UniteWithCursorWord grep` with `<leader>ug`, type key and default Target will echo:
```
[grep] Pattern: LogoutAction
.
[grep] /usr/bin/grep: . : No such file or directory
```

* Expected

* Environment Information
 * OS: Windows && Linux
 * Vim version: 7.4.729

* Minimal vimrc less than 50 lines

```
set encoding=utf-8
set fileencoding=utf-8
set fileencodings=ucs-bom,utf-8,gbk,cp936,gb2312,big5,euc-jp,euc-kr,latin1
let &termencoding=&encoding

set nocompatible              " be iMproved, required

filetype plugin on
set runtimepath+=~/.vim/bundle/vimproc.vim
set runtimepath+=~/.vim/bundle/unite.vim

call unite#custom#profile('default', 'context', {'start_insert': 1, 'smartcase': 1, 'no-empty': 1, 'winheight': 10, 'prompt': ':', 'direction': 'botright'})

nmap <silent> <leader>ug :UniteWithCursorWord grep<CR>
```

* Reproducable ways from Vim starting

 0.startup vim and open file .
 1.type `<leader>ug`
 2.enter default target

* Screen shot (if possible)

**Comment by Shougo** [comment]
I cannot reproduce the problem.
grep can output the results.
I think it is not unite's problem.

grep should recognize "." directory.

**Comment by Shougo** [comment]
Please execute the grep command manually.
You can check it in `<C-a>` mapping.

**Comment by bstaint** [comment]
I try insert test code in `unite.vim\autoload\unite\sources\grep.vim` line 184:
```
echom a:context.source__targets[0]."|string"
```
execute `UniteWithCursorWord grep` will output:
![1](https://cloud.githubusercontent.com/assets/5853792/8122962/73b96554-10f4-11e5-873d-ddab154fe4e8.png)

use map key will output:
![2](https://cloud.githubusercontent.com/assets/5853792/8122969/7f68045a-10f4-11e5-9112-be311a56da33.png)

I think have special character.

**Comment by Shougo** [comment]
```vim
nmap <silent> <leader>ug :UniteWithCursorWord grep<CR>
```

You should use nnoremap instead of nmap.

> I think have special character.

" " is inserted after ".".  It is not unite problem.

**Comment by bstaint** [comment]
OK, THANKS!
