### ISSUE TITLE
Find files in a git project inferred from the current buffer

### ISSUE THREAD

**Issue by bohrshaw** [Shougo/unite.vim#963]
It seems all current file sources including `file_rec/git` all works in the current working directory by default. And it's not obvious how to find files in a git project inferred from the current buffer, like CtrlP.

I tried: (but not working, help!)
```viml
" Note: b:git_dir is auto-set by fugitive. Skip quoting the path for now.
let g:unite_source_rec_git_command = 'git --git-dir='.b:git_dir.' --work-tree='.b:git_dir[:-6]
Unite file_rec/git
```

**Comment by ujihisa** [comment]
For debugging can you shouw your b:git_dir from the file?

`:echo b:git_dir`

**Comment by bohrshaw** [comment]
I'm now on Windows, it's `C:/Users/Bohr/.vim/.git`. -- Going to sleep. :-)

**Comment by Shougo** [comment]
Unfortunatelly, `file_rec/git` supports from current directory only.
