### ISSUE TITLE
Using Unite.vim to prompt for a specific candidate

### ISSUE THREAD

**Issue by samvv** [Shougo/unite.vim#964]
Love the plugin. There's one thing I'm stuck with, though. I was wondering if it is possible to use Unite.vim to prompt for a specific candidate, so I can use it in the functions of my plugin [mux.vim](http://github.com/samvv/mux.vim).

More specifically I'd like to invoke `unite#start` with a specific `default_action` for a kind without having to extend the `action_table` in the kind's script file. 

Some exemplary pseudocode:
````vim
function! s:set_default_pane(pane)
  " Some code goes here
endfunction

function! mux#configure()
  function got_it(candidate)
    s:set_default_pane(candidate.pane)
  endfunction
  unite#prompt('tmux_panes', {
    \ 'pane': {
      \ 'func': got_it, 
      \ 'is_selectable': 0
    \ }
    \ })
endfunction
````
where `candidate.pane` contains some plugin-specific data about the candidate that was set in `gather_candidates()`.

Is this possible?

**Comment by Shougo** [comment]
You can overwrite the kind action table by the source action table.
You should define the original action.

**Comment by samvv** [comment]
Thanks for the quick feedback, will try!
