### ISSUE TITLE
feature request: history of Unite buffers

### ISSUE THREAD

**Issue by mgraham** [Shougo/unite.vim#967]
Unite resume restores the last Unite buffer.  It includes the source and the filter state.

I would like to be able to save the last 10 unite buffers.  

My use case is that I'm using `Unite grep` to search through a bunch of related CSV files.  I'll start by searching for a string.  In the search results, I'll find another string and then perform another `Unite grep` on that string.  And so on.  Each search result leads to another search. 

I have a mapping that calls `Unite grep` on the word under the cursor, so it's very easy to perform one search after another.

But I'd like to easily back out of the current search (e.g. by pressing `CTRL-O`) and get back to the results of the previous search - without having to start back at the very beginning.

I could probably hack something together by intercepting all calls to Unite and using a ring of sequentially named buffers, but I wonder if this wouldn't be a generally useful feature?

**Comment by tex** [comment]
It would be very useful feature for me 😃

**Comment by lambdalisue** [comment]
Check unite/history source

**Comment by lambdalisue** [comment]
oops. sorry history/unite actually

**Comment by mgraham** [comment]
Yeah, I thought history/unite would be the thing I was looking for.  

Maybe I'm not using it correctly, but it only seems to include executions of Unite where an action was actually taken?  I'd want it to include Unite executions where no action was taken.

Also, is there a way (in vimscript) to run `:Unite history/unite` and run the `start` action on the first line?

**Comment by Shougo** [comment]
> Also, is there a way (in vimscript) to run :Unite history/unite and run the start action on the first line?

`:Unite history/unite -immediately`
