### ISSUE TITLE
ackrc not used

### ISSUE THREAD

**Issue by carlitux** [Shougo/unite.vim#968]
I have this (NeoVim)

    let bundle = neobundle#get('unite.vim')
    function! bundle.hooks.on_source(bundle)
      call unite#filters#matcher_default#use(['matcher_fuzzy'])
      call unite#filters#sorter_default#use(['sorter_rank'])
      call unite#custom#profile('default', 'context', {
            \ 'start_insert': 1
            \ })
    endfunction
    
    " let g:unite_data_directory=s:get_cache_dir('unite')
    let g:unite_source_history_yank_enable=1
    let g:unite_source_rec_max_cache_files=5000
    
    " Ack should be already installed
    let g:unite_source_grep_command='ack'
    let g:unite_source_grep_default_opts='--no-heading --no-color -C4'
    let g:unite_source_grep_recursive_opt=''

    function! s:unite_settings()
      nmap <buffer> Q <plug>(unite_exit)
      nmap <buffer> <esc> <plug>(unite_exit)
       imap <buffer> <esc> <plug>(unite_exit)
     endfunction
    autocmd FileType unite call s:unite_settings()

and in ackrc

	# only search with case-sensitivity if there is mixed case
	--smart-case
	# follow symlinks
	--follow
	
	# ignore directories
	--ignore-dir=node_modules
	--ignore-dir=bower_components
	--ignore-dir=bundle
	--ignore-dir=tmp
	--ignore-dir=solr/data
	--ignore-dir=.sass-cache
	--ignore-dir=log
	--ignore-dir=coverage
	
	# added file types
	--type-set=css=.css,.less,.scss,.styl,.sass
	--type-set=styl=.styl
	--type-set=less=.less
	--type-set=html=.html,.mustache,.handlebars,.tmpl,.hbs
	--type-set=json=.json
	--type-set=md=.markdown,.md
	--type-set=svg=.svg
	--type-set=ts=.ts
	--type-set=style=.scss,.sass,.styl,.less,.css
	--type-add=ruby=.haml,.feature
	--type-set=tags=tags
	--type-set=handlebars=handlebars
	--type-add=handlebars=.handlebars,.hbs
	--type-set=jst=.jst,.ejs
	--type-set=video=.mp4
	--type-set=docs=.docx,.doc,.xlsx,.xls
	--notags
	#--noimage
	--novideo
	--nodocs
	--smart-case
	--sort-files
	--color
	--follow
	--group

But on opening the shows all what is in node_modules and on in ignored directories what makes slow

**Comment by Shougo** [comment]
It is feature.
.ackrc is not supported.

**Comment by Shougo** [comment]
ackrc is only used in ack command.
It is not used in file_rec source.
