### ISSUE TITLE
Reuse last window as a preview window

### ISSUE THREAD

**Issue by balta2ar** [Shougo/unite.vim#969]
Currently Unite uses it's own separate preview window to preview search results. Could you please add an option to show preview in the last active window (maybe turned off by default)? Separate preview window is inconvenient for me as it creates a total of three windows in my vim, which is too much for me. Thank you.

**Comment by Shougo** [comment]
Unfortunatelly, No.

**Comment by balta2ar** [comment]
Why?

18 июля 2015 г. 9:30 AM пользователь "Shougo" <notifications@github.com>
написал:

**Comment by Shougo** [comment]
I don't think it is useful.
unite should use preview window.
And the implementation is complex.
I don't want to add the option.

**Comment by Shougo** [comment]
If you want to reuse window, you should use `-no-split` option.
