### ISSUE TITLE
[neovim] Unite buffer source is empty

### ISSUE THREAD

**Issue by davidgranstrom** [Shougo/unite.vim#971]
In neovim `:Unite buffer` does not return any buffers (just an empty prompt), I was just wondering if this is a known issue? If I run the `:ls` command in neovim I get a list of buffers as expected.

Btw, thank you for developing this plugin! I find it extremely powerful and useful for my workflow! :)

NVIM 0.0.0-alpha+201507171736 (compiled Jul 18 2015 15:08:31)
Commit: 4d79edccdc0243a02a20ef46184b8f87f2bda290

OSX 10.9.5

**Comment by Shougo** [comment]
I cannot reproduce the problem.
Please read the issue template.

https://github.com/Shougo/unite.vim/issues/584

**Comment by Shougo** [comment]
No response.
