### ISSUE TITLE
[neovim] Unite file_rec/neovim fails if g:unite_source_rec_async_command is set

### ISSUE THREAD

**Issue by PonderingGrower** [Shougo/unite.vim#972]
Sup,

I just encountered something by accident. I switched from `file_rec/async` to `file_rec/neovim` since I just(finally) noticed that it's available. The thing is I didn't bother to remove configuration for `file_rec/async` which interfered with `file_rec/neovim`.

* Problems summary

When using `Unite file_rec/neovim` I get no results.

* Environment Information
 * OS: Debian Jessie
 * NeoVim version: NVIM 0.0.0-alpha+201504260002 (compiled Apr 26 2015 09:43:57) Commit: 1a636eabd555c3631348bae8291dbb7974523310

* Option:
````
let g:unite_source_rec_async_command = 'ag --nocolor --nogroup -g ""'
````
* nvimrc

````
call plug#begin('~/.vim/bundle')
Plug 'Shougo/unite.vim'
call plug#end()

let g:unite_source_rec_async_command = 'ag -g ""'
````

* Reproducable ways from Vim starting

 0. startup vim.
 1. use `Unite file_rec/neovim:<any_path>
 2. don't get any results

**Comment by Shougo** [comment]
https://github.com/Shougo/unite.vim/issues/961

**Comment by PonderingGrower** [comment]
This is terrible. Without ag `file_rec/neovim` is essentially useless for me because of the size of codebases I work with. When `find` is used I get 5-10 second delays before I see results.

I really hope there's a solution for this because now I have to go back to `vimproc` to be able to use Unite.

**Comment by Shougo** [comment]
Unfortunatelly, it is neovim or ag's problem.
I cannot fix it.
