### ISSUE TITLE
Using `-no-split` always returns to an empty buffer

### ISSUE THREAD

**Issue by fardog** [Shougo/unite.vim#973]
I'm having an issue where any use of the `-no-split` option will clear my current buffer, for example:

1. Open a file `$ vim file.txt`
2. Open a buffer list in a no-split `:Unite -no-split buffer`
3. Press `q` to exit the buffer list
4. The file that was open (`file.txt`) is no longer open, and I see an empty buffer

This happens with other actions also, such as:

1. Open a file `$ vim file.txt`
2. Open a file list in a no-split `:Unite -no-split -default-action=vsplit file_rec/async:!`
3. Select another file to open
4. The file that was open (`file.txt`) is no longer open, and I see an empty buffer in that split. The file I asked to be open is open in a vsplit, as expected.

It doesn't seem like the previous buffer is remembered at all; and I'm able to reproduce this with both `vim` and `nvim`.

Thank you!

**Comment by Shougo** [comment]
Fixed.

**Comment by fardog** [comment]
that's got it fixed! thank you!
