### ISSUE TITLE
unite_source_rec_find_args not accepting multiple paths

### ISSUE THREAD

**Issue by buchuki** [Shougo/unite.vim#976]
* Problems summary
I'm having trouble with the unite_source_rec_find_args parameter

When I set it as follows in my .vimrc:

     let g:unite_source_rec_find_args = ['-path', '*/_build/*', '-prune', '-o', '-type', 'l', '-print']

file_rec/async works as expected; the _build directory is excluded from my search.

However, when I try to set it to also exclude my _bin directory, like this:

    let g:unite_source_rec_find_args = ['-path', '*/_build/*', '-prune', '-o', '-path', '*/_bin/*', '-o', '-type', 'l', '-print']

no files show up in file_rec/async at all.

* Expected

I expect all files to be displayed except those I have explicitly excluded.

* Environment Information

 * remote server
 * over ssh
 * inside tmux
 * using zsh
 * recent neovim
 * OS: Centos 6
 * Vim version: neovim 20150804

* Minimal nvimrc less than 50 lines

```VimL
set background=dark
set mouse=n
syntax on

:tnoremap <Esc> <C-\><C-n>

set runtimepath+=~/.nvim/bundle/neobundle.vim
:helptags~/.nvim/bundle/neobundle.vim/doc/

" Init NeoBundle
call neobundle#begin(expand('~/.nvim/bundle/'))
NeoBundleFetch 'Shougo/neobundle.vim'
"Other bundles
NeoBundle 'Shougo/vimproc.vim', {'build' : {'linux': 'make'},}
NeoBundle 'Shougo/unite.vim'
call neobundle#end()
filetype plugin indent on
NeoBundleCheck


call unite#filters#matcher_default#use(['matcher_fuzzy'])
let g:unite_source_rec_find_args = ['-path', '*/_build/*', '-prune', '-o', '*/_bin/*', '-prune', '-type', 'l', '-print']
```

* How to reproduce
```
1.  run these commands to set up some test files to serach
mkdir test
cd test
mkdir _bin
mkdir _build
mkdir good
touch _bin/bad
touch _build/alsobad
touch good/afile
touch alsogood

nvim
:Unite
ifra<enter>  #to get file_rec_async
```

I expect the result to be

good/afile
alsogood

but i don't get any results at all.

Note that if I run find on the normal command line the */_build/* syntax doesn't work and I need to use this instead:

find . -path '*_bin' -prune -o -path '*_build' -prune -o -print

however no permutation of this syntax has worked inside neovim either.

Also note that I have tried various versions of glob_ignore and glob_pattern, but none of these seemed to alter the output in any way. :-(

**Comment by buchuki** [comment]
I think this message would indicate the problem:

[file_rec/async] /usr/bin/find: paths must precede expression: /home/dgp/heh

**Comment by buchuki** [comment]
This may be relevant:

I added echom join(commands, ';')

  find;-L;/home/dgp/heh;-path;*/_build/*;-prune;-o;*/_bin/*;-prune;-o;-type;f;-print

and the error is

  [file_rec/async] /bin/find: paths must precede expression: */_bin/*

**Comment by Shougo** [comment]
Yes, I tested it...
