### ISSUE TITLE
Allow :Unite to take a range

### ISSUE THREAD

**Issue by msprev** [Shougo/unite.vim#977]
I want to write a source that selects from a list of commands to wrangle text. What I want is to select the text in visual mode, activate `'<,'>Unite` to choose my command, and then execute that command on the line range. I am currently blocked as `:Unite` won't accept a line range. 

Any chance this could be changed and the line range passed to unite sources?

**Comment by Shougo** [comment]
Hmmm...
I can implement it.
But it needs refactoring.

**Comment by msprev** [comment]
It would be great if this were possible.

**Comment by Shougo** [comment]
Implemented.

context.firstline, context.lastline, context.bufnr is available.

**Comment by msprev** [comment]
Thanks! That is brilliant!
