### ISSUE TITLE
Disable ACP for unite 

### ISSUE THREAD

**Issue by belcadarn** [Shougo/unite.vim#978]
Hello,
First, huge thanks for this tremendous plugin I use every day !
I have a little issue regarding unite file_rec with -start-insert option combined with autocompIpop.

The pop up appears after typing few letters (see the attached figure), but completion cannot be used (which is to be honnest not a problem). I would like to disable ACP when using unite and re-enable just after quit the unite buffer.
I have tried 
autocmd bufenter,winenter,bufwinenter unite AcpLock
autocmd bufleave,winleave,bufwinleave unite AcpUnlock
without sucess

Any idea ?
Thank's a lot

![unite_acp](https://cloud.githubusercontent.com/assets/13692881/9133655/b94b6538-3cfd-11e5-88bb-6359aa3b5120.png)

**Comment by Shougo** [comment]
You should use autocmd FileType.

```vim
autocmd FileType unite AcpLock
autocmd FileType unite AcpUnlock
```

**Comment by nmanandhar** [comment]
You can disable completion for unite buffer by adding the following in your vimrc
`if(exists("g:acp_behavior"))
      let g:acp_behavior.unite=[]
  else
      let g:acp_behavior = {'unite':[]}
 endif
`
