### ISSUE TITLE
file_rec/async not working with ag on ubuntu

### ISSUE THREAD

**Issue by jkeylu** [Shougo/unite.vim#981]
- Problems summary

file_rec/async not working with custom g:unite_source_rec_async_command.
It didn't show a list of candidates. And throw two error:

* `Error detected while processing function unite#util#set_default:`
* `E706: Variable type mismatch for: g:unite_source_rec_async_command`

- Expected
I expect it to show a list of candidates.

- Environment Information

OS: Ubuntu 14.04
Vim version: VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jan  2 2014 19:39:32) Included patches: 1-52
Unite version: f130795d3d664b33c8b6ec27fc16c1db48c19990

```
" My minimal vimrc
set nocompatible
set runtimepath+=~/.vim/bundle/unite.vim/,~/.vim/bundle/vimproc/
let g:unite_source_rec_async_command='ag --follow --nocolor --nogroup --hidden -g ""'
```

![unite-error](https://cloud.githubusercontent.com/assets/423045/9269164/24830c16-4299-11e5-958e-737a833bd9a8.png)

**Comment by meunierd** [comment]
The arguments are a list of strings now instead.

    ['ag', '--follow'...]

**Comment by jkeylu** [comment]
@meunierd Thanks

**Comment by robinro** [comment]
this issue left me embarrassed when I tried to show off unite yesterday, but it's already fixed/worked around :+1:
