### ISSUE TITLE
file_rec/async not working with ag on windows

### ISSUE THREAD

**Issue by petobens** [Shougo/unite.vim#982]
Consider the following minimal vimrc:

```vim
set nocompatible

let $ONEDRIVE_HOME = expand('C:/OD/Users/Pedro')
let $DOTVIM = expand('$ONEDRIVE_HOME/vimfiles')

set runtimepath+=$DOTVIM/bundle/unite
set runtimepath+=$DOTVIM/bundle/vimproc/
filetype plugin indent on

if executable('ag')
    let g:unite_source_rec_async_command = ['ag', '--follow',  '--nocolor',
                \ '--nogroup', '--hidden', '-g']
endif
```

Just for testing create a `test` folder in your `Desktop` directory containing two files : `foo.txt` and `bar.txt` 
Now (as in the GIF) open Gvim, run `:cd C:\Users\Pedro\Desktop\test` and then `:Unite file_rec`. You will see that both text files are shown. However if I now run `:Unite file_rec/async` the unite buffer is empty.

![blah](https://cloud.githubusercontent.com/assets/2583971/9290436/1165b74c-436a-11e5-8272-7abaf7adcaea.gif)

**Comment by Shougo** [comment]
```vim
let g:unite_source_rec_async_command = ['ag', '--follow',  '--nocolor',
                \ '--nogroup', '--hidden', '-g', '']
```

is correct  arguments.

**Comment by petobens** [comment]
Thank you!
