### ISSUE TITLE
grep source output and jumping to candidates not working 

### ISSUE THREAD

**Issue by petobens** [Shougo/unite.vim#983]
Consider the following minimal vimrc:

```vim
set nocompatible

let $ONEDRIVE_HOME = expand('C:/OD/Users/Pedro')
let $DOTVIM = expand('$ONEDRIVE_HOME/vimfiles')

set runtimepath+=$DOTVIM/bundle/unite
set runtimepath+=$DOTVIM/bundle/vimproc/
filetype plugin indent on

if executable('ag')
    let g:unite_source_grep_command = 'ag'
    let g:unite_source_grep_default_opts =
                \ '--smart-case --line-numbers --nocolor --nogroup --follow ' .
                \ '--ignore ''.git'''
    let g:unite_source_grep_recursive_opt = ''
endif
```

Now open Gvim, `cd` to your vimfiles directory, run `:Unite grep` and search for `neocomplete`. You will see (as in the GIF) that i) the Unite buffer output showing the candidates has a strange format (for instance it doesn't show the file where the candidates is) and ii) when I select a candidate and press `<CR>` Unite doesn't jump to the line in the file containing the candidate.

![fooo](https://cloud.githubusercontent.com/assets/2583971/9292122/6875993c-43bd-11e5-85ef-d3203df4d896.gif)

**Comment by Shougo** [comment]
Unfortunatelly, I cannot reproduce the problem.

1. Please upload `<Plug>(unite_print_message)` result.

2. Please execute the same command(You can get by `<Plug>(unite_print_message)`) in your command prompt.

3. Please tell me where you get the the Windows ag binary.

**Comment by petobens** [comment]
@Shougo, with the following minimal vimrc:

```vim
set nocompatible

let $ONEDRIVE_HOME = expand('C:/OD/Users/Pedro')
let $DOTVIM = expand('$ONEDRIVE_HOME/vimfiles')

set runtimepath+=$DOTVIM/bundle/unite
set runtimepath+=$DOTVIM/bundle/vimproc/
filetype plugin indent on


if executable('ag')
    let g:unite_source_grep_command = 'ag'
    let g:unite_source_grep_default_opts =
                \ '--smart-case --line-numbers --nocolor --nogroup --follow ' .
                \ '--ignore ''.git'''
    let g:unite_source_grep_recursive_opt = ''
endif

au FileType unite nmap <buffer> <C-b> <Plug>(unite_print_message_log)
```

I opened Gvim, ran `:cd C:/Users/Pedro/vimfiles` and then ran `Unite grep` with pattern `unite_print_message_log` in the current directory. The results of `<Plug>(unite_print_message_log)` from Gvim and from the command prompt are shown in the image below. 

You can get the ag binary for Windows [here](https://blog.kowalczyk.info/software/the-silver-searcher-for-windows.html).

![screenshot 184](https://cloud.githubusercontent.com/assets/2583971/9339498/cc47eee2-45c0-11e5-80ed-8de6cd62766a.png)

**Comment by Shougo** [comment]
OK.   I will try it in Windows.

**Comment by Shougo** [comment]
Fixed.  Please change the ag arguments.

```vim
	  let g:unite_source_grep_default_opts =
	  \ '-i --vimgrep --hidden --ignore ' .
	  \ '''.hg'' --ignore ''.svn'' --ignore ''.git'' --ignore ''.bzr'''
```

**Comment by petobens** [comment]
Thanks @Shougo. Is it possible to improve the highlighting? Currently it looks like this:

![screenshot-20-08-2015_11-52-16](https://cloud.githubusercontent.com/assets/2583971/9390319/dec8539a-4746-11e5-9498-3895d06527d3.png)

It would be nice to higlight i) the filename and ii) the line/column numbers with a different color than the one matched pattern.

**Comment by Shougo** [comment]
@petobens You can change `uniteSource__GrepFile` and `uniteSource__GrepLineNr` highlight.

**Comment by petobens** [comment]
Thank you!!
