### ISSUE TITLE
Splits in insert mode not working

### ISSUE THREAD

**Issue by elvis-sik** [Shougo/unite.vim#984]
Hi. I have the following in my vimrc:

```vim
 inoremap <silent><buffer><expr> <C-c>     unite#do_action('split')
 inoremap <silent><buffer><expr> <C-v>     unite#do_action('vsplit')
```

I open an unite buffer, with the files source. I type something, so that I have the file I want as the first in the result list. If I press C-v, nothing happens (except `^V` appearing on the screen). If I press C-V, the following appears:

```vim
 inoremap <silent><buffer><expr> <C-s>     unite#do_action('split')noremap <silent><buffer><expr> <C-v>     unite#do_action('vsplit')
```

I have C-s mapped to ESC, but I tried removing that without success.

Thank you.

**Comment by Shougo** [comment]
I cannot understand/reproduce your problem.
Please read the issue template.

https://github.com/Shougo/unite.vim/issues/584

**Comment by Shougo** [comment]
@elvis-sik Ping

**Comment by elvis-sik** [comment]
I am sorry for not answering. I haven't found the time to do what you asked. Anyway, this isn't bothering me.

**Comment by Shougo** [comment]
OK.
