### ISSUE TITLE
There is -no-split but there is not -split for when no_split is set

### ISSUE THREAD

**Issue by PonderingGrower** [Shougo/unite.vim#990]
Sup Shougo

I just noticed that there's no way to do a split Unite search if I have set `no_split` using `call unite#custom#profile()`.

Would be nice to have it. There are exceptions when I do want a split, for example for searching through registers.

Cheers man!

**Comment by Shougo** [comment]
Please read the issue template.
I will check it.

https://github.com/Shougo/unite.vim/issues/584

**Comment by PonderingGrower** [comment]
There is no issue. It's a feature request.

**Comment by Shougo** [comment]
Please create minimal .vimrc in the current behavior.
I will try it.

**Comment by PonderingGrower** [comment]
Okay:

```
call plug#begin('~/.vim/bundle')

Plug 'Shougo/unite.vim'

call plug#end()

call unite#custom#profile('default', 'context', { 'no_split' : 1, })

" what I can do, this will not split
nnoremap <space>ur :Unite register<CR>

" what I want to do, this should split
nnoremap <space>uR :Unite -split register<CR>
```

**Comment by PonderingGrower** [comment]
Also, I just realized when `-quick-match` is used with `Unite -quick-match register` there are quick access labels for registers, but they are different than the actual names of the registers(for example pressing `a` will get me the `"` register).

I feel like there should be a mode for `Unite register` that allows one to quick-select a register using it's actual name, rather than an arbitrary label. But that's a totally separate issue and also a matter of preference I guess.

**Comment by Shougo** [comment]
> Also, I just realized when -quick-match is used with Unite -quick-match register there are quick access labels for registers, but they are different than the actual names of the registers(for example pressing a will get me the " register).

It is feature.

**Comment by Shougo** [comment]
Fixed the problem.  It is bug.
