### ISSUE TITLE
file_rec shows relative and absolute path

### ISSUE THREAD

**Issue by chrisfid** [Shougo/unite.vim#991]
* Problem summary
When using file_rec source, it shows the relative path and the absolute path side by side. This is a lot of clutter and makes it hard to quickly read candidates (see screenshot). It does this by default (no custom Unite settings).

* Expected
Some way to disable it (e.g. just show the relative path instead of both relative and absolute).

Maybe it's in the docs already but I could not see how. Sorry ahead of time if it is already documented. Also thank you so much for your awesome work.

![unite](https://cloud.githubusercontent.com/assets/7884955/9425554/c26f21d8-48ea-11e5-8388-4f4733a4d700.png)

**Comment by Shougo** [comment]
I cannot reproduce it.
Please read the issue template.

https://github.com/Shougo/unite.vim/issues/584

**Comment by chrisfid** [comment]
I narrowed it down to the Unite integration with [vim-devicons](https://github.com/ryanoasis/vim-devicons) plugin.

```VimL
set nocompatible
set runtimepath+=C:/Users/Chris/vimfiles/bundle/unite.vim
set runtimepath+=C:/Users/Chris/vimfiles/bundle/vim-devicons
nnoremap <silent><C-p> :<C-u>Unite -buffer-name=files file_rec<CR>
```

**Comment by Shougo** [comment]
OK.  It is vim-devicons problem.
You should create the issue in vim-devicons repository.

**Comment by Shougo** [comment]
I think you can disable the feature by following command.

```vim
let g:webdevicons_enable_unite = 0
```
