### ISSUE TITLE
file_rec/async does not respect config on first use

### ISSUE THREAD

**Issue by rosshadden** [Shougo/unite.vim#992]
* Problems summary

  Unite does not respect the `g:unite_source_rec_async_command` setting on first use of `file_rec/async`.  Instead, it uses some default way to get the recursive list of files, which I only noticed because it was much slower than when it uses `ag` as configured.  My example config below makes the problem much more obvious, running an `echo` command instead of returning a real file list.

* Expected

  Unite respects the `g:unite_source_rec_async_command` setting on first use of `file_rec/async`.

* Environment Information
 * OS: Arch Linux
 * Vim version: 7.4.778

* Minimal `vimrc`

```VimL
set nocompatible

if has ('vim_starting')
	set runtimepath+=~/.vim/bundle/neobundle.vim/
endif

call neobundle#begin(expand('~/.vim/bundle/'))

NeoBundleFetch 'Shougo/neobundle.vim'

NeoBundle 'Shougo/vimproc.vim', {
	\ 'build' : {
		\ 'windows' : 'tools\\update-dll-mingw',
		\ 'cygwin' : 'make -f make_cygwin.mak',
		\ 'mac' : 'make -f make_mac.mak',
		\ 'unix' : 'make -f make_unix.mak',
	\ }
\ }

NeoBundle 'Shougo/unite.vim'

call neobundle#end()

let g:unite_source_rec_async_command = ['echo', 'hi']
```

* How to reproduce

 0. startup vim
 1. `:Unite file_rec/async:!`
 2. `q` (to exit the unite buffer)
 3. `:Unite file_rec/async:!`

**Comment by Shougo** [comment]
It is just the cache file is used.
It is not problem.
