### ISSUE TITLE
'grep output format is wrong.'

### ISSUE THREAD

**Issue by mollerhoj** [Shougo/unite.vim#994]
in `grep.vim` you recently added:
https://github.com/Shougo/unite.vim/commit/6ccf1b362fe92bd47ab828c1a28c348c24d1b749
```
#grep.vim
if path ==# '.'
      call unite#print_source_error(
            \ 'grep output format is wrong.', s:source.name)
      break
    endif
```
This broke my search settings. Why was it added? And I believe the error message needs to be somewhat more descriptive..

**Comment by Shougo** [comment]
Please upload your search settings.
I think your setting is wrong.

```
Q: "ag" does not work in grep source.

A: Please check |unite-source-grep| example.
```
