### ISSUE TITLE
Buffer search (numbers & immediately)

### ISSUE THREAD

**Issue by vito-c** [Shougo/unite.vim#997]
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jul 23 2015 06:35:43)
MacOS X (unix) version
Included patches: 1-796
OS: os-x

Hi I am using the following command `:Unite -start-insert -toggle -auto-preview -no-split -winheight=15 -immediately buffer` to search buffers. When I type my search string and there is only one match I thought -immediately would cause unite to automatically change to the buffer. However this isn't the case I have to actually hit the return key (so much effort).
![img](https://monosnap.com/file/ehMoTF9Mpz1165fec3Acu6XXUlamnM.png)

I was also expecting that I could just put the number of the buffer in the search area and that buffer would become selected but that is not the case. When I put a number in the search no result are shown :(
![s](https://monosnap.com/file/yWv2eLqBub8C3M4Zw9vBhLpmtllN0v.png)

**Comment by Shougo** [comment]
> I was also expecting that I could just put the number of the buffer in the search area and that buffer would become selected but that is not the case. When I put a number in the search no result are shown :(

You can use `converter_abbr_word` for it.

**Comment by Shougo** [comment]
> Hi I am using the following command :Unite -start-insert -toggle -auto-preview -no-split -winheight=15 -immediately buffer to search buffers. When I type my search string and there is only one match I thought -immediately would cause unite to automatically change to the buffer. However this isn't the case I have to actually hit the return key (so much effort).

Implemented.
