### ISSUE TITLE
Neovim Syntax issue

### ISSUE THREAD

**Issue by vito-c** [Shougo/unite.vim#998]
version: `dcbc9a3`
`commit dcbc9a3c676a93c2424b1a8c6322b028803106f4
Author: Xu Cheng <xucheng@me.com>
Date:   Tue Jul 21 21:57:14 2015 +0800`

When I run `Unite -start-insert -toggle -auto-preview -no-split -winheight=15 -immediately buffer` sometimes syntax highlighting turns off for the selected file. I think this might be a neovim issue? I have only seen it happen on neovim.

**Comment by Shougo** [comment]
I cannot reproduce the problem.
Please read the issue template.

https://github.com/Shougo/unite.vim/issues/584

**Comment by vito-c** [comment]
I updated neovim and it's working now

**Comment by vito-c** [comment]
* Problems summary
 When I run `Unite -start-insert -toggle -auto-preview -no-split -winheight=15 -immediately buffer` sometimes syntax highlighting turns off for the buffer being displayed. I believe it happens when the buffer has not be loaded yet. This could be a neovim error.

* Expected
The auto preview should still have syntax highlighting enabled

* Environment Information
 * OS: OS X Yosemite 10.10.4
 * Vim version:
Neovim:
commit d1af520fff5b9f33ce97dee8981306a55e9e116a
Author: Dominyk Tiller <dominyktiller@gmail.com>
Date:   Wed Aug 26 17:40:49 2015 +0100

    sdl: use secure links

* Minimal vimrc less than 50 lines

```
"  Test vimrc
set nocompatible        " Must be first line
set expandtab
set rtp+=~/.vim/bundle/vundle
call vundle#rc()
Bundle 'Shougo/unite.vim'
syntax on
set mouse=
let mapleader = ' '
nnoremap <leader>l :<C-u>Unite -start-insert -toggle -auto-preview -no-split -winheight=15 -immediately buffer<CR>
```

* Reproducable ways from Vim starting

 0. startup via `cd ~/.vim/bundle/unite.vim && nvim ./plugin/**/*.vim
 1. press the <leader>l
 2. start typing a file name that hasn't been shown yet
 3. the syntax in auto-preview won't show up correctly

* Screen shot 
![screen shot](https://monosnap.com/file/l6XHgO1NFa6apgSVQgY81x0LraOVKt.png)
