### ISSUE TITLE
Filtering out term:// & [No Name] buffers

### ISSUE THREAD

**Issue by vito-c** [Shougo/unite.vim#999]
Is there a way to filter out certain buffers when I call `:Unite -start-insert -toggle -auto-preview -no-split -winheight=15 -immediately buffer` 

On neovim term:// are not filtered out with `:Unite -start-insert -toggle -auto-preview -no-split -winheight=15 -immediately buffer:-`

**Comment by vito-c** [comment]
Also filtering out netrw buffers would be great :)

**Comment by Shougo** [comment]
Implemented.

**Comment by vito-c** [comment]
thank you!
